### ISSUE TITLE
Cosmetic: "Next" link lower than other pagination links on forums

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#1000]
![](https://i.imgur.com/8qR5Dl5.png)

Courtesy of DarkbloodBane

**Comment by YLivay** [comment]
https://gamejolt.com/f/next-button-is-lower/327714

**Comment by niksudan** [comment]
This is site-wide by the way (#958)

**Comment by YLivay** [comment]
thx sir

**Comment by hworld** [comment]
yeah, closing since dupe
