### ISSUE TITLE
Blank subject line for new follower notification email

### ISSUE THREAD

**Issue by niksudan** [gamejolt/issue-tracker#1001]
I had an email about a new follower ([sʕ· ᴥ · ʔz](https://gamejolt.com/@BadHairDay)) but it did not have a subject line. With previous notifications I did have one, but the names were made up of alphanumeric characters and common punctuation.

This could be happening because of special characters?

**Comment by hworld** [comment]
Fixed boi! and i did it, not nils

**Comment by niksudan** [comment]
Hooray! My inbox has been restored to normal.
