### ISSUE TITLE
PDF download not starting

### ISSUE THREAD

**Issue by NathanAuckett** [gamejolt/issue-tracker#1004]
Example game: https://gamejolt.com/games/gemelents-tcg/151917

The PDF file download is not starting when on the download page.
Tested on Firefox and chrome. Fails on both.

**Comment by YLivay** [comment]
wow now THAT is weird. I see in the network tab it did issue a request but got back just a hash as a response? Must be a bug with the CDN or Amazon yeesh. I'll look into it

**Comment by YLivay** [comment]
fixed
