### ISSUE TITLE
Screenshot magnifcation issue

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#1005]
![image](https://user-images.githubusercontent.com/11202073/31183406-c786634a-a926-11e7-9c83-e53065d371a7.png)

I clicked a screenshot for magnification, it even appeared for half a second or so and disappeared forever leaving the screen like this. Only the first screenshot I wanted to see worked plus that YouTube video. The rest all resulted into this.

**Comment by hworld** [comment]
this is usually because of mediaserver not being up. i think it went down around this time
