### ISSUE TITLE
Adding a new comment resets window y position

### ISSUE THREAD

**Issue by niksudan** [gamejolt/issue-tracker#1006]
I guess the app is treating the hash as a URL change and resetting the window's y position to 0. This is minor, but the whole flow of the app feels off because of it - you should just write a comment, and it should scroll to it.

Tested on a desktop computer with Google Chrome running Windows 10 on game pages.

**Comment by YLivay** [comment]
this shouldnt happen anymore. no more reflows >:D
reopen if this is still an issue
