### ISSUE TITLE
Add size requirements for thumbnail/header images when creating/editing a game

### ISSUE THREAD

**Issue by nilllzz** [gamejolt/issue-tracker#1007]
Currently, when you are uploading a new thumbnail/header image for a game, the rules that apply to these images are either not at all or very vaguely represented by a text on the right side of the screen.

The specific rules like size and aspect ratio restrictions should be made clear on the upload page.

**Comment by Tricky1975** [comment]
Should we copy this one to gj-improve?

**Comment by niksudan** [comment]
Yeah, move this one over, please.

**Comment by Tricky1975** [comment]
[done](https://gamejolt.com/f/add-size-requirements-for-thumbnail-header-images-when-creating-editing-a-game/341371?sort=active)
