### ISSUE TITLE
Pay what you want HTML5 game doesn't play when selecting "No thanks, take me to download"

### ISSUE THREAD

**Issue by NathanAuckett** [gamejolt/issue-tracker#1009]
Tried to play this game: https://gamejolt.com/games/hinohomo/289542
It's a pay what you want HTML5 game.
Pressed play, asked for money, selected "No thanks, take me to download", and it tried to take me to a download. It's a HTML5 game though so no download begins nor does the game open in browser.

Tried on both chrome and firefox. Both have the issue.

**Comment by YLivay** [comment]
this is fixed
