### ISSUE TITLE
Can't uninstall Game Jolt Client..

### ISSUE THREAD

**Issue by RandomisWeird** [gamejolt/issue-tracker#1010]
So Game Jolt Client is just not cooperating with me and never really has. So I've just decided to "throw it out." Problem with that, it won't let me..
I go to the Control Panel and press **uninstall** on it. It asks if I'm sure and I press **yes.** Then after, it says _**Uninstall has detected that Game Jolt is currently running**_ _(which it isn't)._ _**Please close all instances of it now, then click OK to continue, or Cancel to exit.**_
I don't know why it says that. I've double checked, triple checked and all to make sure I don't have it open but there's nothing open. I kept trying but the same thing keeps popping up. Is there something I'm doing wrong or is it just glitched? What do I do?
I have a Windows 10 if that matters.

**Comment by YLivay** [comment]
Do you see game jolt client in your task manager? or joltron (the client game runner)?
If so, just force close them and uninstall again.

**Comment by YLivay** [comment]
closed for inactivity

**Comment by XxCharlesJustRoblox** [comment]
oooooooooooo

**Comment by Tomfelkerytube** [comment]
uhmm when i tried to delete it deleted itself but i think windows 11 is better to uninstall gamejolt client
.
