### ISSUE TITLE
Clicking on a user's name from one of their games does nothing

### ISSUE THREAD

**Issue by MagikGimp** [gamejolt/issue-tracker#1011]
The intended action would surely be to link to a list of all that user's games they've submitted to Game Jolt? It is possible to search for a user and then click Library > Developer's Games which is the page to where, I would suggest, clicking their name goes.

**Comment by hworld** [comment]
Do you mean in the grid/thumbnail view when browsing a list of games? You want to click the name of the dev to get to the user's page?

**Comment by MagikGimp** [comment]
No, I'm referring to just a regular game page. You've got the name of the game and under that the name of the user that made it but clicking that does nothing. I'd have thought clicking that would take you to a list of all their game or at least their account page. Or perhaps I'm overlooking something here; or my client's just busted?

**Comment by YLivay** [comment]
I can't reproduce this. Has this been fixed?
