### ISSUE TITLE
Analytics = 404

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#1013]
Through a browser you get a "page not found", when you use the client people say nothing will happen at all when you click the link.

**Comment by hworld** [comment]
i believe we fixed this. was a collaborators change

**Comment by Tricky1975** [comment]
I actually forgot about this issue, and I did visit my own analytics for my Fairy Tale REVAMPED game without any trouble, so I guess, it’s fixed indeed.
