### ISSUE TITLE
Collaborator Enhancements

### ISSUE THREAD

**Issue by niksudan** [gamejolt/issue-tracker#1015]
Excellent work on collaborator support! However, I don't see a place where you can see a game's collaborators or a user's collaborations. Here are my thoughts:

### Collaborator Credits
You should encourage collaboration, so the best way to do so is to make them appear everywhere! Rather than typing out the credits in the description or in-game, users can view a list of collaborators. This could be in the "details" section of the page, with respective links and avatars to each profile.

You should be able to set what kind of credit, e.g. "Artist", "Musician", etc. This could either be from a list of predefined roles or a custom text field.

You should be able to re-order the list of credits too.

### Public and Private Collaborations
Sometimes you want to add people and not make them appear publically. The owner of the game should be able to show if the user appears on the game page via a checkbox, similar to how GitHub does this with organisations (but owner-side, not user-side).

### User Profiles
Public collaborations should either be merged in with the user's game listing or split out in a separate section. Whatever the case, this should also make use of the credit title so people know what role they had.

**Comment by hworld** [comment]
Wanna add these suggestions as different topics to the new "gj-improve" forum with voting on it? https://gamejolt.com/f/gj-improve

**Comment by niksudan** [comment]
Sure thing!

**Comment by niksudan** [comment]
Here's a link to the thread for future reference - https://gamejolt.com/f/collaborator-enhancements/341341
