### ISSUE TITLE
Leaderboard in game doesn't display unique scores

### ISSUE THREAD

**Issue by MaskofThoro** [gamejolt/issue-tracker#1016]
"I have a problem with leaderboards in my Game Jolt game (it's unpublished, https://gamejolt.com/games/raftraftraft/293245). If I enable Unique Scores on a table, no scores are listed at all. But if I disable Unique Scores, they're all there again (and when looking at my personal scores, they're all displayed there as well).
This doesn't seem right, could you look into it?"

**Comment by YLivay** [comment]
this is fixed, but need to backfill the old unique scores. this broke around a month ago :(

**Comment by MuNgLo** [comment]
So would a new scoreboard work?
Will the old ones be backfilled and if so how long will it take?

**Comment by YLivay** [comment]
Fixed
