### ISSUE TITLE
Hovering over a user's name should also display profile hovercard

### ISSUE THREAD

**Issue by niksudan** [gamejolt/issue-tracker#1019]
From a usability point of view it makes sense to have this effect whenever you hover over anything to do with the user, rather than just the avatar. The clickable name should at least have this to incentivize following for all cases when someone would go to view a user profile.

**Comment by hworld** [comment]
WHich places?

**Comment by niksudan** [comment]
I encountered this whilst browsing through game comments.

**Comment by Tricky1975** [comment]
Since I deem this a cosmetic improvement I copied this one here >> https://gamejolt.com/f/hovering-over-a-user-s-name-should-also-display-profile-hovercard-cosmetic-suggestion/341370?sort=active
