### ISSUE TITLE
Unnecessary follower count in profile hovercard

### ISSUE THREAD

**Issue by niksudan** [gamejolt/issue-tracker#1020]
You already show the number of followers to the right of the button - there's no need to show it again below.

![image](https://user-images.githubusercontent.com/6004491/32352839-d76f444c-c01a-11e7-8e28-1b2bea2500d6.png)

Additionally, when there are users with no games or videos it only shows the followers statistic. Seems like a waste of space in the white area, and also makes the card feel unnecessarily big.

![image](https://user-images.githubusercontent.com/6004491/32352815-b2961862-c01a-11e7-9eaf-280492ecf5b9.png)

**Comment by hworld** [comment]
Because I want it clickable in the future to see who the followers are. Just haven't finished that page yet.
