### ISSUE TITLE
Feed notification issue

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#1023]
When I receive a new feed for a game I follow I don't see it when I click the notification icon, but I see my old feeds in stead. I have to use my browser's renew button to actually see the feed.

(tried on Google Chrome for Mac).

**Comment by hworld** [comment]
still happening?

**Comment by Tricky1975** [comment]
Last time I checked... no

**Comment by YLivay** [comment]
ah i remember this one, this should've been fixed ages ago.
