### ISSUE TITLE
Not able to reset image upload with same filename even though the image is different.

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#1024]
![image](https://user-images.githubusercontent.com/11202073/32406250-40f1e7ac-c175-11e7-9834-6f1f2eb54b85.png)

Okay, so I'll enlarge the picture and choose it again, and what happens?

![image](https://user-images.githubusercontent.com/11202073/32406257-748b1a02-c175-11e7-8a4f-3cd7d27372a8.png)

Renewing the page completely and then starting to upload "fixes" the issue

**Comment by hworld** [comment]
Is this only safari? Firefox seems to work now. @Tricky1975 ?

**Comment by Tricky1975** [comment]
I think I was using Opera back then... I should try this again
