### ISSUE TITLE
Installers and non-installers same package -OR- Buy one package and automatically get another for free

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#1025]
I know there's #594, but as I'm not sure it's a good idea to handle installers through the client in general....

I came past a Marketplace developer who does want an installer for non-client users, but to have a zip for client users, but due to not being able to upload two builds for the same OS in one package, he's a bit stuck, as the only way to solved is uploading multiple packages... Buy the wrong one and ... oops. Now I believe there are free keycodes to be generated to give to buys, but I guess having to do this manually ain't gonna work, so if installers and zips for the same platform can live together _*OR*_ if we can put in a system that makes you get package b for free if you buy package a (and vice versa)... I guess the problem could be solved.

[Forum thread that brought me to this issue](https://gamejolt.com/f/can-t-install-my-game-through-the-client/339078?page=1)

**Comment by YLivay** [comment]
Add installers to the same package as other build for now.
We have support for installers planned, and it has its own issue #516 
We're not going to do buy one package get another at this point.

**Comment by Tricky1975** [comment]
Problem... that is impossible!!!!
Both the installer and the zip will be for the same platform and the system blocks that, so you closed this issue way too soon, mister!

**Comment by YLivay** [comment]
nono sir, part of the installer support will of course be this.
Also, at that time we'll also add support for tagging which builds should be runnable from the client, don't worry :)

**Comment by Tricky1975** [comment]
Could you be a bit more clearer, as that made little sense to me, I’m sorry.
