### ISSUE TITLE
Un-canceling game produces internal server error

### ISSUE THREAD

**Issue by NathanAuckett** [gamejolt/issue-tracker#1026]
"Whenever i try to un-cancel my game, i get this error.
https://imgur.com/a/pYKSs

I don't know if anyone else is witnessing this issue, but Id really like to have it fixed soon. I need to make my game visible again, and Id rather not have to make a new page!"

**Comment by YLivay** [comment]
which game?

**Comment by NathanAuckett** [comment]
They didn't say, that is a comment made on the gamejolt devlog by user, "Egg_Sandvich".

**Comment by Tricky1975** [comment]
[I now received a complained the server error also happens when canceling a game](https://gamejolt.com/f/error-when-trying-to-cancel-game/341220)

**Comment by nilllzz** [comment]
Fixed, both canceling and un-canceling.
