### ISSUE TITLE
Two character username fails to log in.

### ISSUE THREAD

**Issue by NathanAuckett** [gamejolt/issue-tracker#1027]
A user was unable to log in and was getting the "Username you've entered is invalid" error due to having an old 2 character username.
Had to change the users name to something longer for them to regain access to their account.

Possible some new username rules have produced this error? The user was logging in for the first time in 9 months.

The user: https://gamejolt.com/@victor_k

**Comment by YLivay** [comment]
was this user's username actually still that short version? we forced usernames to conform to the site rules a few months ago.  emails were sent out to people whose username has changed. What was his previous username, do you remember?

**Comment by NathanAuckett** [comment]
I pretty sure his name was just VK or something. It was a two character name I know that much.
