### ISSUE TITLE
Link external site shows blank screen in site previewer

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#1028]
Let's just put it this way, when you put in a link in your own site, it shows immediately on the instant previewer. Let's just behave like an idiot and click it and well, this is what will happen:

![image](https://user-images.githubusercontent.com/11202073/32571417-9100f594-c4c7-11e7-8667-9b8411dbc5c5.png)

This only happens when linking to sites that are not part of Game Jolt, as the button to my personal page on Game Jolt works. Now that is also using the sites features, as I haven't yet tried links to the forums or anything cheesy like that. :-/

**Comment by YLivay** [comment]
I'm not sure what's expected to happen in those cases. should we just disable links in preview? as in.. they'll have the correct styling but empty href? what about anchor tags?

**Comment by hworld** [comment]
too hard, i think. gonna say "wontfix" just because it'll be a lot of effort for little gains
