### ISSUE TITLE
Sending button ignore issue

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#1029]
I've noticed this on the forums, but also in comment sections and I deem it likely this affects other features as well. I press the button to send the message, but nothing happens. Clicking it multiple times will eventually cause whatever was supposed to happen to happen.

**Comment by YLivay** [comment]
Just clarifying, do you mean the button just doesnt do anything? or does it pretend it sended something (showed  some  animation or whatever) but nothing happened? how often does it happen? any pages specifically?

**Comment by Tricky1975** [comment]
Just nothing happens… I see the button flash, meaning an event is properly created, but after that… nothing. I often get a ‘check’ or ‘v’ or whachamacallit once the system actually registered my request and sends it,but that often takes multiple clicks or holding my mouse button a little longer (mostly after multiple clicks). 

I’ve suffered most on the forums, but I have also been “struck” by this issue in comment sections, my DevLog editor, the button to release the new builds of my games. The ‘game description’ editor and so on, basically any send button.

When I posted it I had a 100% score of this issue happening on the forums, and about 60% on comment sections and other sections, at the present time it happens much less, but occasionally I still see this happen.

**Comment by YLivay** [comment]
which browser are you using? and please dont say opera.

**Comment by Tricky1975** [comment]
Currently Google Chrome, but I had this issue in Opera too.

**Comment by Tricky1975** [comment]
In that case I would have seen my posts appear among the spam messages on the moderation overviews, which doesn't happen.

**Comment by YLivay** [comment]
This may have been a transition that was set on the button. We've removed it recently, does this issue still happen?

**Comment by Tricky1975** [comment]
At the current time, no... At least not the past few days.
