### ISSUE TITLE
NEW IDEA FOR GAMEJOLT CLIENT

### ISSUE THREAD

**Issue by Topnikov** [gamejolt/issue-tracker#1030]
**It is necessary to add an animation of the picture of the game when users upload the game with the animation of the picture to the sketch.**

**Comment by YLivay** [comment]
What do you mean "to the sketch"? you mean like.. see a preview of your game thumbnail as it will appear in listings?

**Comment by Dragonify** [comment]
I'm here just to give a small idea and continue this thread. I think it's like a gameplay preview? When player points his/her mouse to the thumbnail of game? Just like YouTube? I don't know, just giving the idea.

**Comment by niksudan** [comment]
Thumbnails will animate anyway if you upload a GIF, so that would conflict.

**Comment by niksudan** [comment]
Since @Topnikov hasn't got back with clarification, I'm going to go ahead and close this.

If you'd like to make a feature request, please submit a thread on [the improvement forum](https://gamejolt.com/f/gj-improve), where users can vote for it.
