### ISSUE TITLE
User view on homepage load is annoying

### ISSUE THREAD

**Issue by YLivay** [gamejolt/issue-tracker#1032]
When you land on the home page, until the user is loaded you see the guest view, so after a split second when your userr loads in the page changes and shifts around. The what is gamejolt banner disappears, the side menu scroll appears as items load in, the top nav adds your avatar activity and  notifications, chat loads in. This is bad UX, we should aim for content to shift around as little as possible.

Is there a way to minimize things moving around without having to wait for the user? alternatively, should we try making the user and guest view more similar? the guest banner pushes games too far down anyways imo.

For the side scroll bar we can make it only appear when hovered.
For the game channels/categories - we can reserve vertical space waiting for the actual categories to load in instead of shifting content down when it appears.

**Comment by hworld** [comment]
this was fixed

**Comment by hworld** [comment]
although for guests it pops in, but yeahhhh
