### ISSUE TITLE
Game Jolt client won't uninstall and isn't even running at all

### ISSUE THREAD

**Issue by ragequitkatie90** [gamejolt/issue-tracker#1033]
I have tried to uninstall Game Jolt, but it says that I have games running. I have even checked my task manager, and there is nothing even related to Game Jolt running at all on my computer. Please help me!!!!

**Comment by YLivay** [comment]
the uninstaller is not concerned with running games at all, how are you attempting to uninstall? can you show a print screen of what you mean?

**Comment by YLivay** [comment]
closed for inactivity
