### ISSUE TITLE
Clicking on the reference link coming to a reply to a deleted forum post --> 404

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#1034]
When a post somebody replies to is deleted by a moderator, the reply remains. The link to the original post in that reply would then just say "This post has been removed", or something like that.

This doesn't happen any more, in stead you just get a 404 page.

**Comment by YLivay** [comment]
Need to remove the link in the post that remains. Tho if you replied to a comment that is removed maybe we should remove the reply as well? hmm...

**Comment by Tricky1975** [comment]
That could work in comments, but in forum posts it's quite common the reply post does not always act as a reply to the original post, but also makes other statements (that kind of behavior is actually encouraged on most forum sites when you have multiple statements to make in order to prevent a lot of needless "double-posts" as that is usually frowned upon), and deleting the reply would then remove those statements as well. Perhaps 'reply to removed post' can do if any confusion needs to be out of the way. (I'm a veteran when it comes to forums, you know). ;)

**Comment by YLivay** [comment]
@hworld Bump! So, should we hide the replies? prevent removing/editing posts that have replies? indicate that the reply has been removed instead of 404ing? maybe make the replies top level posts? What do you think we should do?

We clear the notifications for any further replies.
