### ISSUE TITLE
Issue with removing older builds

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#1035]
[![image](https://user-images.githubusercontent.com/11202073/33095694-d512a5b0-cf04-11e7-8ca8-9aadefed94c1.png)](https://gamejolt.com/f/internal-server-error-when-trying-to-remove-old-game-packages/340865)

Click the image for the real forum thread

**Comment by nilllzz** [comment]
I tried reproducing this with the exact game/package in question and it worked for me.

**Comment by Tricky1975** [comment]
I guess it’s waiting then for the creator of that forum thread to respond.
I’m just the messenger.

**Comment by hworld** [comment]
Think I can close this then?

**Comment by Tricky1975** [comment]
Yup! I shall close it myself so I can reopen it if the poster of that thread shows his face again. ;)

**Comment by Tricky1975** [comment]
[Okay, I didn't expect this would happen so soon when I posted that. In fact I didn't expect it to happen at all, but he made another acquaintance. I shall re-open this issue for now, I can always close it again when he stays away for too long](https://gamejolt.com/x/permalink/forum-post/435699)
