### ISSUE TITLE
Clickteam Fustion HTML5 games appear to be broken.

### ISSUE THREAD

**Issue by NathanAuckett** [gamejolt/issue-tracker#1036]
User emailed support stating Clickteam Fusion HTML5 games are broken. Here is the email:
"
Hi,
I have noticed that HTML5 games exported from Clickteam Fusion are not working on Game Jolt.
They used to work, but now whenever you try to load one, it just displays a white screen and there is an error 400 in the console.

The following games are among those which are affected:

https://gamejolt.com/games/bro-tastic/258385
https://gamejolt.com/games/magic-bricks/201460
https://gamejolt.com/games/cupcakeescape/249530
https://gamejolt.com/games/RUNaway/253238
https://gamejolt.com/games/catchmeifyoucan/249492
https://gamejolt.com/games/hideandseek/249351
"

Can confirm the games get stuck on a white screen. Don't know if it's a Game Jolt issue for a Clickteam issue. That is for a dev to decide.

**Comment by YLivay** [comment]
This is an issue on either our, the cdn or amazon's end. Something is not accepting encoded urls correctly. Will check into this asap

**Comment by hworld** [comment]
Was fixed a bit ago and I forgot to close
