### ISSUE TITLE
Suggestion: Promotional mail platform setting

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#1037]
I’ve received a message from a rather angry user who gets tons of promotional mails about games, which are all for Windows, but tada, he’s a Linux user. Of course, there’s Wine, but I can understand it’s preferable that all the promotional mail he gets is about games he can play on Linux without need of VMs or emulators. Now he considers these mails as they are about games he can’t play anyway as “spam”. 

His idea was to put the filters you can use for searches, like this
Platform:
- [ ] Windows
- [ ] Linux
- [ ] Mac
In settings for e-mails as well, but he couldn’t find those features and neither could I.
Since we cannot blindly assume any more most people are Microsoft users, I suppose some dedicated settings could be in order.

**Comment by YLivay** [comment]
For now he can turn off newsletter or filter it out in his mailer.
Looking at it realisticly, mac/linux usage is abysmal compared to windows and this won't be a straightforward thing to implement in our current set up at all. Can't say when we can get to this.

@hworld mind chiming in?

**Comment by niksudan** [comment]
Discussion for this has migrated to the gj-improve forum.

https://gamejolt.com/f/platform-preference-in-mailing-settings/341181
