### ISSUE TITLE
quick play does not work

### ISSUE THREAD

**Issue by helekron** [gamejolt/issue-tracker#1039]
ive noticed that quick play using the client wont load, but using quick play on the browser is just fine.

**Comment by YLivay** [comment]
hey, quick play should actually open the game to play in the browser, and that seems to work. what is actually happening for you? can you specify which game you've encountered the issue?

**Comment by helekron** [comment]
hello. it seems that it doesnt open in the browser when selecting quickplay. this might be a permissions problem, or something to do with my personal settings. as for which game its been all quickplay ones.

**Comment by hworld** [comment]
We pushed out a new client. It will say v0.13.0 or higher in the footer. Are you able to test again?

**Comment by helekron** [comment]
yes it seems to work now! thank you.
