### ISSUE TITLE
Some advanced improvements in Game Jolt Cilent please :)

### ISSUE THREAD

**Issue by Dragonify** [gamejolt/issue-tracker#1040]
Hmm... My country's internet is very slow, so game download failure is very normal in here. But there's a bug in Game Jolt Cilent that **every time I restart the download, the progress will automatically drop back to 0%**. Please fix that! I'm starting to get mad because of that!

Oh, and also, can you add a option that can **change the browser** (eg. Chrome, Firefox, Edge) when **click a external link** in Game Jolt Cilent? That will be good if that's possible.

**Comment by YLivay** [comment]
hey, thanks for reporting. the client should definitely be able to resume a download. Does this happen every time? or just for specific games?

As for setting a browser - it will use the default browser specified by your OS, we don't specifically tell the client which browser to use.

**Comment by Dragonify** [comment]
I try it on other games and I think it happen every time download every time. And as for the browser thing, i didn't know that before, so sorry about that :)

Also I forgot to mention before, will Game Jolt Cilent opens with windowed fullscreen? 'Cause mine doesn't. Or it is a default setting by my OS again? If it is, I'm kind of stupid right now XD. If it's not, should change that or make an option for every users.

**Comment by hworld** [comment]
@YLivay does this work now? Does it resume properly?

**Comment by Dragonify** [comment]
@hworld No, it doesn't resume properly still......

**Comment by YLivay** [comment]
how aboooouut now?
