### ISSUE TITLE
Developers can follow their own games

### ISSUE THREAD

**Issue by nilllzz** [gamejolt/issue-tracker#1041]
Developers can follow their own games, which does not make much sense.
This should be fixed...

**Comment by Tricky1975** [comment]
I've known that for ages (I even tried this), but as it felt like... er.... masturbating in public... I quickly unfollowed my game...

**Comment by niksudan** [comment]
I say if it feels good, do it.

**Comment by nilllzz** [comment]
Concluded this is working as intended.
