### ISSUE TITLE
Analytics may not be working for game pages for the dev

### ISSUE THREAD

**Issue by hworld** [gamejolt/issue-tracker#1042]
Detailed here: https://gamejolt.com/f/no-data-in-google-analytics/341256

**Comment by JoPed** [comment]
Any news on this, I see you removed the bug label.

**Comment by hworld** [comment]
Sorry, I only removed the "bug" label because everything in this tracker is a bug now.

**Comment by hworld** [comment]
k, so I checked the commands being sent to GA through their debugger and it's definitely creating the tracker correctly and sending the page view data over. I then set up a new Property for testing and attached it to a game page, went to the real time tab, and it was marked there.

It could be one of many reasons. It may be a bot that had the traffic and we didn't filter it out as well as GA was able to. If you access the page as a guest, can you see if it shows the data?

**Comment by JoPed** [comment]
I got a friend to visit a devlog, and nothing shows in GA. Is the because it only works with the game page and not the devlog?
