### ISSUE TITLE
gj-improve top sorting broken

### ISSUE THREAD

**Issue by CyberKiller40** [gamejolt/issue-tracker#1049]
The 'top' sorting option in the new improvements forum doesn't work correctly. Vide screenshot:
![7afd2c48-0d5f-47b1-bbe9-f6193fb78b33](https://user-images.githubusercontent.com/4402309/33654387-36167d02-da70-11e7-930b-73046af36172.png)
It should sort the topics by the highest number of votes, as I understand, right now it looks random.

**Comment by Tricky1975** [comment]
CROS has explained to me how this works and as far as I could calculate it it works as it should, as not only the likes but also the number of replies are being taken up in the sort.

The math works like this:
~~~
l+2r 
~~~

In which l means likes and r means replies.
It might be possible though a better formula is in order as this formula looks confusing indeed ;)

**Comment by CyberKiller40** [comment]
Hmm... well in this case the sorting is actually ok, but without knowing the formula it looks very random.

**Comment by niksudan** [comment]
> not only the likes but also the number of replies are being taken up in the sort

I would say this is fine with every other forum channel except gj-improve. The number of votes should equal the final order.

**Comment by Tricky1975** [comment]
> but without knowing the formula it looks very random.

I agree on that one

**Comment by hworld** [comment]
Maybe "top" shouldn't look at replies, but only votes? Active can look at both.

**Comment by hworld** [comment]
Actually, I do like the idea of "top" only looking at votes. it seems to make way more sense, but active should look at date of last vote or reply

**Comment by hworld** [comment]
k, we changed this to use only votes when showing top
