### ISSUE TITLE
I can unfriend myself

### ISSUE THREAD

**Issue by MaskofThoro** [gamejolt/issue-tracker#1050]
![image](https://user-images.githubusercontent.com/10214401/33670043-4811a2ca-da61-11e7-9f12-7008f31805fc.png)

**Comment by Tricky1975** [comment]
Odd... I can't
![image](https://user-images.githubusercontent.com/11202073/33671562-369a2066-daa8-11e7-8cda-229af81971ca.png)

**Comment by niksudan** [comment]
This occurs if you view another user's profile directly prior to visiting yours.

**Comment by nilllzz** [comment]
@niksudan hm, I tried this and I can't seem to replicate this. Is this consistent/does it happen with all users?

**Comment by niksudan** [comment]
@nilllzz You need to be friends with the user's profile you visit first. Here's a GIF of it in action, with me refreshing at the end.

![2017-12-07 09 53 31](https://user-images.githubusercontent.com/6004491/33709210-89e0420a-db34-11e7-95c2-e10897590a73.gif)
