### ISSUE TITLE
Closed threads in GJ-IMPROVE can be upvoted

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#1051]
Is this a good or a bad thing, I wonder.
It can be good as I can then close a thread that is going into an out-of-hand-discussion, but can then still be upvoted? Or is it a bad thing...

I plan to move suggestions that are either implemented already or being definitely rejected to gj-archive to allow those threads to "die" and not spooking up the currently open suggestions.

**Comment by niksudan** [comment]
There needs to be a way to 'archive' a thread in this forum. Deleting would work, but it would be nice for users to see which ones were implemented. Here's my proposal:

- If a thread is locked, don't display it in any of the tabs
- (Optional) Create a new tab (e.g. "Archived"), and show locked threads in there
- (Optional) We can prefix ones that have been added with "[ADDED]" via title editing

**Comment by Tricky1975** [comment]
I strongly support the idea of an "Archived" tab, and maybe closed threads should indeed be moved there. At least as far as gj-improve is concerned as on the other channels I don't think it will do much good

**Comment by hworld** [comment]
Yeah, I think it only makes sense for voting type channels to have an archive thread. Anything locked would go there. I guess this should be moved to the forum since it's now a feature request? hahaha

**Comment by Tricky1975** [comment]
>  guess this should be moved to the forum since it's now a feature request?

Ain't it a joke? 😛

**Comment by Tricky1975** [comment]
Since this suggestion ( https://gamejolt.com/f/delete-your-own-comments/341381?sort=active ) is already implemented, I've closed it. Perfect chance now to test the archive tab, and that's why I didn't delete it. :P

**Comment by hworld** [comment]
Yeah, we'll probably do this in a bit. Maybe next week or something. We want to get the Client out today.

**Comment by Tricky1975** [comment]
Really? Kewl!

**Comment by nilllzz** [comment]
Implemented, will push out with next release.
