### ISSUE TITLE
Not an issue for me, but I think it's worth to tell you.

### ISSUE THREAD

**Issue by Anzu420** [gamejolt/issue-tracker#1056]
Hi! I'm the creator of dungeon 51, and recently I changed the status of my game from "in development" into "complete", my game had about 800 plays when I did that. So I think by doing that, the system thought I got all of those plays in one second and immediately put my game on the hot page. I would love for it to be there but I have to admit it was probably only a glitch.

Thank you!

**Comment by YLivay** [comment]
Hey, thanks for reporting, and sorry for the slow response. This was by design back then but has since been tweaked :)
