### ISSUE TITLE
Download count doesn't show up on a specific game page

### ISSUE THREAD

**Issue by YLivay** [gamejolt/issue-tracker#1060]
Reported by `@🎄Spencer Eldridge🎄#5990 ` on our Discord, his game doesn't have a download count:
https://gamejolt.com/games/puppetsofreprisal/140059

It may have something to do with him removing his package every time he publishes a new release. Needs more digging into.

**Comment by hworld** [comment]
It's gotta be because their primary package is set to a paid one. We have to make sure it never gets into this scenario, though.
