### ISSUE TITLE
Internal server error changing payment type from free to paid

### ISSUE THREAD

**Issue by YLivay** [gamejolt/issue-tracker#1061]
Reported by `@Facundo#2873 ` on our Discord.
This is the game: https://gamejolt.com/games/snake-eyes-dungeon/147564

**Comment by nilllzz** [comment]
Go do it yourself >:(

**Comment by YLivay** [comment]
This has been solved, the issue was treating removed html builds as active when attempting to change payment types. since selling html games isn't supported yet - it freaked out.
