### ISSUE TITLE
The user photo is overlaid in the profile settings

### ISSUE THREAD

**Issue by SavanDev** [gamejolt/issue-tracker#1062]
Navigating in the configuration of my account, I came to observe this small problem.

![imagen](https://user-images.githubusercontent.com/20217646/33923539-81d4925c-dfb0-11e7-9ea2-64f287116bf6.png)

**Comment by hworld** [comment]
fixed in this commit: https://github.com/gamejolt/gamejolt/commit/6f139b98af2238765e5a749e68e02896ee451b0c
