### ISSUE TITLE
Autosizing of text box doesn't seem to be working.

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#1065]
When I want to edit my bio I get only 1 lines of text of it, because my textbox ain't bigger. Trying to resize it with the browsers resize features do no good. So I have to look up the section I wanna edit line by line. When I found it and actually edit it I *MAY* (if I'm lucky) get a bigger textbox. 

I've seen this most of all in the bio editor, I also vaguely remember seeing this in the site-editor and game description editor.

**Comment by YLivay** [comment]
This is very odd. Which browser are we talking about?
We use a normal not at all fancy html text box element for this. it should behave.

**Comment by Tricky1975** [comment]
Chrome on Mac

**Comment by YLivay** [comment]
@hworld can you try replicating this?
