### ISSUE TITLE
Thread list pagination gone

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#1066]
Where is it?
![image](https://user-images.githubusercontent.com/11202073/34077646-1060aa64-e309-11e7-8667-e81293d5527d.png)

**Comment by Tricky1975** [comment]
Since the first dupes in gj-improve are appearing now as people cannot find the original threads thanks to this bug, I think a bit more priority to get this fixed is in order.

Sorry if I am being a jerk now.

**Comment by Tricky1975** [comment]
Further investigation shows that when I force my way to later pages (by altering urls. Ah, so good to have experience as a webmaster) :P that the "next page" button does not appear, but the "previous page" button does.

**Comment by YLivay** [comment]
Fixed, will be live on next push (probably in a few hours)
