### ISSUE TITLE
Release Analayitcs button leads to a "bad request" page.

### ISSUE THREAD

**Issue by NathanAuckett** [gamejolt/issue-tracker#1067]
Clicking the "Analytics" button ( http://prntscr.com/hopwq8 ) on a Release leads to a bad request page.
http://prntscr.com/hopx0m

This applies to any game as the error was reported by a user and reproduced by me.

**Comment by YLivay** [comment]
The issue is the analytics page requests wrong metrics for the resource type - there's no context of purchases for a release - just for pages.

I'm on it.

**Comment by YLivay** [comment]
Fixed, will work on next deploy.
