### ISSUE TITLE
Problem with name display when someone buys a game

### ISSUE THREAD

**Issue by NathanAuckett** [gamejolt/issue-tracker#1073]
Email to contact@gamejolt from user: https://gamejolt.com/@c12152
"I think your website is currently experiencing a problem with name display when someone buys a game.
It only displays my own username when someone download my game, as if I literally bought my own game.
It happened twice in a row so far. The only indication I had ( that it's actually someone else who bought it ) was in my notification email."

**Comment by YLivay** [comment]
This has been solved, thanks.
