### ISSUE TITLE
Endless Processing

### ISSUE THREAD

**Issue by dalegdawg** [gamejolt/issue-tracker#1074]
Hi,

I uploaded a few game files recently (2 downloadable and 1 html) to one of my game packages.

The downloadable files are fine but the html version has been processing for a whole day and hasn't stopped yet.

I removed it and tried again just in case there was an issue with it but it's still not processing.

The file size of the html version is 263MB if that helps.

![image](https://user-images.githubusercontent.com/30841350/34322037-9dafd420-e814-11e7-811f-0263becbf93e.png)

**Comment by YLivay** [comment]
Hey, looks like the archive you uploaded doesn't have an index.html in the root or first directory of the archive.
