### ISSUE TITLE
When there is only a few comments in the comment section of a devlog-only game, all functionality appears lost.

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#1077]
![image](https://user-images.githubusercontent.com/11202073/34410556-6f45bdf0-ebd1-11e7-81aa-c5e4513fd2a5.png)

And this screenshot shows that only half my message can be read. No I don't get the full message when clicking it, nor are there any links doing so. If there are more comments (I believe more than three) a "read all others" link appears and then we got full functionality.
(Moderation functions are also not available due to this bug, nor can my comment be reported until there are more comments posted causing the "read all" link to appear).

(Oh yeah, the message I wrote is in French since the developer of that specific game is french). ;)

**Comment by hworld** [comment]
Hmmm, I think you can click the Comments tab in the navbar? Either way, this will be changing really soon with the new-ish game page design that combines games and devlogs into one design

**Comment by Tricky1975** [comment]
Nope, no comment in the navbar. Only the main page and DevLogs (if a DevLog is written that is).
