### ISSUE TITLE
Following game doesn't work

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#1078]
I get an "Oh no!" message, which was out of my screen so fast I couldn't read it.
A forum user brought this to my attention and I tried to follow a game to confirm it and confirmed it I have.

**Comment by Mikolaj** [comment]
Yep, I'm getting "Internal Server Error" when I try to follow my own (just published) game.

**Comment by hworld** [comment]
This has been fixed. The issue was a faulty deploy to the servers where all the code didn't end up going out.

**Comment by Mikolaj** [comment]
Yep, it works for me now. Thank you!

**Comment by Tricky1975** [comment]
:happy: Happy happy joy joy :happy:
