### ISSUE TITLE
Hovers for likes on devlogs show mustaches

### ISSUE THREAD

**Issue by Fappp** [gamejolt/issue-tracker#1080]
![afbeelding](https://user-images.githubusercontent.com/6286901/34537383-80928e2a-f0c8-11e7-8010-cb04d50f3af7.png)

**Comment by YLivay** [comment]
@hworld the code seems fine - the translations are outdated?

**Comment by Fappp** [comment]
@YLivay It seems other instances of {{$count | number }} are working. FYI, I was viewing the site in English.

**Comment by YLivay** [comment]
The translations are just outdated like I said. uses old angular memes. We'll handle this
