### ISSUE TITLE
Reply button URL is not absolute in email for comments

### ISSUE THREAD

**Issue by Fappp** [gamejolt/issue-tracker#1084]
When receiving comment notifications over mail the path for the reply button is not absolute.
![image](https://user-images.githubusercontent.com/6286901/34710780-ef1d0674-f51c-11e7-8c80-f5b5c49845e6.png)

**Comment by Fappp** [comment]
This might've been incidental, a later email did offer a proper absolute URL.
![afbeelding](https://user-images.githubusercontent.com/6286901/34719358-d4e2aa5c-f53a-11e7-987e-ed596475de24.png)

**Comment by Fappp** [comment]
The only noticeable difference between the two mails is that the one with error contained a youtube link,

**Comment by YLivay** [comment]
I believe we fixed this a few hours ago heh. If this happens again comment here and i'll reopen.
