### ISSUE TITLE
When choosing indie.af I get "Page Not Found"

### ISSUE THREAD

**Issue by Mikolaj** [gamejolt/issue-tracker#1085]
When I go to https://gamejolt.com/dashboard/site/domain and choose the indie.af option and Save, I get "Page Not Found. You found a secret! But on further inspection, you realize it's just an empty page.".

It may or may not be related to the fact that I've chosen indie.af for my game first (which doesn't work either).

**Comment by NathanAuckett** [comment]
This issue extends to simply turning on the portfolio site as well. Pressing "turn on" takes you to a page not found error.

**Comment by Mikolaj** [comment]
It almost works for me now, but when trying to view the https://funktory.indie.af/allureofthestars/ site, I get "Unable to connect".

**Comment by hworld** [comment]
Sadly, indie.af doesn't work on https, which is why you're getting this issue for that URL.

**Comment by Mikolaj** [comment]
Noted. However, when I enter http://funktory.indie.af/allureofthestars` (as copied from https://gamejolt.com/dashboard/games/305565/site), it redirects me to https and fails. Only when I enter http://funktory.indie.af/allureofthestars/ (note the trailing slash) it works fine.

**Comment by qwertychouskie** [comment]
Maybe set up HTTPS with Let's Encrypt?

**Comment by Mikolaj** [comment]
@hworld: I can't reopen the issue; should I file a new one? ^^^

**Comment by hworld** [comment]
Reopened it.

**Comment by Mikolaj** [comment]
It now works for me in all configurations: http, https, trailing slash or not. However, the certificate is not valid (it's valid only for other domains), so I need to add a security exception.
