### ISSUE TITLE
Can't mention users with "-"

### ISSUE THREAD

**Issue by freezernick** [gamejolt/issue-tracker#1086]
When a user has a minus in their name the mentioning doesn't work
![firefox_2018-01-14_14-40-36](https://user-images.githubusercontent.com/27819706/34916453-e8796270-f938-11e7-8d2f-53321bf84836.png)

**Comment by YLivay** [comment]
Thanks for reporting, this will be fixed when we replace the markdown compiler we've been using. I don't have an exact ETA but i'm working towards it!

**Comment by YLivay** [comment]
should be fixed along with #1162
