### ISSUE TITLE
too many chats open? where?

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#1088]
![image](https://user-images.githubusercontent.com/11202073/34939159-1c4a3ed2-f9eb-11e7-9464-dfc3f2326973.png)

**Comment by YLivay** [comment]
does refreshing fix it?

**Comment by Tricky1975** [comment]
No, makes it worse! This is the result after closing down my browser while these chats were still in my screen and re-opening it later. (I don't know if it matters but I even closed down my complete system in the meantime, so more fresh than this won't be possible I guess).

**Comment by YLivay** [comment]
So for some reason the chat thinks your session is in the rooms but the frontend doesnt show it to you to close them up. Which browser are you using?

**Comment by Tricky1975** [comment]
Chrome for Mac

**Comment by hworld** [comment]
No longer applicable
