### ISSUE TITLE
Internal server error when trying to recieve game keys

### ISSUE THREAD

**Issue by NathanAuckett** [gamejolt/issue-tracker#1090]
Email report received via contact@gamejolt:
"Well, I went ahead and tried claiming my game again, however every time I do it games up with an 'internal server error' on your part."
"The second I click the claim button it kicks to the internal server error, so I don't retrieve the email."

The user was trying to claim his game keys via: https://gamejolt.com/claim

**Comment by YLivay** [comment]
solved
