### ISSUE TITLE
Inability to install Games

### ISSUE THREAD

**Issue by kordusj** [gamejolt/issue-tracker#1091]
Whenever I go to install a game, I immediatly get an error stating " Oh no! We couldn't download this package. Perhaps check that you're still online?" I have been getting this problem for months now, but trying 4-5 times usually ended in success. Now I can't download anything. I have verified that I am online, I have also reinstalled the platform twice.

**Comment by CatLoverForLife** [comment]
i have the same problem but when i try to install it the game that i attempted to install goes to my library under "installed games" and i am unable to uninstall the game or launch it or install it's just there i don't know what to do

**Comment by YLivay** [comment]
Hey, is this still happening? We've had issues with our CDN we recently managed to work out.

**Comment by CatLoverForLife** [comment]
The problem stopped happening

**Comment by YourlocalytpBlank** [comment]
it is happening to me now, i cannot install ANY games, i can't even download from the website on my browser.
