### ISSUE TITLE
Gamejolt still processing macOS binary for SuperTuxKart after multiple days

### ISSUE THREAD

**Issue by qwertychouskie** [gamejolt/issue-tracker#1093]
https://gamejolt.com/games/supertuxkart-a-kart-racing-game-featuring-tux-friends/230914 was updated to 0.9.3 ~1 week ago, but for some reason the macOS binary is still processing, so the page still shows 0.9.2.  See https://github.com/supertuxkart/stk-code/issues/3102

cc @samuncle

**Comment by YLivay** [comment]
I'm checking this out.
It seems that for some reason the build processing treated this dmg as an archive.

p.s. we don't support installers atm, it also makes the GJ Client fail when people are trying to download your game. You should mark installer builds as "other" for the time being.

**Comment by YLivay** [comment]
Sorry about this, but can you retry uploading the build? it should go through now.

**Comment by auriamg** [comment]
Thanks, it worked, though the "launch options" boxes both say "ERROR 2" (doesn't seem to prevent it from working, though)
