### ISSUE TITLE
Tag to channel redirection bug

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#1095]
In this forum topic:
![image](https://user-images.githubusercontent.com/11202073/35612695-f5a4cd7a-0669-11e8-8a0f-163b081b19ed.png)

I refered to the #analog channel.... Then I clicked it and what happens is this:
![image](https://user-images.githubusercontent.com/11202073/35612713-067f41de-066a-11e8-9a15-1e8e939f0430.png)

When I click the "renew" button
![image](https://user-images.githubusercontent.com/11202073/35612731-1e49485a-066a-11e8-916e-619147977956.png)

I've also tried this with #fnaf where the same issue happens and with #vr, of course, those are tags that actually convert into full game channels. When I tried #femaleprotagonist or #trophy this doesn't happen, but those two tags only have games attached and no full channels.

[This topic was created to test this out](https://gamejolt.com/f/test-ignore-this-topic/342077?sort=active)

**Comment by hworld** [comment]
Gonna track in this issue instead: https://github.com/gamejolt/issue-tracker/issues/1185
