### ISSUE TITLE
Google auto-translate in comment sections does pick up the main comments, but not their replies

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#1096]
![image](https://user-images.githubusercontent.com/11202073/36043908-2a165538-0dd1-11e8-9055-ff8370f9793c.png)

(All original comments were in portuguese, so these are all translations, no exceptions. I don't know why there are so many "no"s in the first comment as that's not what I see in the original comment).

**Comment by hworld** [comment]
I've actually disabled that featured for now. It was complicating the code a lot and making it harder to develop out further. I plan to bring it back in the future, but as a "per-comment" feature instead of translating everything on the page.

**Comment by Tricky1975** [comment]
Ah yeah, I saw a big layout overhaul happened in the comment sections while I was sleeping tonight.
It would be great to have it back, especially in possible flame wars in foreign languages. I may be able to speak two languages fluent and a third language well enough to detect a flame war, but when one breaks out in other languages it will be nice to see how things came to be ;)
