### ISSUE TITLE
Downloading files that can be read by a browser will lead to no action at all

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#1097]
[Take this game for example](https://gamejolt.com/games/9-11-the-game/34310)

The source code is a single Python script which has not been zipped. When I try to download it the site shows the download page and nothing happens. This bug affects everything a browser can read. This has been reported before (and shamelessly been closed as "not an issue"), well I do think it *is* an issue, especially as "other" is concerned. Apparently something happens under the hood, as when non-zipped files happen to be flash or any other kind of file that can hold audio, you can hear the audio play sometimes. Perhaps you need to make sure that whatever kind of file is in a download, it can only be downloaded.

**Comment by YLivay** [comment]
it seems to be downloading just fine on my end. we do send the correct headers to hint the browser to download it instead of "open" it. Which browser are you using?

**Comment by Tricky1975** [comment]
Google Chrome (Mac)

**Comment by YLivay** [comment]
Does this still happen?

**Comment by Tricky1975** [comment]
It appears to be fixed now ;)
