### ISSUE TITLE
A little reply issue in the new commenting routine

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#1098]
It went like this.
- Was was notified somebody commented one of my devlogs
- I clicked the notification
- I was taken to my Devlog and the comment in question popped up with a reply box
- I posted my reply
- The pop-up disappeared, but the original comment was all I saw and no reply
- Renewing the page "fixed" this

Of course, to speak in a very arrogant manner, not everybody is as smart as me and will realize you can renew the page, so I do expect this issue, minor as it may be, can lead to people spamming dupes because they never realized their comment was already there (which I also see happening a lot when Robo Jolt catches a message as potential spam).

**Comment by hworld** [comment]
Should be fixed. I knew about this when pushing, but I didn't think it would be too big of an issue for now since it would be a lot of work to fix. Either way, I fixed it!
