### ISSUE TITLE
Control bar for games that run in browser is white instead of black

### ISSUE THREAD

**Issue by nilllzz** [gamejolt/issue-tracker#1099]
![image](https://user-images.githubusercontent.com/2119926/36324497-f252aa50-1354-11e8-8dfc-b4573d9d8c0a.png)

**Comment by Tricky1975** [comment]
Oh… was that a bug? I thought it was part of the new layout...

**Comment by YLivay** [comment]
I think that's by design. The real issue as you pointed out when we talked is that it's one pixel too low: 
![image](https://user-images.githubusercontent.com/996947/37237980-f53a2a46-2424-11e8-8ec9-475bbd1b4d53.png)

**Comment by hworld** [comment]
I thought this was no fixed

**Comment by hworld** [comment]
Ah, just confirmed it is. Both the background color, and the border not going all the way straight.
