### ISSUE TITLE
Twitter posts not showing in activity feed of game jam

### ISSUE THREAD

**Issue by NathanAuckett** [gamejolt/issue-tracker#1100]
Title sums it up.

Twitter posts with the defined hashtag are not showing in the activity feed of game jams.

Example sent in by reporter: http://jams.gamejolt.io/uugamejam

Feed that should be pulled for that jam: https://twitter.com/search?f=tweets&vertical=default&q=ultimateunitycommunitygamejam&src=typd

**Comment by YLivay** [comment]
Activity has been disabled for the time being.
@hworld whats the plan with this?
