### ISSUE TITLE
You can like your own comments

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#1102]
![image](https://user-images.githubusercontent.com/11202073/36670139-93f460ac-1af7-11e8-8b60-c4c41777c981.png)

Is that intentional? Or is that a bug?

**Comment by nilllzz** [comment]
Yeah, that's intentional.

**Comment by Tricky1975** [comment]
Now I wonder why...

**Comment by hworld** [comment]
It was hard with collaborators to enforce. Basically the author couldn't, but other team members could. And then it was tricky when we would change owners of a game to keep in sync. In the end it just didn't seem worth it. It's not much of a big deal for that one extra like.

**Comment by Tricky1975** [comment]
I see... There are also sites were commets you post are automatically liked too... Perhaps an idea ;)
