### ISSUE TITLE
Can't Install Game Jolt Client

### ISSUE THREAD

**Issue by programtester806** [gamejolt/issue-tracker#1106]
I keep getting the error message"The drive or UNC share you selected does not exist or is not accessible. Please select another." How do I select another? The setup closes itself immediately after I hit ok. I have uninstalled and reinstalled game jolt client previously but  now I cannot reinstall it at all.

**Comment by YLivay** [comment]
Hi, sounds like the installer is complaining about the destination it tries installing the client to.
By default it installs into your user directory so there shouldn't be any permission issues. Did you change the destination directory? Does that location require admin privilleges to write to?

**Comment by GamerMinds1901** [comment]
it will not download for me i try to get it to download but still will not i need help

**Comment by goslings151** [comment]
i can not download it either it does nothing when i click on download

**Comment by Mrxx99** [comment]
I also can't download the client, when I click the download button nothing happens

**Comment by YLivay** [comment]
@GamerMinds1901 @goslings151 @Mrxx99 you were having a different issue that's been resolved. @programtester806 seems to be having issues installing, not downloading.

**Comment by programtester806** [comment]
@YLivay I don't think I changed the User Director, I dont know how, Unfortunately I'm also unsure how I would check. Thanks for your help, in advance!

**Comment by YLivay** [comment]
Did you have the client installed previously at some point?

**Comment by D4di69** [comment]
i get the same error every time i try to install gamejolt client. I already installed gamejolt client on my usb pendrive (F:) but now i want to install the client on C; but i can't!
