### ISSUE TITLE
XSS issue in API

### ISSUE THREAD

**Issue by CoombesJ** [gamejolt/issue-tracker#1109]
cross site scripting in site-api/web/profile

Steps to reproduce:

1. Login in to account and edit profile  
2. Edit Displace name to 

> <img src=x onerror=alert('xssbykmcat')>

3. Save and head over the the  site API url eg 

> https://gamejolt.com/site-api/web/profile/@[name]

4. And you have an XSS issue. 

Thanks James

**Comment by YLivay** [comment]
Thanks for reporting this ya legend :)
This is fixed now

**Comment by hworld** [comment]
Yes, thanks for the report!
