### ISSUE TITLE
XSS in create links (markdown)

### ISSUE THREAD

**Issue by CoombesJ** [gamejolt/issue-tracker#1112]
cross site scripting in markdown
Steps to reproduce:

1. Go to location that allows for markdown. (I used edit account page)
   [Link to account page markdown](https://gamejolt.com/dashboard/profile/edit)
2. Edit Profile Bio to 
`Check out [this link](javascript:alert(document.domain))!`
3. Save and go back to profile
4. Click link and XSS payload is executed

Thanks James

**Comment by YLivay** [comment]
Thanks for reporting, this has been fixed :heart:
