### ISSUE TITLE
Hyphens not supported when linking to user.

### ISSUE THREAD

**Issue by LeBodro** [gamejolt/issue-tracker#1113]
![image](https://user-images.githubusercontent.com/11490128/38176107-d86fb464-35b6-11e8-975a-54f594e95c32.png)

As seen in the exemple, linking to a user's page for which the username contains an hyphen does not consider the part of the name after the first hyphen.

**Comment by Tricky1975** [comment]
I reported this long ago, and back then it was closed because hyphens were not supposed to be supported in the first place. This time I suggest to leave it open until at least hyphens in usernames are no longer possible (and something is done about users still having them in their usernames) or the linkup to them is fixed...

**Comment by YLivay** [comment]
Can you link the user you saw with hyphen? This shouldn't be possible haha

**Comment by Tricky1975** [comment]
Well, one of those users is a former moderator: https://gamejolt.com/@jani-nykanen
The user the original poster is talking about this one: https://gamejolt.com/@le-bodro

I know Jani already had his username before any fixes to this were made (or even before the @ system came in place) and he never changed it. I don't know about le-bodro....

**Comment by LeBodro** [comment]
@YLivay  You can see an exemple right here: https://gamejolt.com/games/penguin-panic/330630

The list of developpers in the game's description contains `@le-bodro` but links to the user `le`, at least when using Google Chrome.

**Comment by Tricky1975** [comment]
I guess this duplicates #1086 now... no?

**Comment by hworld** [comment]
yeah, closing in favor of that one
