### ISSUE TITLE
Game Opening Issues

### ISSUE THREAD

**Issue by Dragonify** [gamejolt/issue-tracker#1114]
Recently I was downloading some games to play, and for some unknown reasons, I can't open it. 

I don't think it's problem of games themselves, 'cause first, it happens twice and something tells me that it's not coincidence, and second, nobody comments in the game profile about the same issues.

For example, I successfully downloaded Those Nights at Rachel's (yes, this is the exact game that I'm having a problem with), when I opened it, the bar showing that I'm currently playing it showed up at the bottom. After a few seconds, the game still didn't open, and the bar disappeared. 

Pls fix it! That's another major problem I'm having since the Download Reset issue (it's fixed btw if you saw the post).

**Comment by YLivay** [comment]
Can you navigate to your games folder and launch the game from there manually?

Some common reasons for this issue to happen is:
1. overactive anti virus removing the game executable
2. firewall blocking connection between the client and the runner we use to launch games with
3. file permission issues

If the game works from the games folder, can you try again from the client? then scroll all the way down and hit the "Send System Report" button. in the description write "Issue #1114" so i'll know which log is yours :P

**Comment by Dragonify** [comment]
Hey! Long time since I reply this thread. I just sent a system report. Hope you can see it.
