### ISSUE TITLE
"In response to" hard to read in dark mode

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#1116]
![image](https://user-images.githubusercontent.com/11202073/38237223-dfef13bc-3726-11e8-880d-3736b68960e1.png)

**Comment by Dragonify** [comment]
I think that's an April Fool joke, so that's why they don't take it seriously. Because it had already been taken down.

**Comment by Tricky1975** [comment]
The April Fools Joke was only that flash light thing, the Dark Mode I am talking about was NOT part of that April Fools Joke!

**Comment by hworld** [comment]
Good catch! Will be posting a fix soon. Be sure to post anything else you find. I had to change nearly every component on the site for dark mode, so I expect there will be more bugs.
