### ISSUE TITLE
Cannot unfriend banned users anymore

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#1125]
![image](https://user-images.githubusercontent.com/11202073/39153085-6a8f4d38-474a-11e8-8ee4-2ff6e182e383.png)

This user befriended me, only because they personally wanted to ask me to purge their account. However, now that the purge has been done, it's a bit useless to keep them in my friendlist, but... how to unfriend them?

**Comment by YLivay** [comment]
shouldve been fixed months ago
