### ISSUE TITLE
Claim page text can't be read properally in dark mode=

### ISSUE THREAD

**Issue by NathanAuckett** [gamejolt/issue-tracker#1126]
When using dark mode, the claim page (https://gamejolt.com/claim) has text that is lite grey on a white background and therefor can't be read unless you highlight it with your mouse.
Screenshot: http://prntscr.com/j9qsve

Browser = Firefox

**Comment by Tricky1975** [comment]
I had the same issue in Chrome, so I guess it's not a browser specific issue

**Comment by hworld** [comment]
should be fixed now

**Comment by Tricky1975** [comment]
Confrimed :)
![image](https://user-images.githubusercontent.com/11202073/39465303-dee7454a-4d22-11e8-95ea-c6157f4b4131.png)
