### ISSUE TITLE
Trying to upload an HTML5 game into a package with a Unity build in an older release results in a message telling you that you can't have 2 browser builds.

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#1128]
A user noted that he wanted to upload a game he uploaded in the past as Unity Webplayer as HTML5 now that the webplayer is taken out of use. He DID create a new release, but despite all that the system still complained that you can't have two browser games on one release. I do strongly believe the two different systems (Unity WP -> HTML5) might have caused a conflict here due to their different architechture. Since I think we should really encourage the replacement rather that hindering it, I do think this should be fixed a.s.a.p. ... no?

**Comment by nilllzz** [comment]
I was unable to reproduce this.
