### ISSUE TITLE
Double followers?

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#1131]
![image](https://user-images.githubusercontent.com/11202073/39677880-c633b39e-5182-11e8-8333-17006bad637d.png)

The followers are mentioned TWICE. Does that have a purpose, or is this just a cosmetic mistake?

**Comment by hworld** [comment]
I can't find where this is happening. What's the repro case?

**Comment by hworld** [comment]
It doesn't show for me. I thought maybe it was a translation bug, so I switched to Nederlands but still fine. I tried Chrome and Firefox.

**Comment by Tricky1975** [comment]
It was in the English language setting (as I only use the Dutch setting when testing translations, as despite my first language being Dutch, I hate Dutch software... odd eh?)... I did see this disappearing soon after I posted this however I saw something similar when I posted this is staff-chat for a different question:
![](https://cdn.discordapp.com/attachments/203283987387514880/442801756418867202/unknown.png)

**Comment by hworld** [comment]
Yeah, I saw in the images you posted. I just can't seem to reproduce it.... @YLivay @nilllzz does this happen to you?

**Comment by Tricky1975** [comment]
Oddly enough I don't see it anymore either.... K-Improve is also back to gj-improve, but I wonder what happened there (Trust me I did not photoshop this).

**Comment by hworld** [comment]
super weird.... i'm going to close. if you see it happen again reopen

**Comment by Tricky1975** [comment]
I'll leave a shout when it happens again, as I can't reopen issues I didn't close myself in a repository I don't own ;)

**Comment by hworld** [comment]
Yeah, sorry, I meant comment again. =]

**Comment by nilllzz** [comment]
What extensions do you have installed?

**Comment by Tricky1975** [comment]
Google Drive, MyWot and LastPass

**Comment by hworld** [comment]
Does it happen on incognito/private mode?

**Comment by Tricky1975** [comment]
I've tried this first without and then with it, but as this appears to happen randomly it's hard to tell...

I did see this on GJ-IMPROVE and I wonder if it's caused by the same issue or not:
![image](https://user-images.githubusercontent.com/11202073/40280216-57d86a60-5c50-11e8-9fe1-df124a4601d6.png)
The question is, who posted all these suggestions?

**Comment by Tricky1975** [comment]
I think this is all the same bug and it's back:
![image](https://user-images.githubusercontent.com/11202073/41308584-95cc053c-6e7c-11e8-8121-f769948c0a10.png)

And another detail the thread by I [at]I had to be nik [at]nik (if you open it you'll see that). Why nik became "I".... I really don't know. (I wrote [at] and not '@' in order not to 'notify' people I don't want to notify).
