### ISSUE TITLE
Always using My Theme despite this Option being turned off?

### ISSUE THREAD

**Issue by DisposableMailUser732785** [gamejolt/issue-tracker#1133]
![image](https://user-images.githubusercontent.com/39159720/39870554-1abaa51c-5462-11e8-8deb-ec45dae3ed8b.png)
I'm very very sure the Option to "Always Use my Theme" is turned off (I ensured this many, many Times),
but I think the GameJolt Website always behaves like if this Option was turned ON!
EVERY GAME PAGE has the same Colors I choosed for MY PROFILE, but I don't want it.
I want to ACTUALLY BE ABLE TO SEE the other's Colors, because I turned the Option off.
Here are a few Examples of all Game Pages having the Same Colors I choosed for my Profile
despite the ,,Always use my Theme" Option turned off:
![image](https://user-images.githubusercontent.com/39159720/39870802-f18bb19e-5462-11e8-8028-d1fcc050844e.png)

![image](https://user-images.githubusercontent.com/39159720/39870828-00b7f89e-5463-11e8-9c78-d1da79bd5a48.png)

![image](https://user-images.githubusercontent.com/39159720/39870844-0b94fa32-5463-11e8-835c-19ba21676a93.png)

![image](https://user-images.githubusercontent.com/39159720/39870873-25037a3e-5463-11e8-88d6-48d2ff376528.png)

![image](https://user-images.githubusercontent.com/39159720/39870899-4168df8e-5463-11e8-9d2f-b58ca2a1b59f.png)

I could go on forever with these Examples, but I think that's enough to get the Point.

Now I delete my Disposable E-Mail Address I created just to Address this Issue.
Because of this you won't see me reply with the same GitHub Account or do anything else on GitHub with the same Account.

**Comment by hworld** [comment]
This isn't a bug. It's because those games didn't set a theme for their game page yet. If they did, you would end up seeing their colors. This one has a theme set. You should see a minty green color when going to it: https://gamejolt.com/games/lucid-alpha/33090
