### ISSUE TITLE
width/height requirement for HTML 5 games

### ISSUE THREAD

**Issue by davidfig** [gamejolt/issue-tracker#1136]
For HTML 5, please provide a full-size option instead of a width/height option. Many HTML 5 games can resize to the appropriate size and aspect ratio, and by forcing us to provide a size, we do not end up with ideal screen usage.

**Comment by hworld** [comment]
Yeah, good point. People have asked in the past and I think it's got kind of lost. I'll see if we can get this out soon.

**Comment by hworld** [comment]
All right, I pushed out a new setting when editing your build for the release that allows you to select for it to fit to the viewport. Cheers!
