### ISSUE TITLE
header and Avitar glitch

### ISSUE THREAD

**Issue by pheonixproductions** [gamejolt/issue-tracker#1138]
I am having trouble uploading my avatar/header. I have met all requirements and have tried both the website and client. I have tried resetting my computer as well. nothing appears when I put in the files and when I click 'save profile' on the website nothing happens. Plz tell me if I am doing something wrong.

**Comment by Tricky1975** [comment]
Maybe you should have put this onto the forums before coming here, so we can really make sure this is a bug first, before we actually put it in the bug list.

Well, what's done is done. And if it really is a bug...
Can you copy your avatar and header to a cloud service and put on the link here. That way the files themselves can give us some answers and then we know if the files are not right or if there's really a bug.

**Comment by pheonixproductions** [comment]
Avatar - 
![gamejolticon](https://user-images.githubusercontent.com/39508379/40590967-3e7451b4-61ce-11e8-83a3-f469bd26c6f3.png)

Header - 
![banner](https://user-images.githubusercontent.com/39508379/40590974-5012e2dc-61ce-11e8-816f-11eaa07d1a7f.png)
