### ISSUE TITLE
Game pages on jams cause server errors

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#1141]
![image](https://user-images.githubusercontent.com/11202073/40574895-066ea1e6-60db-11e8-9182-8685a2fe72ac.png)

This is my "Geezer Jam", but frankly I've seen this issue on all jam pages I visited.

EDIT: As soon as one game enters the jam the issue "fixes" itself, so it seems, still gameless jams should not produce an error so I'll keep this issue open ;)

**Comment by hworld** [comment]
I think this is fixed since I could go to a jam's games page when it had no games.
