### ISSUE TITLE
"View all jams" page => server error

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#1145]
![image](https://user-images.githubusercontent.com/11202073/41188197-63a5aaf0-6bba-11e8-9096-8f66b8833437.png)

**Comment by niksudan** [comment]
I'm not getting this - is this still an issue? Might have been too many active jams on at that time.

**Comment by Tricky1975** [comment]
This has been a very long plague on the jam site, but when checking this again, I don't get this server error either anymore. I'll close this issue myself, so I can reopen it, if it pops up again on short term.
