### ISSUE TITLE
Can't update my game

### ISSUE THREAD

**Issue by Dragonify** [gamejolt/issue-tracker#1149]
I can't update my game. When I click update, it just immediately said update failed. I used Game Jolt client. Can you help me to solve the problem?

**Comment by Dragonify** [comment]
I sent the system report. But is there no other way to update my game other than that?

**Comment by Tricky1975** [comment]
Through the client.... No.... Maybe through the site... The devs need time to fix whatever was broken causing this effect, you know...

**Comment by Dragonify** [comment]
Ok understand, thanks.
