### ISSUE TITLE
0% on sale

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#1151]
A game normally costs $7.99 and now it's on sale and now it costs $7.19
![image](https://user-images.githubusercontent.com/11202073/41401930-5578d3fc-6fc1-11e8-8ad9-ea6c3dfdbe45.png)

According to Game Jolt that's 0% cheaper...
According to my calculator that's 10.0125% cheaper, actually... (since you now pay only 89.9875% of the regular price).

Now this just looks like a cosmetic error, but it can to devs who sell their games have some bad consequences. I mean, would you be tempted to buy something if it's advertised with "0% cheaper"?

**Comment by hworld** [comment]
This was fixed. A bit too late because I didn't see this earlier sadly. =\
