### ISSUE TITLE
System keeps requesting fnaf developers to add the fnaf-tag regardless of the fact it's there or not.

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#1154]
Copy from a private chat on this matter:
====

### Photo Negative Mickey - Today at 10:09 AM
idk if it's a gamejolt bug but I'd want to report on something
If u could also pass this on if the creator doesn't know

### Jeroen P. Broks - Today at 10:10 AM
What's the matter?

### Photo Negative Mickey - Today at 10:11 AM
Upon editing the description of a fnaf fangame (for the first time) asks if you to include a fnaf tag along with the other tags included Once doing so it automatically adds the fnaf tag.
![](https://cdn.discordapp.com/attachments/428667816917467167/463617800267890689/unknown.png)
However
When going to update the page again it asks the same thing when it's already there. It makes the tag look spammy in the description
And may make people worry that if they don't tag won't make their game appear at all

### Jeroen P. Broks - Today at 10:13 AM
I can add that to the bug list, no problem... Can you provide me a link to the game on which this happened for now, as the devs will certainly ask that.

### Photo Negative Mickey - Today at 10:13 AM
https://gamejolt.com/games/fnab/348897 It seems to happen on any page that is a fangame to fnaf. But here you go

**Comment by YLivay** [comment]
I'll check this out, it shouldn't suggest it if its already there. thats very weird.

**Comment by hworld** [comment]
@YLivay  was a liar.

**Comment by IronBrandon** [comment]
This is still an issue to this day

**Comment by FlooferLand** [comment]
This is still an issue. It is very irritating and it takes 2 short extra lines of code on GameJolt's side to solve it.

All you have to do is check client-side if there is a tag already in the description before recommending to add it.
Ex:
```diff
- showTagWarning(tag);

+ if (!description.includes('#' + tag)) {
+     showTagWarning(tag);
+ }
```
