### ISSUE TITLE
When I try to close my window it doesn't do anything

### ISSUE THREAD

**Issue by Tripazzy** [gamejolt/issue-tracker#1156]
The close button just flickers. I'm on mac and have the latest version from the site.

**Comment by hworld** [comment]
@Tricky1975 does this happen for you on latest Client?

**Comment by Tricky1975** [comment]
I shall check this out later

**Comment by Tricky1975** [comment]
On v0.18.12 I could just close the window... Is that the newest version?

**Comment by Tripazzy** [comment]
I updated my client, and now it's fixed.

**Comment by hworld** [comment]
Great to hear! Thanks for updating us
