### ISSUE TITLE
I cannot access my account

### ISSUE THREAD

**Issue by LarissaMoretti** [gamejolt/issue-tracker#1157]
Fiz minha conta já faz algum tempo, mas não entrava frequentemente. Quando fui usa-la novamente, já não podia entrar, por conta de meu antigo nome de usuário que continha "_" ( Lary_Moretty).
Desejo entrar novamente em minha conta, se possível.
Obrigada.

**Comment by Tricky1975** [comment]
And this is what Google translate makes out of the text above:
![image](https://user-images.githubusercontent.com/11202073/43758704-447a97a8-9a1d-11e8-9c4d-8e256d3d2bfb.png)

**Comment by YLivay** [comment]
I can't remember if thats the user - but we did get an email to our support with this case and we resolved it. A few months back we had to rename users with invalid characters. All users who were renamed were sent an email with their new username.

If this is still an issue please email contact@gamejolt.com
