### ISSUE TITLE
it will not run properly

### ISSUE THREAD

**Issue by Beinion** [gamejolt/issue-tracker#1159]
![captura de pantalla 1](https://user-images.githubusercontent.com/41135853/42611478-9a178308-8553-11e8-98ba-546e28171ce8.png)

I've managed to download the client, but whenever I try to open the file, it doesn't fully show itself.
I've attached a screenshot to better explain what I'm seeing, but it appears to only come in code...

**Comment by Beinion** [comment]
well, nice to know that the code actually shows the desired image once sent.

**Comment by YLivay** [comment]
This should be fixed in the new client version.
