### ISSUE TITLE
HTML tags show

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#1161]
This shot is taken from the Dutch version of the Client for Windows:
![](https://cdn.discordapp.com/attachments/310689042582994944/475637056069042207/Bug_GameJolt.png)

You don't need to understand the Dutch language to see what's wrong here... The <p> and </p> tags show, and they shouldn't. Is this a bug specific the the client, the GJ code in general or in the translated text? (the latter I can fix with POE editor)

**Comment by YLivay** [comment]
Will be solved when we manage to update translations.
