### ISSUE TITLE
Editing name of package from "alpha" to "Alpha" says that name is already in use.

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#1164]
I edited the details of my game 63 fire of lung package. It was named "alpha", and it just had to exist. Now that I am planning to use the CLI to make daily alpha updates (seems like a good way to test this after all), I put in the data right, but what did I see? As I changed "alpha" to "Alpha" I got the error "Name already in use".... Yeah of course it is, it's the same package.... I could only get rid of this error by just altering this a little like "Alpha Version" or something like that... Oh, damn!

**Comment by hworld** [comment]
Seems like an issue with case sensitivity with the checks.
