### ISSUE TITLE
WHAT JUST HAPPENED TO EVERYONE'S AVATAR?!

### ISSUE THREAD

**Issue by Dragonify** [gamejolt/issue-tracker#1165]
I don't know what just happened, but today I opened my Game Jolt Client, and everyone's avatars are just default, like the bears one. I checked the online Game Jolt, and it's the same. Is this happening to anyone?

**Comment by niksudan** [comment]
It's bear week on Game Jolt, so everyone is now a bear.

https://twitter.com/gamejolt/status/1028332379641765888

Have a beary good week, my friend 🐻

**Comment by Dragonify** [comment]
Ahhhhh okay, should definitely follow their Twitter now. 
And sry for being stupid, but...

What is bear week?

**Comment by niksudan** [comment]
Here's a good video explaining the history!

https://www.youtube.com/watch?v=6XFW_oXwgtY

**Comment by Dragonify** [comment]
Oh okay, didn't know they have a YouTube channel too, huh.
Anyway, thanks! The reason is quite funny haha xD
