### ISSUE TITLE
Ad layout issue

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#1169]
![image](https://user-images.githubusercontent.com/11202073/44710218-e2713680-aaab-11e8-8487-1ee500cd1d7f.png)
 This is not how it's supposed to look, is it?

**Comment by Tricky1975** [comment]
Google Chrome for Mac

**Comment by hworld** [comment]
Is this happening consistently for you?

**Comment by Tricky1975** [comment]
Randomly... Now I need to note that I stopped using Chrome recently and switched to Firefox, where I did not have this issue (Chrome is taking my entire system down all the time for some reason)
