### ISSUE TITLE
Can no longer download since gamejolt update.

### ISSUE THREAD

**Issue by Leurunner** [gamejolt/issue-tracker#1173]
**How are you using Game Jolt?**
Casually
...

**Please describe the issue you are having**

...After installing the newest update i am no longer capable of downloading or installing anything. I will only recieve the meessage installation failed instantly after starting the process. it also aks me to check if i am still connected to the internet. as you may realise because of the fact this report exists, i am indeed still connectet.

**Comment by Leurunner** [comment]
#1160 has a simmiliar problem.

**Comment by YLivay** [comment]
Hey, #1160 is most likely unrelated, its probably a hyperactive anti virus removing the executable we use to manage the games. Do you use McAfee or Windows Defender by chance?

**Comment by Leurunner** [comment]
no.
