### ISSUE TITLE
Can't update gamejolt client

### ISSUE THREAD

**Issue by pooky1225** [gamejolt/issue-tracker#1177]
**How are you using Game Jolt?**
On windows 7 64-bit, using the Client.
...

**Please describe the issue you are having**
The GameJolt Client will not auto-update.
...

**Comment by pooky1225** [comment]
it still doesnt auto-update. it says "please try restarting your client" so I do and it still doesn't work.

**Comment by qwertychouskie** [comment]
I think you need to manually download the latest version and re-install it.

**Comment by Tricky1975** [comment]
> I think you need to manually download the latest version and re-install it.

That's what I said, but apparently that message didn't came through.... :|

**Comment by YLivay** [comment]
can you post a screenshot of the screen youre stuck on? it should definitely go through

**Comment by YLivay** [comment]
Well, if there's an actual problem feel free to reply to this issue and i'll reopen it.

**Comment by progamer63** [comment]
![image](https://user-images.githubusercontent.com/20373130/48172627-7da93800-e2b5-11e8-8210-84e100aeb464.png)
there is the issue, i dunno what else i can add

**Comment by qwertychouskie** [comment]
Have you tried clicking the "reinstall it from the website" link in the shown screen?

**Comment by progamer63** [comment]
i said "auto-update"
thats how i HAVE to do it

**Comment by qwertychouskie** [comment]
Auto-update won't work.  There is a bug in the old client version that prevents it from auto-updating.  You have to use the link to download the latest version manually.

**Comment by progamer63** [comment]
i did install the newest version

**Comment by Tricky1975** [comment]
To be more precise, the "bug" is a change in the underlying nw.js wrapper.
This is not an issue in the client but one in nw.js, and that's why auto-update from the older version to the new one became impossible. @YLivay could go into the details if he desires, but the bottom line is that when you see the screen you posted in the shot above then all you can do is re-install the client manually. Sorry for the inconvenience.

**Comment by WHYGAMEJOLTWHY** [comment]
im having the same issue, reinstalling does nothing

**Comment by WHYGAMEJOLTWHY** [comment]
> Well, if there's an actual problem feel free to reply to this issue and i'll reopen it.

Help, it may be 2 years later but im having the same issue

**Comment by Tricky1975** [comment]
Can't be the same issue anymore after 2 years, unless you never used the client for the past 2 years.
Did you uninstall the client ENTIRELY and install the NEW client from that?
