### ISSUE TITLE
Game removed from account??

### ISSUE THREAD

**Issue by Sesilan** [gamejolt/issue-tracker#1178]
**How are you using Game Jolt?**

I use it to play the ONE game I bought which is why I know it was removed from my account.

**Please describe the issue you are having**

A game I PURCHASED is now MISSING from my account.
![screenshot_85](https://user-images.githubusercontent.com/44093983/46875684-b1906980-ce7f-11e8-9327-60219cb61540.jpg)

**Comment by Tricky1975** [comment]
This is not an issue to be discussion on this issue tracker.
Send an e-mail to contact@gamejolt.com in stead to sort this out
