### ISSUE TITLE
No auto-fill login information

### ISSUE THREAD

**Issue by acidpoison** [gamejolt/issue-tracker#130]
# Short Version
There is no autofill at the login! Please add it.
# Long Version
I am at different computers throughout the day so I carry around a copy of [Chrome Portable](http://portableapps.com/apps/internet/google_chrome_portable) on a flash drive. I have to sign into my google account so I can use my auto-fill on any site that I need to sign into. Unlike the old site, when I go to the new gamejolt site, it doesn't auto-fill it in, I have to manually put in my username and password myself. Will there be auto-fill logins in the future?

**Screenshots**
![1](http://i.imgbox.com/FxxJ78eD.png)
![2](http://i.imgbox.com/c1MeziOC.png)
![3](http://i.imgbox.com/KAdTzhnT.png)
Old gamejolt does auto-fill.
![4](http://i.imgbox.com/BwKQmkNv.png)

**Comment by hworld** [comment]
After the first time that you sign in, does it autofill after that?

**Comment by acidpoison** [comment]
No.

**Comment by hworld** [comment]
Does it allow you to select your login credentials after you start typing in the username field on the new site?

**Comment by acidpoison** [comment]
yes, but it only fills in my username. I have to type in in my password.

**Comment by acidpoison** [comment]
Seems to be working now...
