### ISSUE TITLE
Middle clicking search links doesn't open in new tab

### ISSUE THREAD

**Issue by acidpoison** [gamejolt/issue-tracker#152]
Middle clicking (using scroll wheel to click) links in the search dropdown will open the link in the current tab instead of opening it in a new tab.

Tested in Chrome and IE.

**Comment by Tricky1975** [comment]
I tried this in Opera and in Opera all links I tried open in a new tab.

**Comment by acidpoison** [comment]
Hm. Maybe it's just my computer. I'll check and see if it happens on other computers.

**Comment by hworld** [comment]
So, this is older than time, but I think I finally fixed this
