### ISSUE TITLE
Filter boxes are incorrectly positioned

### ISSUE THREAD

**Issue by NikSudan** [gamejolt/issue-tracker#174]
![](http://i.imgur.com/1yA8nYY.png)

Chrome 41.0.2272.89 for Mac

Seems to happen to 'Status' only

**Comment by MausGames** [comment]
Happens also to **Maturity Rating**, when the window is small enough (e.g. **1280** x 960).

**Comment by Positive07** [comment]
As @MausGames said I have the same issue, miss alignment to the right of the **Maturity Rating** and **Status** dropboxes.

Windows 7 Chrome 430.2357.81 m 1024x600 (Crappy Netbook)

**Comment by hworld** [comment]
Fixed.
