### ISSUE TITLE
Cancelled Twitter/FB linking request directs to "Bad Request" Page

### ISSUE THREAD

**Issue by MaskofThoro** [gamejolt/issue-tracker#180]
When you cancel twitter account linking request, it gives you the option to go back to gamejolt but goes to a bad request page instead of the home page or dashboard/linked-accounts page :

http://wttf.gamejolt.com/dashboard/linked-accounts/link-callback/twitter?denied=q6HB8h9tIyz3kNCivejTMxg7QPhJdMvw

**Comment by YLivay** [comment]
Fixed
