### ISSUE TITLE
Highscore card doesn't show EXP gained

### ISSUE THREAD

**Issue by acidpoison** [gamejolt/issue-tracker#181]
I played [Hyperspace](http://wttf.gamejolt.com/games/hyperspace/55519) and got to the top out of 5 people. The highscore card shows EXP but no number.

It could be because so few people played the game and 0 EXP is given, but there is no 0.

![gj bug hs](http://s3.postimg.org/6ysij5xjn/Screenshot_2015_03_24_at_3_23_50_PM.png)

**Comment by hworld** [comment]
Is it still not showing for you, acid?

**Comment by acidpoison** [comment]
That game gives EXP now that more people have played it. I now it shows that I get 5 EXP from that game. 

Yeah, it still happens. In the table below, It shows I get 0 EXP. Only 2 people have scored on this scoreboard.
![GJ bug hs](http://s29.postimg.org/pp3cvfhbb/Untitled.png)
tested on chrome for pc, not chromebook this time.

**Comment by YLivay** [comment]
Fixed
