### ISSUE TITLE
Expand description button unnecessary when description is a certain length

### ISSUE THREAD

**Issue by acidpoison** [gamejolt/issue-tracker#190]
![gj bug](http://s1.postimg.org/vaby2z7r3/Untitled2.png)
expands to
![gj bug](http://s13.postimg.org/3r4n0cjzr/Untitled.png)
As you can see, the button is unnecessary since the entire description is displayed.

[link to game](http://wttf.gamejolt.com/games/devastatingly-romantic-endearing-tale/25900)

**Comment by acidpoison** [comment]
Also happens with soundtrack displays.
![gj soundtrack bug](http://s15.postimg.org/qukm1fo7f/Screenshot_2015_04_04_at_4_59_18_PM.png)
![gj soundtrack bug](http://s28.postimg.org/j1fcocj2l/Screenshot_2015_04_04_at_4_59_21_PM.png)
[link to game](http://wttf.gamejolt.com/games/jade/26087)

**Comment by hworld** [comment]
Hmm, this one's a bit tricky. THere's gotta be a cut off somewhere, haha. If it's longer than the height that I want I could always cut it off even more. So that there's always at least 100px cut or something. Is that better?

**Comment by acidpoison** [comment]
Yeah, that would probably look better.

**Comment by hworld** [comment]
this was actually done in this commit https://github.com/gamejolt/frontend-lib/commit/2dc492ea02c3dd600d0e61747ac94860b429cced during the rewrite of the frontend
