### ISSUE TITLE
Gas Integration missing on Game Jolt Next

### ISSUE THREAD

**Issue by MausGames** [gamejolt/issue-tracker#192]
On old Game Jolt, I can click on a special link on each game profile, and the game gets instantly downloaded with Gas, ready for play - that feature is still missing on Game Jolt Next.

I cannot live anymore without Gas, please fix ASAP!!!

**Comment by NickRock** [comment]
wait where did you get Gas? :O

**Comment by hworld** [comment]
With Beanz

**Comment by NickRock** [comment]
I NEED IT

**Comment by YLivay** [comment]
Gas has been implemented. Will do a silent release soon.

**Comment by hworld** [comment]
Pfffffffft

**Comment by YLivay** [comment]
That was the silent release, was it?
