### ISSUE TITLE
Need to link to FNAF news somewhere.

### ISSUE THREAD

**Issue by hworld** [gamejolt/issue-tracker#199]
Since it's pulled out from the normal listings, we need a place to show it instead that's visible enough. This needs to be a solution for any of those tags that we deem should be pulled out of normal listings.

I'm thinking we can just show a news row on the tag pages for games at the top that would link to more? Here: http://wttf.gamejolt.com/tag/fnaf could show some news and link to here: http://wttf.gamejolt.com/news/tag/fnaf

**Comment by NikSudan** [comment]
This is sorted, right?

**Comment by hworld** [comment]
There's a place to view it, but not a link to get to it. So, it's still an issue.

**Comment by YLivay** [comment]
DEVLOGS!
