### ISSUE TITLE
Quick 'add to playlist'

### ISSUE THREAD

**Issue by niksudan** [gamejolt/issue-tracker#221]
Sometimes I want to add something to my playlist without clicking on the game's page. Maybe if thumbnails had a :heavy_plus_sign: symbol similar to how they have a :heavy_multiplication_x: symbol on playlists. It would then show the playlist dropdown.

Would also encourage adding to playlists a lot more too.

**Comment by hworld** [comment]
Should there be a follow button, too?

**Comment by NikSudan** [comment]
Would make sense to have it there too. However, it would be pretty distracting for people who aren't interested in that stuff. How could it be even more minimal?

**Comment by hworld** [comment]
hmmm, i think i did this yay
