### ISSUE TITLE
Multiple minimized games

### ISSUE THREAD

**Issue by acidpoison** [gamejolt/issue-tracker#231]
I wasn't sure what to put this under, so change the title if it doesn't fit the bug description.

Multiple windows of a browser game show up. I'm not sure how it happened.

I was playing The [Frozen Tower of Ice](http://wttf.gamejolt.com/games/the-frozen-tower-of-ice/32842) and tried to minimize the window. it didn't work, so I kept playing for a while longer. When I closed the game, I saw a bunch of minimized game boxes. I tried clicking them, but they didn't do anything. I then clicked a screenshot, and I was unable to close it. I then reloaded the page and everything went back to normal.

![gj bug](http://s6.postimg.org/3uldahzm9/Screenshot_2015_05_06_at_4_47_15_PM.png)

**Comment by hworld** [comment]
oh my

**Comment by acidpoison** [comment]
It may be due to the lag I was experiencing at the time and with the crappiness of my Chromebook.

**Comment by hworld** [comment]
Gonna close this, then. It shouldn't be possible, and no one else has complained yet.
