### ISSUE TITLE
Get forums working within new site.

### ISSUE THREAD

**Issue by hworld** [gamejolt/issue-tracker#244]
It may just be that we have to have gamejolt.com/forums/ direct to the old site.

- [ ] Get the top nav bar working better in this case.
- [ ] Get forum post linking working for notifications.
- [ ] We need a way to get to the forums. Maybe do forums.gamejolt.com and make it a sub-site like we've been doing?

**Comment by NikSudan** [comment]
:sweat:

**Comment by hworld** [comment]
Done!
