### ISSUE TITLE
Show some followed games on user's profile with a link to view all.

### ISSUE THREAD

**Issue by hworld** [gamejolt/issue-tracker#249]
Similar to developer games.

**Comment by NikSudan** [comment]
Should this be choosable? Or should it pick out popular or recent playlists?

**Comment by hworld** [comment]
This would just be recently followed games, not playlists. I'm just thinking that it'd be nice to call out the activity of them following on their pages. Right now you have to go into their library and then click Followed. It's kind of annoying. Either that or we could basically put the Followed collection thumbnail there, and then with some top playlists of theirs after, with a link to view their whole library?

**Comment by hworld** [comment]
nah
