### ISSUE TITLE
Signing up automatically makes you a gamer

### ISSUE THREAD

**Issue by acidpoison** [gamejolt/issue-tracker#258]
I made a duplicate account to test #252, but I was automatically made a gamer. There is no sign up option to become a developer.

**Comment by hworld** [comment]
Hmm, this is something I've struggled with. We have a overwhelming majority of gamer accounts instead of dev. It's one extra option that most people signing up don't care about, and if you ARE a dev, me just putting a quick button to switch to a dev account would be pretty frictionless.

I could also show maybe an "Add Game" button in the dashboard for all users that would then say "This will make your account into a developer account..."

**Comment by hworld** [comment]
Ping @NikSudan @YLivay

**Comment by YLivay** [comment]
Pong - 41,700,000 milliseconds round trip.
I like the smooth transition to dev when adding a game, maybe can take it one step further and retain your dev status only while you have an active game up? Would make being a dev an achievement like status :)

**Comment by acidpoison** [comment]
But what if some people are already devs, but just haven't or don't have any games uploaded?

**Comment by NikSudan** [comment]
Why not both options?

**Comment by hworld** [comment]
Which both options?

**Comment by NikSudan** [comment]
I do like @YLivay's comment about the smooth transition, but @acidpoison makes a important point about people who want to sign up as developers. How about a mix?

- On sign up, users shouldn't get to choose if they want to be a gamer or developer - they just enter a username. It makes things a lot simpler, as we're going to be getting more gamers than developers signing up
- The option to change to a developer should be there in the Dashboard, linking to an area where they can choose a display name and find out more information about being a developer.
- The 'Add Game' button should stay in the Dashboard menu, but it should link to the same section as above.

**Comment by hworld** [comment]
Yeah, that's what I was thinking as well, Nik. I would still put the "Become Developer" link in dashboard.

**Comment by hworld** [comment]
No more "become developer" link. That's some weird grammar anyway. We now just show an Add Game button pretty prominently, and if they add one, their account is switched over.
