### ISSUE TITLE
Scroll bug when you click on Dashboard Filter

### ISSUE THREAD

**Issue by NickRock** [gamejolt/issue-tracker#262]
In the mobile version of GameJolt when you view all activity feed you can still scroll the site which is pretty annoying
![screenshot_2015-05-17-12-50-54](https://cloud.githubusercontent.com/assets/11754980/7669934/fe7a8b1a-fc94-11e4-8246-223e69e7fe09.png)
![screenshot_2015-05-17-12-50-59](https://cloud.githubusercontent.com/assets/11754980/7669935/fea9a7b0-fc94-11e4-9cad-54b06679b5a7.png)

**Comment by officialexosoft** [comment]
I mean... It isn't that big of a deal. You can still scroll outside the filters on desktop, why not on mobile?
