### ISSUE TITLE
Images alignment in gallery is off

### ISSUE THREAD

**Issue by acidpoison** [gamejolt/issue-tracker#265]
![bug](http://s6.postimg.org/t99sd111t/bug.png)

**Comment by hworld** [comment]
Is this still happening? I can't reproduce it. Is there any specific thing you do to get it to happen?

**Comment by acidpoison** [comment]
nothing special, if you resize the browser to be that size or something like it, the alignment is off. Tested for it again, it still happens.

![bug](https://lh3.googleusercontent.com/CEy4UUbYYQfRu4yStYjbDT0Y7V5d0XBNzAu3_zSBQA5GOZa9xBgWm4Uje1L4kV904gLBgrR__Upq3v4=w926-h806-rw)

Tested it in IE, and it doesn't happen. However, the images are instead smaller, and they are semi transparent. Also, the scroll bar doesn't fade.

**Comment by hworld** [comment]
Fixed in https://github.com/gamejolt/frontend-lib/commit/4c120686433748ef574856d76d84443b588a60a7
