### ISSUE TITLE
More by developer on game pages

### ISSUE THREAD

**Issue by hworld** [gamejolt/issue-tracker#267]
Could put it either under their info on the right, or maybe instead of You May Also Like?

I don't like taking away the ability to find other developers through game pages to help spread out the traffic a bit, so maybe we should fill the first game of YMAL with one of their games.

**Comment by hworld** [comment]
An update: we show the developer's games on the download page for now if they have more. I still want to prioritize the dev's other games in the "recommended games" section, though.

**Comment by Savordez** [comment]
Just try not to make it recommend the same game the user is already viewing, because that's totally happened a bazillion times before. :>

**Comment by hworld** [comment]
That's already been fixed on the new site. But, yeah, pretty funny. =]
