### ISSUE TITLE
Formatting in game descriptions seems to be a little off

### ISSUE THREAD

**Issue by Savordez** [gamejolt/issue-tracker#283]
![gj past vs future](https://cloud.githubusercontent.com/assets/12786937/8025328/069dd55a-0d5b-11e5-9bbb-59f6d7cad88a.png)

Bold and italic text looks a bit wonky in the Game Jolt Next, but looks completely fine in the old Game Jolt (yeah, apparently it's old now)

**Comment by YLivay** [comment]
I think [ ] are used for urls, maybe it fucks up the styling?
Mind posting the actual text before markdown?

**Comment by Savordez** [comment]
The text would be
﻿Current version: Beta 0.3.3: The Stablest! [Minor Update]

0.4 is coming out soon! Like, really soon!

**Comment by hworld** [comment]
The issue is in the HTML to markdown converter we use. It breaks for some things. After we switch over, you'll have to look at the markdown for your games and make sure it's cleaned up and displaying as you want it.

I'll keep this open to see if any updates to the library fix your game or not.
