### ISSUE TITLE
Unity WebGL Games - iFrame Focus

### ISSUE THREAD

**Issue by banreaxe** [gamejolt/issue-tracker#291]
Now that we are advised to use HTML5/WebGL builds instead of the Unity Web Player Plugin, I have been having issues with getting and keeping keyboard focus on the game itself. I have ended up having to add in some custom javascript to get it to work properly, and even then it is still not optimal.

**Comment by banreaxe** [comment]
there's some discussion and fixes here:

http://gamejolt.com/community/forums/topics/unity5-webgl-game-doest-take-keyboard-focus/9253/

**Comment by hworld** [comment]
There's nothing we can actually do with this as far as I know. I tried to focus the inner iframes but it doesn't work since things are on a different domain.

I believe it's something that must be done within the game.

**Comment by banreaxe** [comment]
you are correct. there is some code us unity devs can hack in ourselves for now, and it will be included in the next update of unity 5.2

**Comment by MartySVK** [comment]
http://unity3d.com/unity/beta/unity5.2.0b2 - WebGL: Fix iframe gaining focus when clicking on WebGL canvas

Did someone test it ?

**Comment by hworld** [comment]
If anyone can try it out and update me on it, that would be great.

**Comment by KerDelos** [comment]
It seems to work if you indicate a larger player size when you upload the build on to Gamejolt. Clicking on the blankspace between the game and the black background let you use the arrow keys. I'll test with the 5.2 version of Unity later tonight.
