### ISSUE TITLE
Comment page numbers in the negative

### ISSUE THREAD

**Issue by acidpoison** [gamejolt/issue-tracker#292]
![bug](http://s6.postimg.org/pf4wb24r5/bug.png)

**Comment by acidpoison** [comment]
Seems to only happen when you click on a notification to a comment on your game or when you go to latest activity and click a link to a comment on your game.

**Comment by hworld** [comment]
Yeah, I noticed that as well. I think it's when a comment is removed but stays in your notifications.

**Comment by YLivay** [comment]
Will be handled in #365
