### ISSUE TITLE
Line Break missing in Markdown

### ISSUE THREAD

**Issue by MausGames** [gamejolt/issue-tracker#301]
Using markdown now to edit game and user descriptions, I miss a crucial feature (for me):

**Line Breaks**
http://daringfireball.net/projects/markdown/syntax#p

Will this feature be implemented in the future?

**Comment by hworld** [comment]
You should be able to do two breaks to make a new paragraph. Are you trying to make it just wrap to the next line without becoming a new paragraph? Like a single `<br>`?

**Comment by MausGames** [comment]
Yep, a single line break is/was not possible.

**Comment by hworld** [comment]
This has been implemented and all content recompiled.

**Comment by MausGames** [comment]
You are the best!
