### ISSUE TITLE
Game dashboard nav text overflow

### ISSUE THREAD

**Issue by Agrosis** [gamejolt/issue-tracker#302]
![screen shot 2015-06-25 at 12 01 10 am](https://cloud.githubusercontent.com/assets/2617549/8347613/84f71608-1acd-11e5-94f1-5121c2ee2da4.png)

on page load, when chat and menu bars are open, the whole nav collapses and that text overflows. if i open and close chat a few times, the navs don't collapse and they show up normally.

**Comment by hworld** [comment]
Fixed with new shell.
