### ISSUE TITLE
Manage Game option is hidden in a pointless menu

### ISSUE THREAD

**Issue by banreaxe** [gamejolt/issue-tracker#304]
Took me awhile to find it, but apparently now there is a three dot menu button I have to click first to see the manage game link. Ok its hidden in a menu, I guess I can dig that. Oh wait, its the only option in the menu right now! why hide it there??

**Comment by hworld** [comment]
It gets trickier as you start adding things such as News, Trophies, Scores, Releases, etc. The menu gets longer, and it gets harder to work with (especially on mobile design).

The easiest way to manage your game is clicking Dashboard and then looking at the left hand side. This [...] is mostly a convenience shorthand.
