### ISSUE TITLE
Forum input font is too small

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#309]
As result for the new site the forum font in entering new forum posts is too small to read.
I'm not quite sure how long it will take for the forums to be replaced by the new ones, but if this is gonna take a long time, maybe the font should be made a bit bigger. My eyes will thank you.

**Comment by NikSudan** [comment]
New forum update is going to use input boxes like the rest of the site, so this shouldn't be a problem when it comes.
