### ISSUE TITLE
Can't unfriend banned people

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#310]
This was also reported in this forum thread: http://gamejolt.com/community/forums/topics/un-friending-banned-users/12779#post-59295

Banned people cannot be un-friended. I tried this out, when a user is my friend not not banned, I can unfriend him by clicking the unfriend button/item.
As I have PowerfulKyurem still in my friendlist even after he got banned (http://gamejolt.com/profile/user/212594) I could check this out and all I get is his name, and the pink box saying he's banned, but the button to unfriend him is gone. 

Now I never removed PowerfulK, just because I felt no need to but if my friend list is every going to be "too large" I might want to remove people to clean my list of, or in case somebody got banned over an issue in which the banned guy was "mean" to me, I might want to kick him out even after banning.

So this might need to be taken a look at.

**Comment by Tricky1975** [comment]
I don't mean to mock you guys about this, .... 
![image](https://user-images.githubusercontent.com/11202073/30515485-c7c12e32-9b28-11e7-9a86-2e0e727386f6.png)

.... BUT, my friendlist is getting very very extremely large, and some people in my list HAVE been banned by now, and of some of them I don't deem it very likely they'll ever be unbanned either (and if they do, they MAY throw me another friend request). I would like to unfriend people who haven't contacted me for awhile, especially if they are banned.

**Comment by YLivay** [comment]
@hworld we talked about this, what would be a better UX decision for this?
If we just make banned users not show up in the list we're blocking people from seeing past conversations with their banned friends, and if unbanned they'd pop back up in the lists which may seem weird. On the other hand unbanning from a banned user's page looks bad. At any rate there's a branch for the latter solution here: https://github.com/gamejolt/gamejolt/pull/104

**Comment by hworld** [comment]
k, i merged in the commit from @YLivay with just a few tweaks regarding messaging. you can now unfriend banned users. let everyone know!
