### ISSUE TITLE
Can't login on Linux Firefox

### ISSUE THREAD

**Issue by jahndis** [gamejolt/issue-tracker#312]
I am using Firefox on Linux 64bit. I am unable to login. It appears as if the login is successful on the login page (a checkmark appears on the Log In button), but it redirects me to the GameJolt home page without logging me in (the Log In and Sign Up links are still visible, and I cannot access my profile).

**Comment by YLivay** [comment]
Hey, I can't recreate this. What ver of firefox are you on?
Can you possibly see if anything shows up in the javascript console when you log in?
Also, whats your GJ username/id?

**Comment by jahndis** [comment]
I'm using Firefox 38.0 for Ubuntu. I'm not seeing anything obvious in the console when I log in (no errors or warning anyway). There are a few "Error: Permission denied to access property "toString""s that show up in the console when I'm on the home page, but nothing that looks related to login.

Username: jahndis

I'm able to log in on Chrome for what it's worth. As a fellow web designer, this is a very odd issue... I haven't seen anything like this before. I might try reinstalling firefox to see if there is anything weird happening with my specific installation.

**Comment by jahndis** [comment]
@YLivay Well, I just tried logging in from Firefox on another installation of Ubuntu and it appears to be working fine. Not really sure what's wrong with Firefox on my laptop... In the meantime, you can mark this as closed.
