### ISSUE TITLE
Java executable .jar files uploaded, incorrectly marked as an archive file.

### ISSUE THREAD

**Issue by raeleus** [gamejolt/issue-tracker#313]
Java developers typically make releases as .jar files to serve Windows, Linux, and Mac computers. These are zip files generated by Java with some extra information included to make it executable as a standalone program on the client's computer. The issue with Game Jolt is that when a developer uploads a .jar, it determines that the file is an archive and tries to find an executable file in it. Finding none, it will demand that the developer provide a path to the executable.

Anything entered into these fields will result in an "Internal Server Error". This means that any .jar uploads will no longer be shown when marked for specific OS's (Windows, Linux, Mac). The only workaround is to include fake executable files within the .jar using a compression utility (ex. WinRAR). This is not a very good solution and goes against the developer friendly interface of the new Game Jolt.

[Forum post here.] (http://gamejolt.com/community/forums/topics/downloadable-jar-builds-java/12782)

**Comment by Tricky1975** [comment]
Fake executables was something I had in mind myself.

**Comment by YLivay** [comment]
This should've been fixed long ago haha.
Forgot to update this issue!
