### ISSUE TITLE
Game headers glitch out on my Android device

### ISSUE THREAD

**Issue by Savordez** [gamejolt/issue-tracker#314]
Turning the device into landscape layout from portrait and back quickly causes game headers to slightly freak out. I have a Nexus 5.

![headerspls](https://cloud.githubusercontent.com/assets/12786937/8391865/d5cf926a-1cdc-11e5-9c79-1ccdce38138f.png)

**Comment by hworld** [comment]
I think this should now be fixed with the new shell? @Savordez any way you can test again for me?

**Comment by Savordez** [comment]
Tried again with my Nexus 5 (Google Chrome) and the issue seems to be fixed. :>
