### ISSUE TITLE
JAR files shouldn't be treated as archives

### ISSUE THREAD

**Issue by YLivay** [gamejolt/issue-tracker#316]
Currently, jar files are treated as archives which is confusing.
We don't want people to upload jar files directly anyways since usually you need extra run parameters to launch them correctly on the platforms you're aiming for - so the way to go should be package the jar file in a zip along with other launch scripts per platform you're aiming for.

What we should do is display a tooltip client side before uploading the jar file encouraging users to do just that and restrict uploading the jar files directly.

**Comment by Tricky1975** [comment]
Sounds a lot like #313 to me.

**Comment by YLivay** [comment]
Yeah it is haha
בתאריך 1 ביולי 2015 17:53,‏ "Jeroen Broks" <notifications@github.com> כתב:

**Comment by YLivay** [comment]
Will update in #313
