### ISSUE TITLE
Unable to upload a new html5 build as zip file

### ISSUE THREAD

**Issue by XenosNS** [gamejolt/issue-tracker#317]
When attempting to upload a new html5 build in a new release, getting an error that the "the chosen file is the wrong type." Attempted creating a zip file with IZArc and default windows function, and tried using a tar file, no change.

**Comment by YLivay** [comment]
Do you have index.html in the root of the zip? Can you attach the file somewhere?

**Comment by XenosNS** [comment]
yes, the index.html is in the root, same setup I've used in the past. 

I've uploaded the zip file to the link below:
https://www.dropbox.com/s/8tu70iaym1b1qug/campfire.zip?dl=0

here's a screenshot of the error
https://www.dropbox.com/s/0s15pdh7j7zmlxv/upload.png?dl=0

**Comment by XenosNS** [comment]
HI, 
Just tried renaming the zip file to a rar file and then uploaded, that seemed to work. Guessing the upload function isn't recognizing zip files for some reason?

**Comment by hworld** [comment]
That's weird since it actually shouldn't even let you upload a .rar file for html games... haha

**Comment by hworld** [comment]
Would you be able to try to upload the HTML .zip file again? You can always add it to a hidden package for testing and then remove it. I think I pushed out a fix.

**Comment by XenosNS** [comment]
I'll give it a try when I get home
Adam

**Comment by XenosNS** [comment]
Looks good, just added a new build, no issues with the upload. Think you got it.

**Comment by YLivay** [comment]
Fixed then
