### ISSUE TITLE
Sometimes only the first page in a games category will show up.

### ISSUE THREAD

**Issue by IamAcoconut** [gamejolt/issue-tracker#318]
Hi. So I was browsing through the gamejolt games, and I noticed that when I went to the 2nd page of the "Other" category in the "Top Rated" section, it said that the page wasn't found. When I tried it again  it worked, but sometimes it doesn't. This also seems to be a bug for other categories as well.

![output_slyg0w](https://cloud.githubusercontent.com/assets/7675201/8397142/393319dc-1d76-11e5-81d2-24e80be525ac.gif)

**Comment by raeleus** [comment]
I get the same thing. I'm using Chrome on Windows. Looking for Top-Rated Arcade games with a couple filters, Page 1 url is http://gamejolt.com/games/best/arcade?os=windows&status=complete

Page 2 url is http://gamejolt.com/games?os=windows&status=complete&page=2 for some reason. It's missing the /best/arcade bit. After going through the website again, it no longer reproduces the issue. It happens at least once a day for me.

**Comment by hworld** [comment]
Fixed. That was a weird one.
