### ISSUE TITLE
Odd rating in notifications (probably deleted rating)

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#319]
![image](https://cloud.githubusercontent.com/assets/11202073/8406172/17d1ef7c-1e5a-11e5-9297-23e9b2626b29.png)

I believe a number between 1 and 5 had to be displayed, I did see a rating 3 on the day this rating was given along with the comment "this game is shit" (which is quite a bold statement for a game which has (yet) no downloadable content). That comment was removed soon after and I even know the sender of that comment was banned, and I think this rating came from the same guy and was considered a "troll rating" and therefore removed. If that's the case, I think it would be less confusing if the notification about it had been removed as well.

**Comment by hworld** [comment]
Yeah, this happens with removed ratings. Users can now clear ratings as well, which means this might start happening more often. I think the correct thing would be to remove the notification.

**Comment by Tricky1975** [comment]
Users can clear ratings. I suppose you mean that if I rated a game I can then remove that rating I gave. Not the ratings I got for my games I suppose (just trying to have this straight) :)

**Comment by hworld** [comment]
Haha, of course. Not developers. The user that gave the rating. :smile:

**Comment by hworld** [comment]
This is finally fixed with the new notifications system.
