### ISSUE TITLE
Need to fix up url/url redirection for links in profile descriptions

### ISSUE THREAD

**Issue by YLivay** [gamejolt/issue-tracker#320]
Example in Florian's profile: http://gamejolt.com/profile/florian-van-strien/16158
The url for his frameworks direct to the old Game Jolt:
http://gamejolt.com/games/other/gamejolt-achievement-api-for-gamemaker-studio/11689/
http://gamejolt.com/games/other/gamejolt-achievement-api-for-rpg-maker-vx-ace/40546/

**Comment by YLivay** [comment]
Yeesh we still didn't do this. Bumping it up.

**Comment by hworld** [comment]
so, the links work since we redirect just fine, however it does a full page refresh, so it would be nice to get them rewritten into new links so it can keep take advantage of the spa nature
