### ISSUE TITLE
Banner explicit

### ISSUE THREAD

**Issue by Ashlex07** [gamejolt/issue-tracker#321]
First : sorry for my English but i'm practicing.

Second: I do not know much about the banners, but I know it is.
The first time I entered everything was normal until I saw one of these Internet banners on your page. Obviously it's to +18.I was a little confused but also nervous that my family thought badly of me.Finally I had to install ''AdBlock'' of Google Chrome.
I do not know if this can help them but this is the only problem I see from your page.

PS: I do not know who is the best to solve the problem but fast, because some people are boys or girls "gamers" minors.

I hope this can help them.

**Comment by hworld** [comment]
Which banner are you talking about? What's the page address/URL?

**Comment by NickRock** [comment]
Google shows you ads that are relevant to the things you search, you can report an add for being inappropriate or irrelevant by clicking the X at the corner of the ad

![1](https://cloud.githubusercontent.com/assets/11754980/8507594/cd568820-2252-11e5-9aae-a08805076aab.PNG)
![2](https://cloud.githubusercontent.com/assets/11754980/8507593/cd4d9a6c-2252-11e5-941d-16c07a2e7b86.PNG)

**Comment by Tricky1975** [comment]
I'm wondering if this is a GameJolt issue or a Google issue.... :-/

**Comment by hworld** [comment]
Ah, yeah. Closing this.

For the future, be sure to email in any ads that were inapropriate and we will work on removing them from rotation. We need a screenshot, though, and hopefully the domain that the ad was going to direct to. You don't have to click into the ad, but can try to look at the address bar when hovering over it instead.

**Comment by Ashlex07** [comment]
I've been checking the site several times and so far have not seen any of
those banners, I think they managed to remove it or I just had a virus on
my computer but it looks good.

2015-07-01 10:36 GMT-04:00 hworld <notifications@github.com>:
