### ISSUE TITLE
Uploading case problem in extentions

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#325]
I don't know if this issue is there for other parts as well, but I do know it's the case for the thumbnails, so the rest of the site should be checked.
The uploaded extension checker is case sensitive.
MyThumbnail.png will upload as a thumbnail
MyThumbnail.PNG will not upload, as a result. 
Since some software does (by default) capitalise all extensions I think it would be handy if checking extensions in uploads ignores upper and lower case.

**Comment by hworld** [comment]
Fixed.
