### ISSUE TITLE
No mobile login link

### ISSUE THREAD

**Issue by acidpoison** [gamejolt/issue-tracker#326]
When visiting gamejolt.com on mobile while not logged in, there is no link anywhere to gamejolt.com/login. The only way to login is by manually typing in the URL yourself.

![bug](http://s6.postimg.org/egaue2i6p/15_DC01_E8_4_C20_4_EA6_A579_766_CD0_D6_CB5_F.png)

**Comment by hworld** [comment]
Is this a really tiny mobile phone? There are join and sign up buttons, but I wonder if the phone is too small to show them or something. If you take your browser and shrink it down to about the size of a phone, you'll see them at the top.

**Comment by Agrosis** [comment]
I just checked it out on my iPhone 4, Log in and Sign up aren't showing, yeah. Moar race condition?!

**Comment by hworld** [comment]
Haha, I just checked. It's because your phones are too small to show them. I'll see if I can make them even smaller so they can fit on iPhone 4 widths.

**Comment by acidpoison** [comment]
They now appear.
