### ISSUE TITLE
Fonts doesn't work on Game Jolt Jams!!!

### ISSUE THREAD

**Issue by Knowlege** [gamejolt/issue-tracker#327]
I tried changing fonts and when I click on font it changes on page (*e.g.:* if I change headings font headings on page have that font) but when I click *SAVE THEME* it becomes normal and when I click *Customize Theme* and see font it's *Choose a font...*
I tried changing old Jam theme (which had fonts) and there were fonts but when I clicked *SAVE THEME* fonts cleared.
I've heard someone previously had problems with fonts but there weren't any answers.
I'm using Windows XP with Chrome.

**Comment by hworld** [comment]
This has been fixed.
