### ISSUE TITLE
502 Bad gateway whenever a link to a games page is shared on facebook

### ISSUE THREAD

**Issue by ecriss** [gamejolt/issue-tracker#333]
To reproduce. Go to any game page. Copy the game's link from the browser. Share it on Facebook. Normally the game description and the game image shows on the feed. Now all that shows is 502 Bad gateway.

**Comment by hworld** [comment]
We were having some server issues when this occurred. It should be okay now.

**Comment by ecriss** [comment]
Still appears to be happening. Have you verified this issue is no longer occuring by doing a test post in Facebook? I noticed that the meta tags are appears to be rendered through AngularJS. Could that affect the way Facebook parses those meta tags?

![gj502](https://cloud.githubusercontent.com/assets/2216122/8636356/c5fe188a-27f8-11e5-90d0-d4a9a92fe95c.png)

**Comment by ecriss** [comment]
Please reopen this issue. It hasn't been resolved yet.

**Comment by hworld** [comment]
![screenshot from 2015-07-12 10-52-50](https://cloud.githubusercontent.com/assets/1024321/8638530/2dc5c55e-2884-11e5-8992-74d8702e5a16.png)

Working for me. What URL are you trying? It could be that Facebook has it cached.

**Comment by ecriss** [comment]
Hmm.. you're right. Other URLs work. Strange that Facebook caches non-200 responses for so long. I'm still getting the error. I was trying to share my game here: http://gamejolt.com/games/word-climber/77812
