### ISSUE TITLE
Animated thumbnail problems. (Firefox and Internet Explorer)

### ISSUE THREAD

**Issue by raeleus** [gamejolt/issue-tracker#334]
I just discovered that you can upload animated GIF's for your thumbnail instead of a static image. Game Jolt seems to convert it into some WEBM format and autoplays it when the user mouses over the thumbnail.

It works great in Chrome and plays over and over until the mouse exits the thumbnail. In Firefox, it only plays once. In Internet Explorer it doesn't play at all. I imagine that it doesn't work in IE because it's an inadequate browser, but that isn't a fair answer for every little problem :-p

Here is [my game](http://gamejolt.com/search/games?q=forward%20gunner) in the search as an example.

**Comment by Tricky1975** [comment]
Just to add, in Opera this works fine too.

" I imagine that it doesn't work in IE because it's an inadequate browser, but that isn't a fair answer for every little problem :-p"
To many webmasters it is these days. Some websites don't even take IE into account any more because it's too expensive to keep everything working in IE (without risking the chance the "adequate" browsers will not run it well any more).

**Comment by raeleus** [comment]
Darnit! I always forget to test Opera. Opera gets no love. Yeah, IE has had a horrible track record as far as web compliance goes. A web design class I visited once upon a time had a chart comparing all the major browsers in HTML5 compatibility and IE had a big, red column of X's going down the length of it. Yet it's the default browser for at least all the PC's sold in North America.

**Comment by Tricky1975** [comment]
I guess it's on all PCs with Windows installed. The last time I used IE was only to download Firefox or Opera. :)

**Comment by hworld** [comment]
You weren't supposed to find this feature yet. \*shifty eyes\* It's still being worked on. =]

**Comment by raeleus** [comment]
Oh... Hee hee. I guess that's what I get for poking around too much. It's a nice feature though. Makes the thumbnails more fun and believable.

**Comment by hworld** [comment]
Yeah, literally the only reason that we haven't released it as a "real feature" is because Firefox doesn't loop. I just can't figure it out yet. If anyone figures it out before me, let me know!

**Comment by raeleus** [comment]
If you noticed from above, I was only *visiting* the web design class. So I don't know this stuff very well. However I figured out through experimentation that Firefox just doesn't like WEBM videos. I made a basic html file with the WEBM video provided by Game Jolt. It plays once and doesn't loop. Even adding controls, it does not respond as if the player had crashed.

I converted the video to MP4 and tried the same code and it worked. Maybe you should set your converter to make MP4 files instead. You have a src listed for one but it doesn't look like it actually exists.

```
<html>

<head></head>

<body>

<video autoplay loop>

<source id="video" src="fg.mp4" type="video/mp4">

</video>

</body>

</html>
```

**Comment by hworld** [comment]
Fixed! It was some craziness with how we were streaming them.

Should work on Firefox and IE now. We actually output mp4 and webm and the browser decides which one it wants to use.

**Comment by raeleus** [comment]
Wow, it works. Thanks Cros!
