### ISSUE TITLE
-x seconds ago posts.

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#335]
![image](https://cloud.githubusercontent.com/assets/11202073/8640626/5df4b354-28ff-11e5-90cd-55a35d2d267e.png)

I see this a lot lately after I posted a new message (mostly on the forums of which I know they will vanish eventually). Should (in this case) mean this message was posted in the future. I have tried to replicate this on the GJ Next pages, but could not yet do so, but maybe it needs to be looked at to see if the issue does not happen there.

**Comment by YLivay** [comment]
This is just minor clock syncing. Should display "Just now" to hide these
cosmetic changes haha
בתאריך 13 ביולי 2015 02:36,‏ "Jeroen Broks" <notifications@github.com> כתב:

**Comment by NikSudan** [comment]
Should be fixed in the new forum update
