### ISSUE TITLE
Link to Dashboard in Friend Request email result in 404

### ISSUE THREAD

**Issue by loicteixeira** [gamejolt/issue-tracker#336]
In Friend Request emails, the link **Go To Dashboard** points to `http://gamejolt.com/dashboard/friends?utm_source=Site&utm_medium=Email&utm_campaign=notification-friendship-request` result in a 404.

**Comment by NikSudan** [comment]
Currently there isn't a page for handling new friend requests. Could put a section on the activity feed?

**Comment by hworld** [comment]
I removed those links in the emails and redirect the old links to just be your dashboard.

Friend request management is done completely in the top nav in the shell, and you manage your friends using chat.
