### ISSUE TITLE
High score list set up in a confusing manner

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#339]
![image](https://cloud.githubusercontent.com/assets/11202073/8744231/e225c9e6-2c75-11e5-8729-c62e703e07e0.png)

I was pretty confused at first, thinking the left row were all the top scores and the right row the lesser topscores, however I now see the list goes sideways in stead of verticallly. Since nearly all scoreboards I see elsewhere (not only different sites, but also professional sports matches) have it up-to-down and the second row for the lesser top scores, I think this getup is quite confusing even with these numbers in.

*EDIT*:
The shot above was what I got for asking ALL SCORES. When I look on the game overview page in stead there it does follow the "right" way to go. Two ways of printing this out makes it even more confusing.
![image](https://cloud.githubusercontent.com/assets/11202073/8744322/8cd0fece-2c76-11e5-86e4-4b10497976e3.png)

**Comment by hworld** [comment]
It is a bit of a bummer since we show 100 scores on the page, which means you would see at the top the best score and the 51st best score. It effectively makes the 25th score less important than the 55th best for example.

**Comment by hworld** [comment]
So we decided just to make it consistent instead so the scores on game overview page shows the same as scores list. I also made the rank numbers a bit bigger so they hopefully are noticeable enough.
