### ISSUE TITLE
Twitter appears at a game profile. Facebook does not

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#340]
I recently linked both my Facebook and Twitter accounts to GameJolt, and I saw this:
![image](https://cloud.githubusercontent.com/assets/11202073/8832769/279ebe4a-30ab-11e5-96f4-a632a3dd2737.png)

Here in my personal profile both links appear.

However the next shot is taken from my game "Star Story"
![image](https://cloud.githubusercontent.com/assets/11202073/8832786/43be68f0-30ab-11e5-96e6-065ac85d5ad9.png)

Here you can see the link to my Twitter account, but not to my Facebook account. Is this a bug? An oversight? Or a plan to allow people to link a game to an actual Facebook page? Since it's my personal information I guess it's a bug/oversight.

**Comment by hworld** [comment]
This is done on purpose. FB profiles are usually more personal, so I didn't want to include them on every game page. We plan on allowing people to eventually link a FB page, which then we would show.
