### ISSUE TITLE
Picture secret trophies do not show in dashboard overview

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#343]
![image](https://cloud.githubusercontent.com/assets/11202073/8919950/097bf654-34c4-11e5-8ff2-15b487904e43.png)
The second trophy does have a picture, but it does not show in the overview as the trophy is hidden, but a picture WAS uploaded for this. In the upload screen I do see the picture I chose, however I wonder... I think it's handier if the picture shows in the dashboard (especially as I can see it's marked as "secret" I guess there is no use for me as the game's dev to keep the picture hidden on a page only I can see).

Also I cannot see the picture or description on the game profile, even though I'm the owner (I guess until I actually score this achievement). I remember I could on the old site. Was this a bug or a choice to make sure I would see the game profile the same way as my player would?

(I think it's quite obvious why I removed the Trophy IDs from this picture, and the hidden trophy description would be a mega-spoiler and I don't know how many of my (future) players are visiting this issue tracker, so I hid that as well. I guess that was also obvious).

**Comment by Tricky1975** [comment]
What I also need to note (so I discovered when I was sorting out my achievements pictures for Star Story, as what the above reference to Tricky1975/Star-Story#174 is about, don't worry about that reference as it came from my own repository) is that the pictures of secret achievements don't even show on my dashboard page AFTER I actually obtained my own achievement.

**Comment by hworld** [comment]
fixed
