### ISSUE TITLE
No extra distributions shown when "more" clicked

### ISSUE THREAD

**Issue by acidpoison** [gamejolt/issue-tracker#344]
Nothing but a single dot.
![idk a bug](http://s6.postimg.org/v0doegett/wtf_is_this_bug_for_real.png)

**Comment by hworld** [comment]
What game is that?

**Comment by hworld** [comment]
Found it. The game was hidden.

Anyway, I actually just recently pushed out an update to this. Is it still happening?

**Comment by acidpoison** [comment]
Fixed. The other distros are showing up fine now.
