### ISSUE TITLE
Ads aren't visible sometimes

### ISSUE THREAD

**Issue by NickRock** [gamejolt/issue-tracker#349]
![unnecessaryspace](https://cloud.githubusercontent.com/assets/11754980/9084544/8aaa006c-3b7d-11e5-80ea-b0599f6ab5a6.png)

This is from firefox and I don't have AdBlock

**Comment by hworld** [comment]
Does it take a long time to load some times? Or it just never shows? Also, do you use Firefox or a different browser?

**Comment by NickRock** [comment]
I only use Firefox. I had to refresh the website but I doesn't happen often

**Comment by hworld** [comment]
This is because we don't have an ad to show for it. We're working on getting a better fill rate, which will cause this to happen less often, not that people would want it to. haha
