### ISSUE TITLE
Playlists thumbnails are messy when there is no content

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#356]
![image](https://cloud.githubusercontent.com/assets/11202073/9426246/7c92657c-4934-11e5-86aa-610924db16ce.png)

This shot (taken from Opera from Mac) looks a lot to me like a broken picture. The user in question was not following any games at all. Perhaps a more elegant solution is in order, like a proper message "no games followed" or "user is not following any games", or a picture clearly indicating that.

**Comment by YLivay** [comment]
Playlists display as "game thumbnail montages" but that doesn't work properly anymore. The goal  is to have the game  thumbnails in the playlist slide within the thumbnail rectangle.

**Comment by hworld** [comment]
hmm, i no longer see the broken image on chrome or firefox. the icon and gray box is supposed to show
