### ISSUE TITLE
News article previews don't show comment count when there is no comment

### ISSUE THREAD

**Issue by acidpoison** [gamejolt/issue-tracker#357]
![bug news comment count](http://s6.postimg.org/o2df5nm6p/image.png)

Should say "0 comments" or "no comments", but instead just states "comment".
Also happens in game overviews.

**Comment by Tricky1975** [comment]
Perhaps, that "comment" is just a link to the comment section? (I tried it, that's what it is). In that case I don't think this is a bug or otherwise undesirable behavior, but the site just acting the way it was intended to act. I've seen this getup with many other websites, as well.

**Comment by acidpoison** [comment]
Ah, that makes sense. If you've seen this with other sites, I trust you when you say that this is probably the same thing.
