### ISSUE TITLE
Duplicate date listing in game news manager

### ISSUE THREAD

**Issue by acidpoison** [gamejolt/issue-tracker#358]
![news date listing bug](http://s6.postimg.org/58rm8nnyp/image.png)

It may have something to do with August 31 being the last day of the month.

**Comment by Tricky1975** [comment]
Happens now (sep 1st) as well, and I've seen the same bug in the graphics view of the statistics (reported in issue #329), and I'm pretty sure what you reported here is the result of the very same bug.

**Comment by NikSudan** [comment]
Yeah, I think this and #329 must be linked somehow... this needs some investigating!

**Comment by hworld** [comment]
This should be fixed now.
