### ISSUE TITLE
Sometimes the links of the menu don't load

### ISSUE THREAD

**Issue by NickRock** [gamejolt/issue-tracker#359]
![links_on_the_menu_dont_load](https://cloud.githubusercontent.com/assets/11754980/9589455/292291d2-5037-11e5-9d9c-0aaf3651c59f.PNG)

**Comment by NikSudan** [comment]
I can see them, they do look like they're there. The styling seems to have messed up though...

**Comment by hworld** [comment]
I believe this is fixed with new menu.
