### ISSUE TITLE
Notification issue when the notification is about the page you're on

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#360]
Nik or CROS, feel free to edit my subject title as this was hard to cut short, so here, my full explanation.

I had a notification somebody replied to a post I made on a news article so I went there, answered it and went AFK. When I came back a new notification did appear about the same article stating somebody replied to me. I could not yet see this reply as the page was not reloaded, so I clicked the notification itself, but the notification was then gone, but I still couldn't see the post we were talking about without using my browser's refresh button.

Of course, when clicking on a notification from another page, this one works the way it should.

I hope that was clear enough :sunglasses:

**Comment by NikSudan** [comment]
Hmm, a solution to this would be forcing an API call to be made regardless of if you are on the same URL. Either that or real time forum posts... which would be cool as hell!

**Comment by YLivay** [comment]
Forums need a redo anyways. The API call IS made, but it marks the notification as read right away because you are on the page. IMO it'll be awkward having the notification just refresh your page too. Is there a more elegant solution?

**Comment by Tricky1975** [comment]
"Forums need a redo anyways." 
I was not talking about the forums, actually. The issue I described above was about the game news section, though the same issue exists on the game profiles.

**Comment by YLivay** [comment]
Notifications overhaul WOOP! Only took a year!

**Comment by Tricky1975** [comment]
Better late than never 😛
