### ISSUE TITLE
Paid games have no play count

### ISSUE THREAD

**Issue by niksudan** [gamejolt/issue-tracker#361]
Not sure if this is intentional or not, but if it is then the tooltip makes no sense.

![thunda gunna woop](http://i.imgur.com/asa99tM.png)

**Comment by YLivay** [comment]
Seems to be a frontend issue, the data is there.

**Comment by Agrosis** [comment]
Actually, I just checked it out and package/release/builds data isn't sent on the normal payload. probably side effect of marketplace

**Comment by YLivay** [comment]
ohohooo something is obsolete!

**Comment by CyberKiller40** [comment]
Paid games are obsolete? Awesome!!!
