### ISSUE TITLE
Users appearing offline in chat when they're not

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#362]
![image](https://cloud.githubusercontent.com/assets/11202073/9749783/aa199eb6-5690-11e5-883e-56cc26f9d046.png)

[Original Forum Thread](http://gamejolt.com/community/forums/topics/incognito-accounts/13493)

**Comment by YLivay** [comment]
Will be fixed in chat recode :)

**Comment by Tricky1975** [comment]
I've seen this bug (I don't know if it's related) happening on a profile page seeing a user marked as "offline" of whom I was pretty sure he was online (since it was my own profile page). Renewing the page did show me on-line though.

**Comment by YLivay** [comment]
Yes its the same thing - all will be fixed!

**Comment by hworld** [comment]
Should be fixed in new chat.
