### ISSUE TITLE
'Send' button on chat stays green when it is pressed

### ISSUE THREAD

**Issue by NickRock** [gamejolt/issue-tracker#363]
![sendbutton_chat](https://cloud.githubusercontent.com/assets/11754980/9835921/b5efe13c-5a0a-11e5-94b0-8ff8c35e33da.gif)

**Comment by YLivay** [comment]
Will be fixed on chat recode.

**Comment by Agrosis** [comment]
This isn't really a bug, this is because gamejolt buttons are set to be that color when they're active. @hworld is this still an issue?

**Comment by hworld** [comment]
I kept it because I guess it's slightly annoying? But, yeah, it's just normal browser behavior... should we close?
