### ISSUE TITLE
'Close' button on chat doesn't work

### ISSUE THREAD

**Issue by NickRock** [gamejolt/issue-tracker#366]
![closebutton_chat](https://cloud.githubusercontent.com/assets/11754980/9885231/c7e80138-5bec-11e5-99d0-53c2480fa882.gif)

**Comment by NickRock** [comment]
Tested again, it works now. I don't know why it didn't work the first time

**Comment by YLivay** [comment]
Closing chat is not completely a client side operation, it still needs a confirmation from the server and you may have lost connection to it temporarily.

At any rate, these issues will be smoothed over in the new chat :)
