### ISSUE TITLE
No comment displayed on comment entry

### ISSUE THREAD

**Issue by acidpoison** [gamejolt/issue-tracker#367]
![no comment](http://s6.postimg.org/plkl0pqvl/Screenshot_2015_10_01_at_11_09_42_PM.png)

Also confirmed to have no comment by Dodgetgo.
Maybe due to foreign characters? (his/her english suggests that he/she speaks a different language)

**Comment by NikSudan** [comment]
On a completely unrelated note, I really like the way you display the chat!

**Comment by YLivay** [comment]
Probably multibyte string issues.

**Comment by YLivay** [comment]
Should be all good twith the new translations branch too.
