### ISSUE TITLE
Better background on transparent avatars Fireside

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#368]
![image](https://cloud.githubusercontent.com/assets/11202073/10250520/87079042-692b-11e5-9109-b3fc158937ed.png)

This screenshot is taken from an article I once wrote as a blog that now ended up on Fireside.
My avatar has an alpha channel, and that pops up pretty ugly here. I don't know if there are any other pages where this issue takes place.

P.S. On this article I also received comment in which the poster expreses his/her(?) confusion because my username (Tricky) is displayed in stead of my screen name "Phantasar Productions". Was that on purpose?

**Comment by hworld** [comment]
gonna close since we're not updating fireside

**Comment by Tricky1975** [comment]
Not updating FireSide? There are different plans for FireSide then?

**Comment by hworld** [comment]
Yeah, basically doing user posts that would show directly in your profile similar to game devlog instead. Going back to the developer news days!

**Comment by Tricky1975** [comment]
I guess based on [this request](https://gamejolt.com/f/profile-devlogs/341456?sort=top), right?
Also brings me to the question, some old pre-gamejolt-next blogs of mine (which I cannot find anymore) were dumped on FireSide... Will they be returned when this feature is available?

**Comment by hworld** [comment]
Well, I've been planning to do user/profile posts for a while now (over a year), but the users definitely seem to want it as well, which is always good!

Your old dev news stuff will come back when we make the switch, yeah!

**Comment by Tricky1975** [comment]
Thanks ;)
