### ISSUE TITLE
Notifications take too long to close

### ISSUE THREAD

**Issue by NickRock** [gamejolt/issue-tracker#369]
![not_take_too_long_to_close](https://cloud.githubusercontent.com/assets/11754980/10341339/fb60836e-6d1c-11e5-81f5-0f11bc19dd35.gif)

**Comment by Tricky1975** [comment]
Do you have the same problem if you dismiss all notifications all at once? (with the "(dismiss all)" link)

**Comment by NickRock** [comment]
Yeah

**Comment by YLivay** [comment]
How many notifications are we talking about? It's usually fast for me.

**Comment by Tricky1975** [comment]
Uhm, yeah looking at that (animated) screenshot, I guess you got a point here.

**Comment by YLivay** [comment]
Irrelevant!  Only took a year but we got there!
