### ISSUE TITLE
Serious server issues

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#371]
Well for starters let's kick off this screenshot:
![image](https://cloud.githubusercontent.com/assets/11202073/10542015/5fbd712e-7415-11e5-8fcd-6b190d474196.png)
I get that one about every 3 or 4 new page loads on GJ at this moment.

I know I have a bad ISP, however, all other websites I regularly visit work fine, GameJolt is the only site that currently does not work on me. At other times I get "Request TimeOut" or "GateWay Time Out" or "Server Error" and so on, and basically this affects ALL GameJolt pages, and the game I'm creating also takes forever to login with the GameJolt API (How fortunately I built in a routine to skip the login procedure). This combined with many many complaints on the forum right now about news not popping up, uploads not working (and according to a few posts by Jani who did have a view in the Dev console of his browser and found most of all server related errors in that console output), I have the feeling that the GameJolt servers are just one big mess at this moment.

I also see a lot of pages only being "half-loaded", a very good example in which that shows is the WYSIWYG editor not showing on the forums. 

I must also say I've seen little announcements from the staff, or response to forum complaints, most of them are now answered by regular forum visitors, and most of them also know little. Now I must say I did try to search FireSide about any status reports or announcements on the current situation (as I might have missed some), but all I got was this:
![image](https://cloud.githubusercontent.com/assets/11202073/10542196/b60fbc48-7416-11e5-9eae-4eb6c6187a84.png)

And I actually had to reload FireSide a few times due to "timeout" errors before I even got that (well I guess that is the "load-load" problem, and I think that's the same problem causing the WYSIWYG editor on the forums not to appear).

**Comment by hworld** [comment]
While I haven't experienced any issues on the networks I've been, I do feel that the site isn't as fast as I'd like yet. I'm currently working on a migration off our current host on to Amazon. The goal is to increase scalability but also speed and reliability of the site.

The news not working was a separate DB issue that has been fixed, however.

I have been on vacation for about a month. The release of the new site really burnt me out, so I needed some time off. Today's my first day back. I'm working on getting some better architecture behind the scenes.

**Comment by YLivay** [comment]
Heya Phantasar, the Github issue tracker is the place you should report issues in. See, 5 minutes in and you get a response :)  
Anyway, the issues you mentioned are unrelated and most of them have already been fixed if you'd check. I wasn't able to confirm any slowness or timeouts on the website, is it something constant or just started happening recently?

**Comment by Tricky1975** [comment]
@hworld 
Ah, thank you for telling me that.
Let me first tell you (if that calms you down) that nobody understands more how preparations for a release of a new site or any project this large can burn you out, as I'm quite familiar with the experience (also because I suffer from a disorder that burns me out easily anyway (I'm an aspie, and that's no secret, I even revealed that on the forums a few time)). 

It was a bit frustrating that I did see a lot of complaints appear on the forums and that only we (the non-staff members) basically had to answer them without knowing where you were. Don't get me wrong, if there was anyone deserving a vacation it's you, but since we didn't know that, things got a little frustrating on us.

@YLivay
Well, I was actually amazed to get a response this fast, since other issues reported in (I'm not only talking about my own) took quite some time before they were even labelled ;)

The time-outs issues have started about 3 or 4 weeks ago, but then only once or twice a day, but it soon became more and more, and since a few days only a few times a page loads fully without any trouble at all (except a bit of a delay).

**Comment by hworld** [comment]
@Tricky1975 I'm going to try to start paying more attention to the community and interact with them more often (even if it means less development time) now that I'm back. =]

**Comment by Tricky1975** [comment]
Thank you :wink:

**Comment by hworld** [comment]
Hey @Tricky1975, is the site more stable now? We've migrated to new servers and done a ton of work on stability. How's it been for you?

**Comment by Tricky1975** [comment]
At this moment stuff is running pretty fine. Of course, some of the stuff I mentioned may need me more time to make sure they are fixed (as they happened a bit randomly, like the WYSIWYG on forum issue), but overall, it appears most issues are gone now.

**Comment by hworld** [comment]
k, great! I've noticed that forum homepage can take a bit of time. I'll work on making it speedy when we redesign it. Gonna close this for now. You can reopen if you see issues again.
