### ISSUE TITLE
News thumbnails not shown when the thumbnail is an animated GIF.

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#372]
When discussing [this thread on the forums](http://gamejolt.com/community/forums/topics/how-do-you-get-an-image-shown-next-to-your-news-in-the-news-stream/13807) it sounds like static thumbnails are shown in the news stream, but animated GIF images appear not. 

Perhaps this needs to be investigated.

**Comment by YLivay** [comment]
This is most likely related to the bug we know about with processing GIFs in general, not just displaying it for the news thumbnail. GIF is a weird format and some times when you optimize it or muck around with it it renders some operations we depend on impossible (like, taking a single frame out of the gif).

@mindlessf I'd like to see if this is indeed the case, can you link the problematic game page and the original gif you uploaded? Also, search for your game in the searchbar and see if it appears blank there too.

**Comment by hworld** [comment]
things will change with devlogs. going to close since a little outdated now
