### ISSUE TITLE
Chat boxes won't close

### ISSUE THREAD

**Issue by NickRock** [gamejolt/issue-tracker#375]
![chat_messages_wont_close](https://cloud.githubusercontent.com/assets/11754980/10894813/534ba346-81b9-11e5-94a8-c23d6f623638.PNG)

**Comment by NickRock** [comment]
Found a little similar bug so that's why I'm posting it here
The previous bug occurred when I clicked anywhere on the page except the chat box (and the chat box was supposed to close)

Now when you click the close button this happens:

![gfdsgfgs](https://cloud.githubusercontent.com/assets/11754980/11305574/12b41d58-8fb6-11e5-9aff-0092715ed65f.gif)

**Comment by hworld** [comment]
What's the bug? It's supposed to close the room but keep the chat sidebar up in case you want to go into a different room.

**Comment by NickRock** [comment]
Woops my bad, I was just used to having the right chat bar always opened and in this version of gamejolt it's closed by default
