### ISSUE TITLE
Trophy Pictures Do Not Load Correctly

### ISSUE THREAD

**Issue by TheRealDannyyy** [gamejolt/issue-tracker#376]
Some trophies do not load the images even after re-uploading them.

**Affected Browsers:**
> Firefox (Tested)
> Chrome (Tested)
> Internet Explorer (Tested...)
> Opera (Tested)

**Dev. View:**
![issue 1](https://cloud.githubusercontent.com/assets/15656049/10946100/b927229a-8320-11e5-97ad-f23b4ff7eeb1.png)

**User View:**
![issue 2](https://cloud.githubusercontent.com/assets/15656049/10946101/b9290c72-8320-11e5-9a83-a4bfe26efb77.png)

**Webconsole Error-Report:**
`Error: Image not available Stack-Trace: exports.NodeActor<.getImageData<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/server/actors/inspector.js:639:29 actorProto/</handler@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/server/protocol.js:1013:19 DSC_onPacket@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/server/main.js:1586:15 LocalDebuggerTransport.prototype.send/<@resource://gre/modules/devtools/dbg-client.jsm -> resource://gre/modules/devtools/transport/transport.js:569:11 makeInfallible/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/DevToolsUtils.js:83:14 makeInfallible/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/DevToolsUtils.js:83:14`

**Comment by Tricky1975** [comment]
Which game are we talking about. Perhaps I should test if the images don't appear on me either, so it can sometimes just be a connection error. I'd like to make sure we can rule that one out.

**Comment by TheRealDannyyy** [comment]
http://gamejolt.com/games/the-ways-of-beer-remastered/19035/trophies
The first trophy ("Now It's Green!") is not loading for me at least

**Comment by Tricky1975** [comment]
This is what I see:
![image](https://cloud.githubusercontent.com/assets/11202073/11022679/e7890710-8664-11e5-98ba-f58fd2cde723.png)

I'm pretty sure this is not what it has to look like (I'm on Opera on Mac).

**Comment by TheRealDannyyy** [comment]
Exacly, the images do not load due to security issues by the serverside I think.

**Comment by hworld** [comment]
Can you add the image file here so I can attempt to upload it and see what may be happening?

**Comment by TheRealDannyyy** [comment]
![now it s green](https://cloud.githubusercontent.com/assets/15656049/11036505/35520d18-86f9-11e5-80a0-efa38e81d488.png)
Here it is.

**Comment by TheRealDannyyy** [comment]
I see you added the picture by yourself, is the issue fixed too so I may test it out on my side?

**Comment by YLivay** [comment]
This should've been fixed ages ago with all the changes we did to mediaserver. I know it's ridiculous to even revisit this issue, but can you check if you still have issues with it? Try reuploading the image.

**Comment by TheRealDannyyy** [comment]
Yeah it was fixed 2-3 days after my report, feel free to close it for me.
Thanks again for the fix!

**Comment by YLivay** [comment]
Haha nice! Thanks!
