### ISSUE TITLE
Deleted messages still in notifications like the deletion never happened

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#377]
![image](https://cloud.githubusercontent.com/assets/11202073/11016525/88f806dc-8584-11e5-9d6e-451dfb939b25.png)

This comment was once posted on Star Story. The one who posted this was (apparently) seen by the moderators as a troll and the comment itself was removed (I believe the author was also banned, but I'm not sure, but that doesn't actually matter in what I'm trying to say here). Yet the notification remained so I discovered today. Now I did see this comment on my game page, and I detected its removal (also due to #319). However it could also have been possible I never saw this message at all on my game page and that the mods removed it before I saw it. I think that can lead to some confusion, and in the case of immature devs maybe also to the flamewar the mods wanted to prevent (and if the PM-shout-replacements comes in place it might even get worse underground). So I think either the removal of the notification as well might be in order (or at least a mark stating a mod removed it to prevent confusion).

**Comment by YLivay** [comment]
This is fixed with the new notifications system.
