### ISSUE TITLE
GameJolt entirely 404

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#378]
Whatever page I try to visit on GameJolt now, I get this:
![image](https://cloud.githubusercontent.com/assets/11202073/11087786/80fad24e-885d-11e5-8c24-e299fd912a33.png)

**Comment by hworld** [comment]
https://twitter.com/gamejolt Will close this after we're migrated.

**Comment by Tricky1975** [comment]
Aha, since I hardly visit Twitter, it's quite obvious I missed that.

**Comment by hworld** [comment]
All done!
