### ISSUE TITLE
RPGMVxAce - Problem login and syncing

### ISSUE THREAD

**Issue by Emicloud91** [gamejolt/issue-tracker#379]
Hello guys! 

I already reported this on forums, but they recommend me to post it here as well:
http://gamejolt.com/community/forums/topics/rpgmvxace-anyone-else-with-problems-login-on-gamejolt/14049#post-68697

I've been wondering if anyone has problems login on Gamejolt using this: https://gamejolt.com/community/forums/topics/gamejolt-achievement-api-for-rpg-maker-vx-ace-beta/5140

I've been using this since months ago, without problem, even a few days ago it was working. But not now...

Keeps saying "Something went wrong...". I tested several times with different users, but doesn't seem to work. I wonder if it's something temporal or maybe the script needs an update.

UPDATE: Some other users reported the same, maybe it has to do with changing the servers, or something like that. 

Please, any comment or help is appreciated!

Thanks!

**Comment by hworld** [comment]
Hey there, is it still happening by any chance? Do you have the game on Game Jolt for me to test it with, by any chance?

**Comment by Emicloud91** [comment]
Hello hworld!
Yes, I tested it just a moments ago, with old versions of the game, and it's not working. 
Here's the game: http://gamejolt.com/games/empty-soul/53589
Thank you for the quick response!

**Comment by YLivay** [comment]
Ahhh, Florian's stuff! I'll look into it.
On a side note, your game looks awesome.

**Comment by Emicloud91** [comment]
Thanks YLivay, I appreciate it! It's been a long and hard project. Hope the problem gets solved, I'll be trying until release next weekend. :)

**Comment by hworld** [comment]
I've fixed this. It was doing a redirect from a URL with a trailing slash in the URL to one without.
