### ISSUE TITLE
Page error when going from big list to small

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#385]
Maybe the topic name isn't clear so let's try to explain it.

When you go from the last page of the "FNAF" tag results to the "Horror" tag results by means of the menu you get an empty page, which isn't so strange since the FNAF tag contains by far more entries than the Horror tag, and thus I end up on a page number far beyond the max number of pages in the new category. Perhaps when switching from one tag to another it's better to switch back to page 1 anyway (since you want the top results anyway, at least most people do)

![image](https://cloud.githubusercontent.com/assets/11202073/11285227/b3681f86-8f0e-11e5-8597-9fdbadfe5bea.png)
(Yeah FNAF has games on this high page number, Horror clearly has not).

**Comment by hworld** [comment]
Fixed! Nice catch. =]
