### ISSUE TITLE
Super fast feature animations

### ISSUE THREAD

**Issue by Agrosis** [gamejolt/issue-tracker#386]
On chrome, it looks like there’s a bug where when you have friends list open and leave tab for awhile, the featured game transitions don’t happen, and when you go back into tab, they all happen really quickly

**Comment by NikSudan** [comment]
Proof

![](http://i.imgur.com/oXT1qSl.gif)

**Comment by Tricky1975** [comment]
Odd. I was not able to replicate this bug on Opera.

**Comment by hworld** [comment]
Fixed this. It no longer transitions the featured spot when the focus moves away from the window. This is probably better anyway.

**Comment by Tricky1975** [comment]
I did see this:
![image](https://cloud.githubusercontent.com/assets/11202073/11301824/05b95d14-8f9a-11e5-9e42-8b223c9a8db1.png)

I don't know if this is related, it could be the result of this fix and me not yet having renewed the page.
