### ISSUE TITLE
Playlist not displaying games

### ISSUE THREAD

**Issue by acidpoison** [gamejolt/issue-tracker#387]
[A few people on the forum](http://gamejolt.com/community/forums/topics/broken-website/14097?forum_topic_post_page=1#forum_topic_posts) are reporting that games in any playist that is not their My Followed Games playlist is not showing up. They're saying it was working up until the recent update.

![gj playlist bug](http://i65.tinypic.com/2djz04x.png)

**Comment by hworld** [comment]
Fixed it! Was only happening to logged in gamers.
