### ISSUE TITLE
Need Alert for Pre-WTTF games without maturity rating or builds for completed/canceled

### ISSUE THREAD

**Issue by MaskofThoro** [gamejolt/issue-tracker#390]
On pre wttf games it's impossible to save changes if never added the now required maturity rating or if their game page state is complete/canceled without a build. We need an alert of some sort letting the dev know to update their game page state to WIP or add maturity rating in order to save/publish changes.

when the "Save Game" button is clicked, the little blue progress bar shoots across the top of the screen as expected, but when it's expanded completely from left to right and disappeared, the save button is still greyed out (with the red mouse icon when hovered), and nothing more happens. On revisiting/refreshing the page, the changes haven't been saved.

RjB Software

**Comment by YLivay** [comment]
this has been done ages ago
