### ISSUE TITLE
When opening chat sidebar, library nav moves down

### ISSUE THREAD

**Issue by Agrosis** [gamejolt/issue-tracker#392]
On /library, opening the chat sidebar causes the left nav to move vertically down until the sidebar is closed. Chrome, OS X

**Comment by YLivay** [comment]
I'm unable to check if this is still an issue. Doesn't happen on Windows tho.

**Comment by Agrosis** [comment]
It still happens if you look really quickly at the nav on the left. It gets slid out to the left now though, so it might not be that important anymore.

**Comment by YLivay** [comment]
Hmm we're gonna be redesigning the /library page entirely anyways, so I'ma gonna close this for now :)

**Comment by hworld** [comment]
Reopening since it's still an issue.

**Comment by hworld** [comment]
fixed in new frontend -- somehow
