### ISSUE TITLE
Middle clicking chat links shift the chat box a little

### ISSUE THREAD

**Issue by acidpoison** [gamejolt/issue-tracker#394]
Just a tiny bug, no big deal really. Clicking the window fixes the alignment.
![bug](https://cloud.githubusercontent.com/assets/11214348/11759413/cf1da102-a047-11e5-8ce2-d4977b7dd44f.png)

**Comment by NikSudan** [comment]
Should this be fixed with new chat @cros @agro?

**Comment by NikSudan** [comment]
Should this be fixed with new chat @hworld @Agrosis?

**Comment by Agrosis** [comment]
Fixed ez.
