### ISSUE TITLE
App crashing when closing

### ISSUE THREAD

**Issue by Disreality** [gamejolt/issue-tracker#398]
When closing the Game Jolt Client on Fullscreen on Mac OS X 11.2, the app just crashes.

App version 0.1.1

**Comment by Colinmaxmangames** [comment]
Same here :'(

**Comment by hworld** [comment]
Does this only happen on full screen? And are you just exiting full screen or are you actually trying to close the client and then it crashes?

**Comment by CyberKiller40** [comment]
Maybe similar: on GNU/Linux the terminal output also mentions a crash dump when the client is closing (regardless of window size or if using the window close button or the exit command in the client), log:

[28544:1223/071445:WARNING:channel.cc(553)] Failed to send message to ack remove remote endpoint (local ID 1, remote ID 1)
[28544:1223/071445:WARNING:channel.cc(320)] RawChannel write error
Parent failed to complete crash dump.

**Comment by PinguRares** [comment]
@hworld no; it just crashes when I press the close button in fullscreen

**Comment by YLivay** [comment]
We're currently updating the client to a newer version of nwjs finally. This upgrade is straight out of a cheesy horror movie but we're getting there.
