### ISSUE TITLE
Downloads not starting even if i'm not playing a game

### ISSUE THREAD

**Issue by wiiblob** [gamejolt/issue-tracker#399]
I just downloaded a game from the client, and when I stopped playing it the black bar at the bottom still said it's playing. Then I decided to install another game, but it won't start downloading because the client still thinks i'm playing. 

Screenshot: http://prntscr.com/9glxxg

EDIT: Tried closing and opening the client but it didn't work!

**Comment by NikSudan** [comment]
What OS are you on?

**Comment by wiiblob** [comment]
Windows

**Comment by YLivay** [comment]
What game were you playing that didnt close? That RePete one?

**Comment by YLivay** [comment]
Cant recreate this, Maybe the game is stuck in process list Check task manager and make sure its quit. Also, visit the game page again, does it say its currently playing?

**Comment by wiiblob** [comment]
Even restarting my pc didn't work!

**Comment by YLivay** [comment]
Well, whatever it was, couldn't recreate - new update should take care of queued downloads a little better now :)

**Comment by YLivay** [comment]
Ive managed to recreate this! Investigating

**Comment by wiiblob** [comment]
Now the problem is that I can't play any game I already launched... for example I played RePete and after I play it, the play button disappears, also the black bar at the bottom shows i'm playing two games.  http://prntscr.com/9hfb21

**Comment by Tricky1975** [comment]
@wiiblob 
On a side note, here on Github you don't need an external host for screenshots.
You can copy and paste pictures in your messages here on GitHub and GitHub will automatically upload them and put in the markdown code for it in the message and it will just appear in the message, automatically scaled (with a link to a big version of the picture) if needed.

Like this:
![image](https://cloud.githubusercontent.com/assets/11202073/12001572/38940402-aaeb-11e5-8d0d-c784049c83ec.png)



Back on the issue itself. I think I should link to [this forum thread](http://gamejolt.com/community/forums/topics/gamejolt-client-problem/14345), as there are multiple people complaining about the same issue there (at least they kept this issue in one thread. The revenue issue gets a new thread every 2 or 3 days). Perhaps one of the sitedevs needs to post a reply to that thread to let people know you guys are on it ;)

**Comment by YLivay** [comment]
Done, needs merge
