### ISSUE TITLE
Client needs back button and most of all a 'refresh' button

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#402]
I did get a few times a blank screen on the client, though I don't know if the client is to blame for that, as I regularly have that in my browser as well, and not only on GameJolt, so that might just be my connection. However, whenever that happens I'm now forced to shut down the client and restart it completely, while a simple "refresh" button could have done the trick.

A "back" (and maybe also a "forward") button are definitely desirable as well.

(I am on Mac, though, I think what I just said will apply on Linux and Windows as well) ;)

**Comment by hworld** [comment]
There are snazzy back and forward buttons in client. Look at the top left. Do you know what pages get blanked? Does it ever try loading before it shows blank?

**Comment by Tricky1975** [comment]
I just went to the main page and then it happened, but like I said I see this a lot in my actual browser as well and not only on GameJolt, but on all sites. 
Ah yeah, I did see the buttons you mean (though they are part of the "site" and not really of the "client", but it indeed helps. A refresh button needed to solve any possible blank screens won't help from inside the site.

**Comment by CyberKiller40** [comment]
This is connected to #419 

BTW: it would be cool if back/forward was also mapped to mouse4 and mouse5 like most browsers do

**Comment by Tricky1975** [comment]
[moved here](https://gamejolt.com/f/client-needs-back-button-and-most-of-all-a-refresh-button/341377?sort=active)
