### ISSUE TITLE
youtube player not working

### ISSUE THREAD

**Issue by samnut64** [gamejolt/issue-tracker#403]
all videos will not load
![jolt error](https://cloud.githubusercontent.com/assets/15760435/11930757/509cbc68-a836-11e5-9f6d-11d258735752.PNG)

but i can still look at them by pressing the youtube button
![jolt error wa](https://cloud.githubusercontent.com/assets/15760435/11930821/bc61e338-a836-11e5-863d-f2e64bab898d.PNG)

**Comment by dnielbloqg** [comment]
The issue has been persistant for me. Neither player nor in-client browser work for me.
![gamejoltclient_y8x8ufx1l8](https://user-images.githubusercontent.com/34980975/51413976-00c9f280-1b71-11e9-9fae-b1254186bb31.png)
![gamejoltclient_yq9q6npkiz](https://user-images.githubusercontent.com/34980975/51413982-058ea680-1b71-11e9-9e94-ef5ebb10c688.png)
