### ISSUE TITLE
Include an icon file with the Linux version

### ISSUE THREAD

**Issue by CyberKiller40** [gamejolt/issue-tracker#405]
Please include a graphical icon file (png, 64x64 or larger) with the client application (at least for GNU/Linux), so a user can create a nice looking shortcut to the client in their system.

**Comment by CyberKiller40** [comment]
OK, found it in:
game-jolt-client/package/app/img/

**Comment by hworld** [comment]
We're making a desktop file right now, as well, that should help.

**Comment by YLivay** [comment]
Done
![Happy happy](http://i.imgur.com/6yY3dfL.png)

**Comment by hworld** [comment]
Just so it's clear. The Client creates this desktop file when you open it up. It'll also create it the next time it auto-updates. So, it should be there shortly after you launch the Client.

**Comment by CyberKiller40** [comment]
Confirm, works ok in KDE5 (OpenSUSE 42.1)
