### ISSUE TITLE
Client appears to remove certain files from game installations

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#406]
Somebody complained that [Cuckoo Castle](http://gamejolt.com/games/cuckoo-castle/87063) (for Mac) does work in a direct download, but that it didn't work when installed through the client. Of course I wanted to make sure if this was GameJolt's fault or the developer's fault and in order to do that I broke open the .app bundle that OS X works with, and I could find the source of the evil pretty easily. Inside the bundle I found dozens of .pak files in the "pure install" and all of these were removed from the installation when the game is installed through the client. I take it the vital information the game needs to run in stored in these files.

The game was written in Construct 2, and I really don't know how Construct 2 creates its distributions, but if the .pak files are created by Construct 2, then more games written with this tool might suffer from this issue. Not to mention .pak is an extension for packed data I found in many games, even commercial ones like "Quake", "Lands of Lore" and games from the "Kyrandia" series (I know these are oldies, but still), so I deem it very likely Construct 2 creates these files and that more game development tools do. 

Now I could only test this out on Mac, if this problem also exists on the other platforms should definitely be looked at.

**Comment by hworld** [comment]
Will certainly take a look at this!

**Comment by YLivay** [comment]
Mine.

**Comment by YLivay** [comment]
If its the same bug behind #418 as I suspect it'll be fixed in next version hopefully!
At any rate - I'm adding it to the next version milestone.

**Comment by YLivay** [comment]
Should be fixed in new version!
