### ISSUE TITLE
Copy current url

### ISSUE THREAD

**Issue by CyberKiller40** [gamejolt/issue-tracker#407]
Just a trivial, low priority enhancement:
Add some way to copy the current site url, to be able to send the link to someone over the chat, etc. This can be done as an option in a right click menu.

Copy link url (for linked games websites) would also be nice.

**Comment by hworld** [comment]
For sure. I think we need a little share menu next to the Add to Playlist button. From there we can actually show the link, and give options for sharing (twitter, fb, send your friend a PM, etc)

**Comment by YLivay** [comment]
Would this be properly handled by #499?

**Comment by CyberKiller40** [comment]
Possibly, if there'll be an option to copy a normal http protocol url. IMHO steam does this in a great way - right click anywhere and just pick 'copy this site url' puts the http url into the clipboard.

**Comment by YLivay** [comment]
Yup! We're going to handle all this in #499!

**Comment by Tricky1975** [comment]
In that case I guess this is one on [gj-improve](https://gamejolt.com/f/need-a-way-to-get-the-current-url-in-client-to-share-also-navigate-to-url-in-client/341375?sort=active) in the same thread as #499
