### ISSUE TITLE
Sometimes games fail to uninstall.

### ISSUE THREAD

**Issue by YLivay** [gamejolt/issue-tracker#412]
Sometimes games simply fail to uninstall. Not sure if due to stress from uninstalling multiple games concurrently or games just being too big. Maybe issuing uninstall twice on a game before it finished triggers it but then it seems the games never finish uninstalling.

Restarting the client allows you  to attempt uninstall again, which finishes almost immediately.

**Comment by YLivay** [comment]
I couldn't recreate it again, but im going to go ahead and plug graceful-fs for del and keep watching for issues like this.

**Comment by hworld** [comment]
I wonder if when you were madly uninstalling games you accidentally clicked on the same one twice? I think I wasn't blocking it from happening more than once before, so that could be the cause.

**Comment by YLivay** [comment]
I do every madly. At any case this hasnt happened since update. Gonna close this.
