### ISSUE TITLE
Better download/unpack user experience

### ISSUE THREAD

**Issue by YLivay** [gamejolt/issue-tracker#414]
__Current situation:__ Currently when you pause/resume a game it wont get queued anymore unless you restart the client and resume a paused task. This effectively bypasses the max downloads/extractions settings.

__Problem:__ When you're resuming multiple games from your installed games view they all get resumed instead of queued, so if you have don't want all of them going off at the same time, you have to remember to resume them yourself.

__Solution:__ I suggest force allowing games to resume  only if you are resuming them from a _queued_ state, not a _paused_ state.

Also, as an extension to this suggestion, how about a _pause all_ / _resume all_ feature available from the installed games view?

**Comment by hworld** [comment]
Always go back into the queue. Don't allow them to downloading/install more than their settings allow for now.

**Comment by YLivay** [comment]
Done, needs merge.
