### ISSUE TITLE
Documentation on allowed archive formats

### ISSUE THREAD

**Issue by CyberKiller40** [gamejolt/issue-tracker#415]
With the client auto extracting games file I think it became more important to include information on the archive formats that work with it. It didn't matter as much earlier, cause every user could extract anything on their own. There is no such info on: https://help.gamejolt.com/dev-packages

So far I found:
works: zip, tar.bz2
doesn't work: 7z
unknown: tar.gz, tar.xz, rar

A note about keeping the Linux permissions (the +x on game binary) in tar.* formats would be good to add too - many game devs don't know about this.

I can write a paragraph for the docs on this topic, if someone provides the information.

**Comment by hworld** [comment]
xz, gzip, and tar all work.Our goal is to just get everything to work so that users don't have to worry about what they upload. 7z should also work so if its not we need to fix that up. It should be a bug if something that a dev uploads is not supported. They shouldn't have to think.

We also ensure that the executable is chmodded so it doesn't matter if devs upload without that for client.

**Comment by CyberKiller40** [comment]
Well, this morning (6:00 CET) a friends game that was packed in 7z didn't extract at all (I got an empty directory, we switched the build to tar.bz2 and it was ok), <del>and I found at least a couple of games that weren't chmoded to be executable (example as of now: http://gamejolt.com/games/donkey-me-raiders-of-the-lost-ark/17987 ). So if this all should work then this needs more investigation.</del>

OK, that particular game works now, but didn't yesterday evening (btw: better chmod to 755, not 777). I guess you put out new versions faster than I can check :-).

**Comment by YLivay** [comment]
Can you link the game you were getting 7z failure in?

**Comment by CyberKiller40** [comment]
@YLivay it's this one, but it no longer has a 7z build http://gamejolt.com/games/vinland-trail/25575

**Comment by YLivay** [comment]
Im going to investigate this now (phew)

**Comment by CyberKiller40** [comment]
This was filed in the first days of the client being out in the open. It might have been fixed already.

**Comment by YLivay** [comment]
It may have but I never tested against this issue specifically!
Also, we've been incredibly busy with other goals this might've got slipped away :(

**Comment by YLivay** [comment]
Can't recreate this. We might've solved it without even realizing haha.
Closing this for now.
