### ISSUE TITLE
Soundtracks don't play on Linux

### ISSUE THREAD

**Issue by CyberKiller40** [gamejolt/issue-tracker#416]
Observed on OpenSUSE 42.1

Problem: The game soundtracks don't play, the player doesn't start at all, doesn't register with pulseaudio. (the same happens in a normal web browser also)

Cause: This might be due to the fact that Linux distros don't supply an mp3 decoder. For the browser that is in the hands of the user, but I think it should work out of the box in the client.

Solution: supply an mp3 decoding lib with the client, or recode the soundtracks on the website to vorbis

**Comment by YLivay** [comment]
GJ radio needs to be fixed. not a client/browser issue tho.

**Comment by YLivay** [comment]
Explained the issue in #576 
Will continue updating there.
