### ISSUE TITLE
Client should allow me to download "unreleased builds" on my own games.

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#417]
This will allow me to check if my games actually work in the client BEFORE I show them to the public, which can save me a lot of nasty comments (and downvotes based on not working client versions, simply because I couldn't test before releasing).

**Comment by YLivay** [comment]
If it works when you download as zip it should work through the client. There's this other bug you mentioned where things didnt get patched correctly in version updates but thats our problem (and we're workin on it!). The issue is that this feature conflicts with auto updates.

**Comment by YLivay** [comment]
I totally misunderstood this issue.
If you link the game page in chat and open in client or find it with your dashboard you'd be install it,
so all it boils down to is #499
