### ISSUE TITLE
Links to external websites in comments

### ISSUE THREAD

**Issue by CyberKiller40** [gamejolt/issue-tracker#419]
I just clicked a link to an external website which was in a game comment (link was to dropbox) and it opened in the client window (not the external browser). Without any forward/back controls, it's impossible to get back to GJ.

**Comment by Tricky1975** [comment]
Now this is odd, since when I try to access the forums through the client I do get directed to my browser (likely because the forums are still part of the "old site").

**Comment by CyberKiller40** [comment]
Not forums, a link pasted inside a comment. See game "Land of traps" and a comment reply from the dev after mine (from yesterday) - it contains a link to dropbox, click it inside the client and you have no way to get back. It should open in an external browser.

**Comment by Tricky1975** [comment]
I understood, ya. What I mean is that it's odd that they did take in mind to direct the forums to the browser, but that a link inside a comment was clearly overlooked.

**Comment by hworld** [comment]
Haha, it's not been overlooked, it's just a bug. We have some components to try to capture external links and open in your browser window instead. For some weird reason it must not be attaching correctly to comments. Will look after Christmas.

**Comment by hworld** [comment]
I haven't been able to reproduce this. Every link I clicked (including the dropbox one you referenced) opens in a new window in browser.

**Comment by CyberKiller40** [comment]
Confirm, now it works correctly. This might have been fixed by some previous update.

**Comment by hworld** [comment]
Yeah, that's what I'm thinking. Sweet!
