### ISSUE TITLE
Client crashing when attempting to view games library or browse games

### ISSUE THREAD

**Issue by Cash120** [gamejolt/issue-tracker#424]
When I click on my games library or try to browse games, the client crashes to desktop. The problem is usually fixed when I re-run the client and attempt the same action.

**Comment by YLivay** [comment]
Hey, what OS are you on?

Can you try running the client from command line? It'll output some useful logs you can attach to this issue.

On Windows first close the client completely through the tray icon. Then hit Windows key + R and type "cmd" in the prompt. Then, simply drag the icon of the client to the black window it opened and hit enter.

**Comment by Cash120** [comment]
I'm running Windows 10 64x.

I can't replicate the problem at the moment. I'll close this for now and re-open it with a log if I can get it to happen again.
