### ISSUE TITLE
Unable to view news posts

### ISSUE THREAD

**Issue by Cash120** [gamejolt/issue-tracker#425]
In my notifications, I can't click on news posts to view them. The cursor changes to the clicking finger, but I can't click them.

**Comment by Tricky1975** [comment]
I think this is due to #423.
Actually I think it's the same bug.

**Comment by Cash120** [comment]
This bug is somewhat different in that I can click other types of notifications, just not news posts.

**Comment by Tricky1975** [comment]
Makes it still the same bug, actually as everything is handled by the same (malfunctioning) routine and very likely due to the same malfunction. It's even possible in the original report not all kinds of notifications were tested.

**Comment by hworld** [comment]
Hey, this is fixed, yeah?

**Comment by Tricky1975** [comment]
I'm at work now. I'll check as soon as I get home.

**Comment by Cash120** [comment]
It appears to be working now, whatever the precise problem was.

**Comment by hworld** [comment]
Nice! I think it was related to this commit I did: https://github.com/gamejolt/issue-tracker/issues/423
