### ISSUE TITLE
It randomly updates games even when there's no updates for the game.

### ISSUE THREAD

**Issue by hworld** [gamejolt/issue-tracker#426]
It MUST be something weird with finding a build that is newer (but maybe hidden)? It's odd, hard to know what's really going on, but it definitely happens.

**Comment by hworld** [comment]
I believe it's just the same games over and over. Down Ward and Passpartout keep doing it. Might be good to check into those.

**Comment by YLivay** [comment]
Probably a newer hidden release/package. Mine!

**Comment by YLivay** [comment]
http://gamejolt.com/games/dexter-stardust-adventures-in-outer-space-night-of-the-hollow-moon-demo/116686 This one also does it.

Need the package hierarchy.

**Comment by YLivay** [comment]
Fixed, needs merge
