### ISSUE TITLE
Unable to publish an Linux/Mac build

### ISSUE THREAD

**Issue by michidk** [gamejolt/issue-tracker#427]
I'm trying to publish a linux & mac build to my release 1.0.0 (with already has an windows & webgl build) http://gamejolt.com/dashboard/games/115658

The builds are already uploaded, but i cant publish them, cause i cant set the paths to the executables.
Why do i have to set the path? (i assume its needed for the GJ client) The players can just download an .zip file and launch the executable. It should be optional to set the path. 

The problem:
first of all, the auto executable detectiong, doesnt work: https://pbs.twimg.com/media/CXAFMsVWQAAI4--.png:large
the other thing, is that i can't set the paths manually: 
https://pbs.twimg.com/media/CXAQWyqWYAA1Jbd.png:large
If i press "set launch options" nothing happens. Tried with Google Chrome and Opera.

The Linux file: https://mega.nz/#!TI0l0AZb!xlp5RK8gONSO7QN6CgS0FMuBEVXVJ1-kfxjHScj1a28
The Mac file: https://mega.nz/#!KBtGTJiL!TtxHltx1FQYjmUWDxY6eFOuHBRdB1_z2ePsLyvYa3Hw
[Universal Linux Build, built with Unity 5.3.1f1]

**Comment by YLivay** [comment]
Looking into this now

**Comment by YLivay** [comment]
Yo, should be working now. Thanks for reporting!
