### ISSUE TITLE
Obsolete subheading text in general chat

### ISSUE THREAD

**Issue by acidpoison** [gamejolt/issue-tracker#429]
![image](https://cloud.githubusercontent.com/assets/11214348/12007585/c1c884ee-abd8-11e5-99d8-69a35ad46492.png)

"In the general chat, it says "If you want to find people to play with you, go to the Multipayer room. Unfortunely, for me at least, the multiplayer room does not exist. It would be great if you 'fixed' this. :)"

[Original forum post](http://gamejolt.com/community/forums/topics/incorrect-text-in-general-chat/14364#post-71130)

**Comment by NikSudan** [comment]
IT WILL ALWAYS EXIST IN OUR HEARTS!

**Comment by NikSudan** [comment]
This is going to become obsolete in the new chat update.
