### ISSUE TITLE
Contact link not working in the client

### ISSUE THREAD

**Issue by CyberKiller40** [gamejolt/issue-tracker#431]
When I click, in the client, on the contact link (the mailto: one) in the page footer, nothing happens.

expected: open external mail client
reproducible: always

**Comment by NikSudan** [comment]
Works for me on Mac. Do other mailto links work?

**Comment by CyberKiller40** [comment]
Just checked this again and it still doesn't work. OpenSUSE 13.1 GNU/Linux 64bit KDE. Mailto links work ok in normal web browsers.

**Comment by CyberKiller40** [comment]
Sorry, my mistake :-/ I didn't have my mail program set up in KDE settings and I removed the default one. After setting that up it works ok.

**Comment by YLivay** [comment]
Closing this for now then :)
