### ISSUE TITLE
Chat not working

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#433]
I have this issue in both the client as in the regular browser.
As "not working" is very vague I shall try to go into all details below.

- When I refresh the page it takes an eternity before the chat rooms show, and it takes even longer to show my friend list.
- Now the system does indicate somebody in my friend list tried to contact me last night (speaking in Dutch local time, I mean).
- Clicking his name (or any other "friend" for that matter) will make nothing happen at all.
- Now I never visited the public chatrooms before, but now I tried to see if I got the same issue there, and yes, trying to open a public chatroom leads to no response from the system.
- As you know I use Opera for Mac, but as I said using the client (for Mac)  leads to the same results.
- While I was typing this the trouble above seems to have "resolved" itself, still I will still send in this ticket because this is not the first time this happens to me and I expect it won't be the last time either.

I have not yet tried other browsers, but I sure will when I see this problem pop up again.

**Comment by YLivay** [comment]
Thanks for reporting, all current chat related bugs will most likely be resolved in the next chat update.
Gonna go ahead and close this.
