### ISSUE TITLE
Installer fails to start on windows xp

### ISSUE THREAD

**Issue by CyberKiller40** [gamejolt/issue-tracker#435]
The installer refuses to start on windows xp, it pops up a window saying to use a newer version. Can you override it somehow to skip this check? The client itself most probably will run.

Or maybe just provide a zipped archive with the client without an installer.

**Comment by YLivay** [comment]
Hey, the client wouldn't work on Windows XP even if it did install.
We dont plan on supporting it any time soon, too. Sorryyy :scream_cat:

**Comment by CyberKiller40** [comment]
Well, you are wrong. I managed to extract the client files out of the installer and it runs fine, installs games, runs games, uninstalls games... Doesn't seem to be anything missing. It uses node webkit and everything else using that works without any problems in winxp.

You don't need to support winxp (as in fix bugs occuring only on this OS), but giving a simple archive with the client files would easily enable all people on this system to use it.

Please reopen the issue.

**Comment by hworld** [comment]
We can possibly add in portable builds so XP can run it in the future. Chrome has decided to stop supporting XP with updates and security fixes from this coming April onward, though: http://chrome.blogspot.de/2015/11/updates-to-chrome-platform-support.html.

I'm hesitant to support something that could potentially break with future updates fairly soon.

**Comment by CyberKiller40** [comment]
Node Webkit is built on Chromium, so I don't think whatever Google Chrome is doing is connected to this.

Anyway, if it stops working one day, then you can rightfully say that you didn't support winxp anyway, but until then I don't see why users shouldn't be allowed to use it.

**Comment by hworld** [comment]
Chromium's support is tied to it. Check it out at the top of this page: http://chromium.woolyss.com/

And the issue is that we'd be putting out something that would auto-update and eventually break come April. I'm not sure I want to do that...

**Comment by CyberKiller40** [comment]
They don't explicitly say they will break the software working on winxp.

BTW: how come *not* making an installer is such a big problem? I'm not asking you to do more work, only to zip the files.

**Comment by hworld** [comment]
I'll reopen it. Just know that when it's pushed out, it won't be tested. I'll have to make a new build process to zip up the files and will also have to upload it each update.

**Comment by CyberKiller40** [comment]
Thank you! :-)

**Comment by YLivay** [comment]
This might already be broken because were touching registry keys that are not xp friendly with the new installer haha..

Nothing a bundled up zip cant solve ha

**Comment by hworld** [comment]
You still on windows xp @CyberKiller40 ?

**Comment by CyberKiller40** [comment]
Woah, this has been 2 years :-). Actually no, I don't use winxp for legacy games at the moment.

**Comment by hworld** [comment]
I think this is too much "extra" work to support XP since it's mostly phased out by now. Gonna close
