### ISSUE TITLE
plz fix

### ISSUE THREAD

**Issue by fredbear3000** [gamejolt/issue-tracker#437]
it wont launch installed games on windows 7

**Comment by Tricky1975** [comment]
"plz fix" is pretty vague for a subject. Especially on a bug tracker being more specific in the subject is very important.

**Comment by hworld** [comment]
Closing since it's been a week with no info.

**Comment by fredbear3000** [comment]
huh who are you?

**Comment by fredbear3000** [comment]
you people are like rays of sunshine hurting other peoples eyes and giving them diabities

**Comment by Tricky1975** [comment]
To answer the question, hworld otherwise known as CROS is the "surpreme administrator" of GameJolt. The owner of the site. The big boss.

"you people are like rays of sunshine hurting other peoples eyes and giving them diabities"
Uhm, are you trying to insult people? Not a very smart move.

**Comment by YLivay** [comment]
This is the first stupid comment ive seen on Github. Gonna unsubscribe to this topic before i accidentally read more.
