### ISSUE TITLE
Can't uninstall a game-

### ISSUE THREAD

**Issue by AnthroShender** [gamejolt/issue-tracker#439]
I downloaded a game, and started playing it. After I closed it, the client queued the game for an update but it doesn't start downloading the new version, and I can't even uninstall it. Anyone knows how to fix that?
P.S. I tried to uninstall the whole client but it didn't work.

![gamejolt](https://cloud.githubusercontent.com/assets/16517434/12074770/c29fc92a-b166-11e5-819e-9919e5c8085f.png)

**Comment by Tricky1975** [comment]
Well a "dirty fix" you could do yourself could perhaps be to uninstall the game manually, however, I don't know if that will cause the client to malfunction or not, and that's why I don't yet explain how you can do that, as I don't want to bear the blame for "killing" your client.

**Comment by AnthroShender** [comment]
Well, I can't use the client right now, so even if after the attempt it doesn't work anymore, it doesn't matter.

**Comment by AnthroShender** [comment]
Ok I figured out that my issue appears to be the same as post #442. I changed the setting and now it's updating the game!

![senza nome](https://cloud.githubusercontent.com/assets/16517434/12079045/fae6416e-b22a-11e5-807c-94e489546678.png)

So thank you!
