### ISSUE TITLE
Show their achieved trophy info on profiles.

### ISSUE THREAD

**Issue by hworld** [gamejolt/issue-tracker#44]
**needs implementation details**

**Comment by Tricky1975** [comment]
Ah,  I was thinking for awhile to suggest this. Good to see it here now. (Issue #44, I guess this was already here before GJ Next was even in the beta?)
Of course, this is about the user profiles, but maybe the trophies themselves may show a list of which users all achieved this trophy (which the date they did). 

Comes close to Nik's "Who else achieved this?" I suppose, but I was rather thinking you could click the trophy in the game's profile for this list.

**Comment by Tricky1975** [comment]
One of the members of the forums came with the idea to put this onto the profile in a tab like this.

![](http://i.imgur.com/ue5ISq1.jpg)

And I think that is a good idea. This user was btw not the first to come with the suggestion to put on the trophies on the profiles. Is there any progress in this one?

**Comment by niksudan** [comment]
Moved to https://gamejolt.com/f/public-page-of-achieved-trophies-achievements/341343
