### ISSUE TITLE
I can't run the client.

### ISSUE THREAD

**Issue by StickMasterNinja2** [gamejolt/issue-tracker#440]
How's life?

Yesterday it was working, today it isn't opening. Can you help me?

**Comment by Tricky1975** [comment]
For me the client works. Which OS are you on? (That is quite often pretty important to know when it handles issues about the client). (I myself am on Mac. That can make the difference).

**Comment by StickMasterNinja2** [comment]
I'm on Windows 7.

**Comment by StickMasterNinja2** [comment]
The client isn't opening for days.

**Comment by YLivay** [comment]
Can you  try running it from command line? Make sure its closed in the task manager, then open CMD (Windows key + R, and type "cmd") and drag the client executable to the black window.

It'll log some messages, attach them to this issue please, thanks!

**Comment by StickMasterNinja2** [comment]
It didn't worked.

**Comment by YLivay** [comment]
Upgrade to the newer version using the new installer.
I can't identify your issue without more info, but it sounds like a bad installation.
