### ISSUE TITLE
Searching for "Stoppa!" and "Stoppa" doesn't come up with the public game titled "Stoppa!"

### ISSUE THREAD

**Issue by Honno** [gamejolt/issue-tracker#441]
Title. Happens on the quick search results dropdown and the full search results page. Both in browser and on client.

**Comment by Tricky1975** [comment]
Can you link us to the game itself, Honno?
Maybe we can find something in the public pages of the game that can lead to a hint what causes this.

**Comment by Honno** [comment]
Oh haha, that makes sense, so it's just because of the weird decision a dev made. Sorry folk!
