### ISSUE TITLE
Auto-Login from old Quick-Play into GJ Client

### ISSUE THREAD

**Issue by MausGames** [gamejolt/issue-tracker#445]
The old Quick-Play feature on Game Jolt automatically forwarded the user-credentials through a file and the command-line for a downloaded game to automatically login the user.

This feature should be re-implemented into the GJ Client to re-enable auto-login and to stay compatible with 1000s of old games.

**Comment by YLivay** [comment]
Definitely! We're also thinking about passing it to the actual executables now, but for next version we'll do the credential files for sure :)

**Comment by YLivay** [comment]
Going to have to aim for a later version with this.

**Comment by YLivay** [comment]
This'll be done using a wrapper around the game process itself rather than the client.
Gonna be trickier.

**Comment by hworld** [comment]
This is done already.
