### ISSUE TITLE
Auto-detecting 64-bit Operating System

### ISSUE THREAD

**Issue by MausGames** [gamejolt/issue-tracker#446]
Currently when downloading and starting a game containing both 32-bit and 64-bit executable (within one build), only the 32-bit version is launched, even though the operating system supports 64-bit and the appropriate launch-options are configured.

Tested only on Windows, should also be checked for other operating systems.

**Comment by CyberKiller40** [comment]
From what I experienced this works correctly on GNU/Linux. Meaning the client launches the 64bit exec if its present. Though that might be partly due to the fact that a 32bit Linux client doesn't exist yet.

**Comment by hworld** [comment]
Yeah, it's a windows only bug. Will be fixed in next version. I twas supposed to be fixed earlier but I typoed it.

**Comment by hworld** [comment]
Will be out in next version.
