### ISSUE TITLE
Client keeps restarting constantly in 2 second flashes

### ISSUE THREAD

**Issue by Milleymour** [gamejolt/issue-tracker#448]
i put in my username/password then it crashed, now every time i open it it keeps crashing and restarting, also the only way i can close it is with task manager. (I'm using windows 7 64-bit)

**Comment by YLivay** [comment]
Woah. Can you try running the client for command line? It'll print out some logs you can attach to this issue

**Comment by YLivay** [comment]
Anything?

**Comment by YLivay** [comment]
Closed for inactivity, can't reproduce either.

**Comment by Milleymour** [comment]
Try closing completely and turning off startup launch settings, it seemed
to work for me.

P.S If you can't close it then use task manager.

**Comment by Milleymour** [comment]
Watching this client makes me want to die

I require a pizza at 8 Wills court Taylors Lakes 3036
