### ISSUE TITLE
Processing after upload takes too long

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#449]
http://gamejolt.com/community/forums/topics/help-please-i-can-t-post-my-game/14386?forum_topic_post_page=1#forum_topic_posts

After you upload a build, GameJolt has to process the upload. None of us know what exactly happens in that process (please enlighten us), but until recently that took a few minutes max. Recently this has begun to take a very long time, and many devs now think uploading new builds has become impossible.

Cyber Killer, Jani and I have taken this to the test. Due to me being required to go AFK for awhile I couldn't clock exactly, but I can confirm that processing an upload took more than 20 minutes, and Cyber Killer clocked one of his own uploads over 30 minutes of processing. It doesn't really seem to matter if it handles big or small uploads, everything appears to take forever. And it's not a surprise some people think uploading has become impossible.

In the end we could conclude that uploading and processing DOES work the way it should, but that simply takes TOO LONG, causing a panic out there.

**Comment by hworld** [comment]
This was because the upload queue was stuck yesterday. It should never take that long. A couple minutes max, unless you have a huuuuge game file. If this happens again, please be sure to alert me on chat or something.
