### ISSUE TITLE
"Room users" sidebar has buggy scrollbar

### ISSUE THREAD

**Issue by NikSudan** [gamejolt/issue-tracker#454]
The scrollbar and it's respective width disappears when you hover over the room users sidebar. It reappears when there is chat activity. This causes the whole chat to jank left/right annoyingly.

**Comment by Agrosis** [comment]
Yeah, so when the scrollbar is visible, hover over the user list and it'll disappear. Focus on something else in the chat window and it reappears. I think we should just enable the scrollbar by default. `overflow-y: auto` is messing things up :(

**Comment by NikSudan** [comment]
Seems like the best idea.

**Comment by hworld** [comment]
I like. Will do.

**Comment by hworld** [comment]
Done!
