### ISSUE TITLE
Feature request: follow #tag like a playlist

### ISSUE THREAD

**Issue by CyberKiller40** [gamejolt/issue-tracker#455]
I think it would be cool if every user could "subscribe" to a game #tag, so that is becomes visible as a playlist on his account. Maybe as a new category. And games would be added to it from the tags that devs put in the game descriptions, so adding games to the lists would not be in the hands of users. They would be only observers.

This would allow to get game "collections" from gamejams or specific genres, but without having to add each game manually.

The usual features like installing, etc should be available from the tags view too.

**Comment by NikSudan** [comment]
With the current system that won't be possible because tag results aren't stored as playlists.

There needs to be some way of following a tag though. We need to connect all communities together with groups - maybe that is the solution? We could have the chatroom hashtag, the forum hashtag and the game hashtag all together.

Organising game tags hasn't really been thought much at all - @hworld what do you think of this?

**Comment by CyberKiller40** [comment]
OK, following a tag is what I mean, the playlist is only as a reference. If it'll look similar then that's what I have in mind.

**Comment by hworld** [comment]
I've wanted to do this actually. I think it can be done. Playlists can be very dynamic on GJ, just like following a developer games list, or following someone else's followed games. Whoa.

**Comment by YLivay** [comment]
It's actually time to rethink this issue now that we have channels for tags.
Do we want any user integrations for following or belonging to channels?

**Comment by hworld** [comment]
Let's just do it, yeah? Should be kind of easy. Just slightly a hassle. Tags are actually already done through the game collection system. I would imagine that following a channel would just follow its tag at the moment. It wouldn't give any more options (yet) for getting information on the channel. Although, that would probably be the goal moving forward. This could be handy for stuff like jams, btw. Add a jam tag to your playlist so you can play through them all easily.

**Comment by YLivay** [comment]
It'll be easy to do, but what I'm afraid of is the huge amount of notifications and activity from users following very big channels. Imagine seeing the entire new devlogs post of #fnaf tag in your activity feed. What exactly will following a tag even be?

**Comment by hworld** [comment]
I don't mean getting notifications. I view it more just as saving it to
your library to view later

**Comment by hworld** [comment]
After thinking about this, it's going to be too hard, I think. The better way would be to show tags in search autocomplete, perhaps. Just a quick switch over to the tag.
