### ISSUE TITLE
Annoying to type multi-line messages in chat.

### ISSUE THREAD

**Issue by hworld** [gamejolt/issue-tracker#462]
It's too easy to accidentally send a message before you're ready. I suggest `shift+enter` starts a multi-line message, and when it's in that mode we don't allow you to send the message with `enter` anymore. `enter` should make new lines at that point and `ctrl+enter` should send the message. We need a message popping up to say that. Stupid Mac and their cmd instead of ctrl.

**Comment by CyberKiller40** [comment]
Shift+enter is the common way to make a newline in most chat applications. Changing that could confuse users.

**Comment by hworld** [comment]
Yes, that would be the same. The thing is that it's very easy after the initial shift+enter to accidentally submit your message. I think after the first shift+enter it would be good to require a ctrl+enter to send after entering the multi-line mode. Many chat apps allow you to edit your message, but GJ chat doesn't, which makes the problem even worse.

**Comment by CyberKiller40** [comment]
OK, I misunderstood, anyway this never seemed a problem to me in various chat programs.

**Comment by hworld** [comment]
Done!
