### ISSUE TITLE
Site enhancement: feature only games playable on the users platform

### ISSUE THREAD

**Issue by CyberKiller40** [gamejolt/issue-tracker#465]
An idea for the main website, similar to some other game store that has a somewhat industrial revolution themed logo :-) have only games running on the users platform (detect from browser user-agent) shown in the featured games at the top of the page.

This especially is meaningful for platforms that are less popular than windows - Linux and Mac. There is little reason to show windows games for users of these system. This would require to have a longer featured games list to show the same amount of games for these platforms.

The detection could include also browser plugins and show/hide featured games that won't run in the users browser due to lack of a specific plugin (mostly Unity and Silverlight).

**Comment by CyberKiller40** [comment]
This would also be an incentive for the devs to make crossplatform games :-).

**Comment by YLivay** [comment]
All game listings have filters for exactly that.
I'm assuming you mean the homepage?

**Comment by CyberKiller40** [comment]
Yes, I mean the big banners on top of the homepage and lower.
