### ISSUE TITLE
Ingame WMV video doesn't work

### ISSUE THREAD

**Issue by Satik64** [gamejolt/issue-tracker#466]
I have short ingame story video in the game intro, but if I play the game through client, video is skipped. In classic way outside the client video is working.
Format of the video is WMV, engine is Game Maker 8.0 and the game is Warped Times: Pres3nt.

**Comment by Tricky1975** [comment]
I have the hunch that this might be caused by the same bug as I described in #406.
Can you check if the WMV file actually exists in the game installation through the client?

**Comment by Satik64** [comment]
Yes, the video file exists in game folder. But if I run this version downloaded from Gamejolt Client in this folder (without client), video still doesn't work in game.

for sure I downloaded same version from Gamejolt web and the ingame video is working. Both videos have same size and I can play them on VLC Player.

**Comment by Tricky1975** [comment]
Hmmm, then I think something else is missing. Too bad I'm on Mac myself and I assume this is the Windows client we're talking about, otherwise I would have tried this out to see if I could find the "evil".

**Comment by CyberKiller40** [comment]
Can you check a checksum (e.g. md5) of both of the video files in the working and nonworking version? Just to make sure they are really identical.

**Comment by Satik64** [comment]
MD5 checksum of both files are the same. Folders have the same size. I found in the log this error: Video file not found (or name too long).

so I have no idea what's happening...

**Comment by Tricky1975** [comment]
I am wondering if the game uses some kind of .dll file or something which isn't installed by the client. Something MUST be different or the game would just have to work, I think.

**Comment by Satik64** [comment]
The game uses a few libraries, but they are placed in game folder without installation. But video playing doesn't requires any of these libraries.

**Comment by CyberKiller40** [comment]
Actually it is possible that a combination of a long username (the game is installed into a subdir of %APPDATA%), long gamename and long file name will exceed 260 characters as the total path, and that is the limit on windows. Source: https://msdn.microsoft.com/en-us/library/aa365247.aspx

**Comment by Tricky1975** [comment]
Basically it can be worth trying to copy the game from the client folder to a removable device (like a USB stick) and take a look if it works then. If it does, @CyberKiller40's theory might be very likely then.

**Comment by Satik64** [comment]
Yes, video is working on USB or root directory. But total path has only 140 characters. Maybe it's limit of Game Maker 8 :(

**Comment by CyberKiller40** [comment]
You can try to rename the video to something like a.wmv (single letter) and rebuild the game package, maybe it'll fit under the path limit.

**Comment by Satik64** [comment]
Thanks, I will try it, I hope it will work at least for users with short username. It seems that this problem is about old Game Maker function, so GJ Client can't fix it. 

But thanks for help and identification of the problem.

**Comment by YLivay** [comment]
If it works from the web and not the client then its confusing.
We recently fixed a bug where the client downloaded 32 bit releases on 64 bit oses. Maybe it just downloaded an old broken release where it doesnt work in?

If this is solved we'd love an update :)

**Comment by YLivay** [comment]
Inactive issue, closing. Also - new way to launch games mightve fixed it.
