### ISSUE TITLE
Feature: Allow to play html5 Swf and Unity Web Player games offline.

### ISSUE THREAD

**Issue by luckcolors** [gamejolt/issue-tracker#467]
Hello.
This is a long term suggestion but it should be possible to cache any of these games resources and update them accordingly.
- Html5 games will be probably the easiest there will only be the need to cache any resource they load.
  -For flash player games (swf) and web unity games same thing but there will be of course the need to bind the Flash Player and Unity Web Player plugin runtimes.

**Comment by hworld** [comment]
Yeah, we'd love to get this in place. We were going to try to to do it for the initial release but ran out of time. Expect it in a soon-ish release.

**Comment by luckcolors** [comment]
Thanks for the reply. :)

**Comment by YLivay** [comment]
Not sure we're going to be able to fit this in the next release but gonna add it anyways >:)

**Comment by YLivay** [comment]
This is already on my todo list for client, although only html5 games will be supported.

**Comment by luckcolors** [comment]
could you atleast make the swf and web unity games downloadable offline just like the html5 ones?
Because it's still possible to use the fòash player projector to run the swf ones. And it is still possible to un the unity3d onesjust by opening the html index wich has the js code that calls the plugin.

**Comment by YLivay** [comment]
if its a unity3d with html its not a unity game its technically an  html5 game. If you mean theres a runner for the .unity3d file plugins it's a different thing.
As for downloading them to play offline, I can't say if the client will or should even support this. How would it launch them?

**Comment by luckcolors** [comment]
A unity3d file requires an index.html wich calls the Unity3d plugin https://unity3d.com/webplayer.
A webuintygame requires only js and thus it will work everywhere without problems.
The flashplayer ones can be easily opened using the flashplayer projector from here.
https://www.adobe.com/support/flashplayer/debug_downloads.html
