### ISSUE TITLE
Feature: Make the gamejolt client portable.

### ISSUE THREAD

**Issue by luckcolors** [gamejolt/issue-tracker#468]
Hello.
It will be awesome if the Game Jolt Client could be installed in any folder (without saving anything on appdata\Local) this way it will be more easy to move and store in different locations than C: itself.

**Comment by Tricky1975** [comment]
You're talking about installing the client itself, right, not the games you install with the client? (the latter is already possible, in the client settings).
Of course the data client stores (like configuration and stuff) in appdata\local is actually a rule set up by Microsoft, all Windows developers have to follow. Mac uses ~/Library/Application Data/ for that and Linux uses ~/.<appname folder> for that respectively. This configuration file needs to be at a 'central' point as the folder where the games are stored in is also in this config file and without it the client knows nothing. And if the config file would move to any device it will never be able to find it, so "without saving anything in appdata\local" is unfortunately not an option.

I have set the client settings to a portable device myself. In order words, all games are installed on a portable device. Now I really don't know what will happen if I connect this device on a different computer (with the same OS) and configure the client to that same folder. If the client could detect my games there in that situation, the client might already be possible. Point is, though, I'm a Mac user, and I only have one working Mac at my disposal at the moment, making me unable to check. And I don't have a working Windows machine at all at my disposal yet, so this is something the admins should answer.

The client itself. On Mac I can already install the client itself where I want, but for Mac Applications that's pretty normal (it will still store the config files on my ~/Library/Application Data/ as per rules for Mac), as I can just download a .dmg (a virtual disk) and drag the client to the folder I want. For Windows things appear to be more complicated, but what that is, I think the admins can explain that better than I can.

**Comment by luckcolors** [comment]
Yeah i'm talking about the launcher.
i mean it's actually possible to do. For instance steam stores all of it's data into the   steam install dir.
I think it's not actually a rule on windows.

**Comment by Tricky1975** [comment]
Yes, it is, trust me on that one. The rule was introduced in order to prevent turning your hard-drive into chaos (which happened a lot in Windows' predecessor MS-DOS). Sometimes a system can even be protected against writing data elsewhere. I think Steam solved this problem by installing the client in a  data folder and not in the folder where .exe files belong (since it's easy to adapt the link to it in the Start Menu and most people will never know). This is a very common trick to void this rule without the possibility to get "access denied" errors (world of warcraft used the same trick) but one that is considered as "dirty", and Microsoft doesn't want developers to go down that road. GameJolt did follow the official standards when it comes to this.
Systems in the unix family (like Linux) are even stricter on this, and I also think GJ doesn't want too many differences between the platforms.

**Comment by luckcolors** [comment]
I mean it's possible to let user choose where they want to keep theyr programs as appdata is an akward place because not all of the user know of the esistence of that folder.

What steam did is to set write permission on the install folder and can be done by the setup.
All the files and data are stored there except for a httpcache file which is in appdata.

**Comment by Tricky1975** [comment]
Yeah, that's also a known method, however some security software will block a program out for this. Steam has a big name, and thus most security packages will therefore ignore any approach Steam does outside the scope of the rules. GameJolt unfortunately is not in that position. In fact on Steam all links to GameJolt are even blocked, and a big party like that blocking GJ out is not something that works in GJ's advantage.

**Comment by luckcolors** [comment]
Mmmh ok (steam was just an example i didn't want to offend any of the GJ folks).
Anyway i understand what you are saying but i want to actually manage where the stuff that i install goes to.

**Comment by YLivay** [comment]
Using the new installer you can now choose where to install the client to and it'll be effectively contained in that location :)

So yeah! We're portable! ish!
Of course if devs bundles installers they are not guaranteed to follow the portability, but theres nothing we can do about it for the time being

**Comment by shnbwmn** [comment]
I don't mean to bark up an old, dead tree, but I have to strongly disagree with this statement and a lot of its follow-up:

> Of course the data client stores (like configuration and stuff) in appdata\local is actually a rule set up by Microsoft, all Windows developers have to follow. Mac uses ~/Library/Application Data/ for that and Linux uses ~/. for that respectively. This configuration file needs to be at a 'central' point as the folder where the games are stored in is also in this config file and without it the client knows nothing. And if the config file would move to any device it will never be able to find it, so "without saving anything in appdata\local" is unfortunately not an option.

This "rule" is not followed by a vast majority of portable programs. Take a look @ [PortableFreeware](https://www.portablefreeware.com/). All truly portable programs (of which there are tons) store their configs in the app folder and don't face any issues.

**Comment by luckcolors** [comment]
The original reason i asked this is because it doesn't make sense to not have the data stored alongside the app. Especially if that data lists installed games (eg: steam stores that alongside the games). 
As of now that data is stored in the chromium datastore in appdata.
If you are using Nw.js this should be changeable with a variable.

**Comment by hworld** [comment]
Hey there, I'm not aware of a variable to change for NWjs. It's the only
reason for not being able to make it truly portable. Do you know for
certain if there is an option with NWjs?

I will say though that even though it's not portable, we do store metadata
files in each game directory. We don't use them for anything yet, but the
idea is we are then able to regenerate your DB from those files stored
alongside the games.
