### ISSUE TITLE
New (chat) messages count incorrect on login

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#469]
I shall explain step by step what I mean.

- Last night I just went AFK and I was still AFK when I went to bed. During this time OS X just logged me out automatically. (OS logout I mean)
- At that time I had in the bottom cat bar a quick link to "a friend" with whom I had a little chat recently.
- After I woke up I logged back in on my mac (system login, I mean, not GJ as I never logged out there).
- Immediately I saw 229 new chat messages had come in
- There were all said to have come from "the friend I mentioned before", now I was really curious what he all had to tell me.
- Opening the chat window itself turned out he sent me none (at least not since I checked my personal chat with him last).
- I was wondering if he sent me 229 messages over the whole period of our 'digital friendship', but some older messages he sent me no longer appeared on my screen, so I'm unable to verify that one.

**Comment by YLivay** [comment]
This is most likely result of backfilling somehow, the chat presences were reset.

This is just a one time oddity that may happen once per friend.

**Comment by Tricky1975** [comment]
I see... And I suppose this may (judging your post) only happen to us "old" members. I mean, if I would create a new account now, this would not happen on that new account?
(The reason I ask is because I do expect some confused messages about this on the forums, pretty soon, and I want to be 100% sure I explain things correct to the "noobs") :)

**Comment by hworld** [comment]
Correct. It should only be for older users with messages between friends.

**Comment by YLivay** [comment]
Closing this as a non issue.
