### ISSUE TITLE
User online/offline growls massively stack up when switching back to the site

### ISSUE THREAD

**Issue by niksudan** [gamejolt/issue-tracker#470]
![image](https://cloud.githubusercontent.com/assets/6004491/12216928/2cf0b154-b6e9-11e5-996d-340e5f3626bb.png)

**Comment by Tricky1975** [comment]
I was about to report that, but I was too late with the screenshot every time, as it goes away very quickly.

**Comment by YLivay** [comment]
In the site there are no notifications for friends anymore, yeh?
In the client im actually not getting them anymore at all. Even though the setting is allowed hmmm...

**Comment by YLivay** [comment]
Doesn't happen anymore (or maybe I just dont have enough friends ;-;)

**Comment by Tricky1975** [comment]
Well I have so many friends in my friend list that I am considering to go "unfriending" soon (if I could only unfriend the banned friends among them), and I haven't seen this happening anymore either for a long time.... let's just assume this is fixed ;)
