### ISSUE TITLE
Chat messages stay faded out after being sent

### ISSUE THREAD

**Issue by NickRock** [gamejolt/issue-tracker#471]
![capture](https://cloud.githubusercontent.com/assets/11754980/12217937/56df60da-b718-11e5-9b18-55867491c8d4.PNG)

**Comment by hworld** [comment]
Is this Internet Explorer?

**Comment by NickRock** [comment]
No that was on Firefox

**Comment by YLivay** [comment]
We love this bug so much we ported it over from the old chat.
This still exists.

**Comment by YLivay** [comment]
Yo @Agrosis any update on this?

**Comment by Agrosis** [comment]
I've never been able to reproduce this.

**Comment by YLivay** [comment]
I've actually not seen this since my last comment either, closing for now, if it happens again we'll reopen.
