### ISSUE TITLE
Feature to turn off the user on-line/off-line growls.

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#474]
On behalf of GJ Member [Foehammer](http://gamejolt.com/profile/foehamner/777487/) I post this here, as I think this feature should indeed be there.

![image](https://cloud.githubusercontent.com/assets/11202073/12220979/6a7bf264-b788-11e5-9c0b-54fef391dda6.png)

[Original Thread](gamejolt.com/community/forums/topics/online-offline-notifications/14467)

**Comment by hworld** [comment]
This will go into the Client Settings page in the next update, but I want to get it into Site as well. We may need a new page for site that is just "Settings".

**Comment by YLivay** [comment]
This has been done :)
