### ISSUE TITLE
After iMac staying on sleep, sometimes Game Jolt Client will return to the normal browser version

### ISSUE THREAD

**Issue by DevSyphon** [gamejolt/issue-tracker#486]
Hello there.
So, there is a bug that I discovered, that after I wake up my mac after staying on sleep, there's a chance of the Game Jolt Client returning to the browser version (cannot access client settings, cannot play installed games etc.). If I reopen the app, it goes back to the client version.

Thank you,
//Syphon

Data:
Game Jolt Client Version 0.1.2 running on iMac, OS X 10.11.2 (El Capitan), Stable Release.

**Comment by hworld** [comment]
What's the browser version?

**Comment by Tricky1975** [comment]
I think he means the site inside the client will show the same way as it shows in a regular browser. In other words without the extra stuff the client provides above the browser.

**Comment by hworld** [comment]
Ah, I missed that. Thanks.
Are you able to verify it still happens, Pingu? It almost seems like maybe there is a bug where a link that you clicked had directed you to gamejolt.com instead of staying within Client.

**Comment by Tricky1975** [comment]
Since I'm on Mac myself (also using El Capitan), I tried to replicate this bug. I can tell the client did how the site in "client mode", however, when I tried to install a game the client crashed (after waking my mac up from sleep mode). I don't know if this is related to this (possible) bug or if this is because of a different issue. I will try it again some other time.

**Comment by hworld** [comment]
I think long long snake is broken for anything other than windows. Because it doesn't work on linux either. =\

**Comment by Tricky1975** [comment]
When I got the time I shall sort out if that particular game does work "clientless", and try another game to replicate this then later....

**Comment by PinguRares** [comment]
@Tricky1975 interesting, that never happened to me
@hworld it does not happen anymore, I tried it about 10 times. Ouch.

**Comment by hworld** [comment]
I think it must've been what I mentioned. I worked on making the links better so they don't open in client. Gonna close.
