### ISSUE TITLE
Installer crash (windows 7 64 bit)

### ISSUE THREAD

**Issue by o0BlackDragon0o** [gamejolt/issue-tracker#487]
after I run the installer, the gamjolt logo shows for about 2 seconds before windows prompts me to close it because it has stopped working. Ive restarted my pc, redownloaded the file, but still it continues to crash. Fustrating!

**Comment by hworld** [comment]
Could you check again with the latest version? I just pushed out a new update.

**Comment by Kerza** [comment]
This problem happened to me too, i just downloaded it and it always crash here is a pic:

![gj error](https://cloud.githubusercontent.com/assets/16678495/12285015/b5a717c4-b9c6-11e5-8665-03b23628780e.jpg)

**Comment by YLivay** [comment]
New installer should fix it :)
The problem was trying to install while the application was running.
