### ISSUE TITLE
Could not launch game?

### ISSUE THREAD

**Issue by HiddenFigure** [gamejolt/issue-tracker#490]
After pressing the launch button for "Long Long: A snake lies in the Past", a notification appeared with the words. "Oh no! Could not launch game." Even though in the background, the game was launched and was working fine.

**Comment by hworld** [comment]
Are you on Linux or Mac by any chance?

**Comment by YLivay** [comment]
I dont see anything suspicious in client-voodoo for this. We may have to wait on https://github.com/gamejolt/issue-tracker/issues/495 for this

**Comment by HiddenFigure** [comment]
I am on a Mac, but keep in mind the game still works, it's just the notification.

**Comment by YLivay** [comment]
Most likely solved :)
