### ISSUE TITLE
Chat window altered when displaying message with long string

### ISSUE THREAD

**Issue by acidpoison** [gamejolt/issue-tracker#492]
![image](https://cloud.githubusercontent.com/assets/11214348/12313483/c6e43fca-ba35-11e5-90e6-5b42fb6aa409.png)

When the browser window is smaller than the chat size, the chat window size is reduced.
When people post any message (usually raw links) that have long strings with no space characters to break, it will alter the chat window size to display it to be too large for the browser window.

**Comment by YLivay** [comment]
Solved on desktop, still on mobile.
Reassigning to @Agrosis again LOL

**Comment by Agrosis** [comment]
This still happens on desktop for me. I tried fixing it by removing flexbox but that didn't work out very well :/ I'll have to play around more with it.

**Comment by hworld** [comment]
Finally fixed
