### ISSUE TITLE
Need a way to submit client logs

### ISSUE THREAD

**Issue by YLivay** [gamejolt/issue-tracker#495]

**Comment by YLivay** [comment]
Last X lines will be written in a temporary file. This file will be trimmed every now and then to assure it never gets big. Then when reporting users may specify an optional description and they'll get a log ID back. Paste this log ID in an issue tracker.

**Comment by YLivay** [comment]
Done. Also, cleaned up tons o logs in client voodoo

**Comment by hworld** [comment]
Merged.
