### ISSUE TITLE
[Game API request] API Endpoint to access packages/builds

### ISSUE THREAD

**Issue by nilllzz** [gamejolt/issue-tracker#504]
I would like to have an API endpoint that allows me to fetch information on the builds of my game.
This would come in handy to check if the player runs the current version of my game or similarly, if there is an update available.

I would propose something like this:
/packages/

With a return structure like

```
"packages": [

    {

        "name" : "MyGame",
        "description" : "The main release of MyGame.",
        "releases" : [
            {
                "version" : "1.0.1",
                "builds" : [
                    {
                        "file" : "MyGame_win.zip",
                        "download_count" : "178",
                        "type" : "executable",
                        "platforms" : [
                            "win32",
                            "win64"
                        ]
                    },
                    {
                        "file" : "MyGame_linux.zip",
                        "download_count" : "25",
                        "type" : "executable",
                        "platforms" : [
                            "linux32",
                            "linux64"
                        ]
                    },
                    {
                        "file" : "MyGame_web.zip",
                        "download_count" : "143",
                        "type" : "web",
                        "platforms" : [
                            "html"
                        ]
                    }
                ]
            }
        ]
    }
]
```

**Comment by YLivay** [comment]
How about making it simpler! Pass in your package ID, OS and Arch and you get the latest build ID available to download. We use this in the client to figure out when games need to be updated but would be useful as part of the game API as well :)

**Comment by nilllzz** [comment]
Maybe have both options on different API endpoints, as they would accomplish different things.
This one stays on /packages/, the other could be /packages/get-latest (or something).

**Comment by YLivay** [comment]
It probably wont be available through the game-api, but it'll be added to a service-api.

**Comment by YLivay** [comment]
already working on it through gjpush and jolt cli. i wont remember to close this issue when im done hahaha
