### ISSUE TITLE
GameJolt API requests never return anything

### ISSUE THREAD

**Issue by Braffolk** [gamejolt/issue-tracker#505]
API requests never load, tested in both browser and my game.
http://gamejolt.com/api/game/v1/data-store/?game_id=32&key=test&signature=912ec803b2ce49e4a541068d495ab570
"The above would return data stored in the system with the key of "test" for the game with the ID of 32."

This, or any other link, never loads or returns anything.

**Comment by nilllzz** [comment]
The URL has to start with api.gamejolt.com, not just gamejolt.com.

**Comment by Braffolk** [comment]
Fair enough, then the documentation has wrong information though.
https://gamejolt.com/api/doc/game

**Comment by nilllzz** [comment]
I believe that is outdated, you use this one instead: https://github.com/gamejolt/doc-game-api/blob/master/v1.x/index.md

**Comment by Braffolk** [comment]
Ahh thanks. That should solve it, I guess the old doc should be replaced though.

**Comment by hworld** [comment]
These old URLs should work as well though. I am going to reopen so I can dig into why this is happening.

**Comment by Tricky1975** [comment]
Isn't it possibe this is related to #438?

**Comment by YLivay** [comment]
Dont think so, theres a lot of difference between being slow and never returning. P.S I ran tests on the API, and its just as fast as it always is. Actually a bit faster now that we optimized db performance. You'll have to be more specific and maybe provide code examples of how youre trying to use it.

**Comment by Tricky1975** [comment]
I shall try to set up a github page for the version for the BMax API I use for my game. The code that actually calls the module is a bit hard to provide since it contains a few security codes, but I shall try to see what I can provide.

**Comment by YLivay** [comment]
Nginx is not being kind to us.
Does it still happen for you guys?

**Comment by hworld** [comment]
I believe this is now fixed. It was nginx not resolving the DNS again periodically even though it changed while proxying.
