### ISSUE TITLE
Unable to remove broken downloaded games from libary

### ISSUE THREAD

**Issue by Cash120** [gamejolt/issue-tracker#507]
I downloaded a game, "Ninelives" in this case, and I can't remove/uninstall it from the games library. The file when downloaded from the website is a setup file, and I don't know if this is what caused the broken installation. If so, could the launcher give a warning/ prompt the game installer to run the first time the game is launched?

**Comment by YLivay** [comment]
Game Jolt Client doesnt support installers just yet. When you launch a game that is an installer it simply executes the installer it downloaded thinking its a game. It doesn't actually install it itself so it doesn't know how to uninstall it or even know that it *should* uninstall it.

You can uninstall the game the same as you would uninstall any other game by finding the uninstaller yourself. For Ninelives the uninstaller is in the game directory you installed it to.

I've opened a ticket to support installers in the client :)
