### ISSUE TITLE
Long code blocks are not kind to the code highlighter in chat.

### ISSUE THREAD

**Issue by hworld** [gamejolt/issue-tracker#513]
It puts too much strain on the servers. It locks them up for a bit since it's not async.

**Comment by YLivay** [comment]
Most of the processing goes on actually detecting which language is written. If there was a way to disable that it could take a huge load off of detection but then we need to make sure users either always select a language after the backticks or be fine with the code block having no highlight at all.

Also if the code is really just ridiculously long we can delegate it over to either a worker or just post it in a pastebin (where it belongs tbh)

**Comment by hworld** [comment]
Highlighter was removed for now.
