### ISSUE TITLE
Game screenshots get misaligned

### ISSUE THREAD

**Issue by CyberKiller40** [gamejolt/issue-tracker#515]
Steps to reproduce:
1. open a game page which has a lot of screenshots (e.g. The Chosen Alpha)
2. open one of the first screenshots, looks ok, close it
3. scroll the horizontal bar under the screenshots to get to the ones further on the right
4. open one of them, notice its displayed a little off to the left of the window
5. repeat steps 3&4, the more to the right is the screenshots list scrolled, the more to the left is each of them displayed

Noticed in: Firefox, Game Jolt Client
Also happens when clicking the next screenshot button while they are opened

**Comment by hworld** [comment]
Whoops, I thought I had this one in the issue tracker already. Guess I forgot. =]

**Comment by hworld** [comment]
I tried in Firefox developer edition and it was perfectly fine. Tried in Chrome and it is wrong. I have a fix for Chrome (sort of), but then it seems to break fx developer... Will need to look into this more.

**Comment by acidpoison** [comment]
Is this related to my #265?

**Comment by CyberKiller40** [comment]
Yeah, this is the same issue and it's still happening. Easy to reproduce in this game page http://gamejolt.com/games/the-chosen-alpha/40495
