### ISSUE TITLE
Add missing game engines to drop down list

### ISSUE THREAD

**Issue by YLivay** [gamejolt/issue-tracker#517]
Peeps have requested we add the following:
- LÖVE
- Unreal Engine 3
- Unreal Engine 4
- RPG Maker MV
- Panda 3D

**Comment by CyberKiller40** [comment]
some notes:
- The correct name of Love2D is "LÖVE" (all caps)
- Unreal Engine 3 and 4 would be good to added separately as there are some major differences between them (versions 1 and 2 were not free for the public so there's no point adding them)

**Comment by MausGames** [comment]
It would also be nice to show the (optional) free-form text from the Other category... it makes no sense otherwise.

**Comment by YLivay** [comment]
Should add Power Point. Yes, its a thing now.

**Comment by Tricky1975** [comment]
I see we do have Blitz3d and BlitzMax, but there is also BlitzPlus

**Comment by 1029chris** [comment]
The [Godot Engine](http://www.godotengine.org/) is an excellent engine, it's similar to Unity and open source. [GDevelop](http://compilgames.net/), [Superpowers](http://superpowers-html5.com/index.en.html), [Gamesalad](https://gamesalad.com/), and [Polycode](http://polycode.org/) are some others than I can think of.

**Comment by CyberKiller40** [comment]
Yeah, +1 for Godot. Though this list should really be based on the data from the database, check what people put into the other field and add everything that is used in at least 5-10 games (+then switch these games descriptions to the new field).

**Comment by niksudan** [comment]
Not sure what the status of adding the new engines are, but there is now a thread about the "other" category on the gj-improve forum. Feel free to vote there and add your feedback.

https://gamejolt.com/f/show-what-other-language-engine-is-used/341363
