### ISSUE TITLE
Visitors not logged can't see public chat rooms

### ISSUE THREAD

**Issue by acidpoison** [gamejolt/issue-tracker#524]
![image](https://cloud.githubusercontent.com/assets/11214348/12438841/acf7218c-bef8-11e5-8b2c-69458b89c37d.png)

However, opening the bar immediately after logging out displays the Lobby chat room.

**Comment by YLivay** [comment]
Sounds funky. I'll add to chat milestone, thanks!

**Comment by YLivay** [comment]
Solved!
