### ISSUE TITLE
Better moderation tools for chat rooms.

### ISSUE THREAD

**Issue by Agrosis** [gamejolt/issue-tracker#526]
So, we need better moderation tools
- [ ] Like timed mutes
- [ ] You should also be able to mute/unmute people not online at the moment
- [ ] Same with mod/demod

@hworld @YLivay More?

**Comment by YLivay** [comment]
Eagro, tracking this somewhere else already.
Maybe I should just move the issues over to here? @hworld

**Comment by Tricky1975** [comment]
It's not possible to mute/unmute offline peeps?
![image](https://cloud.githubusercontent.com/assets/11202073/12447037/e6af4632-bf6d-11e5-879e-0fbe5a1c0056.png)

**Comment by YLivay** [comment]
Possible but not through the new chat moderation panel.

**Comment by Tricky1975** [comment]
Aha.... Now I get it ;)

**Comment by acidpoison** [comment]
Hey, new bug to report to you all... and a story ;)
So I opened up chat today and saw that there was a little box that popped up around each message that I hovered over with my cursor. No information about it popped up, so I somehow assumed that it was a way to delete specific messages in chat. I clicked one of my messages and muted myself. -__-

I don't have the permission to mute/unmute room mods, which means I can't unmute myself. help

**Comment by acidpoison** [comment]
Room mods can mute themselves through the message muter and don't have the permission to unmute themselves.

Muting through message is also difficult because if someone posts a message, all the other messages get moved and you may misclick and mute someone else.
