### ISSUE TITLE
Settings page for games empty

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#527]
![image](https://cloud.githubusercontent.com/assets/11202073/12443270/1499b620-bf57-11e5-84c1-037bae9b5fd9.png)

(Addition. In the client it works, in my browser (Opera) I get this).

**Comment by Tricky1975** [comment]
Addition: A few hours later the settings appeared again. I don't know if that means the issue is fixed or if this was a "stroke of fate"....

**Comment by YLivay** [comment]
Might have something to do with site translations. Keep an eye out.

**Comment by hworld** [comment]
Pretty sure this was because of translations. Closing. Reopen if it ever happens again. I can't repro.
