### ISSUE TITLE
Add a report system.

### ISSUE THREAD

**Issue by YLivay** [gamejolt/issue-tracker#528]
Just logging this so peeps know its on the todo list :)

**Comment by Tricky1975** [comment]
![image](https://cloud.githubusercontent.com/assets/11202073/12446936/58755bc2-bf6d-11e5-9b83-f31f02e0a0fe.png)

**Comment by CyberKiller40** [comment]
Finally! :-)

**Comment by hworld** [comment]
Done. Will be in next Client update.

**Comment by Tricky1975** [comment]
!!!!AT LAST!!!!
