### ISSUE TITLE
Client Download Page can scroll to the right

### ISSUE THREAD

**Issue by NickRock** [gamejolt/issue-tracker#532]
![client_website](https://cloud.githubusercontent.com/assets/11754980/12463632/5749d254-bfcd-11e5-80d1-3b9a342b007e.PNG)

There is no right - left scroll bar but if you click and hold the mouse wheel and move your mouse to the right you can see that the site scrolls to the right.

**Comment by YLivay** [comment]
How did you do this voodoo? This is what I get:
![gj](http://i.imgur.com/yXuPlgd.png)

**Comment by NickRock** [comment]
Yeah, this is what happens when you zoom out but you can still scroll to the right even if you zoomed out

**Comment by hworld** [comment]
I am not sure there's anything I can do about this. It's also a bit of a weird way to trigger it... Gonna close.
