### ISSUE TITLE
System does not always tell me who PMed me

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#533]
![image](https://cloud.githubusercontent.com/assets/11202073/12506470/6af827c4-c0ef-11e5-9770-2d0bb7785711.png)

As "heyguys" is off-line and on top of the list I guess he sent me 2 chat messages while I was sleeping (clicking his name after I took that screenshot confirmed that), but I guess a proper marker would be desirable.

**Comment by YLivay** [comment]
once you clicked his room did the notifications go away? What happens if you refresh?

**Comment by Tricky1975** [comment]
Well, after I indeed opened "HeyGuys" it was clear he send me both messages and they got removed from the marker top-right indeed. As you can see I had a clear bottom bar at the time, as I saw this before when the friend in case was marked on the bottom bar as he was still there. What happens after a refresh is something I cannot reproduce until somebody who is not on my bottom bar PMs me again while I am afk, so we can only hope that will happen shortly, allowing me to answer that one :wink:

**Comment by Tricky1975** [comment]
I'm in luck, it already happened. Renewing the page does "fix" the issue in the sense that everything looks right then.

**Comment by hworld** [comment]
Ah, yeah, I've noticed this issue as well. It has something to do with the view not updating because of some crazy optimizations I do to reduce watchers in angular. Since friend/room lists can be so long, I try to only check if that view should be updated if something happens with the specific user in the list. It must not be working when a notification comes in.

**Comment by Tricky1975** [comment]
Hmm, now that you mention it. Heyguys is not on my screen when he is off-line (unless I scroll down). I guess that is the source of evil then?

**Comment by hworld** [comment]
I believe we've fixed all chat notification issues not updating
