### ISSUE TITLE
Can't access games

### ISSUE THREAD

**Issue by videostealerYT** [gamejolt/issue-tracker#537]
What I mean by this is when I click on a game when browsing through them, the game page does not open.

**Comment by hworld** [comment]
A couple people have brought this up. We're looking into it now. Hopefully we'll have an answer soon.

**Comment by YLivay** [comment]
Sorry for not having a solution for this yet, but in the new version (0.3.0) we now have client system reports you can send over! If it ever happens again please submit a system report by scrolling down to the footer and selecting the "Send System Report" in right side.

**Comment by YLivay** [comment]
Hey, is this still an issue?

**Comment by videostealerYT** [comment]
Nope, this is no longer happening! (Sorry for delayed response)

**Comment by Blubberislife** [comment]
It's happening for me, I sent a report. Thank you for your involvement with the community.

**Comment by YLivay** [comment]
Hey @Blubberislife, you have a different issue, I opened a new issue for it https://github.com/gamejolt/issue-tracker/issues/587
