### ISSUE TITLE
Chat messages sometimes too bright

### ISSUE THREAD

**Issue by Eleuin** [gamejolt/issue-tracker#538]
Ocassionally, the brightness of chat messages are too bright and become nearly unreadable
![bug](https://cloud.githubusercontent.com/assets/5553828/12527945/462b0004-c155-11e5-89da-18bdb69f79ac.PNG)

**Comment by Agrosis** [comment]
It never fades in for some reason. Same as https://github.com/gamejolt/issue-tracker/issues/471. Refer to that one instead for now.
