### ISSUE TITLE
client suddenly stopped working on windows 10

### ISSUE THREAD

**Issue by Chris20DK** [gamejolt/issue-tracker#546]
i have been enjoying the client for a week now, but two days ago it suddenly stopped working, what should i do?

im running the 0.1.2 version btw.

**Comment by YLivay** [comment]
Hey, can you be a bit more specific? What stopped  working? Does it not open at all? Having problem playing games?

**Comment by Chris20DK** [comment]
i client does not open at all

**Comment by YLivay** [comment]
Do you see its icon the system tray? In task manager do you see GameJoltClient.exe?
How are you trying to open it? Through the shortcut? If so, right click it and select open file location. Does it open a directory with Update.exe in it?

**Comment by Chris20DK** [comment]
both when using the shortcut and the original program file, it does not work, but GameJoltClient shows up as running 4 times in task manager. when opening the directory as you suggested there is no update.exe present.

**Comment by YLivay** [comment]
Hmm. It looks like  a  bad  installation  or uninstallation  while the client was  running.
K! Heres what you need to do:
1. Close all GameJoltClient.exe from task manager (Its fine that you may see multiple)
2. Remove the folder %LOCALAPPDATA%\GameJoltClient. Don't worry it wont remove your games.
3. Install again, preferably using the new installer from Game Jolt website. Even better is if you could wait a day or two. We're releasing a new version with loads of fixes and a new installer that solves all of these issues :)

**Comment by YLivay** [comment]
Did it solve your issue?

**Comment by YLivay** [comment]
No input, closing.
