### ISSUE TITLE
Can't play WebGL Based games in the client

### ISSUE THREAD

**Issue by mig876** [gamejolt/issue-tracker#547]
I tried to play MLG FLAPPY BIRD 420 And it says like if I was trying to play in Google Chrome.
And after the message that I need a Browser that supports webGL,The loading freezes.

**Comment by CyberKiller40** [comment]
Works fine for me on OpenSUSE 42.1, what is your operating system, cpu architecture and GPU

**Comment by mig876** [comment]
Windows 7 Ultimate SP1
Intel Atom N550 Akimbo (XD)
Intel GMA 3150

**Comment by Tricky1975** [comment]
It appears that only Firefox accepts WebGL and even there I've experienced a lot of trouble with a lot of games. Particularly when the game in question is written in Unity.

**Comment by hworld** [comment]
Unity has the absolute worst loader I've ever seen. It takes so long to load some times.

**Comment by CyberKiller40** [comment]
Unity web games work ok for me in both Firefox and the GJ client. Though it does take long to launch the games.

**Comment by YLivay** [comment]
They just dont make em light like eggnog anymore. Launched in 4ms flat hah.

It doesnt launch for me as well on Win10 x64 using the client. Then again it doesnt work in browser as well.

**Comment by Tricky1975** [comment]
I believe this is a Unity issue, making this one beyond anyone's powers to fix here on GJ. I suppose we should bug the big boys and girls behind Unity in stead. :sunglasses:

**Comment by YLivay** [comment]
If it works from the site and not Game Jolt its one thing, but this thing doesnt load in site as well unless I leave it for an unnatural amount of time haha..

Im going to close this as a non issue. Other webgl games do work.
