### ISSUE TITLE
Very strange client behavior

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#548]
![image](https://cloud.githubusercontent.com/assets/11202073/12610975/ce8aca40-c4ea-11e5-89d3-ec2a90ecb3c6.png)

Apologies if my title is too vague, maybe the screenshot above explains stuff a little.

Let's sum this up

1. I downloaded Rampage, Guns, Bots - RGB, because the developer requested tips for his next games, and I wanted to see what he could do already before I'd give tips
2. Downloading went as it should
3. When I tried to launch the game I first got the "Oh! No! can't play the game" growl.
4. Despite all that the game started up not once but 5 times, and I have 5 times the same app in my dock (which is supposed to be an impossibility on Mac).
5. After I was past the Unity start up dialog the game itself ran normally
6. I had to close all 5 apps runs manually.
7. The famous "keeps on playing" bug did not get me though.

Client version:
![image](https://cloud.githubusercontent.com/assets/11202073/12611181/b70f13d4-c4eb-11e5-8c37-20b067fbcf86.png)

Mac Version:
![image](https://cloud.githubusercontent.com/assets/11202073/12611197/cc62e512-c4eb-11e5-8db9-e38fd690a7d0.png)

**Comment by YLivay** [comment]
What is the client on 0.1.1? Should've been updated  multiple times already. What does the footer page tell you the version is? Maybe the desktop entry is just stale

**Comment by YLivay** [comment]
Hmm...  this game's doing something weird. It seems like  its forking itself from the main task  and closing so the client thinks it never even opened. Need to look into this more, can't say anything concrete atm. Try running it from the terminal and compare with other games. See how that one quits immediately after its launched

**Comment by YLivay** [comment]
Sounds like #490

**Comment by Tricky1975** [comment]
When I run the game normally (I mean, just through the Finder and not through the client) it works the way it should. I expect the same from the terminal.

**Comment by CyberKiller40** [comment]
It should do an auto update. BTW: how do you check the client version? I can't find it anywhere.

**Comment by hworld** [comment]
New version will have it in the footer. We were going to push the version today but we'll probably do it tomorrow instead.

**Comment by Tricky1975** [comment]
"BTW: how do you check the client version? "
On the Mac version it was just in the AppMenu every Mac GUI app should have under "About". However that menu does not exist on Windows and Linux, so I really don't know how you check it there ;)
![image](https://cloud.githubusercontent.com/assets/11202073/12673483/56c0d42a-c67d-11e5-9a03-94cfa6d2b0a0.png)

**Comment by hworld** [comment]
Yeah, mac shows in that menu, new version will have the version number in footer.

**Comment by YLivay** [comment]
This has been fixed in new version :)
Waiting to push it!
