### ISSUE TITLE
Need Comment Deleted (Not an Issue, just need deleted)

### ISSUE THREAD

**Issue by Ironcreater** [gamejolt/issue-tracker#549]
By MOX Howdy im asriel, asriel dremmur, and i have stucked on the fight with the fallen human "Chara" (me the player) and i cant get the t.reset :D

**Comment by Tricky1975** [comment]
Well I suppose the guys here could check this out for you, but I suppose you should have mailed to contact@gamejolt.com in stead about this particular matter. ;)

**Comment by YLivay** [comment]
Link the comment or game page. Whats your username on Game Jolt?

**Comment by Ironcreater** [comment]
http://gamejolt.com/games/chara-battle-undertale/110195#comment-1107996
