### ISSUE TITLE
Implement support for the old Game Jolt videos.

### ISSUE THREAD

**Issue by hworld** [gamejolt/issue-tracker#55]
There was a period of time when users could upload videos to Game Jolt and we would convert them and serve them ourselves.

We need to get the media bar/lightbox to support these old videos.

**Comment by YLivay** [comment]
Uhh... can close this right?

**Comment by hworld** [comment]
yeah, just silly to try supporting this bc compatibility at this point. too bad, we could've been youtube

**Comment by YLivay** [comment]
We can still be Vimeo.
