### ISSUE TITLE
Games not working,Please Help FAST!!!

### ISSUE THREAD

**Issue by Amnesi4Black** [gamejolt/issue-tracker#554]
Please help when i download a game and start it i play it and when i stop playing it (close the game) and then after i want to play it again the play button is gone and there are only 3 gray dots and the options are view game and uninstall and when i click view game it says that the game is already running.Even when i checked the processes programs and everything it still doesn't work.Please help!

**Comment by acidpoison** [comment]
Sounds like #488.

**Comment by YLivay** [comment]
Hey, thanks for reporting. Can you try restarting the client? Close it from the tray (or in extreme cases the task manager). If the problem persists scroll down and in the bottom right corner find the "Send System Report" button. We'll look at the logs.

**Comment by YLivay** [comment]
No feedback, new version should fix this. closing.
