### ISSUE TITLE
NEED HELP PLZ

### ISSUE THREAD

**Issue by Dnoyce4** [gamejolt/issue-tracker#555]
can anyone help my client is not working it keeps saying update.exe is missing if anyone sees this
plz help me!

**Comment by Dnoyce4** [comment]
here is the pic 
![error](https://cloud.githubusercontent.com/assets/17014562/12733200/0925cd18-c981-11e5-9b2b-9ee970f30499.png)

**Comment by YLivay** [comment]
You already have the client installed and running. First close it from the tray or task manager and then install again.

Or you can wait for next version that'll be released really soon with a new installer that takes care of it for you.

**Comment by Dnoyce4** [comment]
my client is downloaded and it was saying update.exe i gress?
