### ISSUE TITLE
Game stuck "Processing Build"

### ISSUE THREAD

**Issue by BeardoGames** [gamejolt/issue-tracker#556]
Hi!

Tried to upload a build of this game last week:
http://gamejolt.com/games/intergalactic-alien-boy-band-conquest/122335

And it has been stuck in processing.  

It is a Twine game-- so i uploaded a .zip that contains all the images and the .html file.

From what I have read, this shouldn't take more than a few minutes--so something is wrong.

Thanks!

**Comment by YLivay** [comment]
Can you link the archive you were uploading here?

**Comment by BeardoGames** [comment]
[boybandgame.zip](https://github.com/gamejolt/issue-tracker/files/113409/boybandgame.zip)

Here it is.  Thanks.

**Comment by YLivay** [comment]
Thanks  man, im checking it out now :)

**Comment by YLivay** [comment]
Erm... Is it just me or does this archive have nothing but images?

**Comment by BeardoGames** [comment]
There is one .html file - BBGAME.html  that is the twine game-- the rest are the images.

**Comment by YLivay** [comment]
Rename it to index.html and it'll work :)

**Comment by BeardoGames** [comment]
Cool- thanks!
