### ISSUE TITLE
Dragging pictures into the client can make the client go "KABOOM!"

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#557]
A report on the forum that I saw (I don't know which OS this guy was using, but I assume it's Windows) states that dragging a picture (of any format a browser should support) would make the client show the picture in stead of the GameJolt site with no way to get out of this. Just closing the client didn't do it (I think a total restart should do the trick).

I tried to replicate this bug on Mac and there dragging a picture into the client caused the client to crash entirely leading to a crash message by Apple on two tests. On the third test the picture did show in the client, but the client terminated itself immediately after, leaving no crash message this time.

**Comment by YLivay** [comment]
The client is just nwjs wrapper so I can do that! Good catch haha.
And yes, restart would definitely fix it. He just needs to restart it from the tray
