### ISSUE TITLE
Very high client cpu usage during decompression

### ISSUE THREAD

**Issue by CyberKiller40** [gamejolt/issue-tracker#561]
v0.3.0, openSUSE 42.1 (but also noticed this on winxp)

When a game is decompressing after download/update, then one of the client threads uses up a whole cpu core. This might not seem a big issue, but for some reason the webpage rendering in client is affected by this - everything slows down to a crawl.

Make the decompression run at a lower cpu priority or something like that.

**Comment by hworld** [comment]
The decompression is a bit heavy, which is why we make sure it doesn't happen while playing a game, but if it's affecting client browsing, that's problematic. How many cores do you have on your CPU?

**Comment by CyberKiller40** [comment]
I have 2 cores (Athlon 64 X2 4200 @ 2,6GHz), however when this happens only one of them is being used, the other is free. In the task manager I see one of 4 client threads using 50% of cpu, other using none.

This started to be noticeable after the last client update, earlier I was installing a lot of games and it never affected the overall client performance. Right now I can see the pages being loaded in the speed of a few elements per second, I actually can see the text labels for a while before the translation string loads (sic!). But when unpacking is finished, then everything is back to normal.

So like I say - maybe spawn a new process for the decompression and make it run at low priority. Or take a look at what changed in the code for decompression between this and the previous releases, maybe there's something there that can give a hint.

**Comment by addaleax** [comment]
@hworld [Here](https://github.com/gamejolt/client-voodoo/blob/master/src/extractor/index-spec.ts#L12) and [here](https://github.com/gamejolt/client-voodoo/blob/master/src/patcher/index.ts#L166) are calls to the decompression library which explicitly specify `{synchronous: true}`, forcing the decompression to take place in the main/v8 thread. I don’t know the reasons for that, but if it’s some kind of bug with lzma-native you are working around, I’d be glad to help.

**Comment by hworld** [comment]
Ha! Good catch, @addaleax.

@YLivay do we need this for pause/resume functionality, by any chance?

**Comment by CyberKiller40** [comment]
Hmm... but that code is for lzma, and the problem occurred even when the decompression was done for a (200MB) zip file.

**Comment by hworld** [comment]
Every game in client is lzma. We recompress every single build uploaded to the site to have an lzma version too so that we can control the compression. This allows any game to be playable in client no matter what archive was used to upload by the developer, and it ensures that we keep games small while retaining fairly good decompress speed.

**Comment by YLivay** [comment]
We used to need this when we did download/extract concurrently, relying on extraction happening in chunks which async threw off, but now we may as well turn this off.

@Yo addaleax, if we wanted to offer resumable extraction support even when the application quits, not just by pausing the stream to lzma is paused, is it possible to somehow save the extraction context so we can restore it at a later time?

**Comment by addaleax** [comment]
@YLivay I’m afraid that’s not possible, sorry. In the native liblzma library, the internal state of the (de)compressor is hidden from applications behind an opaque pointer, and there’s a lot of pointers to functions and other objects flying around internally, so this really wouldn’t be easily implemented. :/

**Comment by CyberKiller40** [comment]
Is there really any point in resuming a paused decompression? Most games on GJ are <100MB in size, if paused during decompression they could just be restarted from the beginning and nobody would care.

**Comment by YLivay** [comment]
Guess im going to have to go with plan B when we get the time :)
XZ works in chunks of 1-9k bytes. I'll have the download stream pass chunks instead of a steady stream to assemble the file at the end and keep an internal pointer to which/how many chunks were already processed. This way I only need to spoof the header and bypass stream crc checks, shouldnt I?

**Comment by YLivay** [comment]
This is fixed in the newer version. Keeping this open till we push :)

**Comment by YLivay** [comment]
Forgot to close this .-.
