### ISSUE TITLE
Mac doesnt update properly - Need to have update resign the entire package every time.

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#563]
My client version (on Mac) still shows 0.1.1.
I believe the client should auto-update itself and that we are on 0.3.0 now, right?
Of course, I can erase the current client and install the new version manually, but before I do I wanted to verify this.

**Comment by YLivay** [comment]
Can you restart the client, wait for a few seconds and send us a system report?

**Comment by Tricky1975** [comment]
So I guess that means I gotta re-install the client manually then?

**Comment by hworld** [comment]
Weird. It should auto update. I have tested on Mac. I wonder if it is some lame Mac security thing. Would you be able to manually update for now?

**Comment by Tricky1975** [comment]
No prob. I just wanted to make this sure....
I updated manually now, and now it shows version 0.3.0, so I guess I'm on the current version now.

**Comment by YLivay** [comment]
Will do! Im leaving this open for reference and adding to the 0.4.0 milestone

**Comment by Tricky1975** [comment]
As far as I can check this is not an issue anymore.
At least I cannot duplicate stuff anymore.
