### ISSUE TITLE
infinite years update? [Client]

### ISSUE THREAD

**Issue by S3idOtaku** [gamejolt/issue-tracker#564]
Hello!

Reporting a bug here. My client got stuck with an infnite years update!! and i can't uninstall the game...
This Picture show the problem :
![untitled](https://cloud.githubusercontent.com/assets/17096628/12866409/deb3fa1a-cce5-11e5-8410-3edf0d62db7d.png)

i hope you can help me
Thanks!..

**Comment by YLivay** [comment]
Please try pausing and resuming the download, then scroll down to the footer of the page and click "Send Sysem Report"

**Comment by YLivay** [comment]
This is associated with log#13.
Seems like it failed to fetch the url to download from. Either connectivity problem that relates to #550. Or bad handling of aborting downloads before they began.

**Comment by YLivay** [comment]
@hworld this is caused by a suppressed error in the component that calls client voodoo's patcher to get the download url. Make it throw an error. I'll bubble it back through the patcher's chain

**Comment by AvianStowaway** [comment]
Hey, adding on to this since it's a similar/the same bug. My update is doing the same thing, but I'm unable to pause the update or do anything to the updating game. Sent a system report about this as well.

**Comment by hworld** [comment]
Oddly I fixed this in the latest client release: v0.13.0
