### ISSUE TITLE
New Windows installer rejects any possible install path.

### ISSUE THREAD

**Issue by luckcolors** [gamejolt/issue-tracker#565]
Hello.
Thank you for implementing the feature i asked here [issue-tracker](https://github.com/gamejolt/issue-tracker/issues/468)/issues/468 but it seems that the setup says that every path i enter is invalid.
Tests made:
-Default install path: invalid path.
-Custom Install path with spaces symbols and capital letters: invalid path.
-Custom Install path with spaces: invalid path.
-Custom install path folded in the root of the disk(eg. C:\gjclient): invalid install path.
-Tested with rus as admin: invalid path.
![installererror](https://cloud.githubusercontent.com/assets/3228598/12872145/36977e78-cd9a-11e5-9eee-71d73899e483.png)
I hope it helps.

**Comment by YLivay** [comment]
You need to run with administrative rights if youre installing somewhere you need them to write a file. If you select a directory in your user profile does it work? (Thats why it was initially installed in your %LOCALAPPDATA% folder.

**Comment by luckcolors** [comment]
I did and i left the default path in the installer which is the one you are talking about and it still doesn't work.(the path is C:\Users\luckcolors\AppData\Local\GameJoltClient)

**Comment by YLivay** [comment]
Whats your OS/Arch? Does it show any extra info if you run it from cmd? This is a pretty standard innosetup installation, nothing weird about the way it installs, really. Im trying to reproduce this

**Comment by luckcolors** [comment]
Ok my os is: Windows 10 pro 64 bit.
Also i read on the documentation of inno setup here: http://www.jrsoftware.org/ishelp/index.php?topic=setupcmdline on how to log to file.
Here's the setup log:
[Setup Log 2016-02-07 #002.txt](https://github.com/gamejolt/issue-tracker/files/120723/Setup.Log.2016-02-07.002.txt)
Also i tested other innosetup installers and they work so.

**Comment by luckcolors** [comment]
Mmmh could you provide me the inno install script you are using? So i can test if i rebuild the setup the error still happens?

**Comment by YLivay** [comment]
PrepareToInstall eh? Probably has something to do with detecting your old version.
Can you paste a screenshot of this registry key if it exists?
`SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\GameJoltClient`

**Comment by luckcolors** [comment]
That key doesn't exist (i searched in HKEY_CURRENT_MACHINE). :)

**Comment by luckcolors** [comment]
I managed to fix the installer by reinstalling the old version of the client and then installing the new one.
:P (previously i uninstalled gamejolt manually).

**Comment by luckcolors** [comment]
Also @YLivay i know i'm going of-topic i guess for this issue but is not possible to store the stuff that goes in AppData\Local\game-jolt-client alongside the client install dir? If not i'll stop asking :P.

**Comment by YLivay** [comment]
Yo, they key should've existed in local user :)
Glad you got the installer to work out. How exactly does manual uninstallation work by the way? Did you delete the previous directory without calling the uninstaller? So you had ghosts of squirrel installer not backed by anything on file system? That would make sense for the installer to fail in that case - and we'll patch it up for next version

**Comment by luckcolors** [comment]
yeah i deleted the folders in appdata and the local game install path. :)

**Comment by YLivay** [comment]
Aha! Thanks a ton for reporting! Will fix.

**Comment by Fixer66** [comment]
I am having the same issue. I have tried several times, but it still says invalid install path,even on the newest version. Any ideas how to fix this?
