### ISSUE TITLE
Revenue not updating

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#567]
I guess you guys already know about it, but the number of complaints about this matter on the forums is close to 1K and counting. I could not find any other issue about it (as I thought it was already there), so let's open one, shall we.

**Comment by Fappp** [comment]
Is there a static interval for processing the rev?

**Comment by Tricky1975** [comment]
Should be, as far as I know, however that too does not appear to work if I got to believe the complaints.

**Comment by CreativeSparkStudios** [comment]
As a developer I need to know my monthly ad revenue, but right now there's only an all-time revenue on my dashboard.

**Comment by Fappp** [comment]
Oh yeah, in chat complaint about my 10 cents are not here are common. Revenue always updates for me. @CreativeSparkStudios > Sorry if this sounds nitwitty, but having a company means keeping track of everything yourself. I for one just check how much has added since last month and deduct it from the total amount and then avoid taxes on the 5 dollars anyways.

**Comment by YLivay** [comment]
Hey guys, sorry for the inconvenience, you only need bear with it for a while longer!
Most of the revenue issues will be resolved in the Marketplace milestone. Yup. Marketplace! HYPE!
I'm closing this, believe me - you'll know when the marketplace is out without the issue tracker haha >:)

**Comment by CreativeSparkStudios** [comment]
@Fappp, when you need to keep track of revenue from many sources, big and small, it's nice to have a monthly stat as well as an all-time stat. And it's also the industry standard. Check Newgrounds.com, Kongregate.com, MindJolt.com, FGL.com, and other game portals for examples of good revenue reporting features. Not to mention ad providers and app store reporting.
@YLivay Great news, I'll be looking forward to the Marketplace announcement :-)

**Comment by Tricky1975** [comment]
Uh oh, you confused the crap out of somebody by closing this ticket, @YLivay 

I quote:

> So, now the ticket is closed... So, what's happen with this? I need my money :/

I tried to explain things on the forum, but maybe you should go into more detail (unless you think my explanation suffices that is). (You can find him in [this thread](http://gamejolt.com/f/ad-revenue-has-ceased-updating/6660)).
