### ISSUE TITLE
Forum notifications in client get URL http://gamejolt.comundefined/

### ISSUE THREAD

**Issue by Fappp** [gamejolt/issue-tracker#569]

**Comment by CyberKiller40** [comment]
Confirm, when clicking on a notification in client about a new forum post, the external browser gets passed the said url, which ofc doesn't open.

client v0.3.0, GNU/Linux

**Comment by YLivay** [comment]
Thanks for reporting!

**Comment by Fappp** [comment]
Thanks for making GJ awesome xx

**Comment by YLivay** [comment]
We're planning to release a quick patch version soon.
It wont fix this but it'll make the client at least no freak out when it's trying to go to the notification.

**Comment by YLivay** [comment]
So, notifications no longer redirect outside of the client, but they still dont direct you to the actual topic. Hey, it's something! (pinging this back alive)

**Comment by YLivay** [comment]
Fixed!
