### ISSUE TITLE
Use our own avatar system instead of Gravatar

### ISSUE THREAD

**Issue by YLivay** [gamejolt/issue-tracker#573]
Now that we revamped our media serving and we have user reporting in place. We can support our own avatar system.

**Comment by Tricky1975** [comment]
Like I said on the forums, I have great reasons to plead to keep Gravatar and make the users choose between Gravatar or uploading. Hate having to upload my avatar to every site I'm a member of, and if you wonder why I'm still using my old avatar on GitHub, well there you go.

**Comment by CyberKiller40** [comment]
Yeah, keep gravatar, it's a great tool. I also have a million accounts, and thx to gravatar this is one less thing I need to keep in mind about them.

**Comment by Tricky1975** [comment]
What I wanted to suggest is a system that I found out SourceForge uses. I wanted to suggest it before, but now that I see that SourceForge uses it already I can screenshot it:

![image](https://cloud.githubusercontent.com/assets/11202073/13149643/834b8db0-d662-11e5-8ae2-3208f1b18d5b.png)

I think this is fair to both gravatar lovers and haters. If no avatar is uploaded, gravatar is used by default, if the user uploads an avatar, then we won't use gravatar. Both parties happy. No?

**Comment by hworld** [comment]
Yeah, that's always been the plan. I wouldn't remove the ability for gravatar. It would be the fallback if you don't have a GJ avatar uploaded.

**Comment by Tricky1975** [comment]
Thank you, @hworld 
That's what I wanted to hear... Uhm... excuse me... I meant, read! :)

**Comment by hworld** [comment]
holy crap, this is done! https://github.com/gamejolt/gamejolt/pull/97
it will fallback to gravatar if you don't have a GJ avatar uploaded, so no worries there. you can also disable gravatar if you want absolutely nothing showing

**Comment by Tricky1975** [comment]
![image](https://user-images.githubusercontent.com/11202073/30233863-a948f7ae-94f8-11e7-99ca-256d1d8ea2e3.png)

So that's why you changed back to this avatar, eh?
To test if it all works (it's still EEEKS, though) XD
