### ISSUE TITLE
Client doesn't have the correct codecs to play songs.

### ISSUE THREAD

**Issue by TekkertheChaot** [gamejolt/issue-tracker#576]
Hey,
I don't know if its already posted, but the client is unable to play Soundtracks from Games..
This includes:
- WebGL Games
- Unity Games
- HTML 5 Games
- attached soundracks on gamesites

(Sorry for my bad english, I'm from Germany :D )

**Comment by YLivay** [comment]
Hey, what OS are you on?
Could this be related to #416?

**Comment by YLivay** [comment]
NWJS is being stingy and doesn't like the codec you're using. Funnily enough if you upload .ogg and rename it to mp3 it'd work as a temporary workaround. We'd have to actually re-encode all the songs that peeps upload to a codec nwjs is happy with, which will be a royal pain.

**Comment by CyberKiller40** [comment]
Allowing upload of ogg/vorbis files would be a good start - I'd reupload the soundtrack for my games instantly. I actually had to recode them to mp3 back when I was uploading them :-P. Allowing vorbis upload would be awesome.

**Comment by TekkertheChaot** [comment]
Hi, i'm sorry i had abandoned this issue! I simply didn't see it in any of my lists until now.
This issue may be closed as well as all related issues to this seem to be resolved!
