### ISSUE TITLE
Forum in-thread pagination gone

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#579]
I can only see page `#1` of each thread now.

**Comment by hworld** [comment]
What do you mean? When you scroll to bottom you see the pagination widget. I suppose maybe I should put it on top too.

**Comment by hworld** [comment]
Oh, I see. A bug. Haha, fixed.

**Comment by Tricky1975** [comment]
Thanks for fixing it on such a short notice. Lol! And yeah, maybe putting it on top too, would be a good idea. Oh, and maybe in the thread list also, I really miss not being able to get on the last page in one click, and since I'm used to click the name of the last poster... let's say, Jani and I have seen each other profiles VERY much due to the new situation, haha!
