### ISSUE TITLE
Download links for client ignored

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#584]
The buttons for downloading the client (the client itself I mean) appear to be ignored.
This bug came into light for me, as somebody said he couldn't download the Linux version (and I couldn't either), but I tried the links for Windows and Mac and they don't work either. Just nothing happens when I click them. Nothing at all.

(BTW, I used Opera in Windows 10. Yeah, I'm on Windows and not on Mac this time, as I need to do some stuff only Windows can do) :(

**Comment by Tricky1975** [comment]
Possibly this is a dupe of #583, though I don't know if that issue just handles the client download or downloading in general.

**Comment by hworld** [comment]
Fixed. A bad url was pushed out for the download and I was flying sadly.
