### ISSUE TITLE
Download system allergic to "pure" PDF

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#589]
For my game Star Story I just uploaded the game manual in PDF format. First I uploaded the pure PDF file. When I click the download link then I just get the page "The download should begin in just a moment". Actually the download doesn't begin at all. 

I re-uploaded the manual, but this time with the PDF file zipped, and then the download works.
This problem lives on both the site as the client (since the client just opens a browser window/tab to the file to download).

**Comment by hworld** [comment]
Yo, this was fixed a month or so ago but I didn't know there was an issue for it.

**Comment by Tricky1975** [comment]
Lol ;)
