### ISSUE TITLE
A post that replies to you and is in a thread you follow gives you two notifications

### ISSUE THREAD

**Issue by Honno** [gamejolt/issue-tracker#592]
One for the reply, one for a new post in a forum you follow, ie [these two notifications](http://i.imgur.com/KfGtDvb.png) links to [this](http://gamejolt.com/f/done-make-latest-posts-next-to-each-subforum-title-topic-post-stats-on-the-forum-homepage-link-to-latest-post-rather-then-the-thread-s-op/14887#forum-post-75006).

**Comment by YLivay** [comment]
I think this is solved.
Oh, and, stop talking to yourself sheesh
