### ISSUE TITLE
Mark a package as non installable on client

### ISSUE THREAD

**Issue by YLivay** [gamejolt/issue-tracker#594]
Honno made an interesting point of being able to make a package non installable, where the content isn't expected to be "installed" per se, just downloaded.

For example music packs, art packs, _installers_ (temporarily, until we support installers properly).
Instead it'll redirect them to download from the site by default.

**Comment by CyberKiller40** [comment]
Apart from installers, isn't this covered by the 'other system' option?

**Comment by YLivay** [comment]
Installers, custom updaters and more edge cases, mainly.
But yeah, art packs and song packs and those things should normally be other.
