### ISSUE TITLE
Still "playing" a closed game

### ISSUE THREAD

**Issue by niksudan** [gamejolt/issue-tracker#595]
> A closed game is impossible to relaunch from the client because it thinks the game is still running.
It is possible to play a game only if you launch the game from its .exe inside the installation folder.
Take into account that this happens only for those games played at least once: i.e. fresh installed games are not affected (till the first play).

From gamejolt/gamejolt#33 by @MrMoDDoM

**Comment by YLivay** [comment]
Dupe dupe duuuupe #488, #529, #554
