### ISSUE TITLE
Somekind of Software replaced Gamejolt Client with himself

### ISSUE THREAD

**Issue by Cepukka** [gamejolt/issue-tracker#596]
Hello, there!

Today, when I booted up my computer, somekind of NW.js (Node-Webkit) popped up. I was really confused, so I have to search everything about it.
One Explanation about the software said 

> It appears in Task Manager as "Node-Webkit" 

but I can I didn't find it

I tried to check the application what Processor it was using and it said "Gamejolt Client"

.... What? Just what? HOOOOOW?!!!!!!!!!!!!!

I think it's got to be about the server security, becose GameJolt Client uses Internet

Please fix this please, before anything worse can happen

Thanks

**Comment by YLivay** [comment]
Hey! Worry not!
NW.JS is just the "engine" that's running Game Jolt Client, so nothing hijacked your client!
The bad news though is it seems like an auto update failed and got your installation in a corrupt state :(
We're terribly sorry but the only solution for these cases at the moment is complete re-installation.

But, before you do, can you send us your client.log file to contact@gamejolt.com?
In Windows it's in `%LOCALAPPDATA%\GameJoltClient` by default (just paste that in your explorer path bar). It'll help us find the issue and fix it for next times!

**Comment by Cepukka** [comment]
@YLivay I deleted the Client. Does it exit still there?

**Comment by Cepukka** [comment]
@YLivay Sorry, but I deleted it :(

**Comment by Cepukka** [comment]
@YLivay I deleted, but the Appdata folder is still there. Will it work for fixing?

**Comment by YLivay** [comment]
Yeesh haha what a mess.
If you deleted the folder instead of uninstalling it using the installer you may have an issue using the installer as it is. You can either wait for next version with the fix for it (may take a few days) or you can put your hacker pants on and i'll guide you through fixing it :)

What'll it be? Hacker pants or virtuous patience?

**Comment by Cepukka** [comment]
@YLivay I ment that I deleted with an installer, but the Client's appdata folder exits. I ment that

**Comment by Cepukka** [comment]
@YLivay Is it still good for fixing?

**Comment by YLivay** [comment]
Ah yes, appdata is "common grounds" for lots of applications, not just GJ. You shouldn't delete it.

And yes, try installing the client again :)

**Comment by Cepukka** [comment]
Installed it. It was fixed

But I didn't send the log file, becose when you said

> We're terribly sorry but the only solution for these cases at the moment is complete re-installation. But, before you do, can you send us your client.log file to contact@gamejolt.com?

So I thought I have to have it installed so I said

> @YLivay I deleted the client, but the Appdata folder is still there. Will it work for fixing?

**Comment by YLivay** [comment]
Ah its ok, we'll get other chances, thanks for reporting and sorry for the trouble!
