### ISSUE TITLE
Edit client command line for games

### ISSUE THREAD

**Issue by CyberKiller40** [gamejolt/issue-tracker#597]
Feature request:
Add an option to edit the game's executable command line (and arguments) to the client.

Reasoning: there are a lot of incorrectly configured games, some of them need extra cli parameters to run correctly (e.g. to force a rendering engine in Unity games), some of them point to the 32bit binary even for 64bit systems. It's hard to bug game developers to fix their games, advanced users could fix this for themselves.

Ideas:
- add this as option for installed games ("edit launch command line")
- allow selecting to run only the files included in the downloaded package (a minor potential cheating prevention)

**Comment by YLivay** [comment]
This would integrate nicely with the wine support we may or may not be doing in the near future.
Not sure how we're going to approach this though. At any rate, good idea!

?ping @hworld

**Comment by YLivay** [comment]
We have a new game wrapper that makes it possible to bootstrap your own environment variables and arguments to the executable. Its not a raw command line replacement but it gets it closer. I dont know if we should allow free form command line our changing requirements and restrictions may break this at every chain without us or even the devs realizing. We may add some templates to work with, but adding something we cant commit to not break is kind of weird.
