### ISSUE TITLE
Crashing problems

### ISSUE THREAD

**Issue by galogk** [gamejolt/issue-tracker#603]
Im using gamejolt client in my windows 8 computer, for some reason when i type a little too fast or jst when i type the client crashes, i dont know what is happening to the client to make it crash.

**Comment by hslohk** [comment]
Wait wait, why my name is hslohk if i typed in galogk??

**Comment by YLivay** [comment]
Hey,  does it always happen when you type fast? Im not sure it has anything to do with typing, but may be something weird!

Ok, so right after it crashes and you restart the client, please scroll down to the footer and hit "Send System Report". Write something in the title so we'd know it's you and i'll be able to see if theres anything odd about the crash.

**Comment by galogk** [comment]
YLivay, I sent the crash report, do you see it?

**Comment by YLivay** [comment]
Hey, yes I see the client started usually after trying to download this one game, but last time you opened the client it downloaded it successfully. I  think it may have been a  problem with downloads not your typing speed  hmmm...

I'm still not sure what is the cause. If it happens again can you send another client log?
Try downloading sum games!

**Comment by galogk** [comment]
Ok!

**Comment by galogk** [comment]
I was intalling 2 games then it randomly crashed, i sent another report.

**Comment by YLivay** [comment]
hey thanks for reporting.
The logs dont show anything out of the ordinary.

Do you have an anti virus running? Do you have enough disk space at C available?

**Comment by galogk** [comment]
Ylivay, now i cant download or enter pages of most games i want to download in the client and i need to download them in the webpage, some help please?

**Comment by galogk** [comment]
I have 130GB free, ill move some of them to D.

**Comment by galogk** [comment]
Livay, for some reason my client is broken, i cant go to games webpage, my installed games are gone plus they dont show, Help!

**Comment by YLivay** [comment]
When you say you "can't" whats actually happening? Be as specific as you can, describe what youre doing and whats happening in more detail or we can't know what went wrong. When did it start happening? Did you restart the client? Did your computer crash in the last few days? Did you send system reports when you encountered the bugs?

**Comment by YLivay** [comment]
Hey, did you submit the client reports for this yet? I have a couple earlier reports from you but doesnt seem to show the issues youre describing.

**Comment by YLivay** [comment]
Closed for issue inactivity.
