### ISSUE TITLE
Add vote manipulation to game report reasons.

### ISSUE THREAD

**Issue by YLivay** [gamejolt/issue-tracker#604]
Users have no way of reporting a vote manipulation if they dont know who did it and reporting yourself is kinda weird.

We should add vote manipulation as a report option for games to report your own games as being downvoted or other games for being suspiciously upvoted.

Also allow reporting on your own game?

**Comment by Tricky1975** [comment]
Perhaps adding a way to add some text to the report feature and (and put it available if people choose "other" as reason), could also do well (I could put that in a separate issue), since multiple choice questions are not in all cases able to tell the full story.

**Comment by hworld** [comment]
DONE!
