### ISSUE TITLE
Chat displays weirdly on mobile

### ISSUE THREAD

**Issue by YLivay** [gamejolt/issue-tracker#605]
Reported android + chrome is a disaster, chat scrolls to the side and you cant refocus it. Also, visual gtliches when the address bar pops into view.

**Comment by hworld** [comment]
We need to know the Android version. It is fine on my Android phone. None of those glitches occur. Is this an older device?

**Comment by Agrosis** [comment]
Mobile is a pita to get all the bugs fixed on >_< We used `position: fixed` here and there, and mobile devices don't like to play with that very much.

**Comment by hworld** [comment]
Fixed for android
