### ISSUE TITLE
Gamejolt Client downloads games at 1 KBPS.

### ISSUE THREAD

**Issue by LJLativoXD** [gamejolt/issue-tracker#608]
Whenever I try to download a game, the download is only at 0-1 kbps.
I'mpaying for 3 Mbps btw.

**Comment by hworld** [comment]
Are the downloads on gamejolt.com fast for you?

**Comment by YLivay** [comment]
Any update on this? Seems like this would be related to #550

**Comment by YLivay** [comment]
Abandoned issue, can't replicate. Will be handled in #550
