### ISSUE TITLE
Chrome conflicting with 32bit Unity games on Linux

### ISSUE THREAD

**Issue by CyberKiller40** [gamejolt/issue-tracker#609]
This is not totally the fault of the client, but the fault of the browser engine. Somehow chrome, chormium and node webkit prevents from starting 32bit Unity games on a 64bit system. I came to this conclusion after seeing this forum thread on steam:
http://steamcommunity.com/app/304650/discussions/0/405692758702620718/

I had the same problem with a number of Unity games on GJ, I couldn't start them from the client, but I thought it's the fault of unity and the 32bit builds of games (64bit builds worked fine).

I don't know if this is something that is possible to be fixed here, most probably either chromium or unity need to fix their code, but I think it's worth noting that such problem exists currently.

**Comment by YLivay** [comment]
I wonder if we can hack around this in the meantime by generating a one time intermediary launcher script heh. Will check.

**Comment by CyberKiller40** [comment]
That won't help. The issue is if a totally unrelated chromium based application is running at the time. You get the 'player is already running' in strace then.

**Comment by YLivay** [comment]
Our new game wrapper solves it! Yay! It'll be out in next version probably :)

**Comment by YLivay** [comment]
Yup, works now. Closing
