### ISSUE TITLE
Malicious links inserted in the site text

### ISSUE THREAD

**Issue by CyberKiller40** [gamejolt/issue-tracker#611]
I think someone tried to insert spam/malicious links into the translation strings. This is the text from the current add build page (for html build)

> A .zip archive containing all of the files the game needs to run, including an https://b6d3e9q9.ssl.hwcdn.netindex.491da0b1.html in the root. Should be playable in any modern browser without plugins.

and:

> For an HTML game, upload a .zip archive containing all of your game's files and assets. There must be an https://b6d3e9q9.ssl.hwcdn.netindex.491da0b1.html in the root folder.

There used to say "index.html" instead of those links there.

**Comment by YLivay** [comment]
Not malicious, looks like something just doesnt click with the translation process.
We've had this for a while, but no time to look  into it properly ;-;
Hopefully soon when things stabilize

**Comment by 1j01** [comment]
:+1: This was super confusing (even though I didn't need to do anything because I named it index.html presuming that would be how it would work)

**Comment by hworld** [comment]
Was fixed a couple months ago. Forgot to update here.
