### ISSUE TITLE
Site down?

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#612]
![image](https://cloud.githubusercontent.com/assets/11202073/13396949/ae5eb200-def7-11e5-8632-a2b8784f686d.png)

I've been getting this screen since the start of this afternoon (on Feb, 29th, 2016, Dutch local time I mean). Oddly enough I could still reach Thomas Bowen through private chat.

**Comment by Purple-Guy** [comment]
Ik Mine Is Worse It Doesnt Have PM

**Comment by Purple-Guy** [comment]
![screenshot 189](https://cloud.githubusercontent.com/assets/17548529/13397452/4b5eba3c-deb7-11e5-8236-e2e3d7a2af6a.png)

**Comment by YLivay** [comment]
Sites getting ddosed. Hang tight, will be fixed soon.

**Comment by Tricky1975** [comment]
Yeah, I can get back on the site again, but I wonder.
Which MORON (I don't have a better word for that) would DDOS an indie game site such as GameJolt?
Some pathetic little whiner who wanted revenge for getting himself banned or something?
