### ISSUE TITLE
Site Got Nuked?

### ISSUE THREAD

**Issue by Purple-Guy** [gamejolt/issue-tracker#613]
GameJolt Will Not Come Up On Febuary 29th 2016 This Is Either:

1. GameJolt Is Getting Site Updates (Yay New Stuff!!!)

2. Just A Random Bug (Please Fixxxx)

3. Some One Hacked The Servers (Hopefully Not)

Some People Are Able To PM There Freinds Me However Cant Do Anything XD
So Yes This May Be A Bug And I Hope Gamejolt Can Fix It So We Can Enjoy Playing 6000 Games That We Either Built Or Love

![screenshot 189](https://cloud.githubusercontent.com/assets/17548529/13397828/db60aa7c-deb8-11e5-883e-cdda78334468.png)

**Comment by CyberKiller40** [comment]
It's called cracked, not hacked. Hacking is a good activity https://en.wikipedia.org/wiki/Hacker_culture :-)

**Comment by YLivay** [comment]
Just ddosed. The lowest form of attack.
Will be setting up protection soon.
