### ISSUE TITLE
Forum - report threads for being in the wrong subforum

### ISSUE THREAD

**Issue by CyberKiller40** [gamejolt/issue-tracker#614]
As the name says - there are forum threads created in the wrong subforums. Add an item to the report causes list for this, so this can be used to inform moderators to move the thread to the appropriate subforum.

**Comment by Tricky1975** [comment]
I totally agree. I guess ALL forum sites should add this reason to the report feature ;)

**Comment by Tricky1975** [comment]
[Moved to gj-improve](https://gamejolt.com/f/forum-report-threads-for-being-in-the-wrong-subforum/341373?sort=active)
