### ISSUE TITLE
Concept: shared dev games

### ISSUE THREAD

**Issue by CyberKiller40** [gamejolt/issue-tracker#615]
I didn't find such item in this tracker, so I thought I could share some of my ideas for shared development games if anything like this comes to GJ in the future.
1. one user uploads the game and is the 'owner' of the game page, builds etc
2. the owner can add other users as more developers, they get the game displayed on their profiles, but they don't have any way to edit the game page (maybe read-only access to see the build options and stats); the game page lists the owner & all devs as the games creators
3. the owner can assign a fraction of the ads revenue to be given to each additional dev; by default the owner gets 1,0*amount and the others get 0*amount; by adding fractions to each additional dev, the owner lowers his own ratio - this would be effective since the day when each change was done (so there wouldn't be a need to recalculate the revenue many times during a single day, only a full days ad revenue gets split) (or maybe make the revenue ratio per dev change effective per month, if per day is too often)

What do you think? From what I've seen, a lot of people are looking forward to something like this on GJ.

**Comment by YLivay** [comment]
We don't have a solid plan yet for this but its been on the table for a long time.
When marketplace takes shape we'd know better what we can do, but imo we should definitely push towards this. It works well with the whole Game Jolt Groups direction too!

**Comment by CyberKiller40** [comment]
Hey, any progress here? The lack of having other team members officially recognized keeps me away from starting any collaboration projects.

**Comment by niksudan** [comment]
Collaborator support was rolled out [a month ago](http://fireside.gamejolt.com/post/collaborators-dr3uvigz), which covers the initial implementation of this.

I've opened a thread on [the new improvement forum](https://gamejolt.com/f/collaborator-enhancements/341341) that discusses further points. Feel free to open another thread for further additions.
