### ISSUE TITLE
Unable to return to main screen? - GameJolt Client

### ISSUE THREAD

**Issue by ShadowDragon2002** [gamejolt/issue-tracker#620]
After I installed the GameJolt Client, all was good. But then I decided to get an avatar and found out that I had to create a Gravatar Account, so I clicked on GET GRAVATAR ACCOUNT and created one. But once I did that, I realised that there actually wasn't a way to get back to the main screen so I had to reinstall the Client. Please make a way to get back to the main screen as I don't want to reinstall the Client again if I have to do something similar again.

**Comment by CyberKiller40** [comment]
Sounds like #419 strikes back! :-)

**Comment by YLivay** [comment]
Yeah it shouldn't have opened in the client anyways.
For reference, you can make it work by restarting the client.
You do that from the tray icon not just by closing the window because that just hides it

**Comment by YLivay** [comment]
This has been fixed.
