### ISSUE TITLE
Forum reply notifications don't open forums in client

### ISSUE THREAD

**Issue by CyberKiller40** [gamejolt/issue-tracker#621]
1. get a reply in a thread or a new post in a followed thread
2. open the notifications from the top bar in the client
3. click the forum notification

expected: the forum thread opens, scrolled to the new post
current (0.3.2): the notification disappears, but the opened page doesn't change

**Comment by YLivay** [comment]
Sounds like the linux version of #642 
Yay now we got all 3 OSes with issues about this.
