### ISSUE TITLE
My game detected as "unknown virus" by AVG when DLed by GJ client

### ISSUE THREAD

**Issue by maxlefou** [gamejolt/issue-tracker#623]
#It happens in my demo over here:
http://gamejolt.com/games/game-jolt-api-for-ren-py-sample-game/127112

For strange reason, when you install the game with the client and start it, AVG antivirus (maybe other antiviruses too?) detects the .exe as an "unknown" virus. 

I tried to download it manually via the GJ website and launched it after unzipping it, no problem at all. I'm not sure but I guess something went wrong in the GJ Client side.

It's a game made on Ren'Py and includes python code that makes the game communicate with GJ API. I seen this problem only today and only on this game. (it's open-source, you can check the code yourself)

Am I the only one having this?

**Comment by CyberKiller40** [comment]
There's nothing wrong with your files:
https://www.virustotal.com/pl/file/506e063b98dcd53d9588ccb842e3c4914f911c8e32e5e1ce79348dcfc790de5a/analysis/1457952496/

Here's the stats for just the executable file:
https://www.virustotal.com/pl/file/559d5ca234a68bac5a9b1130f9ec73512c1a20178daf0ce04154cbe83dcd32fe/analysis/
(fun fact: it lists a lot of other games that have the same file)

To be even more sure, then don't recompress the zip produced from RenPy (it breaks the Linux permissions btw).

Antiviruses get a lot of false positives when using heuristics. It usually is safe to disable this option.

**Comment by maxlefou** [comment]
actually, I directly use the zip made by renpy (in other cases, i do this too, except for the windows only version which i need to unzip in order to compile a nsis installer) It happens only on the api demo, and only if launched from the GJ client. It doesn't happen in my other renpy games.

**Comment by YLivay** [comment]
Does it complain about the extracted file? Or on the archive the client downloads?
There is no difference between files extracted by the client and files that are in the original archive you upload. All the client does is wrap the files in a tar.xz format instead of the original archive you passed in, so the only thing I can imagine going wrong is the AV panicking about some false positive in the tar.xz temporary file.

**Comment by maxlefou** [comment]
it does it (well it did it. It doesn't do it anymore but i think AVG memorized it as an exception for good. Or maybe GJ team fixed it already) when the game is launched. It detects the .exe, so it complains about the extracted file.

**Comment by CyberKiller40** [comment]
Some antiviruses commonly report an exe launching another exe as a virus.

**Comment by maxlefou** [comment]
that would explain all of this. Now AVG just needs to know Game Jolt isn't a virus giver :D
