### ISSUE TITLE
Media image anchor links from GJ game profiles do not link back to image

### ISSUE THREAD

**Issue by Honno** [gamejolt/issue-tracker#624]
For example, clicking the first image of [this game](http://gamejolt.com/games/travel-to-mars/126709) generates the link `http://gamejolt.com/games/travel-to-mars/126709#screenshot-237917`, but [using it as a link](http://gamejolt.com/games/travel-to-mars/126709#screenshot-237917) gives an error notification ("Oh no, couldn't find that image, maybe it was removed").

**Comment by hworld** [comment]
Fixed finally in a branch. Will be merged in soon.
