### ISSUE TITLE
[GJ Client] [Ren'Py] Says "Oh no! Couldn't launch game" but launches the game.

### ISSUE THREAD

**Issue by maxlefou** [gamejolt/issue-tracker#625]
All is in the title. When you install a game made with Ren'Py then launch it from the Game Jolt Client, the client says "Oh no! Couldn't launch the game" but the game miraculously launches anyway.

Not really a big deal but it had to be mentionned. :p

**Comment by CyberKiller40** [comment]
Works ok with my renpy game.

**Comment by Tricky1975** [comment]
I've seen this with a few other games too, and those were not created with Ren'py.

**Comment by YLivay** [comment]
The way the client detects if a game is still running is by pid at time of creation. If the game started and then forked off and bound itself to a new pid the client wont find its old handle. Sometimes launchers do that. Can you link your game? Also when it happens scroll down to the footer and in the bottom right corner you'll see a "Send System Report" url. Click it and submit so we can see where things went wrong.

**Comment by maxlefou** [comment]
Actually only my renpy games does that. these ones:
http://gamejolt.com/games/game-jolt-api-for-ren-py-sample-game/127112
http://gamejolt.com/games/kare-wa-kanojo/98969
http://gamejolt.com/games/la-34eme-dimension-saison-2/122062

But as i said, it's not a big deal, and what YLivay said is very certainly the cause of it. I would be 
only half surprised if renpy works like that for their games.

**Comment by YLivay** [comment]
Im keeping this open for now because we're going to push out something that changes the way detection works and im not sure what'll happen in these cases.

**Comment by YLivay** [comment]
Is this solved now?

**Comment by Tricky1975** [comment]
I tried this with "Sleepless Night 2: Ladies’ Night(mare)" on Mac, and there the "Can't play growl" does not appear, implying the issue is solved. I don't know how this is on Windows and Linux though.

**Comment by YLivay** [comment]
We changed the way games are launched entirely,  so if the bug survived its something truly annoying! Testing this game on Linux doesn't work, seems to be a configuration issue with the game tho. On Windows it runs fine so the bug's solved :D

**Comment by maxlefou** [comment]
I just tried it on a Windows 7. It's _kinda_ fixed. Now I have it when I close the game (but not when i launch it :D )
