### ISSUE TITLE
Cant download

### ISSUE THREAD

**Issue by mwh100** [gamejolt/issue-tracker#629]
I cant download because when I go to releases there is nothing to press. It is like this on all games I want to play. this is happening on any web browser and gamejolt client. I am using windows 8.1 64 bit.

**Comment by YLivay** [comment]
Sounds like all the games you want to play just dont have a playable build, that's all.
Link the games you were trying to view, and I can confirm it for you :)

**Comment by YLivay** [comment]
Closed for inactivity.
