### ISSUE TITLE
Empty Game Page (!!! EMERGENCY !!!)

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#634]
![image](https://cloud.githubusercontent.com/assets/11202073/14011117/22756bd2-f19c-11e5-8d58-4cfa92fd737b.png)

- Ratings and number of ratings show
- However Ratings Break Down only shows zeros
- You can see this is my game
- And you can see (outside this screenshot) the header banner
- Everything else is not shown

**Comment by hworld** [comment]
So, this is supposed to happen, but only for a second until the rest of the page loads.

Is it still happening? If so, can you press shift+ctrl+i and refresh and see what it logs?

**Comment by Tricky1975** [comment]
When I reported this, this happened on ALL game pages, and it stopped after that.
After only 15 minutes after this report things appear to have turned to normal, and I cannot replicate this anymore, whatever I try.

I also need to note that I was on Windows 10 when this happened, and you should know by know I am primarily a Mac user, and switching between the two systems is always a bit of a hassle for me. Btw, I do assume that *if* the bug is still there, it would also happen on my Mac, but I doubt that key combination works on Mac. 

I think this was only a bit of a side effect when you made the update, as that was when this happened. The first thing that comes to mind is that there may have been a version conflict with some older data that was still cached, either on my Windows PC or on the GJ servers and that the cache has caught up now. I dunno.

If it happens to me again before Sunday I'll give a shout in this issue. If that doesn't happen, I guess the issue "fixed itself"

**Comment by hworld** [comment]
Yeah, I'm thinking it was cache. Makes the most sense as things stabilized after a bit.

**Comment by Tricky1975** [comment]
Whoa.... that reply was fast. ;)

**Comment by hworld** [comment]
Haha, saw the alert pretty fast.
