### ISSUE TITLE
report no response

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#636]
Normally I would not post this on the issue tracker, but I need to know...
Are the mods backlogged or do the reports not come in properly.

[this guy](http://gamejolt.com/profile/1-f5f773/1088245) spams the forums. I've reported 2 of his posts 2 weeks ago and in the mean time, I reported more. 

These two threads:

- http://gamejolt.com/f/temmie/15438
- http://gamejolt.com/f/flowy/15326

Where from his hand and both reported as either spam or hate messages. Nothing has happened so far and today he posted some more spammy messages. 

Since I cannot check the report lists as I am not a moderator, I just wondered if this was just the mods being a bit behind or the reports not coming in fully. I reported more spam threads that are still there.

**Comment by YLivay** [comment]
Yes we have around 2k reports to go through. Problem is also people tend to report completely legitimate things and saturate the real reports completely.

**Comment by Tricky1975** [comment]
Okay, that explains it.
Yeah, maybe we need to make sure people don't do that. 
On the website I moderated in the past I was allowed to ban people who abused the report feature. Of course that site supported temporary bans, and GJ only supports permanent ones, and I suppose a permanent ban goes a bit too far. But at least some system that allows the mods to make clear that people should not just report everything they come across and should only report stuff that is truly "a crime". Perhaps some kind of warning system can already get the message across.
