### ISSUE TITLE
Notification number not recalculated when notifications are being marked as "read"

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#637]
When I have a notification I see a number on of of my screen, telling me how many I got.
When I either click it read the forum post, or comment or whatever it refers to it gets marked as read but the number remains as it was. The number only gets recalculated when I either get

- a new notification
- OR when I click the notification icon again

Since I mostly have multiple windows/tabs open with GJ this always confuses the heck out of me, since I have to reset them all manually on every page (I mostly try to keep my notifications up-to-date).

===

Addition: Friend requests suffer from the same issue in multiple windows/tabs. The screen where I accepted/rejected the friend request itself everything's cool.

**Comment by YLivay** [comment]
Would be dealt with once we revamp the notifications to be a push mechanism. Not sure what the prioritization on this is.

**Comment by hworld** [comment]
Yeah, it's almost there. Sadly we got bogged down by other projects (like marketplace), but real time notifications are soooooooon.

**Comment by YLivay** [comment]
This should be fixed now :)
