### ISSUE TITLE
Download button in banner does not appear to work on all games here

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#639]
Ninja Nick posted this on the forum, and in the picture he showed, he's right.

![image](https://cloud.githubusercontent.com/assets/11202073/14048065/21c5994e-f2ac-11e5-9314-76c468f1ffe6.png)

[Original forum post](http://gamejolt.com/f/download-button-in-game-banner/15462#forum-post-78327)

**Comment by hworld** [comment]
Going to close this as I probably won't do it. If I do allow positioning, it will probably be done a bit differently.
