### ISSUE TITLE
Two different kind of web distros of one game (HMTL5 and Flash in this case) do not combine.

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#643]
Sun Temple posted this on the forums
======

Hello dear forumers,

I've run into a bug of gamejolt.com which occurs when there are 2 web playable versions of the game available: HTML5 + Flash. The Play button on the game cover opens an iframe with a broken link in this case and the game can not be played. It can still be played fine using the buttons on the release panel though. I tried putting the Flash & HTML5 builds into separate releases but it didn't help. Even if they are in different releases the bug occurs anyway. As soon as I delete the Flash build from all releases, the game cover play button starts working fine.

The bug seems to be "cross-browser". I reproed it in FireFox and Chrome.

Here is a screenshot which demonstrates the bug:
http://suntemple.co/gamejolt-html5-flash-iframe-bug.jpg
The game in question:
http://gamejolt.com/games/basket-ball/99795

Does anyone perhaps know a workaround?

Thanks!

### End of Forum post
Here is the included screenshot
 ![](http://suntemple.co/gamejolt-html5-flash-iframe-bug.jpg)

And the link to the original forum thread: http://gamejolt.com/f/flash-html5-web-builds-gamejolt-bug/15524?page=0#forum-post-78647

**Comment by hworld** [comment]
Fixed!
