### ISSUE TITLE
Replying to a fireside comment notifies you of comments before yours

### ISSUE THREAD

**Issue by acidpoison** [gamejolt/issue-tracker#645]
![screenshot 2016-04-01 at 2 55 30 pm](https://cloud.githubusercontent.com/assets/11214348/14217188/95d2a41c-f81a-11e5-93de-501325aa8067.png)
![screenshot 2016-04-01 at 2 55 36 pm](https://cloud.githubusercontent.com/assets/11214348/14217192/9aae0224-f81a-11e5-974d-a8c9b6c4ca9e.png)

I posted a comment after CROS, but I got a notification on his comment after I was subscribed to the thread.

**Comment by Tricky1975** [comment]
The system looked into the future and KNEW you were going to post.
A special algorithm written by the Mad Fortune Teller

![](http://www.freakingnews.com/pictures/113500/Ozzy-Osbourne-the-Fortune-Teller--113535.jpg)

**Comment by hworld** [comment]
Gonna close this since I won't fix this yet. It's basically because the notification system runs periodically with some lag, so you will get notifications for things within that period.

**Comment by Tricky1975** [comment]
So I can get notifications for people replying a few minutes before me, but when we speak of hours or even days, this won't happen (if I got this straight).
