### ISSUE TITLE
Chat links ending with a parenthesis don't link correctly

### ISSUE THREAD

**Issue by acidpoison** [gamejolt/issue-tracker#647]
![screenshot 2016-04-03 at 7 54 59 pm](https://cloud.githubusercontent.com/assets/11214348/14235795/498e67f4-f9d6-11e5-8807-b23406139159.png)

Links to https://en.wikipedia.org/wiki/GT_Racing_(video_game.
Just a rare problem with markdown in general, dunno how big of a deal this is. :/

AND AGAIN

![screenshot 2016-04-03 at 8 00 53 pm](https://cloud.githubusercontent.com/assets/11214348/14235824/dd34cbc4-f9d6-11e5-88e7-d149c341b446.png)

darn wikis

**Comment by hworld** [comment]
What if you wrap in angular brackets like: `<https://en.wikipedia.org/wiki/GT_Racing_(video_game)>`?

**Comment by hworld** [comment]
Either way going to close since this is just an issue with markdown. You can see it failed in GitHub too.
