### ISSUE TITLE
State of emergency!!!! Forums being spammed

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#648]
I've been reporting this with the report feature and through mail and this issue tracker is now my last resort I guess.
On the #casual forum the first post that is not spam is located on page 11 (and that is a post by Frogge only posted 2 hours ago). All forums have been spammed for days now, and none of the reports I send in get an answer, so that's why I'm here now!

I do know we can't stop them due to proxy's and all that kind of stuff, but if a moderator would at least be there to clean the shit up asap the damage can at least be minimalized, as I think many potential new members might run away if they see the forums like this. 

![image](https://cloud.githubusercontent.com/assets/11202073/14317450/a8c64a14-fc08-11e5-99a0-2195123f9c0f.png)
^ this is page 11 ^

By the way there is spam all over the forums right now, but the #casual board is currently in the worst state.

**Comment by hworld** [comment]
cleaned. I will keep trying to look periodically to make sure we clean 'em up. I was traveling so didn't notice

**Comment by Tricky1975** [comment]
Well there is some more (look at the bottom of page 1 in #casual), but the most popular topic have at least been recovered. Thanks ;)

**Comment by Tricky1975** [comment]
Just to note.... He's back!

**Comment by YLivay** [comment]
Some people  have too much free time making spam bots pfft.  Cleared again.

**Comment by Tricky1975** [comment]
And I know you don't want to hear this, but.....
Guess....
Yup, there was another attack.

**Comment by Tricky1975** [comment]
22 pages of spam on the #coding board before you reach the first non-spam thread.

**Comment by YLivay** [comment]
Thanks for keeping on top of it @Tricky1975, it really helps.
I'll look into why the spam filters arent stopping him.

**Comment by Tricky1975** [comment]
Any time, @YLivay ....Nothing is more annoying than a forum full of spam.
Speaking of that, another attack on #casual, not that much this time as before, but still spam.

**Comment by Tricky1975** [comment]
More spam in the #coding channel

**Comment by YLivay** [comment]
Cleared again
