### ISSUE TITLE
Transition developers news to Fireside.

### ISSUE THREAD

**Issue by hworld** [gamejolt/issue-tracker#65]

**Comment by hworld** [comment]
I think we're going to transition these to Fireside and make it so new articles can't be added just yet, but at least their archive of articles will be available. I just don't have the time to build it out in WTTF and it's not worth it since we'll be transitioning that to Fs in the future anyway.

**Comment by NikSudan** [comment]
Is this done now?

**Comment by hworld** [comment]
Yup. Done!
