### ISSUE TITLE
Old forum posts containing smiley will now be "rotten"

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#650]
![image](https://cloud.githubusercontent.com/assets/11202073/14439911/eb3a73ba-002d-11e6-99d3-ac640d2c2356.png)

I know it handles outdates posts, but it still looks a bit messy.

**Comment by hworld** [comment]
I know about this one. We need to make a script to go through all forum posts and change the old emoji images into the new format. Not sure when I'll get around to it.

**Comment by Tricky1975** [comment]
I am wondering about this one. Most of the affected threads are so outdated by now, that immediate closure might be in order if anyone ever necromances them. I'll leave it to you if this should be closed or not, but I wonder if this is still relevant.

**Comment by YLivay** [comment]
Still relevant! thanks for bumping it tho. I'll assign it to meself.

**Comment by Tricky1975** [comment]
Question. Does this update "fix" this issue, or is this still an issue?
