### ISSUE TITLE
Markdown Spoilers can be stacked on top of eachother

### ISSUE THREAD

**Issue by acidpoison** [gamejolt/issue-tracker#651]
Typing `>! >! >! >! >! spoiler` becomes:

![screenshot 2016-04-12 at 5 44 32 pm](https://cloud.githubusercontent.com/assets/11214348/14476605/bd4853a6-00d6-11e6-8847-2d405372a916.png)

It still works, just makes the spoiler zone larger.

**Comment by hworld** [comment]
This is how markdown works even though it's weird. =]
