### ISSUE TITLE
Not showing font in code blocks of markdown.

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#652]
I got this in a thread of mine
![image](https://cloud.githubusercontent.com/assets/11202073/14494229/06b791a6-018a-11e6-9e6f-cdfb96aba09c.png)

After refreshing the page, the code showed, though.

**Comment by Tricky1975** [comment]
I've seen the same issue in displaying my level in my profile. There too renewing the page "fixed" the issue.

**Comment by hworld** [comment]
Seems more like we don't have a fallback font maybe, so it's trying to download the monospaced font and either failed or is taking too long. It should show a default system monospaced font until it finishes loading our custom one.

**Comment by hworld** [comment]
Seems to be fixed.
