### ISSUE TITLE
Installation on linux

### ISSUE THREAD

**Issue by theDoubleLink** [gamejolt/issue-tracker#654]
I am trying to install the tar.gz file on linux and it says that any of the files to install is not found. Could you release a .deb package instead?

**Comment by hworld** [comment]
For Linux it's actually a portable tar.gz package. Meaning that you just extract it somewhere and then launch the executable. It should attempt to create .desktop files for your OS so you can launch again without needing to open the folder.

How are you trying to "install" it?

**Comment by YLivay** [comment]
Closing issue, no feedback.
