### ISSUE TITLE
Some new games not showing

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#655]
In [this thread](http://gamejolt.com/f/game-don-t-show-up/21733#forum-post-86616) I received a complaint about this, and as far as I can see this is indeed a bug.

Only two guys in this thread actually told me the name of the affected games so i could sort this out.

- At the game profiles you can always see how many games the dev has in total. The number of that total is correct.
- The game also shows in the moderation profiles of the dev's in question
- The game does however NOT show in the dev's actual profile
- Neither is it shown when you try to look it up.
- If the game has a #tag, the game also doesn't show up in the games listed for that specific tag.
- The data I could get show the games are not hidden, and no signs of it being removed by a moderator either.

**Comment by hworld** [comment]
The indexer was down. I started it back up.
