### ISSUE TITLE
Hashtag gets linkified in code blocks.

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#659]
![image](https://cloud.githubusercontent.com/assets/11202073/14700906/9a440b20-07a2-11e6-80ba-86f3889e7265.png)

The hashtag was here (of course) used as part of the code, and in Lua the hashtag is used to return the number of elements in a table variable or the number of characters in a string. Many programming languages do have a special meaning for the # character.
Having it work as a tag link in a code block can therefore work confusing.

**Comment by YLivay** [comment]
Is this on forums or chat?

**Comment by Tricky1975** [comment]
The screenshot above is from the forums

**Comment by YLivay** [comment]
Bumping this. I have an unpulled fix for this, will get back on it when I can

**Comment by hworld** [comment]
This was fixed, but we found another bug. Yay!
