### ISSUE TITLE
Chat guidelines still refer to the Mute Appeal thread

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#660]
[Chat Guidelines](https://help.gamejolt.com/chat-guidelines)

Since that thread is now closed and taken out of use, I guess the guidelines need to be altered.

**Comment by YLivay** [comment]
We should actually restore this topic temporarily. We removed it too early before managing to finish the moderation tools for chat but seeing as this is delayed the mute appeal thread should still be the way to go.

Create it again, keep the guidelines pointing to the thread.
