### ISSUE TITLE
Game Jolt Client opening as default nw.js window

### ISSUE THREAD

**Issue by LucasWolschick** [gamejolt/issue-tracker#661]
In the last days, the Game Jolt Client has been opening as the default browser from the nw.js library. To reproduce, just open the client?

**Comment by YLivay** [comment]
This happens when an update has been interrupted unexpectedly most of the times. The easiest solution is to reinstall.

**Comment by YLivay** [comment]
No feedback, assuming problem solved by reinstallation ;=;
