### ISSUE TITLE
The client is having trouble launching games

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#662]
The forum is at this moment overflooding with complaints about the client refusing to launch any game at all.

One person was willing to provide some more data. The client version involved is 0.4.1. Most of the people were on Windows 7 a few on Windows 10
One of the game titles he provided (Mémoire) did also have a Mac build, thus I tried that game on Mac to see if this is a Windows only problem or not. That particular game did not run through the client on my Mac either, which could imply this is not solely a Windows problem.

(I've sent a system report after I did this test on Mac. Hopefully it contains a clue).

**Comment by YLivay** [comment]
This should be fixed.

**Comment by Tricky1975** [comment]
Oh... I thought this was closed already... Completely forgot this was still open ;)
