### ISSUE TITLE
Reporting forum posts should contain the reason "threadjacking".

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#663]
For those unfamiliar with the term "threadjacking", it's a combination of "thread" and "hijacking", and basically it means that somebody posts something entirely unrelated to the thread's subject trying to start his own discussion.

Like:
~~~
Topic: Fairy Tales
Member A:
    Do you like "Cinderella" or "Sleeping Beauty"?
Member B:
    A lot, but I think "Rimplestitzkin" is very good as well, just like "Rapunzel"
Member C:
    Did you guys know Ferrari is the best car in the world? 
    Can you imagine people would prefer a Porsche?
~~~
Well, what member C did in this example is threadjacking. I already have deleted a few messages guilty as charged of "threadjacking", and I can't rule out there are ones that escaped my notion or will escape my notion in the future. ;)

Another kind of threadjacking that can easily get past a moderator's notion is when Pete as a thread showing off his art, which which John suddenly comes placing his art in Pete's thread in stead of creating his own thread.

**Comment by YLivay** [comment]
Report as spam. We dont need super granular reporting reasons or it'll get out of control.
Since a human eventually goes over this is doesnt really matter that much what reason you report it as anyways.. Its just to keep things a bit more organized.
