### ISSUE TITLE
Private Chat messages sometimes don't go through

### ISSUE THREAD

**Issue by MaskofThoro** [gamejolt/issue-tracker#665]
Support ticket issue:

"One last thing, there is a bug, for me at least, where when you're in a private chat with somebody, sometimes your message doesn't go through, and you have to type it again, normally it happens when your internet connection isn't at highest, but it's happened to me a few times.

Also, what's the deal when you type a long message on a comment page? where it doesn't show upend says it's being reviewed or something like that... Happened to me twice, writing a review on a few games, so I'm just curious."

**Comment by YLivay** [comment]
The chat message not being sent is only a problem of a user connection, theres not much we can do about that, but try resending messages when connection is acquired again. Messy business, could end with messages being submitted multiple times.

And long messages sometimes get flagged as spam by auto detection. We'll have an event horizon entry for this and upon approving it it should unhide it. Aaaand you know how many reports we have nowadays hahaha.

I will make sure that when you approve a spammy comment it unhides it. Not sure if we actually did that bit.
