### ISSUE TITLE
One of the forum rules looks a bit contradicting and can work confusing.

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#667]
We all know by know that nobody reads these (the mods would be out of a job if people did), but still I guess it needs to be in order ;)

![image](https://cloud.githubusercontent.com/assets/11202073/14924186/7a4554b4-0e41-11e6-8d8f-6a5a8fc877a6.png)

"Keep it safe for work - really it's not needed"..... This would imply that keeping your forum posts safe for work is not needed. So basically ALL forum posts MUST be UNSAFE for work.... It's a way how this could be implemented. This of course contradicts with the last sentence of this rule. 

You'd never believe how much misery I've seen on a different site because a banned user defended himself because of a typo in the forum rules.

**Comment by hworld** [comment]
how dare you correct my english

**Comment by Tricky1975** [comment]
There is a lot I dare, @hworld 
Of course, me seeing such things while English is not my native language, might get people thinking :P
