### ISSUE TITLE
Upload of webgames takes forever

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#669]
The upload itself is not the problem.
Then we got a small pre-process, all right here
Answering additional questions like Width and Height, all good
And after that another processing rounds starts taking forever.

The forum is currently flooded with complaints about this.

**Comment by hworld** [comment]
I believe this is fixed now. Build processing got backed up because of a bug that amazon pushed out to its command line tools. It was broken for about a day but was fixed last night. We weren't able to upload to the data store after the files hit our servers.
