### ISSUE TITLE
For "Secret Achievement/Trophy" maybe it's better to keep the name secret as well.

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#670]
We set achievements to "secret" in order to avoid spoilers prior to obtaining the trophy.
Quite often I'm dealing with the fact that the title of the trophy/achievement can already be very revealing towards this spoiler.
I solved it a few times by just making the trophy title "???", but the problem is that "???" remains there when the trophy is actually obtained. 

I know that PlayStation Network does exactly that what I just suggested for hidden achievements/trophies. And some networks even do not show them at all (which is for some achievements even better).

**Comment by hworld** [comment]
I think we'd have to have an option for it. It would break backwards compatibility. Why not make the title something mysterious, but the description descriptive once achieving. That's what I assumed people would do when I first made it.

**Comment by Tricky1975** [comment]
The problem is that this does not always work. And I have for example a secret achievement in my game Star Story for which it was VERY important the only title that fits the achievement would remain secret until the moment you obtain it. If you are able to view the achievement list of my game, you will know precisely which achievement I mean, and why I want to keep the name secret (and why also don't put it's title here on GitHub, (even though I do realize you can also find it when looking through my Lua source codes on github, but I guess people are not willing to dig through thousands of lines of code just to find an achievement spoiler)). And that particular achievement was not the first time I was dealing with that problem.
