### ISSUE TITLE
Client gets stuck at Gravatar site

### ISSUE THREAD

**Issue by MaskofThoro** [gamejolt/issue-tracker#671]
"After downloading the Client and installing it, I have found that after going to Gravatar to get my Profile picture, the Client has no way to go back to Game Jolt.  It remains stuck at the Gravatar site.
Just a heads up."

-support

**Comment by FarNiche** [comment]
Thanks for the prompt return email response looking into this issue.
You're welcome.

**Comment by Tricky1975** [comment]
Not to be a know-it-all, but this was reported before #649, but I guess you couldn't find it as the poster of that issue misspelled "gravatar" in the subject.

**Comment by FarNiche** [comment]
That sounds like the same, "getting stuck at the Gravatar site" issue: https://github.com/gamejolt/issue-tracker/issues/649
Thanks.

**Comment by YLivay** [comment]
Fixed
