### ISSUE TITLE
Wrong revenue value shown in the client

### ISSUE THREAD

**Issue by CyberKiller40** [gamejolt/issue-tracker#675]
Client ver 0.5.2, OpenSUSE 42.1

I have a little below 2$ of amassed ads money, this shows correctly in the browser, but when I look at my dashboard in the client it says it's only 0,02$ - not the real amount divided by any meaningful number, just as if it only counted the last 1 or 2 days.

**Comment by hworld** [comment]
Fixed. This was because we had to hack in a fix for old client but didn't remove when pushing new one.
