### ISSUE TITLE
GameJolt Cllient Shortcut opens nw.js!

### ISSUE THREAD

**Issue by zombieknifer223** [gamejolt/issue-tracker#680]
When I open the gamejolt client, it just opens nw.js! What is the meaning of this!

**Comment by Tricky1975** [comment]
It means something went wrong when installing or updating the client. Nobody knows why this happens, but whatever does causes this as a result.

You can fix it yourself by uninstalling the client and re-installing it and if everything goes the way it should this problem should then be fixed.
