### ISSUE TITLE
Client Breaking Bug

### ISSUE THREAD

**Issue by xDarkNightPvPx** [gamejolt/issue-tracker#681]
I've just installed the client, and found out that the screen on client start up appears completely grey, I've tried everything such as
reinstalling the client
deleting the folder and reinstalling the client
tried right clicking the tray icon and pressing browse games library
to no avail, it didn't do anything.
I've included the client that I've downloaded because I don't know if there are any error log files.
**# Included is the Archive file named "My Client.rar" that contains the client that I've downloaded and installed.**
The File: https://mega.nz/#!nI5FCS5D

# **The Encryption Key for the file I've included is the following : !Vsp0m55TxMFk1mViVzP7cn-PiXK6JHWR90GJhDTsBik **

**Comment by YLivay** [comment]
Hey, this was probably around the time amazon was throwing a fit on our servers! The site was down, and the client attempts to contact it. If you have never logged in to the client this first screen is mandatory so the client couldn't skip it.

Give it a shot now and see if it works!

**Comment by YLivay** [comment]
Closed for inactivity
