### ISSUE TITLE
Signup translation problem

### ISSUE THREAD

**Issue by acidpoison** [gamejolt/issue-tracker#682]
![screenshot 2016-05-13 at 12 34 03 am](https://cloud.githubusercontent.com/assets/11214348/15238095/80b23306-18a2-11e6-8ba2-2f9eec5821a0.png)

**Comment by acidpoison** [comment]
also on the main login page

![screenshot 2016-05-13 at 12 38 58 am](https://cloud.githubusercontent.com/assets/11214348/15238197/6e523d7c-18a3-11e6-9bd2-b32fdeb06aba.png)

...and the forgot password page

![screenshot 2016-05-13 at 12 39 14 am](https://cloud.githubusercontent.com/assets/11214348/15238180/53b342b8-18a3-11e6-8c8a-65a7433b9a94.png)

is there some thread that I can just put anything like these errors under?

**Comment by hworld** [comment]
Thanks a lot for the heads up on this one! Having the auth section broken is bad for biznizz. Fixed.
