### ISSUE TITLE
Option to turn off "external growls" in client

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#683]
![image](https://cloud.githubusercontent.com/assets/11202073/15257062/d302909a-1944-11e6-86ac-932e33b300dd.png)

Checking the settings page, it indeed did not seem possible to turn this off (aside from "friend on-line off-line" messages).

**Comment by hworld** [comment]
Are you sure this isn't about the friend online/offline messages?

**Comment by Tricky1975** [comment]
Yeah, turned out to be that way in that specific post.
