### ISSUE TITLE
Clicking a "reply to a comment" notification will result into an "Oh no! Can't go to the comment" growl.

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#684]
Going to the reply manually will show the comment the notification is about though.

[Original forum thread about this matter](http://gamejolt.com/f/can-t-view-comment-from-notification-and-dashboard/22818)

**Comment by Tricky1975** [comment]
Addition, this now happened on a test game comment, but also on a reply CROS made to me on a comment of mine on FireSide, so I had to go to FireSide manually to check out what CROS had to tell me.

**Comment by hworld** [comment]
Fixed!
