### ISSUE TITLE
 I can not download the gamejolt CLIENT

### ISSUE THREAD

**Issue by Monoselha** [gamejolt/issue-tracker#685]

**Comment by hworld** [comment]
Why did you post 3 of these?

**Comment by YLivay** [comment]
Also, nothing prevents you from downloading the client besides your internet connection.
Can you describe the problem in more detail?

**Comment by apap04** [comment]
Try checking if your space is full or check your ram.

**Comment by YLivay** [comment]
Closed for inactivity
