### ISSUE TITLE
Feature Request: Support lossles audio files for OST / soundtrack of games.

### ISSUE THREAD

**Issue by luckcolors** [gamejolt/issue-tracker#688]
So this way users can upload HD amazing ost / soundtracks!

**Comment by YLivay** [comment]
Users can already upload anything they want as 'other' type build. The uploads for the soundtracks to listen online tho have to be in a common codec that their browsers can play. We currently don't reencode the songs the users upload to the game's soundtrack but we're planning too, and I don't know if it'll be lossless.

I think it's good enough for now to just upload soundtrack as an 'other' type build.

**Comment by luckcolors** [comment]
I mean there should be atleast an avaible type of soundtrack upload wich doesn't get recoded (specifically for soundtracks as people who buy the soundtrack i think would prefer to have an HD version and an high quality lossy version).
Wav should be supported by all browsers.

**Comment by YLivay** [comment]
Soundtracks as other builds don't get re-encoded, soundtracks that play on game pages will. Will continue updating on the reencoding in issue #576
