### ISSUE TITLE
Ad timer goes to -1:0-1 and crashes

### ISSUE THREAD

**Issue by Fuzzyzilla** [gamejolt/issue-tracker#692]
When I go to play a game, both online and on the GameJoltClient, one of two things happens:
1. The ad will play in it's entirety. When it ends, four times out of five the "Your game will begin in:" will jump from "0:00" to "-1:0-1." After this, the site fails to recognize the ad has played and just sits there, and does not load the game. (This option mostly happens on the Online version of GameJolt)
2. The ad will instantly end and the "You game will begin in:" will jump to "-1:0-1", or, in the case of the GameJoltClient, "-1:0-2". The same thing happens with the site freezing. (This option mostly happens on the GameJoltClient)

After one of those two options occurs, which happens more often than not, the game is just a black rectangle, the size of the ad. In the case of the online version, there is sometimes a play-button onscreen but clicking it does nothing.

This has left me unable to play games on the site, even my own.

**Comment by YLivay** [comment]
weve done so many changes to the ads i doubt this is relevant anymore. I haven't encountered this issue for a year for sure.

**Comment by Fuzzyzilla** [comment]
Probably no longer relevant, it's been so long...
