### ISSUE TITLE
Wishlist

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#694]
The ability to add games to a wishlist would be nice.
Especially with paid games, this could be handy as not everybody is rich enough to buy all interesting games right away, especially since some of them are pretty pricey, but yet pretty interesting.

But even for free games this would work great. In my case, we all know I'm on mac by now, but I do have a Windows computer, I rarely use, but sometimes I do, and for me it could be nice that if I am on Windows to play those Windows-Only games. With the wishlist I could remember which Windows-Only titles to check out on the rare moments I am on Windows (times that I am at work not counted as I don't think my boss would thank me for downloading and playing games from Game Jolt in the office) 😆

**Comment by hworld** [comment]
You should use a playlist for this! =]

**Comment by Tricky1975** [comment]
Nope! I have an objection against that! Playlists are public! If there is a way to make them UNPUBLIC I'll rest my case!

**Comment by hworld** [comment]
You mean... this one? https://github.com/gamejolt/issue-tracker/issues/206
Mwuahaha!

**Comment by Tricky1975** [comment]
Okay, and then one last thing (I told you I was a jerk)
Playlists don't automatically remove games on the moment I download/purchase them.
