### ISSUE TITLE
Commenting on a game with a "mature" rating will show the mature warning again.

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#695]
I mean it's okay I get it when getting on the game page by browsing the lists, but due to a page reload after placing a comment... I think that goes a bit too far regardless of the settings you have.

**Comment by hworld** [comment]
The page reload is actually a bug. It shouldn't be reloading. Gonna change this to a bug report.

**Comment by Tricky1975** [comment]
This appears to be fixed in the new frontend.
