### ISSUE TITLE
[CILENT] Package downloaded, extracted, opening and CRASH!

### ISSUE THREAD

**Issue by leducthn** [gamejolt/issue-tracker#697]
(This happens on Windows XP.)
The games are not broken but when I open it in the cilent, it's always show some sort of errors. Then, I came to the file directory, run the exe file of the game, and it's run with no problem. My cilent is still fine with browse stuff, download,...

Please help me.

**Comment by YLivay** [comment]
Windows xp is not supported, Im surprised it even installed properly! Anyways, scroll down to the footer and hit the send system report after the client crashes. Well see if its something we can fix

**Comment by leducthn** [comment]
OK, thanks for your support. Coming to gamejolt.com again.

**Comment by YLivay** [comment]
We changed so much with how we launch games since then. Is this still an issue? It might even work on Windows XP now haha

**Comment by leducthn** [comment]
Thanks for your kind support! By the way, I moved to Windows 7 so there's nothing else to worry about now :)

**Comment by leducthn** [comment]
Thanks for your kind support! By the way, I moved to Windows 7 so there's nothing else to worry about now :)

**Comment by YLivay** [comment]
Aha! You upgrade to windows 7 and I downgrade to it. Fun times.
I'm closing this issue anyways since it's not relevant with the new client update we're hatching :P
