### ISSUE TITLE
Flash as downloads work out very strangely.

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#699]
http://gamejolt.com/games/five-nights-at-freddy-s-remembrance/137773

This is a flash game meant to be played on-line, but the dev of this game did decide to make the flash file downloadable so people with a flash player can play it on-line.

The Dev himself says he only gets a blank screen.

On my mac the outcome was even stranger. When I click the download button, I do get the download screen, but in stead of downloading the flash file itself gets activated and my browser (Opera) does not display the game, but I can hear the game's audio. 

The dev uploaded this as Windows, so I cannot test this from the client on my mac.
I do wonder if that blank screen the dev himself got was by means of the client.

[click here of the original forum thread](http://gamejolt.com/f/ok-now-i-have-an-actual-problem-flash-download-issue/23090#forum-post-91423)

**Comment by YLivay** [comment]
SWF files aren't meant to be launched like this. If he wants, he should bundle an executable that embeds it or something that looks for a compatible player on the user's computer.

On my computer for example the flash player is outdated and won't play the game, while on the browser it works.

Not an issue.

**Comment by Tricky1975** [comment]
I do know SWF files are not to be uploaded in this fashion, still you have to admit that what happened to me, is not supposed to happen either. I think the error handling in GJ has failed here, as what happened to me, is pretty odd, and not supposed to happen, even with wrong usage of GJ, you gotta admit that.
