### ISSUE TITLE
Open up cilent, nothing but a black screen

### ISSUE THREAD

**Issue by Jman157** [gamejolt/issue-tracker#700]
I tried to set it up and everything but everytime I open it its just a black screen, please help

**Comment by Tricky1975** [comment]
How much time did you give the client to start up, as sometimes it can require some time to properly start up.

**Comment by Jman157** [comment]
I gave it one or two min and nothing happened, I tried again today and it
came up, I don't know if the server was down or what it was wired

On Jun 2, 2016 6:44 PM, "Jeroen Broks" <notifications@github.com> wrote:
>
> How much time did you give the client to start up, as sometimes it can
require some time to properly start up.

**Comment by YLivay** [comment]
Does it still happen?

**Comment by YLivay** [comment]
Cclosed for inactivity
