### ISSUE TITLE
Sorted by highest rated????

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#702]
![image](https://cloud.githubusercontent.com/assets/11202073/15804626/bdf2df8e-2b0f-11e6-9f29-4f4ff504c396.png)

The screenshot above is the result of searching by tag "#mac". This should be in the order of the highest rated, but this puzzles me. The screenshot clearly shows some UNRATED games in the top row. Is this a bug? Or done on purpose to get them rated as soon as possible? Also the average ratings are close to each other, and then I suppose the game with the most ratings should come first and being the most reliable rating. How exactly is this sorted?

**Comment by YLivay** [comment]
Voltage looks at a global average scores of the games on gj. When there are no scores the sort value is basically that average. The funny bit is that possibly many #mac games are doing no better than the average

**Comment by Tricky1975** [comment]
Ah, yeah I should have taken that in mind. Of course any mac games are not tagged with #mac (only 11 were shown with this tag, while I'm sure we got more games for mac than that), and maybe the mac raters are also few compared to others, who knows :)

Anyway, that clears it up ;)
