### ISSUE TITLE
Chat issue

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#707]
I post this on behalf of Zkrudiz

When he receives messages from his friend, they don't appear
![image](https://cloud.githubusercontent.com/assets/11202073/15905895/fa087c1e-2db6-11e6-8078-39042485af0f.png)

**Comment by YLivay** [comment]
The notifications aren't updated but he receives the messages.
GJ client may some time decide its too fancy for chat and closes the connection without restoring it. Try restarting it and see if it reconnects to the chat properly. Close it through the tray icon.

**Comment by hworld** [comment]
I'm hoping that as we slowly move to angular2 (as it becomes more production ready), we can move chat over first so that it can get the benefit of fixing stuff like this. It could still take months, though. Very big change. =\

**Comment by YLivay** [comment]
Do you know if the messages eventually appeared on client restart?

**Comment by Tricky1975** [comment]
Oh, man this is an old issue. Perhaps you need to contact Zkrudiz yourself since I was only a messenger. 

[This is the thread](http://gamejolt.com/f/i-can-t-see-one-friend-s-messages/23265) on which I decided to post this as an issue.

**Comment by YLivay** [comment]
ohh boy. I'm not necromancing this thread haha. Not only did the chat change from end to end, we know of the existence of a whole new plethora of chat bugs. This one at least should be fixed.
