### ISSUE TITLE
Another user's Games Owned library displays same text as viewing your own

### ISSUE THREAD

**Issue by acidpoison** [gamejolt/issue-tracker#708]
Viewing the paid library of another user that does not own any games displays:

> You don't own any games yet. Go buy some!

![You don't own any games yet. Go buy some!](https://cloud.githubusercontent.com/assets/11214348/15952166/a3aed60c-2e8c-11e6-81b9-bccf34637cfd.png)

Suggest changing the "You" to "This user" or something equivalent and removing the "Go buy some!".

**Comment by YLivay** [comment]
This has been long fixed, sorry for not updating the issue. Thanks for the report!
