### ISSUE TITLE
Marketplace Countries

### ISSUE THREAD

**Issue by shubshub** [gamejolt/issue-tracker#709]
Need to add New Zealand Please
(Also let me Change the country I picked for the Business stuff Because I selected Australia in the mean time)

**Comment by Ucamo** [comment]
I second this, once you choose a country and Businnes Type on the Marketplace Account setup (https://gamejolt.com/dashboard/financials), you can not change it back.

**Comment by Tricky1975** [comment]
Now that we are talking countries. I received a complaint from a Canadian user who is being asked for a TIN code. Since Canada != USA, he (of course) doesn't have one.

**Comment by hworld** [comment]
They would enter whatever their "SSN" type thing is in Canada.

**Comment by YLivay** [comment]
Has this been resolved @hworld ?
