### ISSUE TITLE
Unable to log in from Safari mobile

### ISSUE THREAD

**Issue by loicteixeira** [gamejolt/issue-tracker#718]
Observed with Safari mobile on iOS 9.3.2

If you click *Log In* from any page, you'll be stuck in a loop where the page keep reloading.

**Comment by hworld** [comment]
Do you know if there are any other browsers that do this? Safari on Mac maybe?

**Comment by loicteixeira** [comment]
I wanted to investigate if it was due to some blocker on iOS but without changing anything I can't reproduce the issue anymore. I was travelling so maybe the hotel Wi-Fi router had some weird redirect going or something else changed and it's now working.

Also checked on Safari Mac and this is not happening so I reckon we can close this issue. Sorry for the trouble.

**Comment by hworld** [comment]
Thanks for checking into it!
