### ISSUE TITLE
username / screenname confusion

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#719]
Well if I could post an article on FireSide it would be credited as "@ tricky" (without the space I used in order not to trigger the GitHub MarkDown) since that is my username on game jolt. All my other messages get now credited as "Jeroen P. Broks" which is my current screen name.

This is leading to confusion with the private keys for game content you can appoint to other members, since you need to use the username there to appoint these. Apart from FireSide, these usernames are not shown anywhere on the site, and the first complaint on the forum about stuff not working because a member has a screen name different from his user name, also containing spaces and other "forbidden" characters leading to rejecting the private key appoint request. 

I think that, especially since I guess this use will be expanded more, there should be a way to see usernames more easily.

Maybe the method Twitter uses could work here. 
![image](https://cloud.githubusercontent.com/assets/11202073/16361261/40a2a966-3b8a-11e6-87bf-02bd6f8d74af.png)

**Comment by hworld** [comment]
Yes, we will be slowly shifting to this style of showing names now. We need to prepare for chat as well. And now that key groups for games use username, and adding jam organizers. This will slowly be done. =]

**Comment by YLivay** [comment]
So should we close this issue?

**Comment by Tricky1975** [comment]
Maybe as the main suggestion has been implemented, however, I suggested (in chat) also to make the "@" sign create a link to the account and even go into a notification, similar to how it works here on GitHub when I type @hworld or @YLivay. Maybe it's a good idea to close this after that has been implemented as well?

**Comment by hworld** [comment]
Closing this one since it does make a link for mentions as well. It just doesn't make a notification. I'm not sure yet if I want notifications.

**Comment by Tricky1975** [comment]
Well, maybe when it comes to notifications we might need to make democracy do its work.
Why not ask the users what they want. Can we set up a poll for that?
