### ISSUE TITLE
executable detection inside the uploaded archive appears faulty if the executable is located in a subfolder in stead of the root.

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#721]
I've seen some complaints about this. Using a zip tool is a form of art I suppose. Therefore it often goes wrong and files end up in a subfolder in stead of the root. Then it often happens the .exe detection does not always work (sometimes it does, but often it doesn't) and then we got confused people not knowing what goes wrong.

For now I've only seen this happen on .exe files in Windows. I have no idea how things are in .app bundles on Mac or Linux executables. (Maybe because the Mac zipper is not very likely to make this happen, and I guess Linux users know what they are doing).

**Comment by YLivay** [comment]
This can happen for multiple reasons. The most common one is that if there are too many viable candidates in the same folder. I'm surprised you said it was happening for Windows though, detection should be pretty solid by now. Can you link the archive?

**Comment by Tricky1975** [comment]
Er... that'll be a hard one, the complaints about this are living on the forums somewhere on a page I don't know. This post is about 2 months old by now, and I was just a spokesperson for someone else (as I always use the command line zip myself straight from the right folder I've so far never suffered myself).

**Comment by YLivay** [comment]
Well, we can't do anything without the archive, so i'll be closing this issue for now.
