### ISSUE TITLE
Sound tracks not playing in client (0.7.0) - Mac & Windows

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#722]
Reported to me by a Windows user, but on my Mac it doesn't work either.
When I click the play button nothing happens at all, except for one thing. The "play" icon turns into "stop" icon, and there it ends. When using my browser though (Opera), everything works the way it should.

(I expect this doesn't work on Linux either, but I was not able to confirm that).

**Comment by YLivay** [comment]
Closing in favor of #576
