### ISSUE TITLE
YouTube codes in code blocks show the video

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#723]
We got the "~~~" thingy to make code viewable as code in markdown. However, if I put in youtube codes in these blocks like "{%youtube 2eCAphdQPck %}" the video will show in stead of the code (I had some trouble with this when explaining stuff to a new member). Of course, outside the code block the video should still show, like it does now ;)

**Comment by YLivay** [comment]
Not going to fix this, having to inject our logic in the external parsedown lib we're using isn't healthy and we can definitely live with this side effect haha

**Comment by hworld** [comment]
I'm going to reopen since it is surprising and annoying. Things shouldn't happen in code blocks in my opinion.

**Comment by YLivay** [comment]
But fixing it would mean having to insert ourselves in the parsedown lib. No PR would be accepted for our edge case. We'd have to clone it S:

**Comment by YLivay** [comment]
This is actually a frontend issue not a parsedown issue per se because widgets are passed as is to the frontend. I'll take a look and see how hard it is.

**Comment by hworld** [comment]
I think what we'd have to do when compiling the widgets is figure out if one of their parents is a code block, and if so, don't compile, just turn it into text. It's harder done than said, though
