### ISSUE TITLE
Does not want to connect

### ISSUE THREAD

**Issue by chica-009** [gamejolt/issue-tracker#724]
about a week ago, when i opened the gamejolt client and it said that it has trouble connecting to gamejolt.
Next few days i tried to open gamejolt client and i got the same message.
PS: i was always connected to the internet.
![image](https://cloud.githubusercontent.com/assets/20518850/16917726/ce4fe34e-4cd0-11e6-8d62-25f205a1d31f.png)

**Comment by YLivay** [comment]
Can you try restarting the client?

**Comment by YLivay** [comment]
Closed for inactivity
