### ISSUE TITLE
Multi-language issue

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#726]
Just for testing I put the site to Dutch (which is my native language after all, although I mostly prefer to use any kind of software in English).
And I saw this:

![image](https://cloud.githubusercontent.com/assets/11202073/16978217/25bab830-4e5b-11e6-93c3-cca8dd26d4d0.png)

The footer is indeed in Dutch (side note "krijg het nu" is a very horrible translation. It is a literal translation of "Get it now", but in Dutch this is actually mostly used as an insult. I placed an alternate translation poeditor), but the "this topic is locked" is in English, and the post menu is also in English. The funny part is that I have seen this menu in Dutch, so I do know the menu supports multi-language. I guess the system is not really sure which language to show me.

**Comment by hworld** [comment]
Translations just aren't set for those items. That's why.
