### ISSUE TITLE
comment translator doesn't work at all.

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#727]
I've tried several games. The shot below is from Star Story

![image](https://cloud.githubusercontent.com/assets/11202073/16986529/4ae0aae4-4e87-11e6-959f-eaf5ea433663.png)

As you can see, the comment is still in English, however it should have shown the Dutch translation (as far as Google can translate well) of 1-Up's comment.

=== 

Supplement: It's not that Google itself cannot handle the text as sometimes happen, since this is what happens when I copy-and-paste the text into the google site itself

![image](https://cloud.githubusercontent.com/assets/11202073/16986594/ac46db64-4e87-11e6-8ece-ae1779292f19.png)

**Comment by YLivay** [comment]
Yup, it's borkd

**Comment by hworld** [comment]
This was fixed.
