### ISSUE TITLE
Some translations do not even have English text

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#728]
![image](https://cloud.githubusercontent.com/assets/11202073/17012928/5301dfe2-4f1b-11e6-990f-d73c047cdf32.png)

Hard for me to translate to Dutch if I don't have any original English text, eh?

Also I've done some corrections as I found some HORRIBLE Dutch in the translations, and I've been doing some missing translations (regarding market place for example). So I'd also like to remind you folks to update the translations soon (or at least the Dutch translation).

**Comment by YLivay** [comment]
The correct international translation for "" is "" ;)

**Comment by hworld** [comment]
This is actually an issue. I have to look into it.

**Comment by YLivay** [comment]
Oh? I thought these were the growl messages we don't use anymore.
Does it not pull the translation keys correctly?..

**Comment by Tricky1975** [comment]
> I thought these were the growl messages we don't use anymore.

Couldn't you have said that straight away, in stead of treating me like an idiot? 😝

**Comment by hworld** [comment]
Is this still broken, by the way?

**Comment by Tricky1975** [comment]
I can't find any yet. I shall let you know if I do....

**Comment by hworld** [comment]
Closing since it seems like it may be okay now
