### ISSUE TITLE
GameJolt Client detected as a virus

### ISSUE THREAD

**Issue by CreeperChief** [gamejolt/issue-tracker#729]
My AVG AntiVirus detected the GameJolt Client as a virus.
Is it true or not?
http://imgur.com/a/FKJVL

**Comment by Tricky1975** [comment]
AVG detects anything not known to Microsoft as a virus.
From the moment I saw this in the issue list I *KNEW* you were using AVG before even opening this issue. This is rather an AVG issue than a Game Jolt issue.

Furthermore, viruses are called viruses for a reason. Meaning the virus might already have been living inside your system infecting any random program (could also be the client) in the process.
I've personally lost my trust in AVG and I would rather use a different anti-virus solution, but hey it's your call.

**Comment by YLivay** [comment]
Haha well. It's not a virus, but we can't do anything about the mysterious ways of antiviruses false positives.
