### ISSUE TITLE
Cosmetic: Browsing through screenshots when a game has a lot of them causes the alignment to get out of place.

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#730]
This game has a lot, so here I can demonstrate it well.

This is the first shot (from the left)
![image](https://cloud.githubusercontent.com/assets/11202073/17110407/16d55d02-529d-11e6-8d90-298d91cf14da.png)

And now I'm gonna browse...

This is a very large part on the way near the end.

![image](https://cloud.githubusercontent.com/assets/11202073/17110435/3bcbc15a-529d-11e6-8927-dfd6eac994c0.png)

I get the feeling that if this game had any more, it might even have gone out of the screen borders.

[This is the game tested](http://gamejolt.com/games/left-alone/40551#screenshot-79867), but I think all games with a highload of screenshots suffer like this.

I need to thank slojanko fro bringing this one to my attention in [this forum thread](http://gamejolt.com/f/viewing-images-on-games/29694#forum-post-102510)

**Comment by hworld** [comment]
Old issue that I haven't been able to figure out yet. https://github.com/gamejolt/issue-tracker/issues/515

**Comment by Tricky1975** [comment]
Sorry for this dupe then (the search feature does not always work well) :)
