### ISSUE TITLE
uploading .swf as browser build doesn't auto send/upload. Just sits there.

### ISSUE THREAD

**Issue by MaskofThoro** [gamejolt/issue-tracker#732]
When uploading .swf as browser build, it doesn't auto send/upload. Just sits there. See file below:

"Here is a link to download the package I created when I was trying to force a PLAY button mimicking HTML5 (before realizing the API won't work that way):

http://www.foumartgames.com/feedback/gamejolt/upload_issue/source/ds_download.zip

Do you think it may be the SWF file itself?
It's an encrypted debug version and I'm yet to set up the gamejolt api in the game."

Support ID# 23175

**Comment by YLivay** [comment]
works now
