### ISSUE TITLE
User could not publish game because some required actions were not not, but this user did do those things

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#734]
[Westpol](http://gamejolt.com/profile/westpol/391779) suffering from this:

![](http://hitzinger.org/test/responsive/Help.PNG)

[Original forum thread](gamejolt.com/f/can-t-publish-game/31984)

**Comment by hworld** [comment]
Has to be an old Client. This page isn't in the new site. Gonna close.
