### ISSUE TITLE
Notification page completely bugged

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#735]
![image](https://cloud.githubusercontent.com/assets/11202073/17381828/51cb55b4-59ce-11e6-9328-382ecbb7999e.png)

I wonder what all those notifications where, actually....
Forum posts?

**Comment by hworld** [comment]
Still?

**Comment by Tricky1975** [comment]
Yeah.... still.... Now I see less empty spots, but all forum post notifications are still empty.

**Comment by hworld** [comment]
Fixed!
