### ISSUE TITLE
Can't accept friend request in client

### ISSUE THREAD

**Issue by hworld** [gamejolt/issue-tracker#736]
https://gyazo.com/c81e1cbc5a4375d3a5bc0166ce0d62ba

**Comment by Tricky1975** [comment]
Not only the client suffers here. I could not accept a friend request through the site either (at least not through Opera for Mac).

**Comment by Tricky1975** [comment]
Additional note....
Despite getting an error I got... the friend request I received was still processed as "accepted"...

**Comment by hworld** [comment]
K, this is fixed on site. Will be fixed in client in next build.
