### ISSUE TITLE
There seems to be an issue with e-mails tied to notifications.

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#738]
I cannot replicate this myself (as I turned all e-mail features off), but this one was reported on the forums, and I shall copy it here.

![image](https://cloud.githubusercontent.com/assets/11202073/17456153/f2400f02-5bcd-11e6-8c07-5998e3ccede9.png)

[Original forum thread](http://gamejolt.com/f/just-confirming/32072)

**Comment by hworld** [comment]
Fixed
