### ISSUE TITLE
PRIVATE devlogs PUBLIC

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#740]
Since I have two accounts (one I use for when I'm on Game Jolt in a rather insecure environment so my mod powers are not in danger), I could easily test this out.

I just published a devlog only meant for alpha testers, however with my secondairy account (which has NO ACCESS to this) I could still READ this devlog in full. Luckily it does not contain "too harmful" stuff, but I think this needs to be fixed ASAP, as I fear to other games a lot of secret and sensitive information is now leaked!

P.S. This bug does not affect the releases.

**Comment by YLivay** [comment]
on it, seems weird because the funcitonality should be 1:1 with what game news was.

**Comment by YLivay** [comment]
Should be fixed in a few minutes!
