### ISSUE TITLE
Client goes white when accepting/denying a friend request

### ISSUE THREAD

**Issue by PhotonicPizza** [gamejolt/issue-tracker#742]
Basically what the title says. When I try to accept or deny any friend request, the whole client goes white. No UI, nothing, requiring a restart. Lowering to system tray doesn't fix the issue, nor does switching to Dashboard/Library/etc. The request still gets accepted/denied, however, so the action is registered.

It seems to be tied to the recent graphic overhaul of the chat system, since I didn't have this issue before.

**Comment by YLivay** [comment]
That is weird, it seems like its actually doing a full reload of the client for some reason.
We're currently in the middle of upgrading nwjs to a hopefully more stable version but it's a horror show getting to work properly. Will have to debug this after we update.

**Comment by hworld** [comment]
Oh yeah, this was fixed in latest client: 0.8.2
