### ISSUE TITLE
Avatar looks different depending on browser

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#744]
On Opera my avatar looks like this:
![image](https://cloud.githubusercontent.com/assets/11202073/17545396/15dead4e-5edd-11e6-9cac-4e5fbd229793.png)

(which is also how it is supposed to look).

In Firefox my avatar looks like this:
![image](https://cloud.githubusercontent.com/assets/11202073/17545413/2b97c08a-5edd-11e6-8731-29af06763d9b.png)

I just ran Firefox to investigate #739 and I ran into this one, funny eh?

**Comment by hworld** [comment]
I tested on firefox and this didn't happen. Which version you on?

**Comment by Tricky1975** [comment]
![image](https://cloud.githubusercontent.com/assets/11202073/17559615/27fa725a-5f1f-11e6-8ec5-8b0a330c5fca.png)

But as you can see, FireFox started updating immediately, so let's see what happens after the update.

After the update still no good:
![image](https://cloud.githubusercontent.com/assets/11202073/17559721/839d0320-5f1f-11e6-8a0f-230ae320ab6c.png)

But a nice detail is this, look at my avatar in the upper right corner. There it DOES look the way it should.

**Comment by Tricky1975** [comment]
Oh wait... It just started updating again.... How far behind am I?

**Comment by Tricky1975** [comment]
Okay.... and now it works in Firefox the way it should...
Okay, sorry for bothering you, I know know that everybody who sees only the eyes of my "alien girl" just has an outdated version....
