### ISSUE TITLE
Spelling error (private key section)

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#745]
![image](https://cloud.githubusercontent.com/assets/11202073/17617732/fe5b3584-607b-11e6-8a5b-8ced71c99894.png)

Of course English is not my mother's tongue and I hate to be a grammar nazi, but still I think "a usernames" is incorrect English.

**Comment by hworld** [comment]
Hahaha, yes. Sadly, there are a lot of cases like this on the site and at the moment it's just too hard for me to fix them all. Gonna close it out, even though it breaks my heart.
