### ISSUE TITLE
Filter for either status options (Complete/Stable & Early Access) do not remove the respective types of games from the listings

### ISSUE THREAD

**Issue by Honno** [gamejolt/issue-tracker#746]
^ Title. If you go on the game listings (Featured, Best, Hot, New), the game development status options have no effect on what you see.

**Comment by YLivay** [comment]
Yup, devlogs broke it.

**Comment by hworld** [comment]
Damn devlogs

**Comment by YLivay** [comment]
Honno sorry for the long response. It's not that we don't think the issue is unimportant, it's just that I want to piss you off personally >:D

In other news, this has been resolved.

**Comment by hworld** [comment]
funny we totally forgot about this and then it came up again and then we fixed it and forgot we knew about it
