### ISSUE TITLE
Circular link bug

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#747]
[This post by Jani Nykänen](http://gamejolt.com/x/permalink/forum-post/110555) contains a link referring to the thread the post was posted in. Clicking it ones or twice results into a 404, while the link itself refers to an existing page. Pressing the "renew" button will also "fix" this.

**Comment by YLivay** [comment]
Can you link the problematic post?

**Comment by Tricky1975** [comment]
I already did. The first 5 words of my original post form the link

**Comment by YLivay** [comment]
That's your domain @hworld haha

**Comment by hworld** [comment]
Ah, this is a weird one. It's actually because the link shouldn't be controlled by angular, but angular grabs it thinking it should handle it since it's the same domain. Gotta do a hack I think

**Comment by Tricky1975** [comment]
Yup... I think this bug also causes #640 to happen

**Comment by Tricky1975** [comment]
The new frontend does not have this issue
