### ISSUE TITLE
If url is shared it exposes users game token [bug]

### ISSUE THREAD

**Issue by 1UpNuke** [gamejolt/issue-tracker#748]
So if you play an HTML5 game and press "only show this frame"
 (I myself use this trick to play "fullscreen")
You get an url, now I thought it would be handy to share this link for a fullscreen version, but it contains 2 things 
1. the users who did it username (no biggie)
and 
2. the users game token
You CAN just remove this info and the link will still work fine, but this should be fixed for the unfortunate users who might accidentally share their token.

Example of safe link: http://d-triforce.gamejolt.net/data/games/2/126/169376/files/57b71afee70e0/index.html

Example of unsafe link: http://d-triforce.gamejolt.net/data/games/2/126/169376/files/57b71afee70e0/index.html?gjapi_username=[USERNAME]&gjapi_token=[TOKEN]

note: instead of [USERNAME] and [TOKEN] the second link will actually have those in the places of them

**Comment by YLivay** [comment]
You shouldn't share that url in the first place though. It's to be used on gamejolt domain. You can remove the gjapi_* params manaually and it'll work (just not auto log you in to the game) BUT you should still never share this link directly.
