### ISSUE TITLE
When uploading an image to devlogs with # it will not work

### ISSUE THREAD

**Issue by JeFawk** [gamejolt/issue-tracker#749]
Tried uploading this DevLog#2_Featured_BlurryEdges.png, 224 KB. It was showing as a broken image.

**Comment by YLivay** [comment]
can you attach the actual image? upload it to dropbox or something and we'll check it out

**Comment by YLivay** [comment]
I think its an issue with our file storage name limitation. Should we block it or rename it automatically? @hworld

**Comment by hworld** [comment]
We should rename. No reason not to in this case.

**Comment by YLivay** [comment]
Forgot to update this issue. It's been long resolved :)
