### ISSUE TITLE
Trying to edit account on phone results in a refreshing loop...

### ISSUE THREAD

**Issue by 1UpNuke** [gamejolt/issue-tracker#750]
Yeah, got the idea to edit my account on my phone, but when I try it it starts refreshing over and over before the page even loads fully.

**Comment by YLivay** [comment]
Which browser on which device was this happening?

**Comment by hworld** [comment]
There used to be an infinite redirect loop, but I've fixed that a week or so ago. At most it should only refresh the site once now. That's because it needs to change the protocol to HTTPS.

**Comment by 1UpNuke** [comment]
It is now fixed for me, also it was on a Nexus 5 running android 6.0.1, and the browser was chrome.
