### ISSUE TITLE
Handle password protected archives

### ISSUE THREAD

**Issue by YLivay** [gamejolt/issue-tracker#754]
We need to be able to handle password protected archive by either:
1. Specifying the password for password protected archives so we could unpack them properly.
2. Treating the archives as standalone files.

There are some legitimate uses for password protected archives uploading, such as FPS Creator map files (.fpm) which are basically password protected archives, so we shouldn't just block users from uploading them.

Which option should we go for?

**Comment by hworld** [comment]
"Other" type for build when we detect that it's password protected.
We can automatically toggle to Other during the upload, and we can force them to not be able to change it. is there a way to detect in all cases if the file is password protected?

**Comment by YLivay** [comment]
We should be able to figure out if an archive is password protected simply by trying first without a password. All the funcs we use throw errors into console saying its a wrong password. Then if we're not given any we could force to other type.

What about password protected archives that have a virus in em tho?
Maybe the best thing is to just reject password protected archives when password isn't specified? We could whitelist that check to just the file extensions we're expecting to match the archive type.

**Comment by Tricky1975** [comment]
Forcing to go "other" sounds good to me, but I agree with @YLivay that this can be used as an easy way to upload viruses and the staff never be able to check it. I think that indeed we should block password protected archives for this reason or at least require them to enter the password while uploading.

**Comment by YLivay** [comment]
Well then. After some research its hard to tell if an archive is encrypted in some cases - so it would have to get to the processing phase when it attempts to extract it to finally know if the file's valid or not. Currently it is not possible to raise errors from the processing phase back to the user so the builds will be seemingly stuck in processing.

Support for password protected archives IS done tho, so i'm closing this and will continue updating in issue #761 about the error reporting.
