### ISSUE TITLE
Neither me or my games can be found trough the search function!

### ISSUE THREAD

**Issue by 1UpNuke** [gamejolt/issue-tracker#755]
Help me I wanna just tell my friends to search for me on gamejolt and not have to dig up a link every time :(
I also wan't my games to have atleast some light

**Comment by Tricky1975** [comment]
No?

![image](https://cloud.githubusercontent.com/assets/11202073/17981375/bf0099d2-6b03-11e6-9ead-e5f7614efa52.png)

**Comment by 1UpNuke** [comment]
This issue can be closed as Jeroen told me that using "-" in a search is used to exclude content. So I only need to search "1 up nuke" instead
