### ISSUE TITLE
Post count gone?

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#756]
Look at Jani's post count:

![image](https://cloud.githubusercontent.com/assets/11202073/17981059/51b4fad6-6b02-11e6-8df5-f166296547d3.png)

The odd part is... that as you can see, mine shows, Jani's doesn't, but in some other threads Jani's Post Count DOES show.... Any idea why this happens?

**Comment by YLivay** [comment]
Can you link a thread where it shows and a thread where it doesnt?
I think I know why that happens, I just need  to confirm.

**Comment by Tricky1975** [comment]
That was the [Cool Random Facts](http://gamejolt.com/f/cool-random-facts/191?page=76#forum-post-119985), thread, but I've also seen it with my own posts in different threads. It looks quite random, but it always happens with the same posts.

**Comment by YLivay** [comment]
Yeah confirmed, this happens for users in replies that are not authors of the root posts of the page you're viewing. They get loaded in too late so their counts aren't being fetched.

**Comment by hworld** [comment]
i actually got rid of post counts in new design. it was too hard pulling and keeping updated. not too performant

**Comment by Tricky1975** [comment]
Oh, so nobody can see anymore I posted over 13k messages anymore :(
