### ISSUE TITLE
DevLog of a different game shown in client

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#760]
![image](https://cloud.githubusercontent.com/assets/11202073/18068794/7b146346-6e43-11e6-9e36-7b4d6d3a06b5.png)

The purple guy is Yirl. A playable character in my game Star Story. The DevLog however is of "ThinkToDie". In other words, the DevLog shown here, does not belong to the game that is on the page.

I found out when I used to client to see if it would properly update my game after uploading an update of it, and the client was then on ThinkToDie and I used a search request to get to Star Story. Maybe the linking system (which also causes the forum to suffer with #747 and #640) is responsible for this, or is that just a dumb thing to say?

I discovered this in the client, I was not yet able to check if the actual website suffers as well.

(Addition. Clicking the "DevLog" button, does get the to the correct DevLog page)

**Comment by YLivay** [comment]
This should be resolved in the new frontend :)
