### ISSUE TITLE
Need a way to  report errors back to the user from build processing.

### ISSUE THREAD

**Issue by YLivay** [gamejolt/issue-tracker#761]
Currently if the build fails the build will seemingly just continue processing forever. We have to raise an error in cases where it is due. E.g. encountering a password protected archive.

**Comment by Tricky1975** [comment]
Perhaps a "time-out" error could also do a great deal for uploads that stuck the queue, in order to make sure that uploads sticking the process queue won't cause other people to suffer.

Just an idea. I'm the one who receives the complaints when upload processing takes forever 😝

**Comment by YLivay** [comment]
We still need that desparately, and don't yet have a solid plan on how best to surface these issues. Commenting to bump this up

**Comment by YLivay** [comment]
This is done finally

**Comment by Tricky1975** [comment]
REALLY!? And what will happen? An error box on screen? A growl? Both?
