### ISSUE TITLE
"Internal Server Error" on last page new games.

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#762]
[First click this link](http://gamejolt.com/games/new?os=windows&status=complete,wip)

This link will work perfectly, however scroll down and click "Last" and it will result into an internal server error.

**Comment by YLivay** [comment]
confirmed

**Comment by YLivay** [comment]
We already set a limit on the pagination itself. The issue was result set index being too high. We have a different issue regarding pagination atm but its a separate thing and has it's own issue already, so i'm closing this for now.
