### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#765]
The reason I'm posting this is actually to get a more open view what the plans for the tags will be.

Of course some tags will now direct to channels, like #fnaf, #VR, #analog and #fangame. But other tags are a bit in the dark here.

When trying to search on a certain tag, the quickest (and not really elegant) way to do this is by going to a comment, or devlog or forum post feature type the #tag, click on the preview tab and click it, but I think a simpler more elegant solution is in order by now (as I do not think everybody is clever enough to come up with that 'dirty' method).

What would at least be nice to have is a page showing:
- All tags ever used (maybe the ones only used in hidden/deleted games should not show)
- The 100 tags most used by devs to tag their games
- The 100 tags most used by gamers to find a game

And maybe a sorter to sort them by alphabet or most used.

What exactly are any other possible plans?

**Comment by YLivay** [comment]
We have some awesome plans for the tags. It's already on our list, so after we're done with it (hopefully in a few months when we have time to execute them  finally) feel free to reopen the issue if its still relevant :)

**Comment by Tricky1975** [comment]
If you are talking to me when it comes to "feel free to reopen", I can only reopen issues I closed myself (and I can only close issues I created myself) (unless the issues are posted on my own repositories)
