### ISSUE TITLE
It does not seem possible to remove pictures uploaded to description features

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#766]
This basically affects Game Descriptions and Text Based Devlogs.
You can upload images to them, and use MarkDown to show them, but you cannot remove them, only remove the MarkDown tags in order to not show, them, but people who got the URL can then still access them. I think people should be able to remove the pictures completely (and I do even think copyright laws obligate this also, as people always have the right to retract hosting rights over the stuff they own copyrights over).

**Comment by YLivay** [comment]
Still relevant and a good suggestion. Added to my todo list, thanks!

**Comment by Tricky1975** [comment]
> Pester me about it if you want :P

You know I will, Fern. You know I will 👅
