### ISSUE TITLE
Troyan...?

### ISSUE THREAD

**Issue by NYANCAT996** [gamejolt/issue-tracker#767]
> **_Your antivirus has been detected a troyan??_**
> When i install the client, and i open it, i have to desinstall it becose the antivirus remove the executable, and i cannot enter the client and its so frustant 
> 
> Yes, sorry for my english XD

**Comment by Tricky1975** [comment]
Which anti-virus software do you have? AVG?

**Comment by YLivay** [comment]
not enough info, issue is abandoned..
As for anti viruses, we guarantee the client itself doesn't have any viruses - any detection is just some bs false positive.
