### ISSUE TITLE
@<username> is buggy when the username contains a "-" character

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#768]
The screenshot below shows this with Jani's username with is jani-nykanen.

![image](https://cloud.githubusercontent.com/assets/11202073/18636124/f63a1d3c-7e87-11e6-8ba1-9ff0c21b19c6.png)

Only "jani" is accepted "-nykanen" is not. This creates a link in which only "jani" is a link, and clicking Jani's name in the link I demonstrated here, also leads to a 404.

**Comment by YLivay** [comment]
The username should never contain a '-' character. We have a script ready to fix bad usernames but we haven't deployed it yet. I'm closing this issue for now.
