### ISSUE TITLE
Perhaps code blocks should ignore tags and "at" references

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#770]
![image](https://cloud.githubusercontent.com/assets/11202073/18904051/8b1993d0-855c-11e6-9307-5638f10bdbb0.png)

This is a code block in which I demonstrate the scenario-"language" I used for my game Star Story. And what do we see? A lot of "false" user references (I even doubt these users exist), and also a lot of "false tags". Well the latter in particular can be very nasty for C/C++-coders due to the "#include" commands being turned into hashes as well. Now I can see the backslashes placed in front of all "#" prefixed lines, meaning the "#" should be ignored, but I have the feeling it doesn't work so well.

**Comment by YLivay** [comment]
We're not going to fork parsedown for this, sorry S:
It may have specific language syntax using ```lang in the beginning but we're not planning on fiddling with this atm.
