### ISSUE TITLE
Invalid "word-breaking" in chat

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#771]
![image](https://cloud.githubusercontent.com/assets/11202073/19198336/e6d3e8c4-8cbe-11e6-856a-7d1979547964.png)

The shot above shows what I mean. The content is not important. This was just what I answered long ago when somebody had a problem with the Market Place, which has already been solved by now. You can see the word "site" being broken off incorrectly with "sit" on line 1 and "e" on line 2, with no break-mark or anything. (Now English is not my native language, but is the word "site" allowed to be broken at the end of the line, anyway?) 
Now this is just one occurrence, but I see this happening countless times in chat (better shots I can make contain (unfortunately) too much stuff I want to keep secret as most PM I have now are due to my status as a moderator, like internal chat with fellow moderator Jani or people discussing a mute with me (to which I mostly say I cannot help on mutes)).

**Comment by YLivay** [comment]
Not fixing this. We prefer having this instead of completely breaking the chat with long links and unbreakable things for mobile users. CSS sucks.
