### ISSUE TITLE
Client won't open

### ISSUE THREAD

**Issue by Faceimoo** [gamejolt/issue-tracker#773]
The client won't open when I click on it. awaiting-feedback

**Comment by Tricky1975** [comment]
1. Does nothing happen at all?
2. Or do you get a grey screen saying JSNW?
3. Which OS are you using?

These are very important questions that need answering before any feedback can be given and (in case of a bug) the devs can even start looking for the “evil” that causes this.

**Comment by jtrent238** [comment]
lol once I found this it started working! :laughing:

**Comment by YLivay** [comment]
closed for inactivity.
