### ISSUE TITLE
Unable to use dropdown menus in scoreboard view

### ISSUE THREAD

**Issue by nilllzz** [gamejolt/issue-tracker#775]
![gamejolt1](https://cloud.githubusercontent.com/assets/2119926/19909312/62de14fe-a087-11e6-9559-1026a69aa10e.png)

The circled buttons would open a dropdown menu with more options for the score entry, but when I try to click on them, I get redirected to the score display page as if I would have clicked on the score entry underneath the button. Therefore, it's not possible to use the dropdown menu.

Tested in Firefox and Edge on Windows 10.

**Comment by YLivay** [comment]
I can't see the image anymore but everything seems to be working.

**Comment by nilllzz** [comment]
Yeah, ever since the revamp of the score display, the buttons don't exist anymore, and the associated actions are now present in submenus.
