### ISSUE TITLE
Game Api batch request: Invalid Json in response

### ISSUE THREAD

**Issue by nilllzz** [gamejolt/issue-tracker#776]
For batch requests, one has to have a valid signature for each of the requests in the batch. However, when one puts requests with invalid signatures in a batch call and then generates a valid signature for the entire batch request, this gets returned:
![gamejolt2](https://cloud.githubusercontent.com/assets/2119926/19909463/252094d8-a088-11e6-9bed-6e33ff8078d2.png)
As you can see, the responses for the invalid signatures for each request in the batch gets returned outside the main json object. And because json allows only one root object, this is invalid json syntax.

This is what the output should look like:
![gamejolt3](https://cloud.githubusercontent.com/assets/2119926/19909496/50094f14-a088-11e6-842a-c19c52609b72.png)

**Comment by YLivay** [comment]
How are you forming the signature for batch requests?

**Comment by nilllzz** [comment]
What do you mean exactly?
For this example, I purposely generated incorrect signatures for the requests inside the batch request.

**Comment by YLivay** [comment]
Fix it yourself pleb.

**Comment by YLivay** [comment]
LOOOOL

**Comment by YLivay** [comment]
By the way, it might just be fixed in 1.2 already, I don't remember but I redid how signature checking works. It also includes post parameters.

**Comment by YLivay** [comment]
solved in 1.2
