### ISSUE TITLE
Can't play some games that needs to be extracted.

### ISSUE THREAD

**Issue by ElectricDash** [gamejolt/issue-tracker#777]

**Comment by YLivay** [comment]
More info would be nice. Which games, what exactly is happening, which OS, did you send a system report?

**Comment by ElectricDash** [comment]
For example. "The YouTube Poop World"
Every time I start the game, it needs to be extracted. After extracting the game, it closes, and if I launch it again, it needs to be extracted again.

OS: Windows 10 Pro (64-Bit)

No, I did not send a system report

**Comment by YLivay** [comment]
Scroll down to the footer right after this happens and theres a small text saying "Send system report" Hit it and link this issue. We'll see whats going on with this.

**Comment by YLivay** [comment]
Sorry for not updating in the issue, this should've been long fixed with the new client versions :)
