### ISSUE TITLE
Can't install or abort installation for builds whose path does not exist.

### ISSUE THREAD

**Issue by YLivay** [gamejolt/issue-tracker#779]
Client stuck at preparing fs stage.

**Comment by Lasersiborg** [comment]
I'm also having this issue... Had any luck finding out how to remove them?

**Comment by Lasersiborg** [comment]
So, when I opened my GameJolt Client I saw I only had 2 downloads in there. I was confused so I clicked it. Turns out it managed to install four of the games that wouldn't download. Still I have no clue what caused it, but there are still downloads that are queued.

**Comment by hworld** [comment]
is this fixed @YLivay ?

**Comment by YLivay** [comment]
Yup. sheesh sorry for not responding sooner S:
