### ISSUE TITLE
English forum rules still speak of "news section" in stead of "Devlogs"

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#782]
![image](https://cloud.githubusercontent.com/assets/11202073/20221280/0291dff2-a831-11e6-8adb-10422a52544b.png)

As you can see, I already put "DevLog" in the Dutch translation :)

**Comment by Ayenko1980** [comment]
This is a full o Full of lei

**Comment by Tricky1975** [comment]
@Ayenko1980 ![](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTZABMKb4Ro6d3J9TwkNhh7N-8dhthhVftyeSBqRN9Zsm6sxrvO)

**Comment by YLivay** [comment]
Done, need to repull translations next time we submit and it'll work. Nice catch.

**Comment by Tricky1975** [comment]
Lemme know when I can update the Dutch translations, since they are outdated, so I noticed.
