### ISSUE TITLE
GameJolt Client for some reason turns into NW.JS

### ISSUE THREAD

**Issue by Scizor32** [gamejolt/issue-tracker#783]
For some reason when I start the GameJolt after not having used it in a while it turn into to something called node webkit (i'm sure of the specific program name seeing as I has just re-installed the client to fix this glitch) and displays a webpage NW:blank (which you can't find by searching in the search bar, i have already tried) that displays ,in very large font that glints occasionally, the letters NW.JS and if you search this up on the internet it shows a website https://nwjs.io/. I don't know if any of the extra information helped but I hope this gets fixed soon because it is very inconvenient to re-install the client just to play a game.

**Comment by Tricky1975** [comment]
This is a very well-known issue.
Sometimes the data the installer writes gets corrupted somehow, and it's not really known what causes this. Re-installing (mostly with re-downloading)  works.

I assume you are a Windows user (I've never had this issue on my Mac).
I wouldn't be surprised if there are actually more issues like these on this issue tracker.

**Comment by YLivay** [comment]
We've been working on a new updater for the client and to migrate the client to Vue along with the rest of the site for the past half a year or so. Just updating here that we're getting really close. The working branch for it is https://github.com/gamejolt/gamejolt/tree/client-vue

I'm closing this issue for now, if the problem persists after this is released we'll reopen
