### ISSUE TITLE
Community request: Poll feature in Devlogs

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#788]
Hey, I'm just passing on a message made by the community. This is not my idea.

AngelWire posted this on the forums:

> I've been using the devlog for a while now and I really love how it allows me to communicate directly with my followers. But for me, the communication has been largely one way. I'd love to be able to add a poll to a devlog post in order to quickly and easily get feedback from followers.

And the suggestion did get some support from the community, and thus I decided to pass it on here so you guys WILL see it ;)

([Original Forum Thread](http://gamejolt.com/f/creating-polls-in-the-devlog/209120))

**Comment by hworld** [comment]
hehe, @YLivay has been asking for this since before we even put out devlogs

**Comment by YLivay** [comment]
I'll probably forget to close this issue when we actually roll out polls - but we're definitely going to have those hahah. Closing this  issue then, and consider it done sometime in the hopefully near future.
