### ISSUE TITLE
Suggestion: Add the option to turn off tags and "at" references.

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#790]
I already noted this in #770, but Fernando closed it shamelessly neglecting the fact that this is a CODERS COMMUNITY!!! Being able to post stuff containing @ and # without being bothered with the system picking this up for its own use is ABSOLUTELY essential, and the fact this this is not possible now is very unbecoming for a forum like this. I mean if Game Jolt was a site about housing and taking care of ponies, or about model making, or about tailoring, this wouldn't be an issue, but since we are talking about a community about coding, scripting an other kinds of programming this issue is really not acceptable, sorry!

I do understand that bugging with existing code (in this case ParseDown, with which I also experimented myself), can be quite a chore, so that's why I am suggesting this "compromise" suggestion.

![image](https://cloud.githubusercontent.com/assets/11202073/21260565/d21e1446-c386-11e6-858a-c4f682b048de.png)

Above we see an example in Lua and we see what happens due to the tagging system while this post was actually meant to be "tagless".
C and C++ can be even worse:
~~~C++
#include "myheader1.h"
#include "myheader2.h"
#include "myheader3.h"

#ifndef mycode
// ...
#endif
// and so on
~~~

The solution can be so simple. If you add a checkbox to the forums and maybe also to fireside blogs (and thus also Devlogs as I believe they are also taken up as FireSide blogs) saying "ignore tags and user references", and thus allowing the system to still use MarkDown, but ignore all stuff Game Jolt uses, posts about code (like in the screenshot).
For comments (and maybe also chat) this may be less needed as code blocks are rarely used there.
Especially the #coding channel on the forums can benefit A LOT from this.

And with these features you DON’T have to modify ParseDown. Happy now?

**Comment by hworld** [comment]
ah, I think within code tags we really have to not do that... hmmmm. I wonder how hard this is.

**Comment by Tricky1975** [comment]
Thank you!!! :)

**Comment by YLivay** [comment]
Pretty hard, considering we still haven't done it. I really can't think we can prioritize this any time soon.

**Comment by Tricky1975** [comment]
Well maybe @YLivay an alternate idea is to turn # and @ off completely by checking a box at the forum posts/replies. A checkbox to turn off MarkDown can also work (of course it's recommendable if turning off MarkDown, will not allow HTML tags).

**Comment by YLivay** [comment]
This will be fixed in the next push. I found a really hacky yet effective way to do it.

**Comment by YLivay** [comment]
fixed

**Comment by Tricky1975** [comment]
# WONDERFUL! :)
