### ISSUE TITLE
Left side menu glitch, devlog page comments bug and top menu pop-ups bug.

### ISSUE THREAD

**Issue by MikeyVah** [gamejolt/issue-tracker#792]
The new left side menu is glitchy when used in small windows.
You have to be lightning fast to reach the pop-up menu because of the scrollbar.

GIF:

![left-menu-glitch](https://cloud.githubusercontent.com/assets/24921803/21654445/3407c8b4-d2be-11e6-93b1-504f6af77410.gif)

Another glitch I encountered is about the Devlog pages comments preview section.
If you are fast enough to surf through those, you can get blank windows and/or perma-open windows.

GIF:

![devlog-comments-bug](https://cloud.githubusercontent.com/assets/24921803/21654561/a9551cb6-d2be-11e6-9a4c-12d6be796961.gif)

Another glitch and the last I have encountered is about the top bar pop-up windows.
If you click your profile picture or the friend request tab, they sometimes don't work and/or close themselves automatically.

GIF:

![top-bar-popups-glitch](https://cloud.githubusercontent.com/assets/24921803/21654625/0497f2b0-d2bf-11e6-97b1-5a4154c77a53.gif)

**Comment by YLivay** [comment]
The gifs don't work but the new frontend should've fixed all of those issues (and created new ones haha)
