### ISSUE TITLE
clipping error when you scroll all the way down

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#794]
Thanks to EgniPak to bring this to my attention:

![](http://i.imgur.com/tCjCA6k.png)

Hard to see, but you can see it in the right bottom of this shot.

**Comment by hworld** [comment]
this should be fixed

**Comment by Tricky1975** [comment]
Confirmed... That was quick ;)

**Comment by Ayenko1980** [comment]
Or
