### ISSUE TITLE
Minimizing browser game resets it

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#795]
Well, let's have the one who complained about this to Jani and me explain it himself... ;)

[![image](https://cloud.githubusercontent.com/assets/11202073/21741760/85bd62da-d4e0-11e6-925e-af11e23ee2b0.png)](http://gamejolt.com/f/a-little-bitty-problem/216429#forum-post-298226)

I turned the image into a link to the actual forum thread ;)

**Comment by hworld** [comment]
Fixed
