### ISSUE TITLE
Hi, I use a chromebook

### ISSUE THREAD

**Issue by beberro** [gamejolt/issue-tracker#796]
no pondria unitale para chromebook? les agradeceria mucho esque veo que no esta para chromebook gracias por leer este comentario

**Comment by Tricky1975** [comment]
In case it interests you. Google translate came up with this translation

>Would not unitale for chromebook? Thank you very much I see that you are not for chromebook thanks for reading this comment


Does not really help me understand it, though...

**Comment by hworld** [comment]
Gonna close. Have a feeling it's related to downloading/playing a undertale fangame.
