### ISSUE TITLE
Stuck on gravator

### ISSUE THREAD

**Issue by xXxYoloMaster21xXx** [gamejolt/issue-tracker#797]
I opened gravator in gamejolt client to change my avator so i changed and then i tryed to go back but i cant i cant do anything plz help i cant do anything i want to go back to gamejolt :(

**Comment by Tricky1975** [comment]
This is a known bug. Already reported countless times before.
All you can do until it’s fixed is shut down the client completely and restart it.

**Comment by YLivay** [comment]
New avatars, new frontend. Nothing in the old code relating to this issue has survived the past few months haha. This should be fixed :)
