### ISSUE TITLE
Trouble with username characters on login.

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#800]
I received this complaint and I shall quote it below.

=== Original message ===

recently my friend tried to log into his GJ account. it's called "H.Studios" he enters the name and it has an issue

![alt text](http://i.imgur.com/LHVczAJ.png)

it says that he can only use letters, numbers, underscores, and hyphens. he cannot access his account and i've tried this with my username and it doesn't work either. yet both usernames use only what gamejolt requires us to use. and neither of our accounts are locked out. he still receives notifications via Email though.

if you could help it would be much appreciated.
thanks

=== End original message ===

I've already told this guy to send a mail to contact@gamejolt.com, and once he's wise enough to do so I guess this specific case lies in Yaprak's hands. But that doesn't change the fact that this could happen and that we're speaking of a bug here, so I guess this is something to look at.

**Comment by YLivay** [comment]
This is already fixed, and users whose usernames had to be changed were emailed with their new login  details
