### ISSUE TITLE
Dashboard gone

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#802]
![image](https://cloud.githubusercontent.com/assets/11202073/22743733/696f26e6-ee1b-11e6-9489-d857c3b6c806.png)

**Comment by hworld** [comment]
Would you be able to pull the console log? I'm sure it will contain more
info

**Comment by Tricky1975** [comment]
I could try in Firefox….

**Comment by hworld** [comment]
Should be fixed now
