### ISSUE TITLE
Several games reported download => 404

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#803]
I get several reports of trying to download games resulting into a 404.

[This forum thread](http://gamejolt.com/f/having-trouble-downloading-games/230234) contains several games being listed as giving 404 when trying to download.

**Comment by hworld** [comment]
Fixed! It was related to a change that I did to fix a performance issue in the new angular router version we're using. It ruined the download page, though, so I rolled it back.

**Comment by Tricky1975** [comment]
Not to be a jerk or anything, but threads complaining about being unable to download are popping up on the forum like wheat.
