### ISSUE TITLE
Images not displayed in Linux client

### ISSUE THREAD

**Issue by CyberKiller40** [gamejolt/issue-tracker#806]
Regression in v0.10.4 on OpenSUSE 42.2, though I'm not sure if this happened in this version, because I reinstalled my OS recently.

What happens: all game logo images are not displayed, this also affects screenshots, header images, images in activity stream, dashboard, etc. However the jam banner on the main page works ok. The terminal throws numerous errors like this:
`[3737:0210/171654:WARNING:nss_ssl_util.cc(374)] Unknown SSL error -12218 (SSL_ERROR_ENCRYPTION_FAILURE) mapped to net::ERR_SSL_PROTOCOL_ERROR`

openssl version: OpenSSL 1.0.2j-fips  26 Sep 2016

**Comment by Tricky1975** [comment]
Not just a Linux issue...
![image](https://cloud.githubusercontent.com/assets/11202073/22908261/c2927d64-f24d-11e6-87a3-b1017c6f6be4.png)
As you can see, I've the same problem on Mac, and although not checked, but I expect Windows users to suffer as well.

There are many problems with the client at this moment, and it is in the works, and that is all I know.

**Comment by CyberKiller40** [comment]
Good to know, however it works ok on windows for me.

**Comment by Tricky1975** [comment]
Maybe you should check the version of your client in both Linux and Windows, as some time after I posted that I saw the client update a newer version of itself fixing this issue on my Mac. 
Anyway, I do know that the client is being revised for large parts (and that Fernando is rewriting loads of stuff of it in Go), and that no new versions of the client will be pushed until everything has been properly taken care of. And like I said, that's allI know :)

**Comment by YLivay** [comment]
The eclient is actually horribly outdated because we haven't been able to push an update to it because it requires an update to nwjs itself which requires a full update. I've been working on a new updater that will be used by both the client and the games on and off for the past 2 months. Sadly many other issues kept getting in the way. This is due to the changes we have with moving the site to https.

**Comment by CyberKiller40** [comment]
I found that I have the same version of the client on windows and linux. It seems it could be tied to that openssl errors I see in the terminal.

**Comment by mason1920** [comment]
It's only a problem with Unix-Like OS, I hope they fix it soon.

**Comment by CyberKiller40** [comment]
2 months passed, the issue still exists. v0.11.1

**Comment by CyberKiller40** [comment]
I noticed a strange thing, recently I installed a fresh OpenSUSE on another machine, the same version that I use on my main workstation. On the new system, the images problem doesn't exist in GJ Client. So possibly this is somehow connected to other things that I have installed on my system.

I would need some help debugging this, cause openssl and other crypto libs are the same on both machines.

**Comment by CyberKiller40** [comment]
Client version 0.12.2, OpenSUSE 42.3, looks like the issue is gone.

**Comment by Tricky1975** [comment]
Lemme check that on mac:

![image](https://user-images.githubusercontent.com/11202073/29493969-f79e346c-85a0-11e7-8ee5-807873e9f209.png)

Yup, appears gone here too..

(client v0.12.2 -- Mac -- Sierra - 10.12.6)

![image](https://user-images.githubusercontent.com/11202073/29493984-32dde4c8-85a1-11e7-8a2a-fc538f164e89.png)

**Comment by YLivay** [comment]
Yeah sorry for not updating in the issue. We've managed to get a somewhat more updated version of the client out finally. Native node modules are HORRIBLE.
Thanks for the help guys :)
