### ISSUE TITLE
my chat wont work, fix immediately!!

### ISSUE THREAD

**Issue by djjde12** [gamejolt/issue-tracker#807]
i'm on mac and neither my client nor the website will let me chat.

please help!!!

**Comment by Tricky1975** [comment]
Please lower you tone, immediately...
I understand you're desperate, but the admins are under enough pressure the way already are 😛

**Comment by djjde12** [comment]
i apologize
A: i was taking medicine
B:its hard to finish a game when you cant talk to people.

**Comment by djjde12** [comment]
its fixed now though, so thanks.
