### ISSUE TITLE
Suggestion: Token

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#808]
[![image](https://cloud.githubusercontent.com/assets/11202073/22874930/0a49f57c-f1c9-11e6-8d84-1be7ca656b0d.png)](http://gamejolt.com/f/game-token-suggestion/232519)

(Click the message to get to the original forum post).

**Comment by YLivay** [comment]
Ah oops, didn't know you already opened a similar issue haha, closing mine then

**Comment by Tricky1975** [comment]
To gj-improve or is this one too technical for that?

**Comment by hworld** [comment]
we should keep it here
