### ISSUE TITLE
Jams page not working

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#809]
![image](https://cloud.githubusercontent.com/assets/11202073/22908208/74cfd2fc-f24d-11e6-92c3-004b7b4acbd3.png)

Or is this just connection trouble?

**Comment by Tricky1975** [comment]
I don't know if you fixed it or if I was just lucky, but suddenly it appears to work again...

**Comment by hworld** [comment]
I'm guessing it was the server having issues, or your network connection.
