### ISSUE TITLE
Left nav dropdowns fails on responsive layout

### ISSUE THREAD

**Issue by Fappp** [gamejolt/issue-tracker#810]
When hovering the left nav dropdowns "Browse Games" and "More" the dropdown appears and is hidden right away.

How to reproduce:

- Open chrome developer tools
- Pick "Responsive" as device
- Hover the nav

Issue also appears on Android v5

Error:

```
TransitionRejection(type: 2, message: The transition has been superseded by a different transition, detail: Transition#10( 'forums.landing.overview'{} -> 'discover.games.list._fetch'{"section":"best"} ))
[app.145451.js:21]
```

**Comment by YLivay** [comment]
Yeah i've been getting that too. Is this a race condition?

**Comment by YLivay** [comment]
Does this still happen in the new frontend? I'm unable to test this S:

**Comment by Fappp** [comment]
Browse games is now a working button, and the more is working as expected. Close this.

**Comment by YLivay** [comment]
thx!~
