### ISSUE TITLE
Perhaps a setting to turn off announcement popups

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#820]
I hate nothing more on the internet than popups I didn’t ask for (and since there are pop-up killers around here I KNOW I’m not alone) :P
Each time I log in on Game Jolt the site news now pops up on me, and it’s annoying the crap out of me.
I guess the site news got too little attention in the old style or something, I dunno, I do know that if I was a new user on this particular moment I would run away. 
Isn’t there a more “elegant” way to do this? Or at least a way to turn it off, or allow me to get these as a notification or something to make me notice some news is there. I lost a bit track of counting how many times I’ve seen the news about the 3D post thingy for devlogs by now.

**Comment by hworld** [comment]
You should only get it once... Is it continuing to pop up every time you hit the site?

Also, I can get a setting in place.

**Comment by hworld** [comment]
I added a new setting in place. You can change that here: http://gamejolt.com/settings

Note that it's saved in your browser, not for your account. So any browsers you use you'll sadly have to set it there as well. I haven't had time to do a syncing thing of settings yet. It can be tricky since you can change settings while offline in Client, so I'd have to have some sort of setting conflict resolution thing set up for it.

**Comment by Tricky1975** [comment]
>Is it continuing to pop up every time you hit the site?

After every time I shut down my browser and restart it, yeah.
And as browsers are mostly the evil in about 95% of my lags and crashes, I shut down my browser a lot, yeah...

**Comment by hworld** [comment]
Do you remove cookies every time you close?

**Comment by Tricky1975** [comment]
Nope, only when my entire system is lagging causing me to do a full clean up, but on a Mac you rarely need to do that.

**Comment by YLivay** [comment]
I'm reopening this issue despite not being able to reproduce that. On every browser on windows and my linux it seems to work perfectly fine. I have yet to test mac, tho. Is this still an issue?

**Comment by Tricky1975** [comment]
I should try when I turn the thing back on.

**Comment by hworld** [comment]
Hmph!
