### ISSUE TITLE
412 Error when loading Audio 

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#823]
[![image](https://cloud.githubusercontent.com/assets/11202073/23260429/154a3cb4-f9d2-11e6-8c72-56060df84696.png)](http://gamejolt.com/f/412-error-when-loading-audio/233034#forum-post-316838)

Click the screenshot to get into the original forum thread.

**Comment by YLivay** [comment]
This has been looooong looooong resolved.
