### ISSUE TITLE
Opening the client opens node webkit

### ISSUE THREAD

**Issue by cashregister9** [gamejolt/issue-tracker#828]
I don't know how or when this happened i turned on my computer and nw.js and node webkit started up
opening the client also causes this to happen

**Comment by Taruna188** [comment]
same like me, but iam keep opened gravatar website not node webkit

**Comment by YLivay** [comment]
Sounds like the computer restarted during a critical part of the auto update process, leaving the client in a bad state S:
We've been working on a fix for this for the past 2 months, but for now you'll just have to reinstall, sorry :(
