### ISSUE TITLE
"URL path" field appears to cause confusion and the documentation about game creation appears to be outdated.

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#831]
This field: ![](http://i.imgur.com/WT64T9t.png) causes people to get confused. They try to put in entire URLs without proper understanding what it does. This field came with the "sites" system. Perhaps the documentation needs to be updated.

**Comment by YLivay** [comment]
I saw the thread this was reported on, to be honest it's pretty clear, coupled with the urls actually being updated as you type makes it almost impossible to misunderstand imo.

What do you suggest?

**Comment by Tricky1975** [comment]
Yeah, well it's pretty clear to me too, but as we can see, you must always take in mind a "moron" must be able to understand this, and you'd be surprised what people do not understand.

Maybe changing the field name into something without the word URL in it can help. I'm not 100% certain, but I believe sourceforge calls this field for similar functions "unix name" or something like this with the explanation that URLs are generated on this. I've also seen stuff as "short name"

What I've also seen is something like this
~~~
https://tricky.gamejolt.io/[................]
~~~
Well in which the [....] is the textfield name.

And the guy reporting this spoke of an instruction video. Does it really exist and if so is that video actually made by Game Jolt and thus official? If so and updated version of it will be in order.

**Comment by YLivay** [comment]
Heh, even if such an instruction video exists it's probably outdated. Game Jolt evolves so quickly @_@
At any rate, we think this is very very clear, it even shows the url as you type. We're happy with it as it is, if its not clear at this point it's ermm.. a different problem.
