### ISSUE TITLE
Cannot open jars on windows

### ISSUE THREAD

**Issue by Colep14** [gamejolt/issue-tracker#833]
the client always has problems opening .jar games

**Comment by Tricky1975** [comment]
One thing is important to know.
You do have Java installed, right (I want to rule out that is the problem).

**Comment by Colep14** [comment]
I do have Java installed, I can open them if I download them from the site

**Comment by YLivay** [comment]
The java binary needs to be in your path to work.
The client launches java games using `java -jar /path/to/game`
What happens if you simply write java in the command line?

**Comment by YLivay** [comment]
Closed for inactivity.
