### ISSUE TITLE
Can't use the client in offline mode

### ISSUE THREAD

**Issue by surashu** [gamejolt/issue-tracker#834]
On the [product page](https://gamejolt.com/client) for the client, it said it supports Offline Mode. But when the GameJolt Client is opened without internet, it gets stuck and clicking on the Game Library icon or via the burger menu on the top left doesn't load anything.

![image](https://cloud.githubusercontent.com/assets/12764163/24581556/579d6c44-1750-11e7-8a1d-0e95a2a18a34.png)

In addition, it would be nice to still be able to play the game even while an update is ongoing. Right now, the Launch button is replaced with "Pause" for the currently downloading game. It should still allow launches when clicking on the 3-dotted menu beside the Pause button.

**Comment by mason1920** [comment]
The application is built using web technology, it would be very hard to get an off-line version of the client without completely remaking it.

**Comment by mason1920** [comment]
If you want to play the games you already installed, but have no INTERNET, then you could navigate to the game executable and run it without using the client.(.exe, .x86, .x86_64, .app, etc.)

**Comment by surashu** [comment]
That's not the problem. Look at my screenshot, if it was _entirely_ based off a live server, it wouldn't be able to load everything you see on my screenshot else (the CSS, error image, etc). What I'm talking about is that the game library section of the client should be accessible even without internet to easily launch the already installed games. I know I can just go to the folder but the main reason the client exists is for organizing games. Can you imagine how cumbersome it would be if Steam didn't have an offline mode and you had to manually go to the installation folder to open each game?

**Comment by hworld** [comment]
I believe offline mode is broken at the moment. We're working on a really massive update. It should be fixed in that. Hope to have that out in about 3 weeks time.

**Comment by surashu** [comment]
That's awesome! I'll look forward to that!

**Comment by YLivay** [comment]
This may have been resolved. But hey! even if it isn't - another huge refactor is underway! https://github.com/gamejolt/gamejolt/tree/client-vue

**Comment by to4ooo4** [comment]
@YLivay Nope, this still hasn't been fixed.

**Comment by to4ooo4** [comment]
@mason1920 The thing is that the Gamejolt Client's page _says_ that it supports offline mode. If offline mode won't work offline, then this is a problem. And I can confirm that it doesn't work offline.

**Comment by surashu** [comment]
@to4ooo4 yup, I don't think my GameJolt client has even updated ever. Ever since I installed it some long time ago like... September 30 of last year...?

![image](https://user-images.githubusercontent.com/12764163/30596853-f00d5bde-9d87-11e7-852e-31eb31db2566.png)

**Comment by to4ooo4** [comment]
I wonder when we'll stop being ignored. .-.

**Comment by surashu** [comment]
I honestly don't think we're being ignored. Just that they have a lot on their plates right now and the client is probably not their top priority.

**Comment by to4ooo4** [comment]
@surashu Good point; sorry.

**Comment by surashu** [comment]
@YLivay damn, I thought I was misreading 2.5 on my small phone's screen and zoomed in thinking you meant 25. More power to you guys!

**Comment by to4ooo4** [comment]
I'm sorry for being a dick about it, by the way.

**Comment by hworld** [comment]
Offline mode should be working again. There's still some bugs but we're working through them. Try it out with the new client version 0.13.0
