### ISSUE TITLE
Downloads stuck?

### ISSUE THREAD

**Issue by Rayinator** [gamejolt/issue-tracker#837]
I was trying to install a game.. namely, the Rhythm Rush Demo and it failed to install.. I then clicked retry but then it seemed to just freeze... I clicked Cancel Installation and it wouldn't cancel.. I tried restarting my computer and quitting and restarting Gamejolt but it wouldn't seem to cancel. Any suggestions?

**Comment by CreeperChief** [comment]
Download freeze also happens to me but I can cancel the download at any time without problems.
