### ISSUE TITLE
Cant play any games, AT ALL!

### ISSUE THREAD

**Issue by macalan123** [gamejolt/issue-tracker#842]
I downloaded update 0.4.4 for house party and it wouldn't let me play any of my games. i tried restarting the client and restarting my laptop but it just comes up in a notification "Oh No! Could not launch game"

**Comment by advaith1** [comment]
Probably an issue with the games, please let the game developers know.

**Comment by advaith1** [comment]
When you download the game, does it display an installer? If so, ask the developer to upload the application as a zip, or a standalone app exe file.
