### ISSUE TITLE
Notifications work half [ New Frontend]

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#846]
When I click the notifications I do see the new feeds for new DevLog entries for the games I'm following, but when I try to switch to the tab that shows me comment or forum replies and that stuff nothing happens.

SUPPLEMENT: When using a different browser not yet configured to this front end, it does seem the system counts the message as "read" though, even though I couldn't read it.

**Comment by hworld** [comment]
fixed
