### ISSUE TITLE
"Active Topics" tab not working [ New frontend ]

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#847]
Now I wonder if this is the same bug causing #846 as there it's also tabs not reacting to me at all.

**Comment by Tricky1975** [comment]
![image](https://user-images.githubusercontent.com/11202073/28225320-8fae6ed4-68d2-11e7-8a2f-ca8c383c5bdf.png)

I guess this works, now...

**Comment by hworld** [comment]
ya, works
