### ISSUE TITLE
Hidden games should no longer show in jams.

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#851]
It might be a good idea, to keep a game hidden in the jam pages as well even if the tag of the jam matches with one of the tags in the game. Especially if a game gets hidden by a moderator I wonder if it's desirable if it still appears on the jam pages (effectively still being allowed to compete).

**Comment by hworld** [comment]
We used to show hidden games in jam pages because we didn't have the "devlog" status. Now that we do, people can add their game as devlog and post about it while jamming, and we don't need to allow hidden in the jam anymore. Yay!
