### ISSUE TITLE
Cannot Refresh Pages

### ISSUE THREAD

**Issue by Bedlams** [gamejolt/issue-tracker#852]
I have to go out of the page and back in in order to see new comments or replies. Please fix

**Comment by hworld** [comment]
Is this in the Client?

**Comment by Bedlams** [comment]
Yes. A simple refresh button should fix the problem.

**Comment by niksudan** [comment]
I don't think new comments appear automatically on the site or client anyway?

**Comment by Bedlams** [comment]
They don't, but the site has a refresh button on the web browser.

**Comment by hworld** [comment]
closing since dupe of https://github.com/gamejolt/issue-tracker/issues/402
