### ISSUE TITLE
Norton and microsoft both say this manager cliant is unsafe and need more info to allow it.

### ISSUE THREAD

**Issue by Sojurn7** [gamejolt/issue-tracker#854]
notification that this client of yours is not safe

**Comment by advaith1** [comment]
Could you provide a screenshot of Microsoft saying it's unsafe?

**Comment by Sojurn7** [comment]
Sorry unsure how to do this I never use screen shot before but when I try to use it they pop up and block your site say this maybe I can try again to down load and try to do this after I look up how return with screen shot then..

**Comment by Sojurn7** [comment]
When I download a game on screen window Microsoft defender blocks this and says it might be unsafe, I will run my Norton scan on it and see my Norton scan say it safe to I will turn of defender when opening some of your games/ other...

**Comment by Tricky1975** [comment]
Screenshotting in Windows is easy.
Just push the "PrintScreen" button when the screen is in the state you want to shoot.
Then come here to GitHub, and activate a message field to type a message as always and press CTRL-V and Github will upload the screenshot

**Comment by YLivay** [comment]
Theres nothing malicious or unsafe about the client or the way it launches games. Maybe its complaining about a specific game? Anyways, we've updated the client and theres a whole new way of launching games so maybe this is resolved. Can you retry and see?

**Comment by Tricky1975** [comment]
Let's say that many commercial virus scanners deem anything unsafe that is not registered at MicroSoft or something cheesy like that. I deem this a very bad thing, as it makes me unable to take virusscanners seriously lately. (Some virusscanners (like AVG) will even delete any .exe file it doesn't know without asking or scanning or anything).
Most virusscanners do support whitelisting, although this feature has a different name at each virusscanner. 
I think all we can do about it is just place some proper documentation about most malware scanners about how to whitelist Game Jolt. (if a downloaded game is still a virus, it should still be detected accordingly).

**Comment by YLivay** [comment]
I don't think theres any action we can do to address this haha. The client is open source if you have any concerns :)

**Comment by hworld** [comment]
Maybe we gotta sign it better somehow? haha
