### ISSUE TITLE
Cannot launch any downloaded games

### ISSUE THREAD

**Issue by BlatantLizard** [gamejolt/issue-tracker#856]
All games that I have downloaded through the Game Jolt Client cannot be played. Every time I try to launch a game I get the following message: Oh no! Could not launch game. I have version 0.11.1 of the client on a MacBook pro. My specs are as follows:
MacBook Pro (Retina, 15-inch, Mid 2015)
OS: macOS Sierra version 10.12.5
Processor: 2.2 GHz Intel Core i7
Memory: 16 GB 1600 MHz DDR3
Startup Disk: Macintosh HD
Graphics: Intel Iris Pro 1536 MB

**Comment by YLivay** [comment]
Hey, we've released a new version of the client a month or two ago. Can you update the client and test again?

**Comment by YLivay** [comment]
closed for inactivity
