### ISSUE TITLE
YIKES!!! AUDIO in the Ads

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#857]
I don't mind advertisement on GJ. It's what keeps the site free after all.
What I do mind is that I occasionally get ads with Audio.
I mean
1. I've often gotten an audio ad while I was in the middle of running an audio test in my game development.
2. I've nearly always a GJ window open and being disturbed while doing other work is also not nice.
3. They sometimes disrupt playlists I listen to
4. And my computer is currently in the same room where I sleep and when I sleep I leave my computer on to run backups and updates, and I've been woken up by an ad that came from GJ several times.

Well, except for point 4, turning off the audio of my system is not really an option.
Is there a way to keep your advertisers from putting audio in their ads?

**Comment by hworld** [comment]
We actually have audio ads turned off. They still get through for adsense which is why it happens. There's not much we can do. Ads kind of suck. We're working on trying to get better ad providers but that's about all we can do, and it takes time.
