### ISSUE TITLE
Threads without a title un-accessible

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#858]
![image](https://user-images.githubusercontent.com/11202073/27252816-bd701c62-5367-11e7-9a72-052d6b75d0c0.png)

Since the link doesn't leave a pixel at all to click it. (well, I guess I can still click the user's name to open the thread, but still...)

**Comment by niksudan** [comment]
I thought that a thread needed a title in order to post? Can you post the link/ID of that thread?

**Comment by Tricky1975** [comment]
That won’t make sense any more as I used my moderator powers to enforce a title in it.
I think the author removed the title himself causing this to happen or something…
