### ISSUE TITLE
You don't get notifications when you follow a forum topic.

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#863]
When I follow a thread I do not get notified.
When somebody gives a direct reply to my posts I do get notified (although some of these notifications come days later).

Since I only follow threads I deem very vital, this is quite frustrating.

**Comment by YLivay** [comment]
I'll look into it. Could be either:
* not creating notification
* not attaching users to notification because subscription data is wrong
* consume notification doesn't handle follow thread types
* no notification in frontend to handle those types

**Comment by Tricky1975** [comment]
This issue become worse than it already was. Now the topics I follow, automatically unfollow. Whenever I click "Follow" I see the button change to "following". When I click a different topic or post a reply or whatever causes the topic to be reloaded I see that I am no longer in "following" status.

**Comment by nilllzz** [comment]
Fixed.

**Comment by Tricky1975** [comment]
![image](https://user-images.githubusercontent.com/11202073/47906296-3839d480-de89-11e8-920a-886b53733986.png)
