### ISSUE TITLE
Edit Account links under Your Dashboard are all white

### ISSUE THREAD

**Issue by TheWanderingBen** [gamejolt/issue-tracker#864]
When a user goes to "Your Dashboard", the text for the links under Edit Account are white on a white background, and thus cannot be seen. Possibly related to link text in blog posts being white as well?

![image](https://user-images.githubusercontent.com/13871274/27398869-5ac095ba-5678-11e7-9e86-d1577d1cc413.png)

Steps to repro:
1. Login to an existing Game Jolt account or create a new account
2. Click on "Dashboard" on the left-hand pane
3. Look at the links under "Edit Account" 

Expected:
The links can be seen -- either black or green text (or maybe something fun, like bright orange?!)

Actual: 
The link text is white, and thus cannot be seen on a white background.

Tested using Google Chrome on MacBook Pro (Retina, 13-inch, Mid 2014) with OS X El Capitan 10.11.6

**Comment by hworld** [comment]
Fixed!
