### ISSUE TITLE
Can't tell who PMed me...

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#865]
Can you?

![image](https://user-images.githubusercontent.com/11202073/27508111-d4236faa-58de-11e7-8302-f077eb33e735.png)

**Comment by niksudan** [comment]
I think this happens when the person who PMed you goes offline. If you scroll through your offline friends you may find that rogue notification.

**Comment by Tricky1975** [comment]
Actually I found out later that it was “Red Fox Studios” who PMed me (by just trying everybody), and as you can see in the screenshot, he WAS on-line at the time.

(And maybe a date of the last chat message is also in order, as it was guessing work).

**Comment by hworld** [comment]
should be fixed in new frontend. also, the dates show now in new frontend
