### ISSUE TITLE
Can't remove scores past the 25th entry

### ISSUE THREAD

**Issue by MausGames** [gamejolt/issue-tracker#866]
In the developer dashboard only the first 25 scores are visible. If a guest created a score entry at 27th place with an offending name, and the game itself shows scores past 25, it is not possible to moderate and remove this entry.

**Comment by hworld** [comment]
yeah, this sucks. i'll try getting this done in the rewrite

**Comment by MausGames** [comment]
This is still an issue, please verify and reopen.
