### ISSUE TITLE
downloaded games not playing.

### ISSUE THREAD

**Issue by wolfscar25** [gamejolt/issue-tracker#867]
Every game that I downloaded, if I closed out the client then get back on the client on another day the games that i download say that they could not be played. I don't know if this is some kinda bug or what but it needs fixed, i love playing the games on Gamejolt. But how can I play them if I have to uninstall them and re-download them all over again and have to start my save all over again......

**Comment by niksudan** [comment]
What OS are you running?

**Comment by YLivay** [comment]
Hey, we just pushed a big update that fixes a lot of issues with the client. Can you try again? Sorry for the slow response!

**Comment by hworld** [comment]
closing since no response
