### ISSUE TITLE
Icons all squarez (new UI)

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#870]
![image](https://user-images.githubusercontent.com/11202073/27992718-d35ef4e6-649a-11e7-8558-c2b5a4f67c62.png)

This is how it's supposed to look?

**Comment by hworld** [comment]
You have to use https for new site testing

**Comment by Tricky1975** [comment]
I did!

**Comment by hworld** [comment]
Hmm, it's not https in photo

**Comment by Tricky1975** [comment]
Opera hides the protocol, no matter what it is
