### ISSUE TITLE
Request: Fangame Auto Tagging

### ISSUE THREAD

**Issue by niksudan** [gamejolt/issue-tracker#872]
There's still a plethora of fangames being upload to the site, and some can be easily deduced via keywords, like you do with FNAF. Would clear up newly added a little bit.

Some examples:

- `sonic`
- `undertale`
- `pokemon`
- `mario`
- `zelda`

**Comment by YLivay** [comment]
Can do, but users have a tendency to be very very VERY inventive with their game titles. Bless sanic and <random>tale. We can put very basic detections in place but would it even help?
