### ISSUE TITLE
Something not right on reporting comments

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#873]
![image](https://user-images.githubusercontent.com/11202073/28087103-948ba938-6681-11e7-9c22-9e9f86881a6c.png)

Lay-out issue. Btw... pressing the button to confirm the report does nothing at all.

(Just tested forum has same issue... I'm not sure if I reported this before as now I vaguely remember something like this).

**Comment by hworld** [comment]
fixed, will be pushed shortly
