### ISSUE TITLE
After posting on forum i need to refresh to see what I posted

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#876]

**Comment by Tricky1975** [comment]
Hours later, I did not suffer here anymore, but this morning (CET) I had this all over the forum, and I wonder why....

**Comment by hworld** [comment]
Gonna close. Feel free to reopen if you're able to reproduce

**Comment by Tricky1975** [comment]
It happened again, this morning.... Although it also went away again.
You will have to re-open this yourself, as I can only re-open issues I closed myself.

**Comment by Tricky1975** [comment]
And this problem just happened again. 
And earlier today I suffered from it taking a long time to show.

**Comment by YLivay** [comment]
I'm reopening this issue, if this is fixed please close it. It seems to work for me tho.

**Comment by Tricky1975** [comment]
It's actually happening more wrong than right, so good thing you re-opened this ;)

**Comment by YLivay** [comment]
Is this when youre creating a new post or a topic?

**Comment by Tricky1975** [comment]
I will need to test this for new topics, as mostly I only reply to existing topics, as that is where I discovered this issue. I can try a test topic to find out.

**Comment by YLivay** [comment]
Thanks, I saw your topic and spammed a bit in it too and  actually encountered it once.
It appears when this happens it doesnt even send the request to re-fetch the page. It might be a race condition with the post submit function but at least I managed to confirm it!
