### ISSUE TITLE
I can't install game jolt client

### ISSUE THREAD

**Issue by Naifos-Gametube-YT** [gamejolt/issue-tracker#883]
I tried installing game jolt client but it just won't work!
I all ready did it once but i had to delete because of an issue where i wasn't able to play a game so i tried re-installing client but when i re-tried it just won't work!

**Comment by hworld** [comment]
What's happening when you try launching it? Does it not show at all? Does an error show? Anything?

**Comment by Naifos-Gametube-YT** [comment]
Well, first of all i can't make a shortcut so i can't launch the shortcut.I can use a browser and everything works for now (i only tried searching around a bit on the website nothing else). second an error does show saying this (its in dutch tho):kan geen toegang krijgen tot het opgegeven apparaat, pad of bestand. Mogelijk hebt u niet de juiste toegangsmachtigingen voor het item.

**Comment by niksudan** [comment]
The error message translated says the following:

> Can not access the specified device, path or file. You may not have the correct access permissions for the item.

**Comment by Supermac2006** [comment]
Maybe you are running it on a device that is not a computer nor a laptop. Is this true? If not, check your computer type aka Windows, Mac, etc.

**Comment by hworld** [comment]
Maybe you're trying to install it in a restricted account on your computer? Is it your parent's computer maybe with a user account just for you?

**Comment by Naifos-Gametube-YT** [comment]
I use Windows 10

**Comment by Naifos-Gametube-YT** [comment]
For some reason it works now. Probably because of a bug fix.

**Comment by Supermac2006** [comment]
Good to see this issue fixed. ;)
