### ISSUE TITLE
Picture upload routines don't appear to load in Devlog new front end

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#884]
![image](https://user-images.githubusercontent.com/11202073/28440270-cb7b7e52-6da5-11e7-88df-f7ac636268cb.png)

I've been typing that in one phase directly into the browser.
Now I know I can type fast, but not that fast that that stuff should still be loading.

**Comment by hworld** [comment]
i believe this is fixed now

**Comment by Tricky1975** [comment]
Let's try this....
At the start of the test (mind the clock in the upper-right)
![image](https://user-images.githubusercontent.com/11202073/28490780-c60884c2-6ee2-11e7-8e21-39c6bc7a0072.png)

Now I'm gonna fix myself a cup of coffee (where would a Dutch be without his coffee?)
And then I'll make another shot.




Well not yet finished my coffee, but still I can see things didn't work out at the time still:
![image](https://user-images.githubusercontent.com/11202073/28490812-a019fe02-6ee3-11e7-8ea7-d00e8911f1c6.png)

**Comment by Tricky1975** [comment]
Urm... Don't hate me....
![image](https://user-images.githubusercontent.com/11202073/28490901-9cd31768-6ee5-11e7-8cc8-de02cb83ebca.png)
