### ISSUE TITLE
Package is not running 404

### ISSUE THREAD

**Issue by Supermac2006** [gamejolt/issue-tracker#886]
When I went to gamejolt. I was about to play mysterytale when it said the package was running. It wasn't running on my computer. I can't try to re-install it either. Pls fix this.

**Comment by hworld** [comment]
Would you be able to tell me your client version? Just scroll all the way down. It should show it in the footer.

**Comment by Supermac2006** [comment]
Sorry for being late but I am commenting on an another device. I will check the version ASAP if you don't mind. (I estimate that I could tomorrow)

**Comment by hworld** [comment]
Sounds good. I'll be waiting. =]

**Comment by Supermac2006** [comment]
The version is v0.12.2

**Comment by Supermac2006** [comment]
Please reply, I am waiting.

**Comment by Supermac2006** [comment]
This issue is still open, y'know.

**Comment by YLivay** [comment]
Hey, sorry for the slow reply!
Can you fully restart the client through the system tray? (closing the window is not enough),
then right after it loads in scroll down to the footer and hit the "Send System Report" button.
Also, did you install the package recently or was it sitting around for a few weeks before this issue happened? My guess is that something went wrong while upgrading to the latest version of the client, but I need more info to know exactly what happened to fix it :)

**Comment by Supermac2006** [comment]
Alright. When I was playing the game, my parents shut down my computer till I could actually quit. Therefore, I think the server got muddled up I was still playing but I still need to find the solution. Plus, I downloaded Gamejolt a few weeks ago and I wonder if there is a new version. Plus, I will try restarting the system on Wednesday, since I don't have time tommorow. Plus, your guess is kinda wrong because the game had this issue a few days after I installed it, not immediately after. If I misunderstood your guess, please make it more clear, thank you!

**Comment by Supermac2006** [comment]
Still waiting.

It's been a month.

**Comment by YLivay** [comment]
Hey, again, sorry for the slow reply. I'm sure you can see how many issues we have in the backlog - and we're only 2 people :S 

Anyways, whats your user on GJ? I don't see you sent a system report.

**Comment by Supermac2006** [comment]
Oh sorry, I forgot to send the system report. I'll send it ASAP and my username on GJ is AwesomeMac6002.

P.S. Yeah, there are a lot of issues anyway. I understand.

**Comment by Supermac2006** [comment]
I have sent the system report.

**Comment by YLivay** [comment]
Heya! Thanks for the system report, it's really helpful!
So, what appears to be happening is that the client can't communicate with the game launcher. This is usually something to do with permission errors or a hyperactive antivirus. At any point when launching games did you get a prompt saying 'joltron.exe' needs network access? If you've denied it - it would not be able to communicate to the client and you might have to go to the firewall settings and allow it again. Let me know if any of this rings a bell :)

**Comment by hworld** [comment]
These issues should be fixed with v0.13.0, which we just pushed out now.
