### ISSUE TITLE
Markdown/userlinks/e-mail conflict

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#887]
![image](https://user-images.githubusercontent.com/11202073/28545534-99f58290-70c7-11e7-96ec-83f786c9049e.png)

(Look at the e-mail address at the last line of the post).

**Comment by YLivay** [comment]
Is there a link for this comment?

**Comment by Tricky1975** [comment]
Will be hard to dig that one up, but I created [this test thread](https://gamejolt.com/f/just-a-test-ignore-me/305550?page=1) just for you, so you can see for yourself.

**Comment by YLivay** [comment]
Hmmm, according to [markdown specifications](https://daringfireball.net/projects/markdown/syntax#autolink) this is expected behaviour.
If you want to autolink an email you gotta surround it with `<>`.

I'm not sure if we should automatically do this or not. @hworld thoughts?

**Comment by hworld** [comment]
this is funny. i dug into it and it's actually just for "rt@something.com". We use Twitter's linker, which means RT@User is correct in their format. We will probably have to write our own linker for usernames/hashtags to fix this up.

btw, our email address is actually <contact@gamejolt.com>
