### ISSUE TITLE
Problem in translation showing

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#910]
![image](https://user-images.githubusercontent.com/11202073/28620287-9601509c-720c-11e7-97a5-29991bb1acef.png)

- This is in the Dutch translation.
- Not only show the moderator-only functions in English in stead of Dutch (while they should be translated)
- The HTML tags in the "report" feature show (never saw that on the old site).
- (also odd that "Follow" (Volg) is translated but "add reply" is not).

**Comment by hworld** [comment]
There shouldn't be <p> tags in that element. You able to remove the tags? It should just be the text.

**Comment by Tricky1975** [comment]
Sure I will look into that when I got the time. 
I was planning to give the Dutch translation a look later this week anyway.
I saw the same problem elsewhere too. I guess the html tags need to be removed there as well?
