### ISSUE TITLE
VUE - download page recommended games incomplete

### ISSUE THREAD

**Issue by MaskofThoro** [gamejolt/issue-tracker#915]
![downloadpage](https://user-images.githubusercontent.com/10214401/28635498-0d3107da-71f8-11e7-85ca-6fcc612e4717.JPG)

**Comment by hworld** [comment]
I _think_ this is actually an issue with the label maybe taking up too much vertical space and pushing over the next game thumbnail

**Comment by hworld** [comment]
i think i fixed this by changing vertical alignment of tags
