### ISSUE TITLE
Checking my old issues.

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#916]
Some issues I've reported earlier have not really been fixed, but are no longer an issue due to the new site update. 
I'm just looking these up, so you don't have to, and I'll close those that are no longer issues

# Still an issue
- Can't unfriend banned people #310 
- Picture secret trophies do not show in dashboard overview #343 
- Client needs back button and most of all a 'refresh' button #402
- Old forum posts containing smiley will now be "rotten" #650 (although most post concerned are not really important anymore, so should we keep it still open?)
- Maybe it's better if the hashtag is ignored in code blocks #659 (as far as I can check).
- One of the forum rules looks a bit contradicting and can work confusing. #667
- Active threads issue in forums #668
- For "Secret Achievement/Trophy" maybe it's better to keep the name secret as well. #670
- Improvement: Thumbnail badge for paid games featuring a free demo. #690
- YouTube codes in code blocks show the video #723

# I don't know
- ~Playlists thumbnails are messy when there is no content #356~
- Better background on transparent avatars Fireside #368 (I cannot check this, as I can't find my old blogs that now reside on fireside anymore).
- Dragging pictures into the client can make the client go "KABOOM!" #557 (Is the client already updated? If not I can't check this).
- &quot; tags show in the "Gambling" section of the maturity rating screen #641 (I saw this in English, but I have the setting on Dutch now for testing reasons).
- Markdown code issue #652
- Uploading additional pictures in DevLogs busted #739
- ~Post count gone? #756 (since this happens randomly, it's hard to check).~
- CSS issue on downloads in client #759 (Is the client up-to-date? Otherwise I can't check this one).

# Appears fixed, but I'm not yet 100% sure
- System does not always tell me who PMed me #533

# No longer issues
- Wrong author when linking from one forum thread to another. #640 (vue update "fixed" this).
- Links in forum posts to pages anywhere on GameJolt 404 but will load after renewing the page. #657
- Commenting on a game with a "mature" rating will show the mature warning again. #695
- Circular link bug #747

I wasn't sure where to post this to let ya know, but this way was the easiest for me to do.

**Comment by hworld** [comment]
We haven't yet updated client which is why it looks like the old site still. Also nothing besides main site changed, so fireside is still old code too sadly.

**Comment by Tricky1975** [comment]
Ah, so I guess that means client and fireside issues are still the same ;)

**Comment by hworld** [comment]
k, i've done the ones i can do easily. going to close this out since i'll track in the issue tracker normally
