### ISSUE TITLE
Plural translations broken.

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#921]
![image](https://user-images.githubusercontent.com/11202073/28688436-3dcb8b34-7312-11e7-80d9-13f69a6ddfb0.png)

Error in the Dutch translation files, or in the site's script?

**Comment by hworld** [comment]
translation tag, sadly. this will be fixed when I extract translations again

**Comment by Tricky1975** [comment]
Brings me to the question, can I start already in bringing the Dutch translations up-to-date, or should I wait with that?

**Comment by hworld** [comment]
not yet. i haven't gotten translation extraction working in new frontend just yet

**Comment by Tricky1975** [comment]
Okay, I’ll wait then.
Just gimme the word, and I’ll get on it ;)
