### ISSUE TITLE
PM chat issue

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#922]
Well this little copy from chat explains it further.

Jeroen P. Broks - Today at 7:37 PM
@ Developers In PM chat I can only see the chat "growl" (in browser), but not in my chat windows
CROS - Today at 10:40 PM
@ Jeroen P. Broks I don't fully understand
Jeroen P. Broks - Today at 10:42 PM
Well the there is a kind of a small pop-up at the bottom showing on the moment you are PMed, right? Well that showed, but in my chat window itself (that was with the same person sending me the PM) nothing showed. He could not see my PMs either
CROS - Today at 10:44 PM
Ah, goycha
You able to log that just as you said in issue tracker?
Jeroen P. Broks - Today at 11:51 PM
Uh yeah, sure...

**Comment by hworld** [comment]
this should be fixed now
