### ISSUE TITLE
Removing Friends Removes Other users as Friends

### ISSUE THREAD

**Issue by Ztel** [gamejolt/issue-tracker#933]
So I was trying to remove someone as friend because of the other issue I posted, but instead of removing that user, it removed mr whale, and I do not know why.

**Comment by hworld** [comment]
hmmm, are you sure mrwhale didn't remove you?

**Comment by hworld** [comment]
closing since no response

**Comment by Ztel** [comment]
Yes, I am sure mrwhale did not remove me, even when I tapped on the button,
the confirmation tab asked "are you sure you want to remove mrwhale as your
friend?"
