### ISSUE TITLE
Submitting a game through the client doesn't work?

### ISSUE THREAD

**Issue by derpeyman28** [gamejolt/issue-tracker#940]
I can't submit games through the gamejolt client. I think it might be because its an outdated version (with the inclusion of custom URL paths). If it is then please tell me how to update my client because I dont know how.

**Comment by YLivay** [comment]
Hey! We know about this, sorry for the inconvenience but for now you have to use the site.
We still have a little more work to do on the client before we can bring it up to speed with the rest of the site - and it'll all work then :)

I'll leave this issue open, will update when it's fixed.

**Comment by YLivay** [comment]
Just acknowledging this is still on the todo list. Working branch for it is https://github.com/gamejolt/gamejolt/tree/client-vue

**Comment by hworld** [comment]
Should be fixed since we pushed out the new version! v0.13.0
