### ISSUE TITLE
Interface can overlap menus

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#947]
Now I know I only suffer her because I'm a moderator, but still....

![image](https://user-images.githubusercontent.com/11202073/29015772-ae4e6ada-7b4f-11e7-8307-c6cd0d7a9e41.png)

(If you wanna replicate this, just go to a random thread on the forums, open this menu and scroll down. Especially on threads with very short messages (like the spam threads), this can happen).

**Comment by hworld** [comment]
there's actually a really stupid reason for this. basically when you scroll down further the [add reply] button would actually go over the footer content. -_- i hate styling

**Comment by Tricky1975** [comment]
I am familiar with the pain.
This reminds me of phantasarproductions/tftrevamped#325 in my own game, and the reason there is just as stupid…
Cosmetic bugs can sometimes be really tricky.

**Comment by YLivay** [comment]
all hail the crostyling master. Whenever you get to it I guess

**Comment by hworld** [comment]
This was fixed.
