### ISSUE TITLE
Sometimes Name's won't update

### ISSUE THREAD

**Issue by anonma** [gamejolt/issue-tracker#948]
i have observed 3 people so far attempt to change their names, have it say their names are changed in their dashboard, but not update.
the first one was http://gamejolt.com/@sd-_-bz
NT stepped in and attempted to change the name with mod tools, but it did not update for several minutes, during this time the links to his profile died, but his display name in chat remained the same.
the second was http://gamejolt.com/@DerpyMcDragonPlaysBraThepowero
he didn't say much about what was happening in his case, just that he changed his name, but it wasn't updating and he couldn't change it again because of the 7 day cool down.
the last was http://gamejolt.com/@Medina
i think this name change happened on the 4th of august and still to this day (the 7th) nothing has changed, medina can provide screenshots of the 7 day cool down message

**Comment by YLivay** [comment]
If its in chat then the names are cached for around 5 minutes. Thats normal. Also the  name would be frozen on older messages iirc.
