### ISSUE TITLE
VUE - removing soundtrack takes longer than adding one and crashes

### ISSUE THREAD

**Issue by MaskofThoro** [gamejolt/issue-tracker#950]
Removing a song from a soundtrack takes longer than adding one. It also resulted in server crashes for me when trying to remove an entire "album".

https://i.gyazo.com/5905b39e107fda2b1ef1d1a567fd1e0b.gif

**Comment by hworld** [comment]
sadly i can't make it faster yet to remove music, but I put a loading overlay on top while it's processing so that they know something is happening and so that they don't end up ruining anything while work is being done
