### ISSUE TITLE
Suggestion: Maybe a “close request” feature for collab, jobs and business forums

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#953]
I come past [these kinds of threads](http://gamejolt.com/f/post-deleted/254462) a lot, but they often “hover around” a bit before I actually see them. 

Now this guy removed all content from his own post, but I also often see the OP saying he/she got all the manpower he/she needs and still people replying much to the OP’s annoyance. Of course if you don’t need more people I can understand that people keeping on replying are a waste of time.

Now I don’t see this needed for casual, gj-help and those kinds of boards, but for collab, jobs and business, it might be an idea if people can send a “closure request” (which may end up in the Event Horizon) so I can close these threads after inspection much more quicker and save a lot of trouble. 

I mean people can report their own threads as “spam” or anything cheesy like that, but that may mostly result in confusing me, rejecting the report as a result. I don’t think we want that. :P

**Comment by YLivay** [comment]
This isn't the place to discuss moderation stuff, we should stick to our chat.
As for the suggestion, i really dont think it'll be worth the effort into adding another report type to EV. it's a real pain and the collab/job forums don't seem to justify that. we can continue discussion in our chat if you want.
