### ISSUE TITLE
Incorrect field invalidation when editing a game

### ISSUE THREAD

**Issue by niksudan** [gamejolt/issue-tracker#955]
Entering any data into the package name field results in an error, which means no one can upload packages.

![image](https://user-images.githubusercontent.com/6004491/29227447-c4847b60-7ecd-11e7-8ef7-602a15243333.png)

**Comment by niksudan** [comment]
This also seems to affect any text input field.

![image](https://user-images.githubusercontent.com/6004491/29227507-feae739a-7ecd-11e7-9f2f-36f47e3a1f2d.png)

**Comment by hworld** [comment]
fixed! i was stupid
