### ISSUE TITLE
Post Error? on going away in stead of posting.

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#959]
It goes like this:
1. I visit a forum thread
2. I click the reply box, but I don't type anything at all.
3. I decide to leave the thread be and I click a link to the thread list
4. Now before going to the thread list below the reply box the error "you must type a comment" or something like that appears, while I didn't even **WANT** to post something.

**Comment by YLivay** [comment]
Hey, we know of this - but it's surprisingly annoying to fix and atm we can't see it worth the time haha. For now  just accept it as one of the quirks GJ is infamous for :P
