### ISSUE TITLE
radio doesn't work in client

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#960]
- The interface shows
- But the play doesn't start
- A Windows 10 user reported this one to me
- However I can replicate this on my mac
- I cannot test this in Linux, but since Mac and Windows have the same problem I think it's safe to assume Linux suffers as well...

**Comment by YLivay** [comment]
This is an issue with the codec the songs are using. NWJS, the framework  the client is built on does not support all codecs and at the moment we don't have a plan to do any conversion in the backend. Hopefully a newer update of NWJS fixes it but for now - not going to fix this.

**Comment by Tricky1975** [comment]
Then perhaps the link should be removed or open a browser window in stead.
