### ISSUE TITLE
See me as offline but i'm online.

### ISSUE THREAD

**Issue by MrDollariX** [gamejolt/issue-tracker#961]
I log in to account but the list of friends and chats don't show. I'm go to my profile page but he said what i'm offline. I'm try reinstall client but is not help. I'm try log in via browser (Google Chrome) but he again said "Offline". What's the problem?

**Comment by hworld** [comment]
I had to take down chat for today since it's currently killing the site. There is some bug where it continues to restart and ends up slamming the DB hard.
