### ISSUE TITLE
Editing my own forum posts works kinda odd

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#962]
When I edit my own posts, the save button does often ignore me, or that is what it looks like, as it is possible the edit is processed, but sometimes it's not. In order to make sure my edit has been saved, I must often press the save button multiple times and open a new browser tab to load the same thread to verify if my edit has been saved or not.
This does not always happen, sometimes it works the way it should, but those occasions appear rare.

(I wonder if this bug is connected to #876 and #920, as its behavior appears similar).

**Comment by YLivay** [comment]
Does this still happen?

**Comment by Tricky1975** [comment]
When I use the moderator tools, all's fine.
With the normal-user edit feature it happens, randomly, although I have the feeling the frequency with which it happens has lowered a bit... for now.

**Comment by YLivay** [comment]
The only thing I can think of is the spam detection, but you're whitelisted.. hmm.. Next time this happen see if you get an error in console log. I'm trying to reproduce this..

**Comment by YLivay** [comment]
I haven't had that happen to me a single time S:
@Tricky1975 please close this issue so you can reopen it if it surfaces again. Try seeing if you get an error log next time it happens so we'll have something to go on if you encounter it again.

**Comment by Tricky1975** [comment]
Roger!
Wilco!
