### ISSUE TITLE
won't uninstall certain games

### ISSUE THREAD

**Issue by triggeredguy** [gamejolt/issue-tracker#966]
I cant access because of this. 
![image](https://user-images.githubusercontent.com/31291574/29636251-de94709a-8847-11e7-904d-e51d2594ccf9.png)
I checked the files and the game is gone. I have reset my computer and nothing has changed. and I have tried uninstalling it as well but nothing happens. please help.

**Comment by YLivay** [comment]
Really sorry about this and the slow response :(
I'll be handling all migration issues in #970
