### ISSUE TITLE
Screenshot upload successful, and yet still and error

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#967]
![image](https://user-images.githubusercontent.com/11202073/29715218-a745adc4-89a6-11e7-810e-7ec1778dcd22.png)

(The picture did appear in my picture list allowing me to edit the caption).

**Comment by YLivay** [comment]
context?/ Where  are you uploading the image?  game screenie? Which game?  what file are you trying to upload?

**Comment by Tricky1975** [comment]
This was a screenshot for my game Mörker https://tricky.gamejolt.io/morker
I was uploading it as a screenshot as supposed to, and it's the only screenshot uploaded yet.

**Comment by YLivay** [comment]
Whats the file name? Can you upload the file to dropbox and link it here?

**Comment by Tricky1975** [comment]
[Dropbox? Google Drive acceptable too? :P](https://drive.google.com/file/d/0B4JIYQrVGOnJZjBPTGhPdVUxblU/view?usp=sharing)

**Comment by YLivay** [comment]
And the filename is same as in the drive? I'll check it out

**Comment by Tricky1975** [comment]
I just copied the file from the folder from which it was uploaded with no changes at all, not even in the filename.

**Comment by niksudan** [comment]
There were issues with drag and dropping images in the upload area (#956). Did you try both ways, and refreshing the site before both tries?

**Comment by Tricky1975** [comment]
I just used the "choose file" button. Like I said the upload was successful, so that's why I didn't try any other uploading method, but despite the upload being successful I still got an error.

**Comment by YLivay** [comment]
I think the error message is misleading but there was another issue with it. Hopefully I can get to it soon, but preoccupied with other issues atm.
