### ISSUE TITLE
Password reset causes "Internal server error of the doubious kind"

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#969]
[![image](https://user-images.githubusercontent.com/11202073/29835142-572217a8-8cf1-11e7-9721-91c232379040.png)](https://gamejolt.com/f/gamejolt-doesn-t-allow-to-reset-forgotten-password-help/275881?page=0#forum-post-366972)

Message above is from the forums. Click the message to get into the actual forum thread.

**Comment by YLivay** [comment]
I couldn't reproduce this on my account hmm.. I'll contact the user to do a manual password reset for him hopefully before this weekend.

**Comment by YLivay** [comment]
I couldnt contact the guy, can't reproduce this.

**Comment by YLivay** [comment]
closed for inactivity
