### ISSUE TITLE
Migrating problems

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#970]
I know this is a known issue, but I'm putting it on here now as an issue as people are getting desperate and impatient about it! Aside from this forum thread I regularly find dupes on the matter, and complaints over PM.

[Original forum topic](https://gamejolt.com/f/migrating-games/237260?page=1#forum-post-369289)

**Comment by YLivay** [comment]
This issue sucks, especially since I can't give it priority at the moment. Really sorry for this and to everyone who experiences this issue. We're trying to work through our issues so we can get to these asap.

**Comment by hworld** [comment]
All migration issues should be fixed, thanks to @YLivay ! Fixed with version 0.13.0
