### ISSUE TITLE
"Impossible to scroll pages" on mobile

### ISSUE THREAD

**Issue by niksudan** [gamejolt/issue-tracker#971]
Apparently occurs on Chrome v59 using Android v5.1.1. I have not been able to verify this.

Was reported by Duster (ApTeMoH3e#5829) from the Game Jolt Discord server.

**Comment by YLivay** [comment]
Im also unable to verify this. Does this happen only on that specific version?

**Comment by niksudan** [comment]
Sorry for the delay. I've sent a message to the user if they are still having problems with this.

**Comment by niksudan** [comment]
> it was already fixed with just getting new version of chrome
