### ISSUE TITLE
Outdated information found

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#972]
http://gamejolt.com/api/doc/game/users

This information was shown to me by a user, about the (removed) quickplay feature.
Then again, when I look at the page lay-out, this is clearly still in the old site setting.
Shouldn't this be updated or removed somehow, before more people get confused about this?

**Comment by YLivay** [comment]
The api docs have been rewritten for the new 95% finished unreleased new version haha..
This'll be resolved as soon as we release it,  so i'm closing this for now.
