### ISSUE TITLE
*Sigh* This isn't an issue, but mostly a question.

### ISSUE THREAD

**Issue by SplatoonPro** [gamejolt/issue-tracker#979]
Does anyone know how to add games to a library? Thanks in advance.

**Comment by SplatoonPro** [comment]
Playlist* oops lol

**Comment by niksudan** [comment]
You can do this in two ways:

On the pages with lists of games, there is a little plus icon in the top right hand corner. Click this and you will be able to select a playlist to add this into.

![image](https://user-images.githubusercontent.com/6004491/30369037-0902b94e-986b-11e7-8a95-0963362f5a8a.png)

The other way is on the game page - to the right of the follow button is a plus button, which does the same thing.

![image](https://user-images.githubusercontent.com/6004491/30369062-1be743a4-986b-11e7-9aa1-28b2e02b42cb.png)

**Comment by hworld** [comment]
Thanks, @niksudan !
