### ISSUE TITLE
I suspect confusion about the "analog" tag

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#981]
Last time I checked the "analog" channel I did see games with a "windows download".
For a channel meant for games not requiring a computer, this looks quite odd, right.
However "analog" can in gaming also refer to the "analog controller", so I believe the computer games tagged like that refer to the analog controller.
I must say that looking for a #boardgame tag was more obvious to me, but of course, since the #analog tag can also be used to present a new sport (inspired by Football/Soccer or Tennis or whatever) I guess boardgame would not be a good idea. Still a way to rule out all confusion may be a good idea.

**Comment by YLivay** [comment]
Its fine that they have downloadable builds, it could be supplementary material for the game or anything. Since analog is not really limited to board games i dont think we shsould  change  the channel name. How about you open a community thread about it? I don't we'll get better feedback there.

**Comment by hworld** [comment]
i think we should have a boardgame tag for sure. analog can also be "biggames" which is stuff you'd play outside with friends. i think we need to rethink this in the future when we work on tagging
