### ISSUE TITLE
back from 404 issue

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#982]
Of course, as a moderator, this happens to me a lot when cleaning up spam, but the bug itself can also hit normal users, as the bug does not occur in the moderation features themselves.

When you open a thread a thread on the forum that was deleted by a moderator (if the moderator did so after the thread overview was loaded on your machine, this is nothing odd) you get the "not found" screen. So far so good, that was supposed to happen. If you click your browser's "back" button however, you get the "not found" screen again. To "fix" it the page needs to be refreshed.

**Comment by YLivay** [comment]
Hmm  this probably has something to do with nested  routes not doing history replacement properly. I can't currently put it on the immediate todo list but thanks for reporting. It's on the back  burner for now :P
