### ISSUE TITLE
No games? (Client)

### ISSUE THREAD

**Issue by 128Modz** [gamejolt/issue-tracker#989]
So, I've had this issue for a _long_ time. Usually I start up the client, and see games on the dashboard. But when I do anything else, like search up a game or browse games, I get nothing. No games, no comments, no posts, nothing. It just shows that there are no games that matches what I was looking for. No matter what, no games ever appear. I quit using it for a while until I got a new computer. Then it did it again. I would really love it if this issue was fixed.

**Comment by YLivay** [comment]
Hey, thanks for reporting! Which version of the client are you using? It says so in the footer.
Also, right after youre searching and not finding any results can you scroll down to the footer and hit "send system report"? In the description put the link to this issue so i'll know your report belongs to this  issue and i'll check it out.

Ah, also, which game were you looking for?

**Comment by hworld** [comment]
no feedback, closing
