### ISSUE TITLE
All forum thread have 1 reply

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#990]
![image](https://user-images.githubusercontent.com/11202073/30514668-1083e592-9b1a-11e7-8f57-ef5f7e22c5eb.png)

At least this is shown. Reality is that I can confirm that some threads on this forum channel really have more replies. Much more.

**Comment by Tricky1975** [comment]
Supplement:

And all forums on the general overview only have 1 topic:

![image](https://user-images.githubusercontent.com/11202073/30515023-19e5ea20-9b21-11e7-8531-baa497d7c210.png)

**Comment by YLivay** [comment]
Ah, nice catch. Confirmed.

**Comment by Tricky1975** [comment]
Supplement.
Renewing the page "fixes" the bug until you click any link, as that will cause the false data to be shown again.

**Comment by Tricky1975** [comment]
I've been wondering if this is connected to #982 
But maybe I'm just talking silly :P

**Comment by YLivay** [comment]
isn't this fixed?

**Comment by YLivay** [comment]
yeah, fixed

**Comment by Tricky1975** [comment]
I wanted to check this, but I was short on time, sorry :(
