### ISSUE TITLE
thread lists do not always load

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#992]
![image](https://user-images.githubusercontent.com/11202073/30531565-7a84919a-9c4f-11e7-8cb6-7c41e64e6d6b.png)

Especially when cleaning tons of spam I come across this. I think a conflict between the huge thread removal and the thread reading my cause this. Pagination indexation conflict? I don't know how you guys coded the database, so I'm guessing stuff. Renewing the page, "fixes" the issue.

**Comment by YLivay** [comment]
Hmm, this hasn't happened to me yet but im not as active as you on the forums haha.
Whenever this happens again can you paste your javascript console log?

**Comment by Tricky1975** [comment]
Yeah, sure, if you can tell me how to "summon" that in Chrome for Mac (which is currently the browser I use).

**Comment by YLivay** [comment]
It's Cmd+Opt+J
Againt, hasn't happened to me once hmm..

**Comment by Tricky1975** [comment]
I will do so.
The problem is that this happens randomly, so that makes it hard to replicate it for me too.
If I can't reproduce this in say 14 days or so, maybe I should close this until it happens again.
(yeah, you may remind me of that).

**Comment by Tricky1975** [comment]
It’s been a long time since I saw this issue last. 
I shall now close it and reopen it if I see this happening again.
