### ISSUE TITLE
Offline Mode Doesn't Activate

### ISSUE THREAD

**Issue by to4ooo4** [gamejolt/issue-tracker#993]
Offline mode simply will not activate for me. If I'm not connected to wi-fi, offline mode doesn't activate. If I've turned wi-fi off, offline mode doesn't activate. I am using Windows 10.
While a similar issue has already been posted ( #834 ), this issue seems to have been forgotten.

**Comment by to4ooo4** [comment]
:/

**Comment by YLivay** [comment]
Yeah we know about offline mode. We're doing a rewrite to the client and only then we'd be able to tackle the issue. Since we already have an issue about this i'm closing this one. Thanks for reporting tho! It helps us prioritize :)
